### ISSUE TITLE
DNS settings -- Access settings -- Save Configuration error

### ISSUE THREAD

**Issue by doutuo** [AdguardTeam/AdGuardHome#4011] opened 2021-12-24 17:29 UTC
Version: 
v0.107.0

DNS settings -- Access settings -- Save Configuration error

Please see the attached picture

[![TNbHM9.png](https://s4.ax1x.com/2021/12/25/TNbHM9.png)](https://imgtu.com/i/TNbHM9)

**Comment by ainar-g** [comment] 2021-12-24 17:31
Duplicate of #3975

**Closed by ainar-g** 2021-12-24 17:31 UTC
