### ISSUE TITLE
Feature Request: Real-time Statistics on Dashboard

### ISSUE THREAD

**Issue by Miraz4300** [AdguardTeam/AdGuardHome#7135] opened 2024-07-15 06:31 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Lack of Real-time Statistics on Dashboard:

- Current State: The AdGuard Home dashboard provides statistical data regarding DNS queries, blocked requests, and other relevant metrics. However, this data is not updated in real-time, which limits the users' ability to monitor and respond to network activity dynamically.

- Impact: Users are unable to make timely decisions based on the most current data, leading to potential delays in addressing issues such as unusual traffic patterns, security threats, or performance bottlenecks.
<br>

### Implement Real-time Statistics on Dashboard:

**Description:** Enhance the dashboard to display real-time statistics by leveraging WebSocket or similar technologies to push updates to the UI as soon as new data is available.

**Benefits:**
- Users can monitor DNS queries and blocked requests instantaneously.
- Improved ability to detect and respond to unusual activities or potential threats in real-time.
- Enhanced user experience with a more dynamic and interactive dashboard.

**Implementation Steps:**
- Integrate WebSocket support in the backend to stream real-time data.
- Update the front-end components to handle and display live updates without requiring page refreshes.
- Ensure efficient data handling to minimize performance overhead on the server and client side.

**Comment by ainar-g** [comment] 2024-07-15 12:26
Please only file one feature request at a time.

Your first one sounds like a duplicate of #1739.  I cannot really understand your second, as it seems to be a mix of unrelated feature requests, but it seems like a duplicate of #666 and/or #4036.  Please search the issue tracker, to make sure nobody else has already requested the things you're requesting and rewrite your request to be about one new thing.

**Closed** 2024-08-08 10:52 UTC
Labels: waiting for data
