### ISSUE TITLE
Error: control/filtering/refresh | Network Error When more than 38 blacklists are active

### ISSUE THREAD

**Issue by merj1928** [AdguardTeam/AdGuardHome#2671] opened 2021-02-12 07:34 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

### Issue Details:

If more than 38 blacklists are active in AdGuard Home I get this error message: 
Error: control/filtering/refresh | Network Error

* **Version of AdGuard Home server:**
  *  v0.105.0
* **How did you install AdGuard Home:**
  *  Raspberry Pi Guide here.
* **How did you setup DNS configuration:**
  *  Ubuntu Server, Asus RT AC68U Router
* **If it's a router or IoT, please write device model:**
  *  Raspberry Pi 3 Model B
* **Operating system and version:**
  *  Ubuntu Server (last)

### Actual Behavior
 If more than 38 blacklists are active in AdGuard Home I get this error message:  Error: control/filtering/refresh | Network Error 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ainar-g** [comment] 2021-02-12 09:51
Hi, and thank you for your report.  Could you please [configure] AdGuard Home to collect logs by setting  `verbose` to `true` and post logs here as an attachment?  Thanks!

[configure]: https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file

**Comment by dioey** [comment] 2021-02-12 11:48
Hi i have same error like that, 37 blacklist, this is the log [https://raw.githubusercontent.com/dioey/AdGuard/main/adguad](url)  [https://imgur.com/a/xxYDs3Q](url)

**Comment by ameshkov** [comment] 2021-02-12 11:49
@dioey the link seems t obe invalid

**Comment by ameshkov** [comment] 2021-02-12 11:50
@ainar-g couldn't it be our POST body size limit shooting ourselves in the foot?

**Comment by dioey** [comment] 2021-02-12 11:51
sorry first time too post here the link https://raw.githubusercontent.com/dioey/AdGuard/main/adguad

**Comment by dioey** [comment] 2021-02-12 11:52
and here the screenshot https://imgur.com/N6GqUU7

**Comment by dioey** [comment] 2021-02-12 11:57
Correction about the blocklist i have 27 not 37

**Comment by ainar-g** [comment] 2021-02-12 11:58
@ameshkov, possibly.  Investigating.

**Comment by merj1928** [comment] 2021-02-12 12:23
@ainar-g 

Yes, I can do that.
Just need a little time

**Comment by ainar-g** [comment] 2021-02-12 13:40
We don't use the body size limit when downloading filters, as far as I can see.  I also couldn't reproduce the issue in Chrome on a Windows VM.

@merj1928, @dioey, do you happen to use a proxy to access the web interface?

**Comment by dioey** [comment] 2021-02-12 13:50
hem i dont use a proxy, but i use unbound as a recursive DNS server, is that a proxy? i using this tutorial from Pi-Hole, https://docs.pi-hole.net/guides/dns/unbound/ previous version never have this error

**Comment by merj1928** [comment] 2021-02-12 13:50
@ainar-g 

Is there a way to switch to the previous version?

**Comment by merj1928** [comment] 2021-02-12 13:52
> hem i dont use a proxy, but i use unbound as a recursive DNS server, is that a proxy? i using this tutorial from Pi-Hole, https://docs.pi-hole.net/guides/dns/unbound/ previous version never have this error

The Same here. I use unbound.

But with the previous version it worked without problems.

**Comment by ainar-g** [comment] 2021-02-12 14:06
> Is there a way to switch to the previous version?

If you followed the guide on our wiki, you can fist backup your AdGuard Home data and configuration, uninstall it, and then install it using the archive from [v0.104.3 release page].

[v0.104.3 release page]: https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.104.3

**Comment by merj1928** [comment] 2021-02-12 14:12
> > Is there a way to switch to the previous version?
> 
> 
> 
> If you followed the guide on our wiki, you can fist backup your AdGuard Home data and configuration, uninstall it, and then install it using the archive from [v0.104.3 release page].
> 
> 
> 
> [v0.104.3 release page]: https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.104.3

Ok.thanks 
I am a complete beginner.
How can I install it via terminal on Linux ?

**Comment by dioey** [comment] 2021-02-12 14:41
OK I downgrade to Previous version it work normally now 😁😁

**Comment by merj1928** [comment] 2021-02-12 15:12
> OK I downgrade to Previous version it work normally now 😁😁

Could you tell me how you did that ?
Headless install ?

**Comment by dioey** [comment] 2021-02-12 15:34
> > OK I downgrade to Previous version it work normally now 😁😁
> 
> Could you tell me how you did that ?
> Headless install ?

First you need uninstall first, using terminal go to AdGuardHome folder, in my case in /opt/AdGuardHome/ then uninstall using command `./AdGuardHome --service uninstall` then download adguarhome for your OS and extract it and install, it will show error port 80 already in use, i am not good at explaining thing. I got some tutorial from here https://frankindev.com/2019/11/26/doh-dot-based-on-adguardhome/

**Comment by merj1928** [comment] 2021-02-12 15:48
@ainar-g 

Am also back on AdGuard Home v0.104.3.
No problems, runs fine

**Comment by merj1928** [comment] 2021-02-12 16:24
@ainar-g 

I will post the log file here tomorrow, today it is not enough for me anymore

**Comment by merj1928** [comment] 2021-02-12 16:43
@ainar-g 

It is also not possible for me to insert block lists from the following sources:

https://energized.pro/

https://oisd.nl/

Under AdGuard Home v0.104.3. this works without problems.

**Comment by merj1928** [comment] 2021-02-13 04:48
> Hi, and thank you for your report.  Could you please [configure] AdGuard Home to collect logs by setting  `verbose` to `true` and post logs here as an attachment?  Thanks!
> 
> 
> 
> [configure]: https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file
> 
> 

Excuse me, but how can I provide you with the file?
I have Adguard Home running on a Raspberry pi (headless) and I access it from a MacBook Pro via ssh.

**Comment by dioey** [comment] 2021-02-13 05:02
You need too edit 2 line on AdGuardHome.yaml by change the value `verbose: true` and `log_file: "debug.txt"` then restart AdGuard Home, the copy the debug.txt here for the log

**Comment by merj1928** [comment] 2021-02-13 10:45
> You need too edit 2 line on AdGuardHome.yaml by change the value `verbose: true` and `log_file: "debug.txt"` then restart AdGuard Home, then copy the debug.txt here for the log

Thanks a lot

**Comment by merj1928** [comment] 2021-02-13 10:47
> You need too edit 2 line on AdGuardHome.yaml by change the value `verbose: true` and `log_file: "debug.txt"` then restart AdGuard Home, then copy the debug.txt here for the log

Where is the Debug.txt stored ?

**Comment by dioey** [comment] 2021-02-13 11:15
in my case in folder /opt/AdGuardHome/ i am using ubuntu 18 LTS

**Comment by merj1928** [comment] 2021-02-13 16:36
[AdguardDebug.txt](https://github.com/AdguardTeam/AdGuardHome/files/5976037/AdguardDebug.txt)

**Comment by merj1928** [comment] 2021-02-13 17:38
>  @merj1928 in my case in folder `/opt/AdGuardHome/` i am using ubuntu 18 LTS

How can I upload the file here ?

**Comment by merj1928** [comment] 2021-02-14 05:01
> Hi, and thank you for your report. Could you please [configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs by setting `verbose` to `true` and post logs here as an attachment? Thanks!

**Comment by merj1928** [comment] 2021-02-14 05:06
@ainar-g 
Sorry, I did not mean to close this !

**Comment by merj1928** [comment] 2021-02-15 11:28
With or without unbound. The error occurs when you update the lists manually.
However, it seems that they are updated during the automatic update.

**Comment by ainar-g** [comment] 2021-02-16 10:13
Seems the same as #2682, so I'll close this one as well.  Please write new issues if you see any new errors.

**Closed by ainar-g** 2021-02-16 10:13 UTC
Labels: P3: Medium, bug
