### ISSUE TITLE
Adguard Home v0.107.10 Docker container doesn't start after update - [fatal] unexpected type of dns: map[string]interface {}

### ISSUE THREAD

**Issue by jayscovill** [AdguardTeam/AdGuardHome#4847] opened 2022-08-18 13:24 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

x86

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.10

### Description

After pulling the lastest v0.107.10 image of the Docker container the container doesn't start. 

Docker container logs:
`
2022/08/18 12:58:23.353535 [info] AdGuard Home, version v0.107.10
2022/08/18 12:58:23.356648 [info] Upgrade yaml: 10 to 11
2022/08/18 12:58:23.356692 [info] Upgrade yaml: 11 to 12
2022/08/18 12:58:23.356730 [fatal] unexpected type of dns: map[string]interface {}
`

**Comment by ainar-g** [comment] 2022-08-18 13:26
Duplicate of #4846, we're already working on the fix.  Thanks.

**Closed by ainar-g** 2022-08-18 13:26 UTC

**Comment by jayscovill** [comment] 2022-08-18 13:29
Thank you, my apologies. If I'd have scrolled down further in that issue I would have seen the matching log entry.
