### ISSUE TITLE
[error] stats: deleting unit: bucket not found

### ISSUE THREAD

**Issue by liang-hiwin** [AdguardTeam/AdGuardHome#4900] opened 2022-09-07 15:42 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

x86

### Installation

Custom port

### Setup

On one machine

### AdGuard Home version

v0.107.11

### Description

Run "systemctl status AdGuardHome" , 
prompt

[error] stats: deleting unit: bucket not found

**Comment by ainar-g** [comment] 2022-09-07 15:49
Sounds like a duplicate of #4850.  Can you install the v0.107.12 and see if it's fixed for you as well?

**Comment by liang-hiwin** [comment] 2022-09-07 15:50
> Sounds like a duplicate of #4850. Can you install the v0.107.12 and see if it's fixed for you as well?

I just switched the version to: v0.108.0-a.270+53209bc4

**Comment by liang-hiwin** [comment] 2022-09-07 15:51
Because I was disconnected from the Internet, I realized that it was adgh reporting an error.

**Comment by liang-hiwin** [comment] 2022-09-07 15:58
> Sounds like a duplicate of #4850. Can you install the v0.107.12 and see if it's fixed for you as well?

I may not be able to reproduce this problem, using (AdGuard Home v0.107.11) may not be able to parse anything, because currently I can't switch to AdGuard Home v0.107.12, it has already affected our work, and can only be tested after get off work, sorry.

**Closed** 2023-09-07 12:15 UTC
Labels: waiting for data

**Comment by 9000000** [comment] 2024-10-08 13:42
I got the same error in the latest update,  v0.107.53
`2024/10/08 20:00:00.440007 [info] stats: warning: deleting bucket err="bucket not found"`

**Comment by timkgh** [comment] 2024-10-09 04:23
> I got the same error in the latest update, v0.107.53 `2024/10/08 20:00:00.440007 [info] stats: warning: deleting bucket err="bucket not found"`

Same error for v0.108.0-b.58
