### ISSUE TITLE
docker version v0.107.2    validating ports: duplicated values: [3000]

### ISSUE THREAD

**Issue by yanxin152133** [AdguardTeam/AdGuardHome#4161] opened 2022-01-18 12:02 UTC
docker image version v0.107.2 
"validating ports: duplicated values: [3000]" appears when deploying

**Comment by EugeneOne1** [comment] 2022-01-18 12:07
@yanxin152133, hello.  I suppose this is a duplicate of #4095.  Note the [comment](https://github.com/AdguardTeam/AdGuardHome/issues/4095#issuecomment-1008904663).

**Closed by EugeneOne1** 2022-01-18 12:07 UTC
