### ISSUE TITLE
Question: Show blocked websites from a category?

### ISSUE THREAD

**Issue by BoBBer446** [AdguardTeam/AdGuardHome#1424] opened 2020-02-21 14:41 UTC
Is it possible to display the websites that are displayed in a category?

Blocked malware/phishing | 8
Blocked adult websites | 11
Enforced safe search | 1723

**Comment by ArchiveBase** [comment] 2020-02-21 17:42
Duplicate of #882 #1292

**Closed** 2020-02-23 14:50 UTC
Labels: duplicate
