### ISSUE TITLE
Error: control/clients/add | Network Error

### ISSUE THREAD

**Issue by Mikl97490** [AdguardTeam/AdGuardHome#5955] opened 2023-07-01 13:38 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux/AMD64 (aka x86_64)

### Installation

Docker

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.108.0-a.586+2069eddf

### Action

Hi,
When i try to add new client i have an error "Error: control/clients/add | Network Error".
There is a solution to solve this error?
Thx

### Expected result

A step-by-step tutorial

### Actual result

I have this error "Error: control/clients/add | Network Error"

**Comment by yyysuo** [comment] 2023-07-01 15:24
got same issues here

**Comment by shukryshuk** [comment] 2023-07-02 10:29
what happened here? this also happened to me

**Comment by QuadrifoglioVerde** [comment] 2023-07-02 18:12
Same here, clients can be edited/removed but adding throws error.

**Comment by cylonr** [comment] 2023-07-02 20:23
Same error here. Cant add new clients.
Any help ?
Thanks
Luis Belo

**Comment by Dougiebabe** [comment] 2023-07-02 22:28
Same here, can't add new clients

Error: control/clients/add | Network Error

**Comment by ainar-g** [comment] 2023-07-03 09:54
Duplicate of #5946

**Closed by ainar-g** 2023-07-03 09:54 UTC

**Comment by papampi** [comment] 2024-12-12 08:33
Looks like this problem is back 
I updated my docker container yesterday 
AdGuardHome version: v0.107.55
And since yesterday I'm getting this error:

`Error: control/clients/find?ip0=192.168.1.121&ip1=192.168.1.15&ip2=192.168.1.142&ip3=192.168.1.111&ip4=192.168.1.115&ip5=192.168.1.118&ip6=192.168.1.105&ip7=192.168.1.117&ip8=192.168.1.124 | Network Error`

With all stats blank
