### ISSUE TITLE
Keep custom dns entries working when disabling protection

### ISSUE THREAD

**Issue by Kareltje1980** [AdguardTeam/AdGuardHome#2972] opened 2021-04-16 19:00 UTC
### Problem Description
the adguard is accessed using its own subdomain adguard.domain.com. This is set using the DNS rewrites features. When disabling the protection, this rewrite stops working. 

### Proposed Solution
Keep dns rewrites active while disabling protections

**Comment by Aikatsui** [comment] 2021-04-17 12:57
Duplicate of #1558

**Closed** 2021-04-18 20:53 UTC
Labels: duplicate
