### ISSUE TITLE
DNS stopped working in recent update

### ISSUE THREAD

**Issue by dwbrock62** [AdguardTeam/AdGuardHome#5944] opened 2023-06-29 13:44 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.32

### Action

nslookup -debug -type=a 'www.google.com' 192.168.1.21
;; connection timed out; no servers could be reached

192.168.1.21 is the address of my home assistant server

### Expected result

Resolve IP address.

### Actual result

 connection timed out; no servers could be reached

### Additional information and/or screenshots

Home Assistant OS on Raspberry PI 4

**Comment by ainar-g** [comment] 2023-06-29 14:31
Duplicate of #5896

**Closed by ainar-g** 2023-06-29 14:31 UTC
