### ISSUE TITLE
Add Traffic Destination Map to Dashboard

### ISSUE THREAD

**Issue by fpellicciotti** [AdguardTeam/AdGuardHome#4398] opened 2022-03-15 13:54 UTC
In the dashboard, it would be nice to see a "Destination map" of internet traffic that you have visited. Something similar to what NextDNS has.

![image](https://user-images.githubusercontent.com/12274971/158393139-c9d5f7ca-aefe-4fe1-b5de-dfd78e208641.png)

**Comment by agneevX** [comment] 2022-03-19 09:34
Duplicate of #1605.

**Comment by Birbber** [comment] 2022-08-17 18:40
Closing as a duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/1605.

**Closed by Birbber** 2022-08-17 18:40 UTC
Labels: duplicate
