### ISSUE TITLE
Dark theme Query Log drop down box problem

### ISSUE THREAD

**Issue by Wanabo** [AdguardTeam/AdGuardHome#5551] opened 2023-03-01 13:37 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve? 
Since the Dark theme was introduced the Query Log drop down options box has a white background with white letters. Only by hovering with your mouse over the different options makes it readable. http://111.222.333.444/#logs

#### Proposed solution. 
Fix background color in this drop down box for better readability.

#### Additional information. 
I really like the Dark theme. 👌

**Comment by ainar-g** [comment] 2023-03-01 13:39
Hello.  Which version are you using?  #5441 fixed it in the latest beta.

**Comment by Wanabo** [comment] 2023-03-01 13:39
Version: v0.107.25

**Comment by ainar-g** [comment] 2023-03-01 13:41
Then this issue is most likely a duplicate of that one.  Please feel free to reopen if the solution in the latest Edge/Beta releases doesn't work for you.

**Closed by ainar-g** 2023-03-01 13:41 UTC
Labels: waiting for data

**Comment by Wanabo** [comment] 2023-03-01 13:45
A duplicate indeed. I did however a search on "Dark" but only on open issues.
I'll wait for the next update. If the issue persists I'll report back.
