### ISSUE TITLE
[Feature Request] Enable Drill Through to the Query log from the Dashboard

### ISSUE THREAD

**Issue by jdpg2** [AdguardTeam/AdGuardHome#1842] opened 2020-06-28 16:03 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Problem Description

Enable Drill through from the query log by IP/Domain.  A user selects the IP/Domain and then is take to the Query log that is pre filtered by that IP or Domain

**Comment by mHatsune** [comment] 2020-06-29 05:33
Duplicate of #1625

**Closed** 2020-06-29 11:54 UTC
Labels: duplicate
