### ISSUE TITLE
Support client group

### ISSUE THREAD

**Issue by Ovear** [AdguardTeam/AdGuardHome#7018] opened 2024-05-22 15:09 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Although we can currently use subnets/multiples IPs to identify clients. 

However, it overrides client name, making it more difficult to filter query logs by client, especially for dual stack network.

### Proposed solution

Consider supporting client group may be good.

### Alternatives considered and additional information

Add an extra field to show/filter original client identity.

**Comment by ainar-g** [comment] 2024-05-22 15:11
Duplicate of #2527 and #5143

**Closed by ainar-g** 2024-05-22 15:11 UTC
Labels: feature request

**Comment by Ovear** [comment] 2024-05-22 15:33
I am not sure if this is a duplicate of those issues, as they focus on "filter rules". 

However, the main theme of this issue is filtering query logs, since the ctag won't work with some scenario, such as overriding upstream DNS. 

Specifically, if I want to override upstream for some clients, I have to add each client individually to make hostname searches works. Otherwise, I will lose those hostnames when I am searching through query logs.

Any suggestion?

**Comment by ainar-g** [comment] 2024-05-22 16:00
The first issue I've mentioned seems to cover settings in general, including custom upstream settings.  Searchability in the query logs would probably be implemented after that one as well.
