### ISSUE TITLE
Replicate Settings Between Instances

### ISSUE THREAD

**Issue by ted-gould** [AdguardTeam/AdGuardHome#2315] opened 2020-11-15 23:16 UTC
### Problem Description

On my home network I have two Ubuntu Core Adguard Home appliances each running on it's own RPi. This is so that I have a backup and can easily move them around without taking down the whole network. While it isn't a huge deal, it would be nice if they had the same settings. I've messed this up more than once and it gets *really* confusing when they're not the same.

### Proposed Solution

I'd like to be able to set one of them up as a "settings sync" mode where it would pull the settings from the other one. This way I could set the settings on the primary and the secondary would get them in due time (doesn't have to be immediate, but would be nice to be reasonably quick). It would be nice if I could also set up more than two as I have pis that I'd like to retire. (I think there's a reasonable use-case for three, but I don't see a reason to have more than one primary)

### Alternatives Considered

Probably going to get up some sort of rsync scheme in the mean time. But that's kinda a "hacker solution" and it'd be nice to have something other people could do as well.

**Comment by ameshkov** [comment] 2020-11-16 07:52
Duplicate of #573

**Closed by ameshkov** 2020-11-16 07:52 UTC
