### ISSUE TITLE
Add search filters in query log

### ISSUE THREAD

**Issue by msbjr88** [AdguardTeam/AdGuardHome#6421] opened 2023-11-14 13:20 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

The problem is when trying to review the query log, you have to manually scroll back to the date and time which can take hours to find what you're looking for.

### Proposed solution

Add filters to the query table to allow to search with more granularity.

**Comment by ainar-g** [comment] 2023-11-14 13:21
Duplicate of #481

**Closed by ainar-g** 2023-11-14 13:21 UTC
Labels: feature request
