### ISSUE TITLE
Release 4.8.2 keeps stopping, I am still stuck with version 4.7.6

### ISSUE THREAD

**Issue by KruseLuds** [AdguardTeam/AdGuardHome#5572] opened 2023-03-06 22:19 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

64-bit ARM

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

Trying 4.8.2 but it's still broken since 4.7.6 so I had to go back again

#### What did you do?

Tried to update to 4.8.2

#### Expected result

For it to work - but does not work beyond v4.7.6 becuase it keeps trying to connect to a nonsencial IPv6 address (which I do not use and IPv6 is not even available through my ISP):

#### Actual result

Does not work, when it launches, then is stops because it is still trying to use IP6 which I do not have and my ISP does not even provide that service to me yet, only IPv4. The fatal error message in the log that keeps reappearing whenever it tries is:

Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: 2023/03/06 17:03:17.592300 [fatal] couldn't start forwarding DNS server: listening to udp socket: l**isten udp [::1]:53:** bind: cannot assign requested address

(More log details in the later section below)

#### Screenshots (if applicable)

N/A

#### Additional information

Here are the contents of the SYSLOG showng how it tries to start, is unable to connect to some nonsenical IPv6 address unsuccessfully, and then stops. Also, below that, are specs on my system setup.

Mar  6 17:03:10 kruse-pi hassio_supervisor[587]: #033[32m23-03-06 17:03:10 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/adguard/aarch64 with version 4.8.2#033[0m
Mar  6 17:03:11 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service s6rc-oneshot-runner: starting
Mar  6 17:03:11 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service s6rc-oneshot-runner successfully started
Mar  6 17:03:11 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service base-addon-banner: starting
Mar  6 17:03:11 kruse-pi addon_a0d7b954_adguard[587]:
Mar  6 17:03:11 kruse-pi addon_a0d7b954_adguard[587]: #033[34m-----------------------------------------------------------#033[0m
Mar  6 17:03:11 kruse-pi addon_a0d7b954_adguard[587]: #033[34m Add-on: AdGuard Home#033[0m
Mar  6 17:03:11 kruse-pi addon_a0d7b954_adguard[587]: #033[34m Network-wide ads & trackers blocking DNS server#033[0m
Mar  6 17:03:11 kruse-pi addon_a0d7b954_adguard[587]: #033[34m-----------------------------------------------------------#033[0m
Mar  6 17:03:12 kruse-pi addon_a0d7b954_adguard[587]: #033[34m Add-on version: 4.8.2#033[0m
Mar  6 17:03:12 kruse-pi addon_a0d7b954_adguard[587]: #033[32m You are running the latest version of this add-on.#033[0m
Mar  6 17:03:12 kruse-pi addon_a0d7b954_adguard[587]: #033[34m System: Debian GNU/Linux 11 (bullseye)  (aarch64 / raspberrypi4-64)#033[0m
Mar  6 17:03:12 kruse-pi addon_a0d7b954_adguard[587]: #033[34m Home Assistant Core: 2023.3.1#033[0m
Mar  6 17:03:12 kruse-pi homeassistant[587]: #033[32m2023-03-06 17:03:12.976 INFO (Wemo Events Thread) [pywemo.subscribe] Resubscribe for <Subscription basicevent "Living Room Armchair Lamp">#033[0m
Mar  6 17:03:13 kruse-pi addon_a0d7b954_adguard[587]: #033[34m Home Assistant Supervisor: 2023.01.1#033[0m
Mar  6 17:03:13 kruse-pi addon_a0d7b954_adguard[587]: #033[34m-----------------------------------------------------------#033[0m
Mar  6 17:03:13 kruse-pi addon_a0d7b954_adguard[587]: #033[34m Please, share the above information when looking for help#033[0m
Mar  6 17:03:13 kruse-pi addon_a0d7b954_adguard[587]: #033[34m or support in, e.g., GitHub, forums or the Discord chat.#033[0m
Mar  6 17:03:13 kruse-pi addon_a0d7b954_adguard[587]: #033[34m-----------------------------------------------------------#033[0m
Mar  6 17:03:13 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service base-addon-banner successfully started
Mar  6 17:03:13 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service fix-attrs: starting
Mar  6 17:03:13 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service base-addon-log-level: starting
Mar  6 17:03:13 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service fix-attrs successfully started
Mar  6 17:03:13 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service base-addon-log-level successfully started
Mar  6 17:03:13 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service legacy-cont-init: starting
Mar  6 17:03:13 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service legacy-cont-init successfully started
Mar  6 17:03:13 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service init-nginx: starting
Mar  6 17:03:13 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service init-adguard: starting
Mar  6 17:03:13 kruse-pi hassio_supervisor[587]: #033[32m23-03-06 17:03:13 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from a0d7b954_adguard#033[0m
Mar  6 17:03:14 kruse-pi hassio_supervisor[587]: #033[32m23-03-06 17:03:14 INFO (MainThread) [supervisor.api.middleware.security] /network/interface/eth0/info access from a0d7b954_adguard#033[0m
Mar  6 17:03:15 kruse-pi hassio_supervisor[587]: #033[32m23-03-06 17:03:15 INFO (MainThread) [supervisor.api.middleware.security] /network/interface/wlan0/info access from a0d7b954_adguard#033[0m
Mar  6 17:03:16 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service init-nginx successfully started
Mar  6 17:03:16 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service init-adguard successfully started
Mar  6 17:03:16 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service adguard: starting
Mar  6 17:03:16 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service adguard successfully started
Mar  6 17:03:16 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service discovery: starting
Mar  6 17:03:16 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service nginx: starting
Mar  6 17:03:16 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service nginx successfully started
Mar  6 17:03:16 kruse-pi addon_a0d7b954_adguard[587]: [17:03:16] INFO: #033[32mStarting AdGuard Home server...#033[0m
Mar  6 17:03:16 kruse-pi addon_a0d7b954_adguard[587]: 2023/03/06 17:03:16.386502 [info] AdGuard Home, version v0.107.25
Mar  6 17:03:16 kruse-pi addon_a0d7b954_adguard[587]: 2023/03/06 17:03:16.386779 [info] AdGuard Home updates are disabled
Mar  6 17:03:16 kruse-pi addon_a0d7b954_adguard[587]: 2023/03/06 17:03:16.390878 [info] tls: using default ciphers
Mar  6 17:03:16 kruse-pi addon_a0d7b954_adguard[587]: 2023/03/06 17:03:16.406466 [info] Initializing auth module: /data/adguard/data/sessions.db
Mar  6 17:03:16 kruse-pi addon_a0d7b954_adguard[587]: 2023/03/06 17:03:16.406751 [info] auth: initialized.  users:0  sessions:0
Mar  6 17:03:16 kruse-pi addon_a0d7b954_adguard[587]: 2023/03/06 17:03:16.406792 [info] web: initializing
Mar  6 17:03:16 kruse-pi addon_a0d7b954_adguard[587]: 2023/03/06 17:03:16.487471 [info] dnsproxy: cache: enabled, size 4096 b
Mar  6 17:03:16 kruse-pi addon_a0d7b954_adguard[587]: 2023/03/06 17:03:16.487529 [info] MaxGoroutines is set to 300
Mar  6 17:03:16 kruse-pi addon_a0d7b954_adguard[587]: 2023/03/06 17:03:16.488070 [info] AdGuard Home is available at the following addresses:
Mar  6 17:03:16 kruse-pi addon_a0d7b954_adguard[587]: 2023/03/06 17:03:16.488569 [info] go to http://127.0.0.1:45158
Mar  6 17:03:16 kruse-pi addon_a0d7b954_adguard[587]: [17:03:16] INFO: #033[32mStarting NGinx...#033[0m
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: [17:03:17] INFO: #033[32mSuccessfully send discovery information to Home Assistant.#033[0m
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service discovery successfully started
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service legacy-services: starting
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service legacy-services successfully started
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: 2023/03/06 17:03:17.587077 [info] Starting the DNS proxy server
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: 2023/03/06 17:03:17.587135 [info] Ratelimit is enabled and set to 20 rps
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: 2023/03/06 17:03:17.587146 [info] The server is configured to refuse ANY requests
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: 2023/03/06 17:03:17.587154 [info] dnsproxy: cache: enabled, size 4194304 b
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: 2023/03/06 17:03:17.587172 [info] MaxGoroutines is set to 300
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: 2023/03/06 17:03:17.587204 [info] Creating the UDP server socket
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: 2023/03/06 17:03:17.587460 [info] Listening to udp://192.168.0.34:53
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: 2023/03/06 17:03:17.587481 [info] Creating the UDP server socket
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: 2023/03/06 17:03:17.587571 [info] Listening to udp://172.30.32.1:53
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: 2023/03/06 17:03:17.587581 [info] Creating the UDP server socket
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: 2023/03/06 17:03:17.587639 [info] Listening to udp://127.0.0.1:53
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: 2023/03/06 17:03:17.587648 [info] Creating the UDP server socket
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: 2023/03/06 17:03:17.592300 [fatal] couldn't start forwarding DNS server: listening to udp socket: listen udp [::1]:53: bind: cannot assign requested address
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: [17:03:17] INFO: #033[32mService Adguard Home exited with code 1 (by signal 0)#033[0m
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service legacy-services: stopping
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service legacy-services successfully stopped
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service discovery: stopping
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service nginx: stopping
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service discovery successfully stopped
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: [17:03:17] INFO: #033[32mService NGINX exited with code 0 (by signal 0)#033[0m
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service nginx successfully stopped
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service init-nginx: stopping
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service adguard: stopping
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service init-nginx successfully stopped
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service adguard successfully stopped
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service init-adguard: stopping
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service init-adguard successfully stopped
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service legacy-cont-init: stopping
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service legacy-cont-init successfully stopped
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service fix-attrs: stopping
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service base-addon-log-level: stopping
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service fix-attrs successfully stopped
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service base-addon-log-level successfully stopped
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service base-addon-banner: stopping
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service base-addon-banner successfully stopped
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service s6rc-oneshot-runner: stopping
Mar  6 17:03:17 kruse-pi addon_a0d7b954_adguard[587]: s6-rc: info: service s6rc-oneshot-runner successfully stopped

## System Information

version | core-2023.3.1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.10.0-21-arm64
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.31.0
Stage | running
Available Repositories | 1309
Downloaded Repositories | 24

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 19

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2023.01.1
agent_version | 1.4.1
docker_version | 23.0.1
disk_total | 915.4 GB
disk_used | 19.1 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | AppDaemon (0.11.0), Core DNS Override (0.1.1), Duck DNS (1.15.0), File editor (5.5.0), Home Assistant Google Drive Backup (0.110.1), Log Viewer (0.14.0), Mosquitto broker (6.1.3), Samba share (10.0.0), Terminal & SSH (9.6.1), AdGuard Home (4.7.6)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 15
views | 29
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | February 5, 2023 at 2:03 PM
-- | --
current_recorder_run | March 3, 2023 at 6:14 PM
estimated_db_size | 2256.60 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

**Comment by ainar-g** [comment] 2023-03-07 10:52
This is essentially a duplicate of your previous issue, #5481.  The aforementioned unconditional addition of the IPv6 address is [still there in the addon's codebase][1], and hassio-addons/addon-adguard-home#385 is still open.

If none of the workarounds in the issue work for you, your options are either forking the addon, removing the lines, and using your own fork or use the official AdGuard Home package.

[1]: https://github.com/hassio-addons/addon-adguard-home/blob/400ab556a6504dbc45fe3efa9318f649a14ce439/adguard/rootfs/etc/s6-overlay/s6-rc.d/init-adguard/run#L60-L61

**Closed by ainar-g** 2023-03-07 10:52 UTC

**Comment by KruseLuds** [comment] 2023-03-07 21:58
Just to make life easier for folks reading this stuff later, as it is no longer an issue for me - steps to resolve (thank you @InToSSH  for the below):

pi@kruse-pi: sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0
pi@kruse-pi: sudo ifdown lo
pi@kruse-pi: sudo ifup lo
pi@kruse-pi: sudo ip addr show lo
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever

Running the latest flavor of adguard now does work, so to make it permanent, I updated update in: /etc/sysctl.conf, this statement
 from
net.ipv6.conf.all.disable_ipv6 = 1
 to
net.ipv6.conf.all.disable_ipv6 = 0
