### ISSUE TITLE
AdGuard Home isn’t caching HTTPS (type 65) queries

### ISSUE THREAD

**Issue by handcoding** [AdguardTeam/AdGuardHome#4471] opened 2022-04-07 21:29 UTC
### Issue Details

* **Version of AdGuard Home server:**
  * v0.107.5
* **How did you install AdGuard Home:**
  * I installed AdGuard Home as an add-on within Home Assistant
* **How did you setup DNS configuration:**
  * Within my Eero’s DNS settings, I pointed the Eero to use the Pi’s internal ip address for DNS. 
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4B
* **CPU architecture:**
  * ARM 64 bit
* **Operating system and version:**
  * Home Assistant OS (Linux) version 2022.3.8

### Expected Behavior
I would expect that AdGuard Home would return HTTPS-type queries from its cache when possible.

### Actual Behavior
For HTTPS-type queries, AdGuard Home seems to be querying my upstream DNS servers every time, rather than serving those from the cache. 

Other config details:
* Cache size: 64 MB (I realize that this is ridiculously large for a cache, but I set this to be especially large to try to make sure that almost all lookups would be cached for the sake of this test)
* Minimum TTL: 3600
* Maximum TTL: 86400
* ✔︎ Optimistic caching

### Screenshots
* In this log excerpt showing a search for `youtubei.googleapis.com`, type A and type AAAA queries are being returned from the cache (which you can tell from their super-short elapsed times), while the type HTTPS queries (at `15:46:37`) are going through to the upstream DNS servers, even though one would think that they would’ve been cached (seeing as though they were previously queried at `15:33:28`) 
<img width="991" alt="2022-04-07 at 4 09 p m" src="https://user-images.githubusercontent.com/118319/162311101-b3e90b67-ba39-4dc7-acec-073884427510.png">

### Screenshots

<details><summary>Upstream DNS servers:</summary>
<img width="976" alt="2022-04-07 at 3 57 p m" src="https://user-images.githubusercontent.com/118319/162303535-19bd8001-9e62-4321-af8e-b88c5ebe28bf.png">
</details>

<details><summary>Bootstrap DNS servers:</summary>
<img width="959" alt="2022-04-07 at 4 00 p m" src="https://user-images.githubusercontent.com/118319/162305133-681e1ecb-61d2-4f38-ac71-5ca977f14334.png">
</details>

<details><summary>Cache settings:</summary>
<img width="606" alt="2022-04-07 at 3 58 p m" src="https://user-images.githubusercontent.com/118319/162304424-545f6833-b885-403f-b856-bbf41e7ecd54.png">

</details>

**Comment by fernvenue** [comment] 2022-04-08 03:24
Can not reproduce on my multiple servers including Raspberry Pi:

![screenshot](https://user-images.githubusercontent.com/84565547/162355842-1bd55959-6fdc-499d-a5c7-cbdbd6dc004b.png)

Even if I set the same DNS cache configuration as yours, AdGuardHome still return HTTPS-type queries from its cache, maybe you can use [verbose log](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) to get more information about that.

**Comment by handcoding** [comment] 2022-04-08 04:10
@fernvenue Many thanks for your reply! 

For whatever it’s worth, I’m running AdGuard Home through an add-on in Home Assistant. And for the life of me, I can’t quite seem to figure out how to access AdGuardHome.yaml so as to change that config option for the logging level. (I found [some references online to accessing the docker container through public SSH keys](https://community.home-assistant.io/t/howto-how-to-access-the-home-assistant-os-host-itself-over-ssh/263352), but I don’t know what docker is or how SSH keys work.)

If by any chance you might be open to it, I’d be happy to pay you for your time if you might be open to helping me get these options changed (or if you might be open to making this change on my Home Assistant server directly if I were to give you access to it).

**Comment by ainar-g** [comment] 2022-04-08 11:46
@handcoding, hello.  Is it possible that your upstream server removes `SOA` records from the authority section?  That is where DNS caches take the TTL for caching responses with no actual answer records.  You can check that by using `dig`:

```sh
dig 'youtubei.googleapis.com' @"$YOUR_UPSTREAM_SERVER" IN TYPE65
```

The response should have an `AUTHORITY SECTION` with a `SOA` record:

```none
; <<>> DiG 9.16.1-Ubuntu <<>> youtubei.googleapis.com @1.2.3.4 IN TYPE65
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45032
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;youtubei.googleapis.com.       IN      TYPE65

;; AUTHORITY SECTION:
googleapis.com.         60      IN      SOA     ns1.google.com. dns-admin.google.com. 440057678 900 900 1800 60

;; Query time: 132 msec
;; SERVER: 1.2.3.4#53(1.2.3.4)
;; WHEN: Fri Apr 08 11:43:25 UTC 2022
;; MSG SIZE  rcvd: 109
```

**Comment by handcoding** [comment] 2022-04-08 13:31
@ainar-g Well how about that—I believe you might be on to something! (Though see also the end of this comment for the part that still puzzles me.)

When I run `dig 'youtubei.googleapis.com' @2620:119:53::53 IN TYPE65` (`2620:119:53::53` corresponds to [one of OpenDNS’s public ipv6 servers](https://www.opendns.com/about/innovations/ipv6/)), _there’s no_ `AUTHORITY SECTION` (!):

```bash
$ dig 'youtubei.googleapis.com' @2620:119:53::53 IN TYPE65

; <<>> DiG 9.10.6 <<>> youtubei.googleapis.com @2620:119:53::53 IN TYPE65
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34322
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;youtubei.googleapis.com.	IN	TYPE65

;; Query time: 13 msec
;; SERVER: 2620:119:53::53#53(2620:119:53::53)
;; WHEN: Fri Apr 08 08:15:06 CDT 2022
;; MSG SIZE  rcvd: 52
```

…But when I run `dig 'youtubei.googleapis.com' @209.18.47.62 IN TYPE65` (`@209.18.47.62` corresponds to one of my ISP’s DNS servers), _there is_ an `AUTHORITY SECTION`:

```bash
$ dig 'youtubei.googleapis.com' @209.18.47.62 IN TYPE65

; <<>> DiG 9.10.6 <<>> youtubei.googleapis.com @209.18.47.62 IN TYPE65
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9287
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;youtubei.googleapis.com.	IN	TYPE65

;; AUTHORITY SECTION:
googleapis.com.		57	IN	SOA	ns1.google.com. dns-admin.google.com. 440057678 900 900 1800 60

;; Query time: 9 msec
;; SERVER: 209.18.47.62#53(209.18.47.62)
;; WHEN: Fri Apr 08 08:16:07 CDT 2022
;; MSG SIZE  rcvd: 109
```

So here’s the part that especially confuses me—since I have AdGuard Home set to `override minimum TTL` to `3600` seconds, then shouldn’t that override the stripped TTL information anyway?

<img width="970" alt="2022-04-08 at 8 26 a m" src="https://user-images.githubusercontent.com/118319/162445192-9cd085a1-31a4-4053-a9ac-cfe7f0ff9488.png">

**Comment by ainar-g** [comment] 2022-04-08 13:41
Thanks for testing.  The TTL override feature currently works as an override, not as an addition, so if there isn't anything to override, it doesn't do anything.

In fact, [RFC 2308][1] explicitly recommends against caching such responses:

 >  ```none
 >  Negative responses without SOA records SHOULD NOT be cached as there
 >  is no way to prevent the negative responses looping forever between a
 >  pair of servers even with a short TTL.
 >  ```

I'll close this issue, since this seems to be an issue with OpenDNS's servers and not with AdGuard Home.  Feel free to open new ones if you encounter anything.

[1]: https://datatracker.ietf.org/doc/html/rfc2308#section-5

**Closed by ainar-g** 2022-04-08 13:41 UTC
Labels: waiting for data

**Comment by handcoding** [comment] 2022-04-08 13:48
@ainar-g Ah—interesting! 

And at this point, if OpenDNS’s ipv6 servers are indeed broken, then might it be worth removing OpenDNS’s ipv6 entries from [AdGuard Home’s list of recommended DNS servers](https://kb.adguard.com/en/general/dns-providers#cisco-opendns)? 

(When you run `dig 'youtubei.googleapis.com' @2620:119:53::53 IN TYPE65`, I take it that you likewise aren’t seeing an `AUTHORITY SECTION`?)

**Comment by ainar-g** [comment] 2022-04-08 14:15
@handcoding, I've opened an [issue][1] in the DNS Knowledge Base repo.  You can open new issues regarding DNS documentation there.

[1]: https://github.com/AdguardTeam/KnowledgeBaseDNS/issues/16

**Comment by handcoding** [comment] 2022-04-08 15:35
Thank you so, so much for all your help with this, @ainar-g and @fernvenue—I really appreciate it!
