### ISSUE TITLE
Custom Filter Rule for Adguard home IP is now Returning 127.0.0.1

### ISSUE THREAD

**Issue by damooooooooooh** [AdguardTeam/AdGuardHome#1918] opened 2020-07-23 22:39 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ X ] I am running the latest version
- [ X ] I checked the documentation and found no answer
- [ X ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.103.2
* **How did you setup DNS configuration:**
  * Raspberry Pi
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4 2GB
* **Operating system and version:**
  * Raspberry Pi OS (32-bit) Lite

### Expected Behavior

I have assigned a FQDN to my Adguard home instance i.e. dns.mydomain.com (I own this domain and run it on internal network and have setup the encryption configuration.  I have a custom Filter setup  as 192.168.1.128 dns.mydomain.com.  Befor ethe update adguard was previously returning the correct IP when I browse to dns.mydomain.com with adguard set as the DNS server.

DIG OUTPUT BEFORE
;; QUESTION SECTION:
;dns.mydomain.com.                IN      A

;; ANSWER SECTION:
dns.mydomain.com. 10      IN      A       192.168.1.128

### Actual Behavior
With the same custom filter, adguard is now returning 127.0.0.1.

DIG OUTPUT BEFORE
;; QUESTION SECTION:
;dns.mydomain.com.                IN      A

;; ANSWER SECTION:
dns.mydomain.com. 10      IN      A       **127.0.0.1**

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Torom** [comment] 2020-07-24 07:55
I think I have a simular issue. I have a local URL assigned to my AdGuard instance. It's not an FQDN, I used an custom rule in AdGuard to point it to my server.

In 0.102 it worked just fine, for AAAA requests it sends an NOERROR and its IPv6 adress and for A requests it sends just an NOERROR.

Now in 0.103.2 it sends for AAAA the IPv6 but for A requests it answers with NXDOMAIN. Because of that my browsers are not listening to the AAAA response, Firefox is redirecting to www.LOCAL.DOMAIN, Chrome just throw an error.

**Comment by ameshkov** [comment] 2020-07-24 08:03
Check what blocking mode is set in DNS settings -> DNS server configuration.

Also, it's recommended to use DNS rewrites for this sort of things.

**Comment by Torom** [comment] 2020-07-24 08:27
I use the 0.0.0.0 blocking mode. And sorry, I am using rewrite rules not a custom rule.

**Comment by damooooooooooh** [comment] 2020-07-24 09:22
Sorry all, this was coming from the 127.0.1.1 entry in my hosts file on the Pi.  I have updated the entry with my static IP.

**Comment by szolin** [comment] 2020-07-24 09:39
> Now in 0.103.2 it sends for AAAA the IPv6 but for A requests it answers with NXDOMAIN.

@Torom Can you show what's nslookup or dig prints?  What is your rewrite rule?

**Comment by szolin** [comment] 2020-07-24 09:41
@damooooooooooh 

To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by Torom** [comment] 2020-07-24 09:54
```
$ nslookup ad.guard
Server:         192.168.178.3
Address:        192.168.178.3#53

** server can't find ad.guard: NXDOMAIN
```
```
$ nslookup -q=A ad.guard
Server:         192.168.178.3
Address:        192.168.178.3#53

** server can't find ad.guard: NXDOMAIN
```
```
$ nslookup -q=AAAA ad.guard
Server:         192.168.178.3
Address:        192.168.178.3#53

Non-authoritative answer:
Name:   ad.guard
Address: CORRECT IPv6 ADRESS
```

The rewrite rule is the domain `ad.guard` with the IPv6 adress of the server.

**Comment by Torom** [comment] 2020-07-24 10:01
```
$ dig ad.guard A

; <<>> DiG 9.16.1-Ubuntu <<>> ad.guard A
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 38282
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;ad.guard.                      IN      A

;; AUTHORITY SECTION:
.                       71583   IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2020072301 1800 900 604800 86400

;; Query time: 2 msec
;; SERVER: 192.168.178.3#53(192.168.178.3)
;; WHEN: Fri Jul 24 11:59:23 CEST 2020
;; MSG SIZE  rcvd: 101
```
```
$ dig ad.guard AAAA

; <<>> DiG 9.16.1-Ubuntu <<>> ad.guard AAAA
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49865
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;ad.guard.                      IN      AAAA

;; ANSWER SECTION:
ad.guard.               10      IN      AAAA    CORRECT IPv6 ADDRESS

;; Query time: 3 msec
;; SERVER: 192.168.178.3#53(192.168.178.3)
;; WHEN: Fri Jul 24 11:59:24 CEST 2020
;; MSG SIZE  rcvd: 54
```

**Comment by damooooooooooh** [comment] 2020-07-24 12:06
> @damooooooooooh
> 
> To troubleshoot this issue we need to see AdGuard Home logs.
> 
> 1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
>    
>    * Specify `log_file`
>    * Set `verbose` to `True`
> 2. Restart AdGuard Home and reproduce the issue
> 3. Post the log file here.

Hi My issue is closed, shall I leave the thread open of @Torom?

**Closed** 2020-07-24 13:27 UTC
Labels: P3: Medium, bug
