### ISSUE TITLE
Query log: Add option to Show drop-down for showing domains that haven't triggered a rule

### ISSUE THREAD

**Issue by twcau** [AdguardTeam/AdGuardHome#1848] opened 2020-06-30 03:25 UTC
# Problem Description
At present, Query log has a small number of filters and options to reduce the data shown. Most issues for improving it are the subject of other feature request tickets.

But something that isn't is the options available in the drop-down to choose what is shown.

At present, the options are either:
* Show All
* Show Filtered

However, there's no way to see *only* what hasn't been filtered. This means the user can't focus and simplify on finding those domains that may need attention; as the results included all the filtered (or permitted by rule) content.

### Proposed Solution
For the Show... drop down, add a new option called Show Passed, which shows only those records with a filtering status of Ellapsed (according to the querylog.json file with all the logging).

This would then allow the user to only see those domains that haven't triggered a rule, and proceed accordingly.

### Alternatives Considered
No plausible alternatives identified.

### Additional Information
N/A

**Comment by mHatsune** [comment] 2020-06-30 13:16
Duplicate of #882

**Comment by ameshkov** [comment] 2020-07-02 12:00
Already resolved in the beta version:

![image](https://user-images.githubusercontent.com/5947035/86356361-c83eab80-bc74-11ea-958a-c694f72fa9c7.png)

**Closed by ameshkov** 2020-07-02 12:00 UTC
