### ISSUE TITLE
Couldn't get version check json

### ISSUE THREAD

**Issue by laoshitai** [AdguardTeam/AdGuardHome#4153] opened 2022-01-17 12:38 UTC
I met an error like this:
Error: control/version.json | Couldn't get version check json from https://static.adguard.com/adguardhome/release/version.json: *fmt.wrapError updater: HTTP GET https://static.adguard.com/adguardhome/release/version.json: Get "https://static.adguard.com/adguardhome/release/version.json": requesting https://dns10.quad9.net:443/dns-query: Get "https://dns10.quad9.net:443/dns-query?dns=Wo8BAAABAAAAAAAABnN0YXRpYwdhZGd1YXJkA2NvbQAAHAAB": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) | 502

**Comment by ainar-g** [comment] 2022-01-19 12:24
Looks like a duplicate of #3038.  Please try changing the upstream servers.

**Closed by ainar-g** 2022-01-19 12:24 UTC
