### ISSUE TITLE
DNS cannot function during Filter update

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardHome#928] opened 2019-08-11 10:25 UTC
### Issue Details
Whilst AdGuard Home is updating filters, all DNS traffic is halted until the update is complete.
This is very obvious when using a large filter, and having slow internet speeds.

* **Version of AdGuard Home server:**
  * v0.97.1-54-ga59b
* **How did you setup DNS configuration:**
  * IoT
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 3 Model B+
* **Operating system and version:**
  * Raspbian (Latest)

### Expected Behavior

DNS traffic can continue to work whilst updates are running.

### Actual Behavior

All DNS traffic cannot work, until the update is fully complete.

### Additional Information

Pi-hole is able to run gravity updates separately, allowing all traffic to continue as expected and then restarts the DNS server once the download is complete and the filter updates are applied.

**Comment by ilya-fedin** [comment] 2019-08-16 23:03
I have the same issue. For now adtidy.org is down, Aguard Home tries to update safebrowsing list in loop, while updating DNS doesnt't work:
```
2019/08/17 02:56:49 [info] Failed to do safebrowsing HTTP lookup, ignoring check: Get https://sb.adtidy.org/safebrowsing-lookup-hash.html?prefixes=4D2AF688/9B541B2D/EE240335/BBA06DD3/7F428118/: couldn't dial to 176.103.133.133:443, cause: dial tcp 176.103.133.133:443: connect: connection timed out
```
So, all users with enabled safebrowsing should have problems with DNS resolving.
I think, this issue should have high priority.

**Comment by ameshkov** [comment] 2019-08-18 21:03
@ilya-fedin sorry for the late reply, please see the answer here: https://github.com/AdguardTeam/AdGuardHome/issues/936#issuecomment-522353903

**Comment by szolin** [comment] 2019-08-20 15:23
@planet0 I can't reproduce it.  Can you show application logs?
The only reason I can think of that can cause the issue is that downloading a filter uses the whole available bandwidth and DNS packets can't pass through.

**Comment by szolin** [comment] 2019-09-02 16:37
@planet0 Does the issue persist?

**Comment by planet0** [comment] 2019-09-04 10:33
@szolin Sorry about not responding sooner, I was hoping to have the chance to reproduce this issue for the application logs but I haven't.

Something in AGH's behaviour prevents any DNS filtering traffic to occur until the update process is done. Pi-hole runs the update procedure separately from the active DNS rules until they are complete, and then applies the new rules in 1 or 2 seconds which the same issue occurs.

**Comment by szolin** [comment] 2019-09-04 11:18
> instead of the entire time to update all the filters (20MB+) in AdGuard Home

We don't lock DNS operations while we're downloading updates.
When I start filter update procedure, and while the filter data is being downloaded, DNS server responds just fine, without delays.  That's why I want to look at the app logs - maybe we can find what causes the delays in your case.

**Comment by planet0** [comment] 2019-09-04 11:21
Thanks for letting me know, it's hard as a user to know what goes on in the background! 😅

The only other idea (if possible) is to imitate my slow internet connection, at 3 Megabits per second download and 1 Megabit upload speeds, then try to force update filters.

Otherwise I'll need to reinstall AdGuard Home and try it again soon for you.

**Comment by ameshkov** [comment] 2019-09-10 11:57
Well, unfortunately we cannot reproduce this. It'd be much easier to troubleshoot if we had debug level log.

**Comment by ArchiveBase** [comment] 2019-09-10 14:10
I think what @szolin assume is right.
> The only reason I can think of that can cause the issue is that downloading a filter uses the whole available bandwidth and DNS packets can't pass through.

@planet0 said above,
> my slow internet connection, at 3 Megabits per second download and 1 Megabit upload speeds,

Just i didn't check the source code to see how the update works but prefer add a suggestion. AGHome able measure network speed before start download anything (filters or software updates) then activate a slow download mode with optional notification to user then download filters one by one with low bandwidth such as few Kb/s (100-350) (but software update must be re-verify whether damaged or not prior install) 

Measure network speed bit unwanted but it helps to exclude faster network connections and download all filters and software updates at once without delays.

**Comment by ilya-fedin** [comment] 2019-09-10 14:15
Even if there are no problems with DNS filters updating, there is definitely a problem with safe-browsing lists updating - the recent incident with DDoS of the safe-browsing worksheet server proof that.

**Comment by ameshkov** [comment] 2019-09-10 14:19
Yeah, but this is not relevant to this particular issue:)

**Comment by ilya-fedin** [comment] 2019-09-10 14:21
@ameshkov where's issue about safe-browsing lists updating?

**Comment by ameshkov** [comment] 2019-09-10 14:22
https://github.com/AdguardTeam/AdGuardHome/issues/525#issuecomment-520482071

**Comment by szolin** [comment] 2019-09-10 14:40
> download filters one by one using low bandwidth

We can let user to set a limit for filters downloading rate in configuration.  I don't know if we can easily add this feature, but it's just a possible solution.

**Comment by ilya-fedin** [comment] 2019-09-10 14:48
@ameshkov thank you

**Comment by ArchiveBase** [comment] 2019-09-10 15:35
> We can let user to set a limit for filters downloading rate in configuration.

I believe no one will get benefit from this option except power users so it must be work automatically.

**Comment by szolin** [comment] 2019-09-10 15:40
Yes, but determining Internet speed automatically is a task of another complexity level, and it would require much time to implement.

**Comment by ArchiveBase** [comment] 2019-09-10 16:06
We should always give something perfect by design and suitable for everyone to use without effort or thirdparty assistance however this issue so far affect for less users then able move for upcoming milestones.

**Comment by planet0** [comment] 2019-09-10 21:16
Reading this discussion made me realise that I also had Browsing Security enabled as well. Would that have had any affect on the issue?

**Comment by ArchiveBase** [comment] 2019-09-11 10:02
@planet0 not that much. if you want to see this issue practically as easy to understand, just start to upload any large file to a cloud storage service that claims about offer fast upload and downloads meantime try to visit google.com or other website through browser then you'll see no internet notification or keep loading more time although certain file still uploading as well so that's what happening vise versa. you can check it without AGHome too.

**Comment by ameshkov** [comment] 2019-09-13 15:19
@szolin the problem is not downloading filter lists but initializing the filtering engine. If you add a huge filter list (energized or dbl.oisd.nl) it takes a while to initialize the engine, and AGH is unresponsive when it happens.

This will be difficult to resolve.

**Comment by planet0** [comment] 2019-09-24 01:36
Thank you!

**Comment by ameshkov** [comment] 2019-10-03 10:26
@planet0 have you checked out the beta version? Does it work okay now?

**Comment by planet0** [comment] 2019-10-03 12:34
@ameshkov Just tested v0.98.1-136-g423d now with dbl.oisd.nl, can still browse the net whilst updating/downloading! 👍🏼

**Comment by ameshkov** [comment] 2019-10-03 12:35
@planet0 awesome, thank you:)

**Comment by planet0** [comment] 2019-10-03 12:35
@ameshkov Only issue is, I just noticed the queries are not being blocked during update, they pass through. Noticed it with logs.roku.com for the SDNS Filter.

**Comment by planet0** [comment] 2019-10-03 12:43
@ameshkov @szolin Only issue is, I just noticed the queries are not being blocked during update, they pass through. Noticed it with logs.roku.com for the SDNS Filter.

Before (blocked):

<img width="672" alt="Screen Shot 2019-10-03 at 10 36 05 pm" src="https://user-images.githubusercontent.com/46271764/66127065-3eeb4180-e62e-11e9-9535-1f89c273ee97.png">

During Update (notice dbl.oisd.nl entry as well):

<img width="684" alt="Screen Shot 2019-10-03 at 10 36 20 pm" src="https://user-images.githubusercontent.com/46271764/66127111-51657b00-e62e-11e9-9c21-f2c3de77a14c.png">

After Update (back to being blocked):

<img width="687" alt="Screen Shot 2019-10-03 at 10 40 47 pm" src="https://user-images.githubusercontent.com/46271764/66127396-e5cfdd80-e62e-11e9-9643-d6fbaf43b445.png">

**Comment by ameshkov** [comment] 2019-10-03 12:46
Hm, yeah, that's not ideal.

The prev filtering engine should continue to work while the updated one is being initialized

**Closed** 2019-10-10 09:33 UTC
Labels: P4: Low, bug
