### ISSUE TITLE
How do I disable ipv6 queries or limit the number of ipv6 queries

### ISSUE THREAD

**Issue by thb007** [AdguardTeam/AdGuardHome#1312] opened 2019-12-26 12:59 UTC
1.Because the adghome server I built in vps does not provide an ipv6 address, and currently there are very few doh / dot that support ipv6 parsing.
2. I saw in the web panel that AAAA requests have been querying, and the corresponding ipv6 cannot be queried (Status: NOERROR). These requests take up a lot of CPU and memory. How can I stop him Not looking up this IPv6 address?
3. How can I handle this request 154.1.254.10.in-addr.arpa --- PTR
Status: NOERROR?

**Comment by szolin** [comment] 2019-12-31 11:05
I don't understand your questions.  Who is making IPv6 requests?  Do you mean you want to block AAAA answers?  How do you want to handle PTR responses?

**Comment by thb007** [comment] 2019-12-31 11:33
> 我不明白你的问题。谁在发出IPv6请求？您是说要阻止AAAA答案吗？您想如何处理PTR响应？

I found out why adghome has been trying to resolve a domain name without an IPv6 address

**Comment by ameshkov** [comment] 2019-12-31 15:14
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/473

**Closed by ameshkov** 2019-12-31 15:14 UTC
Labels: duplicate
