### ISSUE TITLE
AGH uses a broken filter list

### ISSUE THREAD

**Issue by Sakura-Luna** [AdguardTeam/AdGuardHome#5258] opened 2022-12-11 12:09 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.20

#### What did you do?

I updated the latest version and found it **difficult** to update the (custom) filter list (poor network status), AGH updated the **broken** list and caused the entire filtering service to malfunction. In fact, in the old version, the update list will be **stuck or crashed** probabilistically.
#### Expected result

Successfully updated or only updated list of successfully downloaded
#### Actual result

Update unresponsive and broken lists
#### Additional information
Compared with expired lists, damaged lists will cause more serious problems. The integrity of the list should be ensured, such as adding an integrity check mechanism for the list, such as a comment mark at the end of the Goodbye Ads list.

**Comment by Sakura-Luna** [comment] 2022-12-23 03:01
@EugeneOne1 I observed it for a few days and found no problems for the time being. But when I actively update the filter list, I encountered a program crash.

**Comment by Sakura-Luna** [comment] 2022-12-23 03:18
@EugeneOne1 I removed the part at the end of the list and started AGH, which loaded it directly, causing the problem to recur.

**Comment by EugeneOne1** [comment] 2022-12-23 08:08
@Sakura-Luna, what exactly do you mean by "actively update the filter list"?  Do you mean pushing the updating button several times within a short period of time?  Could you please collect a [verbose log](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) capturing the crash for us?  You may send it to devteam@adguard.com, this would really help to troubleshoot further, thanks.

Also, which file have you edited manually (removed the part at the end)?  Was it within the AdGuard Home's working directory under `<WD>/data/filters` or the actual file used to create custom list?

**Comment by Sakura-Luna** [comment] 2022-12-23 13:27
@EugeneOne1 Not used many times, just press the update button once, AGH has a certain chance to crash after a few minutes, due to network problems, updating to a large list is prone to occur. I have checked the run.log, and there are only logs that are automatically restarted after a crash.

I deleted the end of a list file under the filter path, and loaded it directly after starting AGH. If a "||www" is left at the end of the line, a batch of websites cannot be accessed. This is a problem I had before. AGH requires a feature to support completeness or validity checking of lists.

**Comment by EugeneOne1** [comment] 2022-12-23 15:07
@Sakura-Luna, actually the `||www` is a valid rule matching any domain having a label which starts with `www`.  I don't really think there is a way to distinguish such "broken" lists from valid ones.  I mean AdGuard Home assumes the local rule lists are always valid since is not intended to work within the setup suffering from recurring data corruption.

However, I believe we're able to validate the data transmission status.  Particularly, AdGuard Home now requires each rule in the list to be trailed with `\n`, so that other rules (e.g. not fully transmitted) are ignored.

As for the crash, unfortunatelly, we cannot reproduce it, probably because it seems to require some specific network conditions.  That's why we'd really like to look at your verbose log.  Sorry, I didn't notice that you're using docker.  The `log_file` there should point inside the working directory to expose it outside the container.  On each restart AdGuard Home will just append the new lines at the end.

**Comment by Sakura-Luna** [comment] 2022-12-23 15:34
@EugeneOne1 I know, the "||www" is just an example, what I actually encountered before was "||4", which caused me to spend a few hours before I found out that the list was wrong. I don’t know whether the current AGH can guarantee that every update is a valid list, so I proposed the need for integrity verification. Like Goodbye Ads, there are rules at the beginning and comments at the end, so it is not difficult, of course, maybe not all of them can As such, can be a feature.

**Comment by EugeneOne1** [comment] 2022-12-23 15:53
@Sakura-Luna, I think it makes sense to open a new feature request for that and focus on the crash here.

**Comment by Sakura-Luna** [comment] 2022-12-23 16:03
@EugeneOne1 I rechecked the logs and think the crash is not an AGH issue, it might be that the reload list is taking too much CPU and being restarted by Docker, unfortunately I'm not likely to verify it. AGH's regular update is rarely a problem.

**Comment by EugeneOne1** [comment] 2022-12-26 08:13
@Sakura-Luna, well, the original issue seems solved, so I'll close the issue if you don't mind.  Could you please fill a separate one for the feature request, this is to keep topics as atomic as possible and to simplify the search.

**Closed by EugeneOne1** 2022-12-26 08:13 UTC
Labels: bug, waiting for data, P3: Medium
