### ISSUE TITLE
Add green logo back

### ISSUE THREAD

**Issue by Dynasty-Dev** [AdguardTeam/AdGuardHome#4412] opened 2022-03-20 06:59 UTC
On the adguard home dashboard you should replace the black adguard logo with the old adguard green one that you used before as it looks cleaner. Also will there be dark mode added in 0.108.0?

**Comment by fernvenue** [comment] 2022-03-20 12:36
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/613.

**Comment by gyCfjSnO** [comment] 2022-03-21 09:56
> Duplicate of #613.

Disagree the main query OP is asking about is the logo 🤪

PS. Are you the duplicate police?

**Comment by fernvenue** [comment] 2022-03-21 21:20
> > Duplicate of #613.
> 
> Disagree the main query OP is asking about is the logo 🤪
> 
> PS. Are you the duplicate police?

As you can see, the logo changes have also been discussed in https://github.com/AdguardTeam/AdGuardHome/issues/613, the author of the issue has clearly mentioned the logo problem in the description.

**Comment by EugeneOne1** [comment] 2022-03-30 15:25
@gyCfjSnO, hello.  The dark mode is planned to **v0.108.0**.  We'll consider your suggestion during the redesign, but I'll close the issue for now as a duplicate.

**Closed by EugeneOne1** 2022-03-30 15:25 UTC
