### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yikexiaoyao** [AdguardTeam/AdGuardHome#2680] opened 2021-02-13 14:43 UTC
Error: control/filtering/refresh | filters update procedure is already running | 500

**Comment by ameshkov** [comment] 2021-02-15 07:35
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) AdGuard Home to write verbose-level log.
2. Reproduce the issue.
3. Post the log file here.

**Comment by alexpovel** [comment] 2021-02-15 19:24
Duplicate of #2671 (of which #2687 is also a duplicate)?

**Closed** 2021-02-16 09:54 UTC
Labels: waiting for data
