### ISSUE TITLE
Flag for updating from the command line

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#4223] opened 2022-01-28 12:36 UTC
(Split from #4219).

We need a command line flag to perform an update *without* the need to enable / use the Web API.  Something like `./AdGuardHome --update`.

**Comment by Vexz00** [comment] 2022-11-23 15:32
How exactly does this work now? I use the `--update` option and the console seems to be stuck doing nothing.
Shouldn't it be checking for an update and if there is no update available telling something like "There's no new update." or something? It's confusing to me.

**Comment by webmihir** [comment] 2022-11-24 17:26
> How exactly does this work now? I use the `--update` option 

Same question. I am trying to see if I can integrate this into a nightly CRON job by calling `/opt/AdguardHome/AdguardHome --update`. However similar to the previous poster's observation, the console is stuck and never returns.

**Comment by Vexz00** [comment] 2022-11-24 20:25
> I am trying to see if I can integrate this into a nightly CRON job by calling `/opt/AdguardHome/AdguardHome --update`.

That was exactly my plan but I think it's just an argument when launching AGH and it will automatically update AGH when it finds an update. Not quite what I was looking for because I don't want to run into DNS query timeouts when I actively need AGH during the day.

**Comment by elandorr** [comment] 2022-12-07 15:50
Same here. The description in `--help` says it will update and exit, but it does literally nothing.

My 'workflow' is as follows for windows clients if anyone cares:

1. see new stable on git
2. download
3. verify sig
4. `AdGuardHome.exe -s uninstall`
5. replace file
6. `AdGuardHome -s install --no-check-update` (installs the service with `-s run --no-check-update`)

Automatic connections are unwanted here.

An improvement would be:

1. see new stable on git
2. run `AdGuardHome.exe --update`
3. agh downloads and verifies the signature
4. agh replaces itself and keeps the `--no-check-update` flag for the service

Cheers

**Comment by wesley800** [comment] 2022-12-12 19:19
LOL seems not usable at all. I'm stucked too.

**Comment by EugeneOne1** [comment] 2023-01-09 11:34
@Vexz00, @webmihir, @elandorr, @wesley800, hello y'all.  We've published the `edge` release which should fix the `--update` flag.  Could you please check it out?  Also keep in mind that the proper update needs the next release to be published, however AdGuard Home now shouldn't freeze even in case the release is absent.

**Comment by EugeneOne1** [comment] 2023-01-17 14:08
Well, I'll close the issue for now if you don't mind, since we've been able to succesfully test it on our machines.  Please feel free to reopen it if you'll face any issues with our fixed implementation.

**Closed by EugeneOne1** 2023-01-17 14:08 UTC
Labels: feature request, P3: Medium

**Comment by webmihir** [comment] 2023-01-17 15:22
> Well, I'll close the issue for now if you don't mind, since we've been able to succesfully test it on our machines. Please feel free to reopen it if you'll face any issues with our fixed implementation.

I'm sorry I forgot to respond over there long weekend. Yes I can confirm this is working on edge. Looking forward to this making it's easy to 108 along with the actual fix!

**Comment by elandorr** [comment] 2023-01-18 06:17
Thanks, I'll test it on the next update as well!

**Comment by Vexz00** [comment] 2023-01-20 14:35
Sorry for the late reply. I tried it earlier today and it looks like it would work if there was a new update available.

But I have one question left: Will it update an already running instance of AGH so we can make a cron job to automatically update and completely forget about it? This would be a dream come true since this would mean I wouldn't have to do anything anymore and AGH is always up to date.

**Comment by EugeneOne1** [comment] 2023-01-20 14:47
@Vexz00, it'll actually only try to restart the service if the one installed.

**Comment by elandorr** [comment] 2023-02-06 17:01
I tested it today with the new update.

- If run with root permissions, the service definition is not touched, so the `--no-check-update` stays intact.
- If run without root permissions, the error message about the service is wrong, but it couldn't know any better. It did finish and replace the binary I think, but it can't have restarted the service, so it'll probably crash sooner or later.

Seems like it works fine. You can update when you explicitly want to update, without additional unwanted network activity, and without manually visiting github/unpacking/etc.

Does this verify signature based on the initial binary, though? That seems pretty critical.

We set it up once, verify your sig, and it then continues to rotate. Otherwise, if you're ever taken over, having this without human oversight seems risky. If you do it manually, there's a bigger chance you may notice the github repo is weird.

**Comment by ainar-g** [comment] 2023-02-06 17:03
@elandorr, please file a separate issue about that.

**Comment by elandorr** [comment] 2023-02-06 17:22
About what? This is just the promised feedback for when there's a new update.

**Comment by Vexz00** [comment] 2023-02-16 13:30
> @Vexz00, it'll actually only try to restart the service if the one installed.

And that's fine because with the start of the service an instance of AGH is started too. That means when there's a new update it'll install the update and restart the service which also restarts AGH. Everything is working fine this way. Only a manually started instance of AGH doesn't get restarted.
