### ISSUE TITLE
Need to query log export feature in GUI

### ISSUE THREAD

**Issue by locrianmod** [AdguardTeam/AdGuardHome#6278] opened 2023-10-04 07:53 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Might be good query txt or csv log export option over GUI. 

### Proposed solution

In manually I used for log export from ssh, 

used command, 

`AdGuardHome/data/querylog.json | jq -r '[.QH, .IP, .Result.'IsFiltered'] | @csv' > /AdGuardHome/data/querylog_parse.txt`

gives following output with below format, 

```
"www.google.com","192.168.10.10",true
"g.whatsapp.net","192.168.10.12",
"mediaservices.cdn-apple.com","192.168.10.12",
"www.google.com","192.168.10.15",
"doh-fi.blahdns.com","192.168.10.15",true
```

**Comment by ainar-g** [comment] 2023-10-04 11:38
Duplicate of #3389

**Closed by ainar-g** 2023-10-04 11:38 UTC
Labels: feature request
