### ISSUE TITLE
[Feature Request] Auto Generate Config - Install Option

### ISSUE THREAD

**Issue by alec-hs** [AdguardTeam/AdGuardHome#4435] opened 2022-03-27 01:31 UTC
### Problem Description
I deploy AdGuard Home using a script that installs then setups up LetsEncrypt certs using Cloudflare DNS challenge. This all works fine but I have to pause in the middle of the script to prompt the user to go to the Web Gui and complete the setup. 

I would like there to be an install option or even a post install option to generate the AdGuardHome.yaml config file with either a default or random password. 

### Proposed Solution
When running the install script or post install - have an option to generate default config yaml file.

### Alternatives Considered
I have setup a clean version of AdGuard Home and exported the config yaml file. I could add that to my script and create it on the target machine but this relies on me checking to make sure there have been no updates to the format of the config. 

### Additional Information
Here is my current install script for reference.
```bash
#!/bin/bash

# To be run as user with sudo permissions
# Will install adguard home with DNS on port 53 and admin portal on port 443 using LetsEncrypt for SSL
# Requires Cloudflare API Token with Zone:Zone:Read and Zone:DNS:Edit permissions

# Install Adguard Home
sudo curl -s -S -L https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -v

# Install LetsEncrypt dependencies and setup folders/files
sudo apt update -y
sudo apt install certbot python3-certbot-dns-cloudflare -y
sudo mkdir /root/.secrets/ 
sudo touch /root/.secrets/cloudflare.ini 
sudo chmod 0700 /root/.secrets/
sudo chmod 0400 /root/.secrets/cloudflare.ini

# Get info from user needed for certbot
read -p "Enter Cloudflare API token: " api_key
read -p "Enter FQDN for web admin: " domain
read -p "Enter email for LetsEncrypt updates: " email
echo "dns_cloudflare_api_token = $api_key" | sudo tee -a /root/.secrets/cloudflare.ini

# Request cetrtificate
sudo certbot certonly --dns-cloudflare --dns-cloudflare-credentials /root/.secrets/cloudflare.ini -d $domain --preferred-challenges dns-01 -n --agree-tos --email $email

# Ask user to setup basic settings
hostname=hostname
read -rsp $'
Please go to http://'$hostname':3000 and complete basic setup...
When done press any key to continue.
' -n1 key

# Setup Adguard Home config
certpath="/etc/letsencrypt/live/$domain/fullchain.pem"
keypath="/etc/letsencrypt/live/$domain/privkey.pem"
sudo sed -i 'N;s+tls:\n  enabled: false+tls:\n  enabled: true+g' /opt/AdGuardHome/AdGuardHome.yaml
sudo sed -i 's+certificate_path: ""+certificate_path: '$certpath'+g' /opt/AdGuardHome/AdGuardHome.yaml
sudo sed -i 's+private_key_path: ""+private_key_path: '$keypath'+g' /opt/AdGuardHome/AdGuardHome.yaml
sudo sed -i 's+server_name: ""+server_name: '$domain'+g' /opt/AdGuardHome/AdGuardHome.yaml
sudo sed -i 's+force_https: false+force_https: true+g' /opt/AdGuardHome/AdGuardHome.yaml
sudo service AdGuardHome restart
```

**Comment by fernvenue** [comment] 2022-03-27 06:07
> ...but this relies on me checking to make sure there have been no updates to the format of the config.

That seems reasonable, because almost every version of AdGuardHome adds new features, which means the configuration file is changing. But for the security of your users, especially if you're helping your users expose the admin portal on the public network, so I don't think adding a default password is a good idea. Random password sound's not bad but a script **should not** make its own decisions on anything about security right?

**Comment by mdawsonuk** [comment] 2022-03-27 11:20
> Random password sound's not bad but a script **should not** make its own decisions on anything about security right?
Unless it's configuring security best-practices 😄 

I want to say this issue is a duplicate of one I've seen before, but after searching I can't find it...

**Comment by alec-hs** [comment] 2022-03-27 20:05
> because almost every version of AdGuardHome adds new features, which means the configuration file is changing

Yep - this is why it would be great to have AdGuard Generate the file at the install stage - let us complete the steps that we normally complete on http://ip:3000 in the CLI - this way it gets round the security concerns. 

> I don't think adding a default password is a good idea. Random password sound's not bad but a script should not make its own decisions on anything about security right?

Yes and yes, random is good user input is better - since the password can be generated with htpasswd I don't think it would be too much to have apache2-utils as a requirment to use a setup with CLI feature.

>  I've seen before, but after searching I can't find it...

Yeah I did look but couldn't find anything related.

**Comment by mercyground** [comment] 2022-04-04 01:43
Might have been one of my posts regarding OpenWrt and the choosing of reasonable defaults. I was musing on ways to "prefill" in order to automate opkg installs of the AGH package. At present we presetup some stuff and then you step through AGH install once it is up. Having some way to either pass variables to AGH that it then fills into its yaml file or even just making a mini yaml file that AGH parses and writes to its main file was something i was wondering.

https://forum.openwrt.org/t/how-to-updated-2021-installing-adguardhome-on-openwrt/113904

https://openwrt.org/docs/guide-user/services/dns/adguard-home

**Comment by mercyground** [comment] 2022-04-21 16:32
https://github.com/AdguardTeam/AdGuardHome/issues/4199

Its actually part of the 108 build tree to do.

**Comment by ainar-g** [comment] 2022-04-21 17:15
Yes, I'll merge it into that one.  Thanks.

**Closed by ainar-g** 2022-04-21 17:15 UTC
