### ISSUE TITLE
dont cache for specifying upstream

### ISSUE THREAD

**Issue by Bitcion** [AdguardTeam/AdGuardHome#6363] opened 2023-10-28 23:11 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Upstream DNS queries on UDP port 53 may not necessarily be secure, and UDP53 should not be cached to use

### Proposed solution

dont cache for specifying upstream DNS

**Comment by ainar-g** [comment] 2023-10-30 09:42
Seems like a duplicate of the issue you've reported before?  #5164.

**Closed by ainar-g** 2023-10-30 09:42 UTC
Labels: feature request
