### ISSUE TITLE
Can't filter any ads

### ISSUE THREAD

**Issue by cdwmhcc** [AdguardTeam/AdGuardHome#679] opened 2019-03-28 17:04 UTC
I have set the DNS of my router to DNS 192.168.50.1 in the AdGuard Home Wizard.

But can't filter any ads

There are detailed images in this Google Drive link below.

https://drive.google.com/drive/folders/1kWlFzXuUr4fHaZaCfRyZ5Wxv0ay6_oXC?usp=sharing

**Comment by ameshkov** [comment] 2019-03-28 20:36
Duplicate of #677

**Closed by ameshkov** 2019-03-28 20:36 UTC
