### ISSUE TITLE
Last version requires arp to be installed or DNS resolution takes +4000ms

### ISSUE THREAD

**Issue by cloudz** [AdguardTeam/AdGuardHome#1486] opened 2020-03-17 17:46 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

I'm running 2 instances on 2 separate minimal Debian Buster nodes in Proxmox

After the update to v0.101.0 I noticed a serious performance hit on the network. Queries that normally took 40 > 60ms now suddenly took +4000ms.

Running parallel queries over UDP53 to Quad9 & Cloudflare 

It was easily fixed by manually installing the network tools that included arp as a command on Debian Buster. Before this update all worked fine. 

Maybe you can add this as a required piece of software on the box.

**Comment by ameshkov** [comment] 2020-03-17 19:50
Hm, weird, I don't understand where it came from.

Could you please reproduce the issue and collect AGH verbose logs?

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by cloudz** [comment] 2020-03-17 20:05
Running it now. It took a few hours before it got started yesterday too. As soon as it does it again, I'll drop the log here.

**Comment by ameshkov** [comment] 2020-03-17 20:14
We had some issues with AdGuard DNS in the morning. If you have browsing security or parental control enabled, this may have caused the slowdown.

**Comment by cloudz** [comment] 2020-03-17 20:15
Ah. That explains a ton -- and a stupid coming together of possible solutions.

**Comment by ameshkov** [comment] 2020-03-17 20:18
Yeah:)

Closing it for now then.

**Comment by ArchiveBase** [comment] 2020-03-18 06:19
> We had some issues with AdGuard DNS in the morning: https://twitter.com/AdGuard/status/1239849374706028547
> 
> If you have browsing security or parental control enabled, this may have caused the slowdown.

Status page?

**Comment by ameshkov** [comment] 2020-03-18 10:25
> Status page?

https://status.adguard.com/

**Comment by ArchiveBase** [comment] 2020-03-18 11:34
But no link on adguard.com homepage, footer or search engines havent recognized that page

https://www.site24x7.com/site24x7-pricing.html also better than https://www.statuspage.io because cheap, more features and [detailed status page](https://status.zoho.com/#/components/Di-skrVIo8k_NnBP_JkW-JqyndzfkikY5mmQX-NxJPLPERZS53tRqnPyVWUp95El) for each components

**Comment by ameshkov** [comment] 2020-03-20 14:34
> But no link on adguard.com homepage footer or somewhere else. Search engines havent recognized that page too

Yeah, we'll add it.

> https://www.site24x7.com/site24x7-pricing.html also better than https://www.statuspage.io because cheap, more features and has detailed status page for each components however it's bit complicated so test 30days before buy (if really prefer)

Well, the same is possible with statuspage, it's just we would like to keep it simple (until we really need that).

**Closed** 2020-03-20 22:10 UTC
Labels: question
