### ISSUE TITLE
no answer after enable upstream_dns_file

### ISSUE THREAD

**Issue by catsimple** [AdguardTeam/AdGuardHome#6006] opened 2023-07-13 11:59 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

openwrt (linux 5.15.116) /AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

issue occurred higher than 0.107.29

### Action

upgrage version higher than 0.107.29 and enable "upstream_dns_file" .

### Expected result

DNS query anwser from ADG.

### Actual result

I can got dns anwser from the first few seconds after ADG started, but few seconds after no anwser from ADG. The front end of ADG still works but no dns anwser.

### Additional information and/or screenshots

The dnsfile I specified: [ChinaList.txt](https://github.com/AdguardTeam/AdGuardHome/files/12039050/ChinaList.txt)
LOG file : [AdGuardHome2.log](https://github.com/AdguardTeam/AdGuardHome/files/12039091/AdGuardHome2.log)

**Comment by ainar-g** [comment] 2023-07-13 12:44
Thank you for the report and the verbose log!  We cannot reproduce the issue, but based on the information in the log we have a few theories:

* Does the issue go away if you do not use `upstream_dns_file` and just put some upstreams into the upstreams field in the UI?
* Does the issue go away if you set `clients.runtime_sources.rdns` and `clients.runtime_sources.whois` to `false`?

**Comment by catsimple** [comment] 2023-07-13 13:01
> Thank you for the report and the verbose log! We cannot reproduce the issue, but based on the information in the log we have a few theories:
> 
> * Does the issue go away if you do not use `upstream_dns_file` and just put some upstreams into the upstreams field in the UI?
> * Does the issue go away if you set `clients.runtime_sources.rdns` and `clients.runtime_sources.whois` to `false`?

- issue did not go away when I just put some upstreams into the upstreams field in the UI.
- issue go away when I you set clients.runtime_sources.rdns and clients.runtime_sources.whois to false.

**Comment by duckxx** [comment] 2023-07-13 13:24
这问题我也遇到过，会导致开启adguardhome后等半个小时，dns解析器都不进入工作状态，但是管理页面可以进入。后来就放弃用分流文件形式了，就算成功启动了，前几分钟的dns解析延迟高达5000ms。

**Comment by ainar-g** [comment] 2023-07-13 13:26
@catsimple, I see, thank you for the information.  We'll look into it.

**Comment by duckxx** [comment] 2023-07-13 13:43
> @catsimple, I see, thank you for the information. We'll look into it.

触发bug条件是拥有一个运行很久并且有人使用的adguardhome，并按反馈者设置，新建的adguardhome是很难一下子触发。因为在此之前服务器满载的bug缓解的办法就是重新安装adguardhome。

**Comment by catsimple** [comment] 2023-07-14 12:33
> 

I did meet a problem today even I downgraded to 107.29 before. ADG would not give any dns query answer randomly.

**Comment by catsimple** [comment] 2023-07-14 12:37
> > @catsimple, I see, thank you for the information. We'll look into it.
> 
> 触发bug条件是拥有一个运行很久并且有人使用的adguardhome，并按反馈者设置，新建的adguardhome是很难一下子触发。因为在此之前服务器满载的bug缓解的办法就是重新安装adguardhome。

不清楚，我在用107.29之后的版本，即使是全新配置的yaml，只要一指定dns上游文件就崩，用107.29就没问题，但是今天107.29用久了也遇到同样的问题了

**Comment by ainar-g** [comment] 2023-07-18 16:14
@catsimple, could you please check the recent versions on the Edge channel?  If the issue still persists, please send us the new verbose logs from that version as well.

**Comment by catsimple** [comment] 2023-07-25 03:36
> @catsimple, could you please check the recent versions on the Edge channel? If the issue still persists, please send us the new verbose logs from that version as well.

seems problem still, I received many errors from docker

`Tue Jul 25 11:31:36 2023 daemon.err dockerd[3621]: time="2023-07-25T11:31:36.734071112+08:00" level=error msg="[resolver] failed to query DNS server: 127.0.0.1:53, query: ;o1098464.ingest.sentry.io.\tIN\t A" error="read udp 127.0.0.1:37577->127.0.0.1:53: i/o timeout"
Tue Jul 25 11:31:37 2023 daemon.err dockerd[3621]: time="2023-07-25T11:31:37.061673371+08:00" level=error msg="[resolver] failed to query DNS server: 127.0.0.1:53, query: ;plogin.m.jd.com.\tIN\t A" error="read udp 127.0.0.1:49128->127.0.0.1:53: i/o timeout"
Tue Jul 25 11:31:37 2023 daemon.err dockerd[3621]: time="2023-07-25T11:31:37.861543666+08:00" level=error msg="[resolver] failed to query DNS server: 127.0.0.1:53, query: ;o1098464.ingest.sentry.io.\tIN\t A" error="read udp 127.0.0.1:39694->127.0.0.1:53: i/o timeout"
Tue Jul 25 11:31:40 2023 daemon.err dockerd[3621]: time="2023-07-25T11:31:40.735355257+08:00" level=error msg="[resolver] failed to query DNS server: 127.0.0.1:53, query: ;o1098464.ingest.sentry.io.\tIN\t A" error="read udp 127.0.0.1:42253->127.0.0.1:53: i/o timeout"
Tue Jul 25 11:31:41 2023 daemon.err dockerd[3621]: time="2023-07-25T11:31:41.062177329+08:00" level=error msg="[resolver] failed to query DNS server: 127.0.0.1:53, query: ;plogin.m.jd.com.\tIN\t A" error="read udp 127.0.0.1:46372->127.0.0.1:53: i/o timeout"
Tue Jul 25 11:31:41 2023 daemon.err dockerd[3621]: time="2023-07-25T11:31:41.863083416+08:00" level=error msg="[resolver] failed to query DNS server: 127.0.0.1:53, query: ;o1098464.ingest.sentry.io.\tIN\t A" error="read udp 127.0.0.1:59257->127.0.0.1:53: i/o timeout"
Tue Jul 25 11:31:45 2023 daemon.err dockerd[3621]: time="2023-07-25T11:31:45.863528960+08:00" level=error msg="[resolver] failed to query DNS server: 127.0.0.1:53, query: ;o1098464.ingest.sentry.io.\tIN\t A" error="read udp 127.0.0.1:46253->127.0.0.1:53: i/o timeout"
Tue Jul 25 11:31:47 2023 daemon.err dockerd[3621]: time="2023-07-25T11:31:47.083418186+08:00" level=error msg="[resolver] failed to query DNS server: 127.0.0.1:53, query: ;plogin.m.jd.com.\tIN\t A" error="read udp 127.0.0.1:38596->127.0.0.1:53: i/o timeout"`

[Uploading AdGuardHome.log…]()

**Comment by catsimple** [comment] 2023-07-25 03:59
> @catsimple, could you please check the recent versions on the Edge channel? If the issue still persists, please send us the new verbose logs from that version as well.

seems problem still, I received many errors from docker

`Tue Jul 25 11:31:36 2023 daemon.err dockerd[3621]: time="2023-07-25T11:31:36.734071112+08:00" level=error msg="[resolver] failed to query DNS server: 127.0.0.1:53, query: ;o1098464.ingest.sentry.io.\tIN\t A" error="read udp 127.0.0.1:37577->127.0.0.1:53: i/o timeout"

Tue Jul 25 11:31:37 2023 daemon.err dockerd[3621]: time="2023-07-25T11:31:37.061673371+08:00" level=error msg="[resolver] failed to query DNS server: 127.0.0.1:53, query: ;plogin.m.jd.com.\tIN\t A" error="read udp 127.0.0.1:49128->127.0.0.1:53: i/o timeout"

Tue Jul 25 11:31:37 2023 daemon.err dockerd[3621]: time="2023-07-25T11:31:37.861543666+08:00" level=error msg="[resolver] failed to query DNS server: 127.0.0.1:53, query: ;o1098464.ingest.sentry.io.\tIN\t A" error="read udp 127.0.0.1:39694->127.0.0.1:53: i/o timeout"

Tue Jul 25 11:31:40 2023 daemon.err dockerd[3621]: time="2023-07-25T11:31:40.735355257+08:00" level=error msg="[resolver] failed to query DNS server: 127.0.0.1:53, query: ;o1098464.ingest.sentry.io.\tIN\t A" error="read udp 127.0.0.1:42253->127.0.0.1:53: i/o timeout"

Tue Jul 25 11:31:41 2023 daemon.err dockerd[3621]: time="2023-07-25T11:31:41.062177329+08:00" level=error msg="[resolver] failed to query DNS server: 127.0.0.1:53, query: ;plogin.m.jd.com.\tIN\t A" error="read udp 127.0.0.1:46372->127.0.0.1:53: i/o timeout"

Tue Jul 25 11:31:41 2023 daemon.err dockerd[3621]: time="2023-07-25T11:31:41.863083416+08:00" level=error msg="[resolver] failed to query DNS server: 127.0.0.1:53, query: ;o1098464.ingest.sentry.io.\tIN\t A" error="read udp 127.0.0.1:59257->127.0.0.1:53: i/o timeout"

Tue Jul 25 11:31:45 2023 daemon.err dockerd[3621]: time="2023-07-25T11:31:45.863528960+08:00" level=error msg="[resolver] failed to query DNS server: 127.0.0.1:53, query: ;o1098464.ingest.sentry.io.\tIN\t A" error="read udp 127.0.0.1:46253->127.0.0.1:53: i/o timeout"

Tue Jul 25 11:31:47 2023 daemon.err dockerd[3621]: time="2023-07-25T11:31:47.083418186+08:00" level=error msg="[resolver] failed to query DNS server: 127.0.0.1:53, query: ;plogin.m.jd.com.\tIN\t A" error="read udp 127.0.0.1:38596->127.0.0.1:53: i/o timeout"
`

[AdGuardHome.log](https://github.com/AdguardTeam/AdGuardHome/files/12156952/AdGuardHome.log)

**Comment by ainar-g** [comment] 2023-07-26 10:33
@catsimple, thank you for the informative logs.  The new logs we've added point at one of the issues:

```none
[debug] whois: received response (2135 bytes) from "whois.apnic.net:43" about "[IPv6 address]"
[debug] clients: finished processing [IPv6 address] with whois in 37.89008224s
```

It seems like the WHOIS lookup sometimes gets stuck and lasts over 30 seconds, which is a very long time.  Additionally, the log has lots of these:

```none
[debug] upstream [IPv4 address]:53 failed to exchange ;www.youtube.com.	IN	 A in 20.002065543s: exchanging with [IPv4 address]:53 over udp: read udp [IPv4 address]:37835->[IPv4 address]:53: i/o timeout
[debug] proxy: replying from upstream: rtt is 20.002116193s
```

Again, 20 seconds is a very long time, so my guess is that there is something wrong with your connection to some upstreams.  So you should probably disable WHOIS resolving of clients and either choose a different upstream or lower the `dns.upstream_timeout` value in the configuration file so that these stuck queries are retried by clients quicker.

Since these don't seem like bugs in AdGuard Home, I'll close the issue, if you don't mind.

**Closed by ainar-g** 2023-07-26 10:33 UTC
Labels: bug, P3: Medium
