### ISSUE TITLE
Clearing query logs raises panic: Runtime error

### ISSUE THREAD

**Issue by mediclab** [AdguardTeam/AdGuardHome#6327] opened 2023-10-18 14:39 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

Docker

### Setup

Other (please mention in the description)

### AdGuard Home version

v0.107.39

### Action

In General settings click on button "Clear query logs"

### Expected result

Contaimer continue running. Query log cleared

### Actual result

Container restarted, because of runtime error. Query log not cleared.
![image](https://github.com/AdguardTeam/AdGuardHome/assets/1334139/fd2cf431-4f50-41ac-bbb5-aed3261da939)

### Additional information and/or screenshots

Installation: Synology DS920+ with DSM 7.2-64570 Update 1
Installed in Container Manager with Docker

**Comment by ainar-g** [comment] 2023-10-18 15:08
Duplicate of #6304

**Closed by ainar-g** 2023-10-18 15:08 UTC
