### ISSUE TITLE
does not load filters from the blocklist site

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdGuardHome#881] opened 2019-07-13 14:27 UTC
does not load filters from the site https://blocklist ahhh!site/app/dl/ads 

1. add filter from https://blocklist ahhh!site/app/dl/ads
2.  Error: control/filtering/add_url | Couldn't fetch filter from url https://blocklist.site/app/dl/ads: non-text response | 400

### Expected behavior
load filter

### Actual behavior
error

| Version of AdGuard Home server:| 0.97
| If it's a router or IoT, please write device model:| Raspberry Pi 3 Model B+
| Operating system and version:| Raspbian Buster

**Comment by ameshkov** [comment] 2019-07-14 19:31
Duplicate of #527

**Closed by ameshkov** 2019-07-14 19:31 UTC
Labels: duplicate
