### ISSUE TITLE
Users (multiple, none)

### ISSUE THREAD

**Issue by ErSpieltHD** [AdguardTeam/AdGuardHome#3158] opened 2021-05-17 12:45 UTC
So I don't see the point of having a username field on the AdGuardHome Dashboard because
a) you can't create multiple users
b) I'm using it AGH on my own and there is no need to have a username field

Could you make us able to remove usernames and create multiple users (I don't need multiple but what else is the username field for?)

thx

**Comment by ainar-g** [comment] 2021-05-17 13:19
I think that multiple users is something that we want to support in the v1 API, but I'm not sure.  The only mention I've found so far is discussion #3129.  @ameshkov, do we plan on supporting multiple users, possibly with some sort of ACL?

**Comment by ErSpieltHD** [comment] 2021-05-17 17:25
As I've said I would want to have no user at all. At least till it has no real use. But as I've said I won't use it with multiple users anyways so I want it gone.

**Comment by Aikatsui** [comment] 2021-05-17 18:45
> I think that multiple users is something that we want to support in the v1 API, but I'm not sure. The only mention I've found so far is discussion #3129. @ameshkov, do we plan on supporting multiple users, possibly with some sort of ACL?

See https://github.com/AdguardTeam/AdGuardHome/issues/997 (I lost that account)

**Comment by ainar-g** [comment] 2021-05-18 09:43
@Aikatsui, thanks!

@ErSpieltHD, we'll probably go the multiple users route in the future, so I'll mark this as a duplicate of the issue that Akatsui has linked.  With that said, we'll probably consider hiding the username if there is only one user.  Thanks.

**Closed by ainar-g** 2021-05-18 09:43 UTC
