### ISSUE TITLE
[QUESTION] is it possible have a path to a certificate?

### ISSUE THREAD

**Issue by Omoeba** [AdguardTeam/AdGuardHome#902] opened 2019-07-28 00:40 UTC
I have an Nginx server that includes auto-updating the letsencrypt certificate. Is it possible to use a path to the certificate instead of copy and pasting to AdGuardHome?

**Comment by Akruidenberg** [comment] 2019-07-28 09:10
+this is my most wanted feature. Frustrated to update changes from new certificate.

**Comment by szolin** [comment] 2019-07-29 12:42
duplicate of #634

**Comment by ameshkov** [comment] 2019-08-04 13:50
Closed as dup

**Closed by ameshkov** 2019-08-04 13:50 UTC
Labels: duplicate
