### ISSUE TITLE
Syncing between two or more AdGuard Home instances

### ISSUE THREAD

**Issue by hawkers89** [AdguardTeam/AdGuardHome#5583] opened 2023-03-11 05:49 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
Management of syncing between two or more AdGuard Home instances from within the UI

#### Proposed solution
Take the already existing AdGuardHome-Sync solution and incorporate it into AdGuard Home
https://github.com/bakito/adguardhome-sync

#### Alternatives considered
Using AdGuardHome-Sync but it would be good to include it within AdGuardHome and configure via the UI rather than yaml file

#### Additional information
None

**Comment by ainar-g** [comment] 2023-03-13 16:13
Duplicate of #573

**Closed by ainar-g** 2023-03-13 16:13 UTC
