### ISSUE TITLE
AdGuard Home v0.99.0 query log search timeout

### ISSUE THREAD

**Issue by kkkgo** [AdguardTeam/AdGuardHome#1102] opened 2019-10-21 05:19 UTC
In the lastest releases,
>Also, we conducted small research, and it clearly tells that the most interesting events usually lie between requests 5001-10000. So the query log is no more limited to the last 5000 records!

I tried to search for DNS records, but he timed out, I guess my DNS log data is too large and the search is difficult.

![log.jpg](https://i.loli.net/2019/10/21/kJgLj4UpAZ2dR83.jpg)

My DNS server generates about 100 query records per second.

**Comment by ameshkov** [comment] 2019-10-21 07:17
Huh, 100rps AGH server is unusual, I've assigned this to v0.100 then.

**Comment by szolin** [comment] 2019-10-22 12:13
It looks like a crash, is there anything unusual in logs (error messages, Go stack traces)?

**Comment by kkkgo** [comment] 2019-10-22 12:23
When I type google.com, one letter at a time, the search results below will gradually show up, but when I try to enter a longer domain name (www.google.com), the search results will show loading, then No response. After a while, a red tip will pop up in the lower right corner:
"Error: control/querylog?filter_domain=www.google.com&filter_client=&filter_question_type=&filter_response_status=&older_than= | Network Error"

**Comment by szolin** [comment] 2019-10-22 12:30
When you receive a "Network Error" it's may be caused by a crash of sub-process that handles UI request - that's why I need to see what's in application logs.

**Comment by kkkgo** [comment] 2019-10-22 12:36
I tried 
/home/adg/AdGuardHome -s run -l /root/debug.log
but he does not generate any log files

**Comment by szolin** [comment] 2019-10-22 12:37
try `./AdGuardHome -l debug.log`

**Comment by kkkgo** [comment] 2019-10-22 12:51
2019/10/22 20:44:19 381580#888 [debug] querylog: read 581 entries in 10.125543ms, 17.427µs/entry, seek-reqs:2
2019/10/22 20:44:21 381580#888 [debug] GET /control/querylog?filter_domain=www&filter_client=&filter_question_type=&filter_response_status=&older_than=
2019/10/22 20:44:21 381580#888 [debug] querylog: read 581 entries in 10.51459ms, 18.097µs/entry, seek-reqs:2
2019/10/22 20:44:22 381580#888 [debug] GET /control/querylog?filter_domain=www.&filter_client=&filter_question_type=&filter_response_status=&older_than=
2019/10/22 20:44:22 381580#888 [debug] querylog: read 581 entries in 11.385828ms, 19.596µs/entry, seek-reqs:2
2019/10/22 20:44:24 381580#888 [debug] GET /control/querylog?filter_domain=www.goog&filter_client=&filter_question_type=&filter_response_status=&older_than=
2019/10/22 20:44:24 381580#888 [debug] querylog: read 581 entries in 16.161341ms, 27.816µs/entry, seek-reqs:2
2019/10/22 20:44:24 381580#888 [debug] GET /control/querylog?filter_domain=www.goog&filter_client=&filter_question_type=&filter_response_status=&older_than=2019-10-22T20%3A42%3A25.925071721%2B08%3A00
2019/10/22 20:44:24 381580#888 [debug] querylog: read 244 entries in 6.378181ms, 26.14µs/entry, seek-reqs:11
2019/10/22 20:44:24 381580#888 [debug] GET /control/querylog?filter_domain=www.googl&filter_client=&filter_question_type=&filter_response_status=&older_than=2019-10-22T20%3A42%3A25.925071721%2B08%3A00
2019/10/22 20:44:24 381580#888 [debug] querylog: read 244 entries in 6.210793ms, 25.454µs/entry, seek-reqs:11
2019/10/22 20:44:25 381580#888 [debug] GET /control/querylog?filter_domain=www.google&filter_client=&filter_question_type=&filter_response_status=&older_than=
2019/10/22 20:44:25 381580#888 [debug] querylog: read 581 entries in 12.31206ms, 21.191µs/entry, seek-reqs:2
2019/10/22 20:44:25 381580#888 [debug] GET /control/querylog?filter_domain=www.google&filter_client=&filter_question_type=&filter_response_status=&older_than=2019-10-22T20%3A42%3A25.925071721%2B08%3A00
2019/10/22 20:44:25 381580#888 [debug] querylog: read 244 entries in 6.265182ms, 25.676µs/entry, seek-reqs:11
2019/10/22 20:44:25 381580#888 [debug] GET /control/querylog?filter_domain=www.google.&filter_client=&filter_question_type=&filter_response_status=&older_than=2019-10-22T20%3A42%3A25.925071721%2B08%3A00
2019/10/22 20:44:25 381580#888 [debug] querylog: read 244 entries in 6.372263ms, 26.115µs/entry, seek-reqs:11
2019/10/22 20:44:25 381580#888 [debug] GET /control/querylog?filter_domain=www.google.c&filter_client=&filter_question_type=&filter_response_status=&older_than=2019-10-22T20%3A42%3A25.925071721%2B08%3A00
2019/10/22 20:44:25 381580#888 [debug] querylog: read 244 entries in 5.971619ms, 24.473µs/entry, seek-reqs:11
2019/10/22 20:44:25 381580#903 [debug] GET /control/querylog?filter_domain=www.google.co&filter_client=&filter_question_type=&filter_response_status=&older_than=2019-10-22T20%3A42%3A25.925071721%2B08%3A00
2019/10/22 20:44:25 381580#903 [debug] querylog: read 244 entries in 7.040688ms, 28.855µs/entry, seek-reqs:11
2019/10/22 20:45:50 381580#5246 [error] Saving querylog to file failed: decoded buffer differs: [Result.IPList.slice[0].slice[0]: 0 != 10 Result.IPList.slice[0].slice[1]: 0 != 226 Result.IPList.slice[0].slice[2]: 0 != 100 Result.IPList.slice[0].slice[3]: 0 != 53 Result.IPList.slice[0].slice[4]: 0 != <no value> Result.IPList.slice[0].slice[5]: 0 != <no value> Result.IPList.slice[0].slice[6]: 0 != <no value> Result.IPList.slice[0].slice[7]: 0 != <no value> Result.IPList.slice[0].slice[8]: 0 != <no value> Result.IPList.slice[0].slice[9]: 0 != <no value>]
2019/10/22 20:46:00 381580#888 [debug] GET /control/querylog?filter_domain=&filter_client=&filter_question_type=&filter_response_status=&older_than=
2019/10/22 20:46:00 381580#888 [debug] querylog: read 581 entries in 11.487953ms, 19.772µs/entry, seek-reqs:1
2019/10/22 20:46:00 381580#800 [debug] GET /control/querylog_info
2019/10/22 20:46:08 381580#929 [debug] GET /control/querylog?filter_domain=w&filter_client=&filter_question_type=&filter_response_status=&older_than=
2019/10/22 20:46:08 381580#929 [debug] querylog: read 581 entries in 14.036972ms, 24.16µs/entry, seek-reqs:2
2019/10/22 20:46:09 381580#929 [debug] GET /control/querylog?filter_domain=ww&filter_client=&filter_question_type=&filter_response_status=&older_than=
2019/10/22 20:46:09 381580#929 [debug] querylog: read 581 entries in 13.29902ms, 22.889µs/entry, seek-reqs:2
2019/10/22 20:46:10 381580#929 [debug] GET /control/querylog?filter_domain=www&filter_client=&filter_question_type=&filter_response_status=&older_than=
2019/10/22 20:46:10 381580#929 [debug] querylog: read 581 entries in 13.556656ms, 23.333µs/entry, seek-reqs:2
2019/10/22 20:46:10 381580#929 [debug] GET /control/querylog?filter_domain=www.&filter_client=&filter_question_type=&filter_response_status=&older_than=
2019/10/22 20:46:10 381580#929 [debug] querylog: read 581 entries in 13.63011ms, 23.459µs/entry, seek-reqs:2
2019/10/22 20:46:11 381580#929 [debug] GET /control/querylog?filter_domain=www.g&filter_client=&filter_question_type=&filter_response_status=&older_than=
2019/10/22 20:46:11 381580#929 [debug] querylog: read 581 entries in 11.804019ms, 20.316µs/entry, seek-reqs:2
2019/10/22 20:46:11 381580#929 [debug] GET /control/querylog?filter_domain=www.g&filter_client=&filter_question_type=&filter_response_status=&older_than=2019-10-22T20%3A42%3A25.917395911%2B08%3A00
2019/10/22 20:46:11 381580#929 [debug] querylog: read 242 entries in 5.234598ms, 21.63µs/entry, seek-reqs:9
2019/10/22 20:46:12 381580#929 [debug] GET /control/querylog?filter_domain=www.go&filter_client=&filter_question_type=&filter_response_status=&older_than=
2019/10/22 20:46:12 381580#929 [debug] querylog: read 581 entries in 15.184052ms, 26.134µs/entry, seek-reqs:2
2019/10/22 20:46:12 381580#929 [debug] GET /control/querylog?filter_domain=www.go&filter_client=&filter_question_type=&filter_response_status=&older_than=2019-10-22T20%3A42%3A25.925071721%2B08%3A00
2019/10/22 20:46:12 381580#929 [debug] querylog: read 244 entries in 6.288998ms, 25.774µs/entry, seek-reqs:11
2019/10/22 20:46:13 381580#929 [debug] GET /control/querylog?filter_domain=www.goo&filter_client=&filter_question_type=&filter_response_status=&older_than=
2019/10/22 20:46:13 381580#929 [debug] querylog: read 581 entries in 12.704511ms, 21.866µs/entry, seek-reqs:2
2019/10/22 20:46:13 381580#929 [debug] GET /control/querylog?filter_domain=www.goo&filter_client=&filter_question_type=&filter_response_status=&older_than=2019-10-22T20%3A42%3A25.925071721%2B08%3A00
2019/10/22 20:46:13 381580#929 [debug] querylog: read 244 entries in 8.308553ms, 34.051µs/entry, seek-reqs:11
2019/10/22 20:46:14 381580#929 [debug] GET /control/querylog?filter_domain=www.goog&filter_client=&filter_question_type=&filter_response_status=&older_than=
2019/10/22 20:46:14 381580#929 [debug] querylog: read 581 entries in 12.750229ms, 21.945µs/entry, seek-reqs:2
2019/10/22 20:46:14 381580#929 [debug] GET /control/querylog?filter_domain=www.goog&filter_client=&filter_question_type=&filter_response_status=&older_than=2019-10-22T20%3A42%3A25.925071721%2B08%3A00
2019/10/22 20:46:14 381580#929 [debug] querylog: read 244 entries in 8.782249ms, 35.992µs/entry, seek-reqs:11
2019/10/22 20:46:14 381580#929 [debug] GET /control/querylog?filter_domain=www.googl&filter_client=&filter_question_type=&filter_response_status=&older_than=
2019/10/22 20:46:14 381580#929 [debug] querylog: read 581 entries in 12.944077ms, 22.278µs/entry, seek-reqs:2
2019/10/22 20:46:14 381580#929 [debug] GET /control/querylog?filter_domain=www.googl&filter_client=&filter_question_type=&filter_response_status=&older_than=2019-10-22T20%3A42%3A25.925071721%2B08%3A00
2019/10/22 20:46:14 381580#929 [debug] querylog: read 244 entries in 8.518546ms, 34.912µs/entry, seek-reqs:11
2019/10/22 20:46:15 381580#929 [debug] GET /control/querylog?filter_domain=www.google&filter_client=&filter_question_type=&filter_response_status=&older_than=
2019/10/22 20:46:15 381580#929 [debug] querylog: read 581 entries in 13.033376ms, 22.432µs/entry, seek-reqs:2
2019/10/22 20:46:15 381580#929 [debug] GET /control/querylog?filter_domain=www.google&filter_client=&filter_question_type=&filter_response_status=&older_than=2019-10-22T20%3A42%3A25.925071721%2B08%3A00
2019/10/22 20:46:15 381580#929 [debug] querylog: read 244 entries in 6.426806ms, 26.339µs/entry, seek-reqs:11
2019/10/22 20:46:15 381580#929 [debug] GET /control/querylog?filter_domain=www.google.&filter_client=&filter_question_type=&filter_response_status=&older_than=
2019/10/22 20:46:15 381580#929 [debug] querylog: read 581 entries in 12.923085ms, 22.242µs/entry, seek-reqs:2
2019/10/22 20:46:15 381580#929 [debug] GET /control/querylog?filter_domain=www.google.&filter_client=&filter_question_type=&filter_response_status=&older_than=2019-10-22T20%3A42%3A25.925071721%2B08%3A00
2019/10/22 20:46:15 381580#929 [debug] querylog: read 244 entries in 5.843033ms, 23.946µs/entry, seek-reqs:11
2019/10/22 20:46:16 381580#929 [debug] GET /control/querylog?filter_domain=www.google.c&filter_client=&filter_question_type=&filter_response_status=&older_than=
2019/10/22 20:46:16 381580#929 [debug] querylog: read 581 entries in 13.604064ms, 23.414µs/entry, seek-reqs:2
2019/10/22 20:46:16 381580#929 [debug] GET /control/querylog?filter_domain=www.google.c&filter_client=&filter_question_type=&filter_response_status=&older_than=2019-10-22T20%3A42%3A25.925071721%2B08%3A00
2019/10/22 20:46:16 381580#929 [debug] querylog: read 244 entries in 6.519804ms, 26.72µs/entry, seek-reqs:11
2019/10/22 20:46:17 381580#929 [debug] GET /control/querylog?filter_domain=www.google.co&filter_client=&filter_question_type=&filter_response_status=&older_than=
2019/10/22 20:46:17 381580#929 [debug] querylog: read 581 entries in 12.524904ms, 21.557µs/entry, seek-reqs:2
2019/10/22 20:46:17 381580#929 [debug] GET /control/querylog?filter_domain=www.google.co&filter_client=&filter_question_type=&filter_response_status=&older_than=2019-10-22T20%3A42%3A25.925071721%2B08%3A00
2019/10/22 20:46:17 381580#929 [debug] querylog: read 244 entries in 5.770175ms, 23.648µs/entry, seek-reqs:11
2019/10/22 20:49:23 381580#10318 [error] Saving querylog to file failed: decoded buffer differs: [Result.IPList.slice[0].slice[0]: 0 != 10 Result.IPList.slice[0].slice[1]: 0 != 226 Result.IPList.slice[0].slice[2]: 0 != 100 Result.IPList.slice[0].slice[3]: 0 != 53 Result.IPList.slice[0].slice[4]: 0 != <no value> Result.IPList.slice[0].slice[5]: 0 != <no value> Result.IPList.slice[0].slice[6]: 0 != <no value> Result.IPList.slice[0].slice[7]: 0 != <no value> Result.IPList.slice[0].slice[8]: 0 != <no value> Result.IPList.slice[0].slice[9]: 0 != <no value>]

**Comment by szolin** [comment] 2019-10-22 16:32
First of all there is a strange `[error] Saving querylog to file failed` messages but they are not related to this problem.

Everything looks normal to me - your `GET /control/querylog` requests are handled immediately.
What I need is to see the log messages at the moment you send your request and the moment when you receive the Network error.

Note: Please use `grep -i` next time and insert log as code for readability.

**Comment by kkkgo** [comment] 2019-10-23 02:36
![stop.gif](https://i.loli.net/2019/10/23/wUPHKJgBOhqDRuL.gif)

![666.png](https://i.loli.net/2019/10/23/XzPKFI4Um5BCsQx.png)

When I type a string over a certain length in the search box, the interface will get stuck, the display will load, and then time out.
But I can't find the query log record of www.google.com in the log. The log has no other errors except the above similar error.
Because my DNS server is running, the logs are so large that I can't post the full logs. But I observed the logs before and after, there is no relevant record, just as I did not perform the query log of www.google.com.

**Comment by szolin** [comment] 2019-10-24 12:28
That's very strange - as if like the server doesn't receive the last request with the final `m`.
I can't reproduce on my side - can you post a screenshot of these requests using your browser developer tools?

**Comment by ameshkov** [comment] 2019-10-24 12:33
@kkkgo just in case, could it be some browser extension blocking google.com?

**Comment by kkkgo** [comment] 2019-10-24 12:49
![chrome.png](https://i.loli.net/2019/10/24/tvzi54wUZaMsyI3.png)

**Comment by szolin** [comment] 2019-10-24 12:55
Do other requests work while this request is in `pending` status?  For example, can you go to dashboard - does everything load fine?
Are there any other examples except for www.google.com that cause this behaviour?

**Comment by ameshkov** [comment] 2019-10-24 13:52
Tbh, I have no idea how this can happen. Does this happen with `www.google.com` only?

**Comment by kkkgo** [comment] 2019-10-25 14:10
After some tests, it seems that only the google domain name is like this, my DNS server is also used as sniproxy, some google domain name  is resolved to the DNS ip (this step is upstream of AdGuard), I dont know if this will affect the query.

**Comment by ameshkov** [comment] 2019-10-31 12:48
@kkkgo check what's going on inside Chrome: chrome://net-export

**Closed** 2019-11-06 15:08 UTC
Labels: cannot reproduce
