### ISSUE TITLE
Exceptions for the “Disable resolving of IPv6 addresses” feature

### ISSUE THREAD

**Issue by denymz** [AdguardTeam/AdGuardHome#6330] opened 2023-10-19 02:36 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

When I have enabled the "Disable resolving of IPv6 addresses" feature, if I encounter single-stack websites with only IPv6 resolution results, I would like to provide an option for users to decide whether to allow the return of these IPv6 resolution results.

### Proposed solution

Offer an option below 'Disable resolving of IPv6 addresses' for users to switch.

**Comment by ainar-g** [comment] 2023-10-19 11:39
Note that you can already achieve something similar with e.g.:

```AdBlock
*$dnstype=AAAA,dnsrewrite=NOERROR
@@|www.google.com$dnstype=AAAA,dnsrewrite
```

**Comment by denymz** [comment] 2023-10-20 01:29
> Note that you can already achieve something similar with e.g.:
> 
> ```AdBlock
> *$dnstype=AAAA,dnsrewrite=NOERROR
> @@|www.google.com$dnstype=AAAA,dnsrewrite
> ```

I think these are two completely different things. Because I don't know in advance whether a domain name only has ipv6 addresses returned.

**Comment by ainar-g** [comment] 2023-10-20 09:20
In that case, this sounds like a duplicate of #5577.

**Closed** 2023-11-07 10:49 UTC
Labels: waiting for data
