### ISSUE TITLE
AdGuard cpu 300%

### ISSUE THREAD

**Issue by myfreeqq** [AdguardTeam/AdGuardHome#3994] opened 2021-12-23 05:36 UTC
The CPU resource is full, AdGuard Home v0.107.0.

Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you install AdGuard Home:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ainar-g** [comment] 2021-12-23 11:14
Please fill out the full issue template to help us diagnose the issue.  We haven't seen anything like that in any of our test installations.

**Comment by ainar-g** [comment] 2021-12-29 19:04
Duplicate of #4042

**Closed by ainar-g** 2021-12-29 19:04 UTC
Labels: waiting for data
