### ISSUE TITLE
Allow Adding Multiple Filter Blocklists at One Time Rather Than One at a Time

### ISSUE THREAD

**Issue by DriftDevil** [AdguardTeam/AdGuardHome#4837] opened 2022-08-13 17:35 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
Currently have to either manually add the filter list via the Web or manually add a multiple list via the AdGuardHome.yaml file 

#### Proposed solution
Have an option to add multiple blocklist at the same time

#### Alternatives considered
Allow adding multiple lists by comma separated urls

**Comment by EugeneOne1** [comment] 2022-08-15 11:49
@DriftDevil, hello.  I suppose this is a duplicate of #522.

**Closed by EugeneOne1** 2022-08-15 11:49 UTC
