### ISSUE TITLE
Average upstream response time

### ISSUE THREAD

**Issue by 8680** [AdguardTeam/AdGuardHome#6581] opened 2023-12-24 10:33 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Average upstream response time，Can you sort from low latency to high latency by default?

### Proposed solution

Can add this option in the settings? This can be convenient for people with obsessive-compulsive disorder.:wink:

**Comment by agneevX** [comment] 2023-12-24 13:50
Current setting is just fine and goes with the column on the right. You can always click the column to change the sort order.

**Comment by schzhn** [comment] 2023-12-25 10:12
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/6190

**Closed by schzhn** 2023-12-25 10:12 UTC
Labels: feature request
