### ISSUE TITLE
Potential memory leak with 0.107 beta

### ISSUE THREAD

**Issue by agneevX** [AdguardTeam/AdGuardHome#3913] opened 2021-12-03 13:14 UTC
### Prerequisites

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.107.0-a.213+936a7057
* **How did you install AdGuard Home:**
  * Docker
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * 
* **Operating system and version:**
  * 

### Issue details.

AGH 0.107 betas seems to use an excess amount of memory. I was on 0.106.3 a while back, and it barely crept above 60-70M. I think this is quite concerning.

![Screenshot (17)](https://user-images.githubusercontent.com/19761269/144608340-334926b7-2a8d-4466-8838-a23a9efd6b3d.png)

![Screenshot (19)](https://user-images.githubusercontent.com/19761269/144608664-f6381081-eed9-448f-bf05-89857b298e4c.png)

### Additional Information

Query logs are stored in-memory only with retention period of 30 days. 

Since the last restart, the memory usage has increased from the initial 60MB-80MB, within a period of 4d 11h, it has increased to 211MB.

**EDIT**: Added additional info

**Comment by ainar-g** [comment] 2021-12-10 15:47
@agneevX, just to be clear, what do you mean when you say:

 >  Query logs are stored in-memory only with retention period of 30 days.

**Comment by agneevX** [comment] 2021-12-10 17:07
I have the following options set:

```sh
agneev@always-on ~> cat /opt/appdata/adguardhome/config.yml | grep querylog
  querylog_enabled: true
  querylog_file_enabled: false
  querylog_interval: 720h
  querylog_size_memory: 300000
```

**Comment by ainar-g** [comment] 2021-12-14 11:42
@agneevX, we haven't found any real sources of potential memory leaks so far, but we have made a few optimisations in the recent days.  Could you please check if the latest `edge` build makes the situation better for you?

**Comment by agneevX** [comment] 2021-12-14 11:43
Thanks, will do and report back.

**Comment by ainar-g** [comment] 2021-12-17 11:23
@agneevX, any findings?  We still haven't been able to reproduce the issue on the `edge` channel`.

**Comment by agneevX** [comment] 2021-12-17 11:32
I thought I had already submitted a comment here, but I think I closed the tab before I hit Comment. So here goes...

There's been significant improvement. It doesn't seem to exceed ~200MB in general usage, saving only for certain times when it hits ~500MB and goes back down within a couple of minutes.

At startup, AGH seems to use <120MB, which is more than 0.106.3.

The server was actually accidentally power cycled today, so I lost some metrics data.

I'll be able to provide a long-term update (that I originally reported upon) within a couple of days.

**Comment by agneevX** [comment] 2021-12-27 17:36
After running for 9 days, this is how it hovers around:

![Screenshot (71)](https://user-images.githubusercontent.com/19761269/147494652-59b71f3f-4feb-4231-81fe-3682922d0439.png)

I still think its excessive.

**Comment by ainar-g** [comment] 2021-12-27 18:17
@agneevX, I see, thanks.  We'd like to see the heap profile of your situation, if you don't mind.  To get one:

1.  Stop AGH.

2.  Edit `AdGuardHome.yaml` and set `debug_pprof: true`.

3.  Restart AGH.

4.  (Wait for the memory to grow.)

5.  Navigate to `http://localhost:6060/debug/pprof/heap?debug=1&gc=1`.  This API is only served on `localhost`.

6.  Save the page's contents and send that data to devteam@adguard.com.

Also, just clarify, how many filter lists do you have enabled?  If they're not private, could you give us the whole list?

**Comment by agneevX** [comment] 2021-12-27 18:24
Here's the lists:

![EC05A745-2D13-42CB-BAC7-5ACE2C60A821](https://user-images.githubusercontent.com/19761269/147497744-3599c67b-8eff-4418-883b-0d2f6e1bed4d.jpeg)

I'll make sure to get the Go mem pprof.

**Comment by ainar-g** [comment] 2021-12-29 11:42
@agneevX, another question, just in case.  Are you sure that you have used exactly the same filter lists on v0.106.3?  I'm asking, because that makes about 800,000 rules in total, which is quite a lot.

Also, were all of the filters URL-based?  The thing is, when you use a file-based filter, AGH doesn't actually load the whole file into the memory, but rather uses the filesystem more, which is slower but saves RAM.

**Comment by agneevX** [comment] 2021-12-29 11:45
The only list that's new is the last one with the most amount of rules. Should unchecking any reduce usage?

**Comment by 63780223** [comment] 2021-12-30 05:02
AdGuardHome-mipsle

[alog12.txt](https://github.com/AdguardTeam/AdGuardHome/files/7791551/alog12.txt)

**Comment by 63780223** [comment] 2021-12-30 09:10
[alog20.txt](https://github.com/AdguardTeam/AdGuardHome/files/7792231/alog20.txt)
[AdGuardHome.yaml.txt](https://github.com/AdguardTeam/AdGuardHome/files/7792237/AdGuardHome.yaml.txt)

**Comment by ainar-g** [comment] 2021-12-30 11:53
@agneevX, yes, the filtering rules are probably the largest consumer of RAM in most AGH installations.  The other two that might have changed are query logs (if I recall correctly, you've mentioned in another issue that you keep them in RAM; was it always the case?) and the static assets, which we plan to optimize in #4025.

**Comment by agneevX** [comment] 2022-01-09 11:32
Here's the requested data @ainar-g: https://www.dropbox.com/s/1tuk5jc641v22um/adg_pprof.txt?dl=0

**Comment by agneevX** [comment] 2022-01-17 14:24
Hmm that's interesting. Does it not purge the older lists, once newer ones have downloaded?

I've reduced the amount of blocklists I use, so I thought it'd make a difference, but I guess not.

**Comment by ainar-g** [comment] 2022-01-17 14:27
It does once all references to the old list are eliminated, but the garbage collection may take some time.

Is there anything else we can do in this issue?

**Comment by agneevX** [comment] 2022-01-17 14:40
If there's nothing else than can be done, then this issue can be closed I think. 

But 250MB of RAM usage is a lot, and this is sure to impact people who run AGH on Pi Zeros for example.

**Comment by ainar-g** [comment] 2022-01-17 14:53
While it's true, it's also natural for a program's RAM usage to grow as the data it processes grows.  As I've mentioned, the file-based filters aren't uploaded to the RAM, and so people with strict RAM requirements are better off using those, even if that means that the filtering is slower.

I'll close this issue for now.  There are a few other issues which, once resolved, should improve some of memory usage.

**Comment by agneevX** [comment] 2022-08-24 15:00
Hello @ainar-g, I have v0.107.8 running for 11 days, and it's using up 424MB of memory...

![image](https://user-images.githubusercontent.com/19761269/186452325-d37cdcda-e6e4-46af-bfef-ff60014c698e.png)

This has increased significantly from what I initially reported.

**Comment by ainar-g** [comment] 2022-08-24 15:03
@agneevX, hello.  Just to be clear, does lowering cache size, `querylog_size_memory`, and the number of filtering rules decrease the memory usage, or does it stay the same?

**Comment by agneevX** [comment] 2022-08-24 15:10
The cache is disabled, what value should I set `querylog_size_memory` to? Currently, it's set to `30000`.

![image](https://user-images.githubusercontent.com/19761269/186453713-ad202d9a-3f4b-4acd-b99b-1e75501fc5c6.png)

**Comment by ainar-g** [comment] 2022-08-24 15:16
It's better to keep cache enabled, but at some smaller value, like 1 MiB.  The `querylog_size_memory` looks okay as well.  The number of rules is quite large, but my AGH with ~50K rules only consumes 32 MiB of RAM.

Also, I've noticed that you're showing the output of the Docker image, which includes an entire Linux system within it.  I'm also not sure if you're launching it on Windows or if you simply SSH'ed to the server, but if you *are* running it on Windows, the VM may interfere as well.  Can you see the output of `top` from *within* the container?

**Comment by agneevX** [comment] 2022-08-25 14:11
> Can you see the output of top from within the container?

```text
Mem: 3629396K used, 254908K free, 540156K shrd, 135724K buff, 1704396K cached
CPU:   2% usr  12% sys   0% nic  85% idle   0% io   0% irq   0% sirq
Load average: 0.66 0.42 0.49 3/939 66
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
    1     0 root     S    1280m  33%   0   0% /opt/adguardhome/AdGuardHome --con
   65    53 root     S     1736   0%   1   0% /bin/ash
   53     0 root     S     1668   0%   1   0% /bin/sh -c printf '\e[0m\e[?25h' &
   66    65 root     R     1664   0%   1   0% top
```

**Comment by ainar-g** [comment] 2022-08-25 14:21
@agneevX, ah, I forgot that `top` on Alpine Linux doesn't show shared memory by default.  Please run `top -m` to make it actually show the `RSS` and `SHR` columns.

**Comment by agneevX** [comment] 2022-08-25 18:48
Here you go:

```
Mem total:3884304 anon:1241380 map:318384 free:252536
 slab:377312 buf:128824 cache:1706096 dirty:132 write:0
Swap total:0 free:0
  PID^^^VSZ^VSZRW   RSS (SHR) DIRTY (SHR) STACK COMMAND
    1 1280m  634m  317m     8  296m     0   132 /opt/adguardhome/AdGuardHome --
   78  1736   240  1108   900   192     0   132 /bin/ash
   79  1680   184   920   856    64     0   132 top -m
   67  1668   172  1096   900    64     0   132 /bin/sh -c printf '\e[0m\e[?25h
```

**Comment by ainar-g** [comment] 2022-08-26 09:20
Thanks!  So, about 300 MiB for an installation with ~500K rules.  That doesn't sound that unreasonable, to be fair.  If you still think that there is a leak, please do the following:

1.  Try running AdGuard Home without Docker, if you can do that, to minimize the Docker/VM footprint.

2.  Repeat the process from [this comment](https://github.com/AdguardTeam/AdGuardHome/issues/3913#issuecomment-1001687117) but also make sure to save the output from `http://127.0.0.1:6060/debug/pprof/goroutine?debug=1` so that we could see if there are any connection leaks.

Thanks!

**Comment by ainar-g** [comment] 2023-08-24 13:18
@agneevX, hello, is this issue still relevant?  There have been a few optimization since then, and if you are still having issues, goroutine or allocation profiles would be great to have.

**Comment by agneevX** [comment] 2023-08-25 14:58
This continues to be an issue at least on an edge build (v0.108.0-a.650+c54635e8).


```
~> docker stats adguard --no-stream
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O         BLOCK I/O       PIDS
3d67aa247e9c   adguard   0.03%     777.4MiB / 3.701GiB   20.51%    284MB / 189MB   893kB / 161MB   12
```

> if you are still having issues, goroutine or allocation profiles would be great to have.

Are you referring to pprof?

Also not sure if it's helpful, but here are a couple of (extra) configuration that I use:

```yml
querylog:
  interval: 168h
  size_memory: 300000
  enabled: true
  file_enabled: false
...
dns:
  max_goroutines: 0
```

**Comment by ainar-g** [comment] 2023-08-25 15:22
Yes, the pprof debug API.  Assuming it's enabled on port 6060, the following commands will produce the necessary profiles:

```sh
curl 'http://127.0.0.1:6060/debug/pprof/goroutine?debug=1' > goroutine.txt
curl 'http://127.0.0.1:6060/debug/pprof/heap' > heap.pprof
curl 'http://127.0.0.1:6060/debug/pprof/allocs' > allocs.pprof
```

We can then analyse the files and see if there is anything abnormal and what can be optimized further.

**Comment by handongming** [comment] 2023-09-06 04:13
I had a similar issue with the OpenWRT system. If turn on too many filters, the system will stuck after 24 hours.
I wonder if there is a recommendation for number of filters vs size of memory. or is it really a memory leak?
running AdGuardHome v0.107.26.

**Comment by overwatch3560** [comment] 2024-04-02 00:09
Is this still an issue with the most recent version @handongming @agneevX ?

**Closed** 2024-04-16 11:05 UTC
Labels: cannot reproduce
