### ISSUE TITLE
Do not show new version blue notification if using the latest version already

### ISSUE THREAD

**Issue by rfgamaral** [AdguardTeam/AdGuardHome#701] opened 2019-04-02 13:12 UTC
### Steps to reproduce
Not sure how, it appeared to me just once.

### Expected behavior
Do not show the new version blue notification for a version which is the one already installed.

### Actual behavior
The blue notification saying version X is now available appears even if version X is the one already installed.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/96476/55405006-171d0300-5551-11e9-8217-ec32334c7316.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| (e.g. v0.94)

**Comment by adrianh-za** [comment] 2019-04-03 04:33
Duplicate of #660

**Closed** 2019-04-03 07:31 UTC
Labels: duplicate
