### ISSUE TITLE
AdGuard Home has added a web service toggle option to prevent web logins when using encrypted DNS over HTTPS.

### ISSUE THREAD

**Issue by Edgar-qiqi** [AdguardTeam/AdGuardHome#7149] opened 2024-07-25 09:06 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

AdGuard Home has added a web service toggle option to prevenAdd a toggle for the web access service.

### Proposed solution

Add a toggle for the web access service.

**Comment by ainar-g** [comment] 2024-07-25 11:32
Duplicate of #1964

**Closed by ainar-g** 2024-07-25 11:32 UTC
Labels: feature request
