### ISSUE TITLE
Save configuration with backup/restore

### ISSUE THREAD

**Issue by muok** [AdguardTeam/AdGuardHome#3793] opened 2021-11-02 04:39 UTC
There should be a UI option to save current configuration for backup or restore purposes. Would ease migrations.

Thank you.

**Comment by ainar-g** [comment] 2021-11-02 09:42
Duplicate of #1147

**Closed by ainar-g** 2021-11-02 09:42 UTC

**Comment by chadfixit** [comment] 2023-06-24 05:40
+1 Make a backup and restore for kernel exchanges to device upgrades!
