### ISSUE TITLE
/etc/hosts ignored and rewritten when it shouldn't

### ISSUE THREAD

**Issue by Caesarovich** [AdguardTeam/AdGuardHome#6541] opened 2023-12-13 15:50 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.43

### Action

```sh
nslookup my-computer.local
```

Result:
```
Server:		10.10.XX.XX
Address:	10.10.XX.XX#53

Non-authoritative answer:
Name:	my-computer.local
Address: 10.21.XX.XX   # That's the actual address I need
** server can't find my-computer.local: NXDOMAIN
```

### Expected result

When requesting a for domain names from my local network (Which are stored on the server's `/etc/hosts` file), it is expected that the upstream DNS does not find any attached domain name. But as the `hosts` file contains an entry for that domain, it should return it instead.

### Actual result

The upstream DNS does in fact return NXDOMAIN because it can't possibly know about my local domains, but this overwrites the first response from the `hosts` file and tells the requesting computer that it does not exist.

It can be seen here in the log:
![Screenshot from 2023-12-13 16-30-55](https://github.com/AdguardTeam/AdGuardHome/assets/38408878/79e25ed3-832f-4f72-911d-d0f40ea255ab)

First AGH answers with the IP stored in the `hosts` file, but it is then rewritten with the response from the upstream DNS (`NXDOMAIN`) 120 milliseconds later.

See details:
(First it answers the right IP)
![Screenshot from 2023-12-13 16-35-51](https://github.com/AdguardTeam/AdGuardHome/assets/38408878/a29407b4-8239-47d2-81bd-4b4ffa92c54d)
(Then it overwrites and says the domain doesn't exist)
![Screenshot from 2023-12-13 16-38-08](https://github.com/AdguardTeam/AdGuardHome/assets/38408878/6c359f33-6fcb-4ea0-82f9-50ed9e99c3e1)

### Additional information and/or screenshots

This is my first issue here, please let me know if I forgot something. If people agree that it is a non-desired behavior, I'll start working on a PR as soon as I can.

I propose that the behavior should be as follow:
- Either the content of `/etc/hosts` is always the priority.
- Or the content of `/etc/hosts` should be used if the upstream do not find a matching DNS record.

**Comment by ainar-g** [comment] 2023-12-14 11:50
@EugeneOne1, it seems like the latest release has lost the `NODATA` logic when processing hosts files.  Please investigate and fix.

**Comment by EugeneOne1** [comment] 2023-12-14 14:28
This has indeed been broken since `v0.107.37` as far as I can see.  Consider this a bug.

**Comment by Caesarovich** [comment] 2023-12-15 04:57
Hi @EugeneOne1 , thanks for responding to my issue. I've been struggling quite a lot to build a local version of AGH but I think I have a working sample.

If this helps I found an odd behavior in my initial testing:

When requesting for a host from `/etc/hosts` that corresponds somewhat to the localhost, AGH works as intended
```sh
> nslookup nixos 127.0.0.53
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	nixos
Address: 127.0.0.2
Name:	nixos
Address: ::1
```

But for other hosts the behavior is as described in the issue.

```sh
> nslookup server-test 127.0.0.53
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	server-test
Address: 10.0.0.1
** server can't find server-test: NXDOMAIN
```

I will continue my investigations, but I won't be able to do much in Go.

**Comment by EugeneOne1** [comment] 2023-12-18 14:59
@Caesarovich, hello again.  We've tried to fix handling the hosts from `/etc/hosts` having only a single corresponding address family.  Could you please try the edge build and tell if it now works as intended?

Regarding the second note, if those NXDOMAIN requests displayed as resolved from `/etc/hosts` in Query Log?

**Comment by Caesarovich** [comment] 2023-12-19 16:29
Hi @EugeneOne1 , I have tried the new changes and so far it looks like the problem has been fixed. See below:

```sh
[nix-shell:~/Code]$ nslookup google.com 127.0.0.53
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	google.com
Address: 172.217.16.206
Name:	google.com
Address: 2a00:1450:4001:831::200e


[nix-shell:~/Code]$ nslookup nixos 127.0.0.53
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	nixos
Address: 127.0.0.2
Name:	nixos
Address: ::1


[nix-shell:~/Code]$ nslookup server-test 127.0.0.53
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	server-test
Address: 10.0.0.1
```

The query logs looks like so:
![Screenshot from 2023-12-19 16-40-45](https://github.com/AdguardTeam/AdGuardHome/assets/38408878/a49ab55b-f92b-4aa7-ba2a-8cda6c73a752)

No more NXDOMAIN. Thanks for the fix, I will try it out at work when the update is available.

**Note:** In my testings, I found out that AGH appears to not load the `/etc/hosts` file the first time it is run, or at least not properly. And when I queried my local domain, AGH crashed (Nil pointers de-reference). But it works fine after restarting it at least once. Should we make an issue for that as well ?

**Comment by EugeneOne1** [comment] 2023-12-19 16:37
@Caesarovich, thanks for testing, that's really helpful.  I'll close this issue for now.

Panic at the initial startup is definitely worthy of a separate issue, so it'd be appreciated.

**Closed by EugeneOne1** 2023-12-19 16:37 UTC
Labels: bug, P3: Medium
