### ISSUE TITLE
Set different EDNS values ​​for users to enhance privacy and reduce the impact of latency

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdGuardHome#3470] opened 2021-08-19 17:10 UTC
For example, users in mainland China can be set to "Hong Kong users" to enhance privacy

For example, Hong Kong users can be set to "Taiwan users" or "Japanese users" to enhance privacy

This will not increase too much network delay, and can greatly enhance user privacy.

**Comment by c2xusnpq6** [comment] 2021-08-19 19:51
Freedom on the Net | Freedom House:
https://freedomhouse.org/report/freedom-net

Explore the Map | Freedom House:
https://freedomhouse.org/explore-the-map?type=fotn&year=2020

**Comment by ainar-g** [comment] 2021-08-20 09:47
Duplicate of #2514.

Please, add all of your EDNS subnet faking suggestions there.  Thanks.

**Closed by ainar-g** 2021-08-20 09:47 UTC
