### ISSUE TITLE
Search on client name not working in Query log only with IP address

### ISSUE THREAD

**Issue by BobWs** [AdguardTeam/AdGuardHome#1530] opened 2020-03-31 11:21 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ y] I am running the latest version
- [y ] I checked the documentation and found no answer
- [y ] I checked to make sure that this issue has not already been filed

### Issue Details

For me searching within the Query log with a client name isn't working only when I use the IP of the clients. Is this a bug or is AGH design to work this way?

* **Version of AdGuard Home server:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

### Screenshots

![Screen_Shot](https://user-images.githubusercontent.com/5485820/78020803-65c2d000-7352-11ea-942b-42bc10c20adf.png)
<details><summary>Screenshot:</summary>

</details>

**Comment by ArchiveBase** [comment] 2020-04-01 19:19
Duplicate of #1273

**Comment by ameshkov** [comment] 2020-04-02 19:59
closed as dup

**Closed by ameshkov** 2020-04-02 19:59 UTC
Labels: duplicate
