### ISSUE TITLE
AdGuard Home DHCP Server not assigning Connection-specific DNS Suffix for Windows clients

### ISSUE THREAD

**Issue by ZolliusMeistrus** [AdguardTeam/AdGuardHome#6993] opened 2024-05-12 17:10 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

When AdGuard Home DHCP Server is activated, and in the AdGuardHome.yaml file the entry "local_domain_name" has been assigned a custom value, then when Windows clients are assigned an IP address, their "Connection-specific DNS Suffix" is not updated to this custom value, and they are not able to resolve clients in this domain without specifying the FQDN when trying to resolve. For example - when resolving "hostname" in Windows CMD, then no results are returned. When resolving "hostname.custom.domain" then the IP is returned from the AdGuard Home DHCP cache.

### Proposed solution

Add the option of using a custom domain name in the AdGuard Home web interface for DHCP Server, as well as set the "Connection-specific DNS Suffix" for Windows clients. If the Pi-Hole can do this, I'm sure AdGuard Home can also do this.

**Comment by ainar-g** [comment] 2024-05-17 14:05
Duplicate of #6749

**Closed by ainar-g** 2024-05-17 14:05 UTC
Labels: feature request
