### ISSUE TITLE
Add scheduling on services

### ISSUE THREAD

**Issue by pcel03** [AdguardTeam/AdGuardHome#5569] opened 2023-03-06 02:26 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
I am using adguard home on my raspberry pi. Blocking of services is great but the toggle switch is static and needs manual intervention everytime. as a work around, I am using nextdns as my upstream server for adguardhome so it can do the task. Ultimately, i wanted to get rid of NextDNS and stick with Adguard Home once this feature is installed.

#### Proposed solution
add a scheduler on blocked services for AdguardHome. This will benefit parents who have children having online schools at home.

#### Additional information
here's a screenshot of the schedule from nextDNS  for reference.
![image](https://user-images.githubusercontent.com/46251650/223005306-7650ec20-0bc9-44ca-8688-cfd9c6c18536.png)

**Comment by ainar-g** [comment] 2023-03-06 10:13
Duplicate of #951

**Comment by ainar-g** [comment] 2023-03-06 10:13
Please note that if you're using AdGuard DNS as your upstream, you can already use a schedule there.

**Closed by ainar-g** 2023-03-06 10:13 UTC

**Comment by pcel03** [comment] 2023-03-06 10:35
Hi Ainar, 

Thank you for the reply. Is there like a KB page about using AdGuard DNS as my upstream, where I can use the schedule for services?

I tried changing the upstream server of my Adguard Home and i can't find anything that allows me to change the schedule.

**Comment by pcel03** [comment] 2023-03-06 10:46
> Hi Ainar,
> 
> Thank you for the reply. Is there like a KB page about using AdGuard DNS as my upstream, where I can use the schedule for services?
> 
> I tried changing the upstream server of my Adguard Home and i can't find anything that allows me to change the schedule.

nvm, i think i saw it. the scheduler is available in "Private Adguard DNS" but the monthly subscription is higher than NextNDS' offering.  I really wish to have this built in to Adguard Home soon. Thank you!

![image](https://user-images.githubusercontent.com/46251650/223088853-76c8b01b-36e2-44a3-b92e-f7f829c24333.png)
