### ISSUE TITLE
Query Log drop-down list for selecting different types of requests shown, is rendered incorrectly in dark mode

### ISSUE THREAD

**Issue by GritsanY** [AdguardTeam/AdGuardHome#5490] opened 2023-02-16 06:48 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Windows

### CPU architecture

AMD64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.24

#### What did you do?
Open any Query Log page, and click on drop-down list in top right corner, while the UI is in dark mode
#### Expected result
text on all items of said drop-down list is readable
#### Actual result
the displayed list is rendered incorrectly - All items of the drop-down list are white expect of the selected one, and the text is just barely visible.
#### Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/17610768/219289393-54a25ea5-9a5a-42bc-b2e5-8d0c71dffe4c.png)

**Comment by ainar-g** [comment] 2023-02-16 08:14
Duplicate of #5441

**Closed by ainar-g** 2023-02-16 08:14 UTC
