### ISSUE TITLE
Improve the Query Log page

### ISSUE THREAD

**Issue by lifansama** [AdguardTeam/AdGuardHome#944] opened 2019-08-21 00:12 UTC
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

I hope I can see one client's log by search using the name set in the Client settings page.
If I have two client whose ip are `192.168.1.12` and `192.168.1.123`, I cannot see `192.168.123.12` only.

**Comment by ArchiveBase** [comment] 2019-08-22 13:08
https://github.com/AdguardTeam/AdGuardHome/issues/481#issuecomment-515673586

**Comment by planet0** [comment] 2019-08-26 12:17
Duplicate of #636?
@ameshkov

**Comment by ameshkov** [comment] 2019-08-27 08:28
@planet0 yup, indeed, thank you!

**Closed by ameshkov** 2019-08-27 08:28 UTC
Labels: P3: Medium, UI, enhancement
