### ISSUE TITLE
Building SNAPSHOT with an error called "invalid snap version cannot be longer than 32 characters (got: 33)"

### ISSUE THREAD

**Issue by hezhijie0327** [AdguardTeam/AdGuardHome#2410] opened 2020-12-10 07:17 UTC
Tag: v0.105.0-beta.1
Commit: ef178610d6440ca187f419d844b45d93bad257af

<img width="1189" alt="Xnip 2020-12-10 15 14 13" src="https://user-images.githubusercontent.com/58100052/101734000-a0445580-3afa-11eb-8221-cbd0a7e615e0.png">

**Comment by ainar-g** [comment] 2020-12-10 09:45
<p>Good&#xA0;day, and thank you for the report!&#x2003;We know about this issue,
and you can expect a&#xA0;fix today-ish.&#x2003;On a&#xA0;larger scale, our
prerelease versioning is actually a&#xA0;bit broken according to SemVer, and
we're planning to fix that as well in the nearest&#xA0;future.</p>

**Comment by ainar-g** [comment] 2020-12-10 12:48
<p>Should&#xA0;be fixed as of commit e2738fdf.&#x2003;Can you please check if
our solution fixes the issue for&#xA0;you?</p>

**Comment by hezhijie0327** [comment] 2020-12-10 13:03
I retry to build the snapshot e2738fd, but it still didn't work. At this time, it return another error.
<img width="1116" alt="Xnip 2020-12-10 20 52 03" src="https://user-images.githubusercontent.com/58100052/101775904-2082af00-3b2b-11eb-8d46-e32ac3c81527.png">
<img width="1163" alt="Xnip 2020-12-10 21 00 39" src="https://user-images.githubusercontent.com/58100052/101775907-21b3dc00-3b2b-11eb-97e0-ef4648916023.png">

**Comment by ainar-g** [comment] 2020-12-10 13:13
<p>It's&#xA0;hard to tell what's wrong this time without seeing the full build
configuration.&#x2003;That doesn't really reproduce in our builds here on
<i>GitHub</i>.&#x2003;But make sure that <code>goreleaser</code> is installed
<strong>before</strong> the snapcraft stage, and also that they are within one
job/VM.&#x2003;As a&#xA0;debug measure, you can add the command <code>ls -a
/home/runner/go/bin</code> to your build step before the call to
<code>goreleaser</code> and check the&#xA0;output.</p>

**Comment by hezhijie0327** [comment] 2020-12-10 14:00
<img width="708" alt="Xnip 2020-12-10 22 00 03" src="https://user-images.githubusercontent.com/58100052/101781685-16fd4500-3b33-11eb-9ca9-c2f349ad02b4.png">

After use "sudo ln -s /home/runner/go/bin/goreleaser /bin/goreleaser":
<img width="739" alt="Xnip 2020-12-10 21 37 35" src="https://user-images.githubusercontent.com/58100052/101779265-01d2e700-3b30-11eb-97f1-5f7e5022f11f.png">

**Comment by ainar-g** [comment] 2020-12-10 14:20
<p>Now&#xA0;it seems to be missing the
<code>go generate ./...</code>&#xA0;step.</p>

<p>I&#xA0;will close this issue for now, since the original issue is
resolved.&#x2003;If you want to make your own <i>AdGuardHome</i> build
infrastructure, I&#xA0;would highly recommend starting by just copying our
<i>GitHub</i>&#xA0;<a href="https://github.com/AdguardTeam/AdGuardHome/tree/e2738fdf3f2cab3c4832bc3173c6cebd36379443/.github/workflows">workflows</a>.</p>

**Closed by ainar-g** 2020-12-10 14:20 UTC
Labels: P2: High, bug, infrastructure
