### ISSUE TITLE
Ability to identify clients using ISP

### ISSUE THREAD

**Issue by hexclann** [AdguardTeam/AdGuardHome#4893] opened 2022-09-06 15:25 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
Client identification 

#### Proposed solution
Currently we can identify clients using CIDR, IP address, MAC address and client IDs. There should be a method to uniquely identify clients using the ISP or country name. 

Country and ISP details are already available in adguard.

#### Alternatives considered
None

**Comment by ainar-g** [comment] 2022-09-06 15:48
This is basically a duplicate of #1487, since this would require a GeoIP database.

 >  Country and ISP details are already available in adguard.

If you mean the WHOIS information that we show in the Query log, this information is gathered at runtime and may not be available, so any kind of blocking based on it will not be reliable at all.

**Closed by ainar-g** 2022-09-06 15:48 UTC
