### ISSUE TITLE
New Lists

### ISSUE THREAD

**Issue by gyCfjSnO** [AdguardTeam/AdGuardHome#3691] opened 2021-10-01 08:05 UTC
### Problem Description

Have to manually find more lists, defaults aren't enough

### Proposed Solution

Add lists that are green & bulleted with a tick from Firebog.net to the default "Choose from the list" option

https://v.firebog.net/hosts/lists.php?type=tick

**Comment by ainar-g** [comment] 2021-10-01 09:54
This is basically a duplicate of #1913 and #2644.  Please add your proposal to one of these issues.  Thanks!

**Closed by ainar-g** 2021-10-01 09:54 UTC
