### ISSUE TITLE
AdGuard Home leaks memory until OOM, CPU and I/O spikes

### ISSUE THREAD

**Issue by jsynowiec** [AdguardTeam/AdGuardHome#1599] opened 2020-04-20 08:45 UTC
### Issue Details

* **Version of AdGuard Home server:**
  * v0.101.0
* **How did you setup DNS configuration:**
  * System, using [static release](https://static.adguard.com/adguardhome/release/AdGuardHome_linux_amd64.tar.gz) and `-s install`
* **Operating system and version:**
  * Ubuntu 18.10

### Expected Behavior
AdGuard Home just runs indefinitely not leaking memory.

### Actual Behavior
AdGuard Home leaks memory, consumes ~1GB of RAM in few days days. This results in an extensive CPU and I/O load and renders VM host inaccessible. Power cycling is required.

Everything was fine until around April 13. No updates or restarts were performed on the VM. AdGuardHome worked for months, consuming ~60% of RAM, but no more.

### Screenshots
<details><summary>Screenshot: VM load graphs, last 7 days</summary>

<img width="753" alt="Screenshot 2020-04-20 at 08 45 03" src="https://user-images.githubusercontent.com/1029142/79722357-33b6e500-82e4-11ea-895e-e3f09b2e6184.png">

</details>

<details><summary>Screenshot: VM memory graph, last 30 days</summary>

![Screenshot 2020-04-20 at 10 42 24](https://user-images.githubusercontent.com/1029142/79732341-d62a9480-82f3-11ea-988c-343ce4cf55d4.png)

</details>

```
$ ps aux | grep AdGuard
root      8204  0.0  7.6 118120 77092 ?        Ssl  Apr19   0:27 /home/adguard/AdGuardHome -s run
#
root      8204  0.0 15.3 254192 155008 ?       Ssl  Apr19   0:51 /home/adguard/AdGuardHome -s run
# close to 2 days
root      8204  0.0 23.4 322356 236540 ?       Ssl  Apr19   2:10 /home/adguard/AdGuardHome -s run
# a bit over 3 days
root      8204  0.0 46.3 594644 467384 ?       Ssl  Apr19   4:29 /home/adguard/AdGuardHome -s run
```

After ~2 days from start AdGuardHome uses 240M of RAM.

### Additional Information
* Nothing else is running on the VM
* VM with 1GB of RAM, no swap
* 15 blocklist files, ~80k hosts total
* Similar to #991, but different distribution and setup
* 3-4 different clients top, usually 1-2
* SSL, DoT, DoH enabled
* query log disabled, 24h stats

**Comment by ameshkov** [comment] 2020-04-26 12:32
@jsynowiec hi, could you please try the latest beta version? https://github.com/AdguardTeam/AdGuardHome#test-unstable-versions

If the issue is still there, we may need to get `pprof` memory dumps (and this is possible with the beta version only).

**Comment by jsynowiec** [comment] 2020-04-28 08:16
@ameshkov Thanks for the reply, but due to memory leaks I had to remove AdGuardHome 3 days ago and switch to a Pi-hole with cloudflared upstream and nginx DoT-DNS gateway. Sorry, but I can't help anymore.

**Comment by ameshkov** [comment] 2020-04-28 08:48
@jsynowiec got it, no prob! 

To everyone else: if you experience this issue, please comment here, I'll reopen it.

**Comment by jsynowiec** [comment] 2020-04-28 11:19
@ameshkov please find below an annotated memory usage graph. Maybe it'll be somewhat helpful. Nothing in AdGuardHome configuration nor in amount of enabled lists changed when memory leak started to occur.

<img width="495" alt="aghome_memleak" src="https://user-images.githubusercontent.com/1029142/80481490-d1e52380-8952-11ea-927d-1ea23dcb34a0.png">

**Comment by grzesiczek1** [comment] 2020-05-08 22:28
Hey,

I seem to be having same issue with AdGuardHome 0.101.0 installed on OpenWRT 19.07.02 with WRT3200ACM router. Would you still need someone to reproduce it?

![OpenWRTMemoryAGH](https://user-images.githubusercontent.com/58589583/81454237-f67b9f80-918b-11ea-93b2-d7c7a12500c2.png)

**Comment by ameshkov** [comment] 2020-05-08 22:34
@grzesiczek1 Yeah, we do, thank you!

Could you please check if the issue is still present with the beta version?
https://github.com/AdguardTeam/AdGuardHome#test-unstable-versions

If it is, I'll send you more detailed instructions on how to collect `pprof` dump.

**Comment by grzesiczek1** [comment] 2020-05-08 23:04
Upgraded to beta as per docs and landed on this build - will keep an eye on it
![AdGuardVersion](https://user-images.githubusercontent.com/58589583/81455931-021d9500-9191-11ea-805d-30fceda7f2fa.png)

**Comment by grzesiczek1** [comment] 2020-05-09 11:45
Unfortunately, same symptoms on the beta build. 

Let me know how I can get you pprof dump.

**Comment by grzesiczek1** [comment] 2020-05-11 18:20
Hey, @ameshkov - I am ready to help. Let me know please how can I assist.
Having RSS on around 200MB and VSZ on 830MB sounds excessive - here is AdGuardHome process stats for the last 24h. 
![AdGuardMemory](https://user-images.githubusercontent.com/58589583/81596714-d256d300-93c4-11ea-819c-1de80b3d0a27.png)

**Comment by grzesiczek1** [comment] 2020-05-11 18:20
![AdGuardMemory](https://user-images.githubusercontent.com/58589583/81596732-d8e54a80-93c4-11ea-80e5-2bd7eceec85e.png)

**Comment by ameshkov** [comment] 2020-05-11 21:54
@grzesiczek1 

> VSZ on 830MB

Care not about VSZ, it simply does not matter how much it is.
RSS matters, though. How many blocklists do you use?

Here's what we need:

1. Stop AGH
2. Set `debug_pprof` to `true` in `AdGuardHome.yaml`
3. Start AGH
4. It'll start listening on `localhost:6060`

Now if you open `http://localhost:6060/debug/pprof/heap`, you'll download the heap dump. I'd like to have two of them, for 120MB and 200MB RSS on your charts.

Also, if you have go and graphwiz installed anywhere, you can take a look yourself:
`go tool pprof -http localhost:3434 path_to_dump` will open a nice UI interface for exploring the dump.

**Comment by grzesiczek1** [comment] 2020-05-12 13:49
Hey - three heap dumps attached - one just after start; one around 1h after it was started and 3rd around 6h later. Graphwiz summary is excellent!
[Heap.zip](https://github.com/AdguardTeam/AdGuardHome/files/4615988/Heap.zip)

**Comment by ameshkov** [comment] 2020-05-12 14:01
@grzesiczek1 one more question -- what filter lists do you have?

**Comment by ameshkov** [comment] 2020-05-12 16:04
Meanwhile, I examined the heap dumps, and I don't see any leak there.

Switch to `inuse_space` to inspect how much memory is consumed and what objects do that.
Most of the memory is consumed by the filtering DNS engine (~38MB in your case) which is expected, filter lists are usually heavy. It stays about the same in both heap dumps.

I think the RSS size increase should be attributed to the Go runtime. It loves allocating, but it's not quick to free it and usually waits until the system asks it to. According to the second heap dump, the allocation happened when we were "refreshing" (updating) filters. When AGH does that, it creates a copy of the DNS engine, and that's why there's a spike in the RSS usage.

Anyways, it's still interesting why AGH consumes 38MB on filter lists, if you tell me what lists you have, I'll try to reproduce this.

**Comment by grzesiczek1** [comment] 2020-05-12 19:21
Here is the filter list I use :
1. https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt  
2. https://adaway.org/hosts.txt 
3. https://www.malwaredomainlist.com/hostslist/hosts.txt
4. https://raw.githubusercontent.com/ookangzheng/dbl-oisd-nl/master/abp.txt
5. https://raw.githubusercontent.com/mmotti/adguard-home-filters/master/regex.txt (this one is currently disabled)
6. https://raw.githubusercontent.com/mmotti/adguard-home-filters/master/filters.txt

On a side note - is there an easy way to tell which filter blocked how many % of all the blocked count? I could disable those least effective. 

Regarding GO loving memory - would there be any system command (possibly cronnable) I could use to force memory cleanup? Could run some tests to see if that helps.

**Comment by ameshkov** [comment] 2020-05-12 23:34
The filter lists are quite huge so I see why it takes about ~40MB of heap space.

> On a side note - is there an easy way to tell which filter blocked how many % of all the blocked count? I could disable those least effective.

Nope, unfortunately, but there was a feature request about that.

> Regarding GO loving memory - would there be any system command (possibly cronnable) I could use to force memory cleanup? Could run some tests to see if that helps.

Not that I am aware of:(

With Go programs, RSS is kinda unreliable. When the memory is freed, part of the memory is marked as "unused" and free for the OS to take. However, it won't reduce the reported RSS unless it actually takes it back, and it may take quite some time.

I've added some mitigations in the latest beta version, please check how quickly the memory is reclaimed now. Could you please try it?

**Comment by HorayNarea** [comment] 2020-05-13 02:26
> With Go programs, RSS is kinda unreliable. When the memory is freed, part of the memory is marked as "unused" and free for the OS to take. However, it won't reduce the reported RSS unless it actually takes it back, and it may take quite some time.

You can try running AdGuardHome with the environment variable `GODEBUG=madvdontneed=1`:
> setting madvdontneed=1 will use MADV_DONTNEED
instead of MADV_FREE on Linux when returning memory to the
kernel. This is less efficient, but causes RSS numbers to drop
more quickly. -- https://golang.org/pkg/runtime/

**Comment by grzesiczek1** [comment] 2020-05-13 08:11
Moved to new beta version - testing in progress: AdGuard Home, version v0.101.0-166-ga09e, channel beta, arch linux arm v6

**Comment by VlivesRaw** [comment] 2020-05-14 07:11
I noticed this as well! In the past 7 days I had 2 complete OOM crashes. Adguard is running in Proxmox LXC container, with 256MB ram allocated, and for the past 3 months it's been using 110MB of ram flat, but since 8th of March memory leaks started to happen. As a temporary measure I increased ram allocation to have more than 3 days between crashes.
![Screenshot-20200514100609-1587x565](https://user-images.githubusercontent.com/8009182/81903536-90977980-95ca-11ea-9130-39dc7e2f2374.png)

**Comment by grzesiczek1** [comment] 2020-05-16 07:00
RSS on the recent beta still looks high but definitely more stable now - I installed it on Wednesday. However, CPU time seemed doubled. 
![AdGuardMemoryWeek](https://user-images.githubusercontent.com/58589583/82113110-a2f0ef00-9753-11ea-9e8d-ec956a72578e.png)

**Comment by VlivesRaw** [comment] 2020-05-18 08:39
With the beta version memory usage went back to normal for me :+1:. CPU usage actually lowered (from 6-8%, to 3-4%). While copying settings to the beta install, I noticed that one of the filter lists was returning 404 and one out of 3 resolvers didn't work. I removed the list and replaced the resolver, so I wonder if that could be causing issues if resolver and/or list do not respond.
I also updated to 0.102 just now, hopefully things are as good as on 0.101-beta

**Comment by ameshkov** [comment] 2020-05-18 08:58
@grzesiczek1

> However, CPU time seemed doubled

Interesting, have you changed anything in the configuration?

> I removed the list and replaced the resolver, so I wonder if that could be causing issues if resolver and/or list do not respond.

Well, they shouldn't in theory.

**Closed** 2020-07-25 02:50 UTC
Labels: cannot reproduce, wontfix

**Comment by grzesiczek1** [comment] 2020-08-27 08:43
Hi All,

Been a while but I can confirm that since the recent release I do no longer see any memory over-utilization - all being kept within reasonable ranges and no leak observed. Problem moved into long-lasting CPU spikes but I will post details that into separate issue.

![image](https://user-images.githubusercontent.com/58589583/91418056-ee865f00-e851-11ea-93cd-cff571750376.png)

Thanks,
Greg

**Comment by ameshkov** [comment] 2020-08-27 08:45
Regarding CPU spikes, please compare them with AdGuard logs before posting, it should be clear what exactly causes them.
