### ISSUE TITLE
DHCP Option is continously removed and not applied on DHCP serveur

### ISSUE THREAD

**Issue by samsam-rolon** [AdguardTeam/AdGuardHome#3101] opened 2021-05-07 12:27 UTC
### Issue Details

* **Version of AdGuard Home server:**
  * v0.106.2
* **How did you install AdGuard Home:**
  * Docker Images 

### Expected Behavior
When I changing client or DNS or DHCP setting, the YAML which contain a DHCP Option should not erase the "option" field

### Actual Behavior
Option Field of DHCP is continiously edit 

### Additional Information
Why not enable the support of DHCP option in GUI to avoid this issue ?

**Comment by samsam-rolon** [comment] 2021-05-07 13:10
Also, it's look like the DHCP server doesn't take in count, wireshark analysis doesn't show my option

**Comment by samsam-rolon** [comment] 2021-05-11 12:22
Hello,
In order : I use docker with portainer stack (docker compose) running on MacVlan Network 
``` bash
  adguardhome:
    image: adguard/adguardhome:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "68:68/udp"
      - "68:68/tcp"
      - "80:80/tcp"
      - "3000:3000/tcp"
      - "443:443/tcp"
      - "853:853/tcp"
    environment:
      TZ: 'Europe/Paris'
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguard.rule=Host(`adguard.int.*********fr`)
      - traefik.http.routers.adguard.entrypoints=websecured
      - traefik.http.routers.adguard.tls.options=hardening@file
      - traefik.http.routers.adguard.middlewares=HTTP_optizer@file,IP_LAN_Filtering@file,HTTPS_Hardening@file
      - traefik.http.services.adguard.loadbalancer.server.port=80
    volumes:
      - /volume1/docker/lan/adguardhome/adguardhome-work/:/opt/adguardhome/work
      - /volume1/docker/lan/adguardhome/adguardhome-conf/:/opt/adguardhome/conf
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
        rolon_lan:
          ipv4_address: 172.16.0.93
```
My config is located in `/volume1/docker/lan/adguardhome/adguardhome-conf/AdGuardHome.yaml`
I can configure it more verbiously BUT :
I just switch to the EDGE revision on your docker image stream and the issue is solved : is it linked to the global DHCP issue that you had already identified #3096

**Comment by ainar-g** [comment] 2021-05-11 14:06
Thank you for the info.  That is actually weird, because we haven't landed any changes to the `edge` regarding that issue yet.  Have you tried switching back to `v0.106.2` and seeing if the issue is still there?

**Comment by ainar-g** [comment] 2021-05-18 13:12
@samsam-rolon, hello, are there any updates on this?  We still cannot reproduce the issue.

**Comment by samsam-rolon** [comment] 2021-05-20 22:04
Sorry... due to the WAF, I need to rollback to my classic DHCP server in order to get TV works again... I have disable the DHCP Feature but as I said, in all nightly I test, it was working so I think it's okay now !

**Comment by ainar-g** [comment] 2021-05-21 11:11
I see, thanks.  We'll close the issue for now then.  Feel free to report any new issues.

**Closed by ainar-g** 2021-05-21 11:11 UTC
Labels: waiting for data
