### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dishuostec** [AdguardTeam/AdGuardHome#843] opened 2019-06-20 11:06 UTC
After upgrade to 0.96-hotfix, adguard will exit after working a while.

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| 0.96-hotfix (linux arm64)
| How did you setup DNS configuration:| System
| If it's a router or IoT, please write device model:| NanoPi Neo2
| Operating system and version:| Ubuntu 16.04.4 LTS

systemd log:
```
AdGuardHome[2417]: panic: runtime error: invalid memory address or nil pointer dereference
AdGuardHome[2417]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x1d94bc]
AdGuardHome[2417]: goroutine 8001 [running]:
AdGuardHome[2417]: crypto/tls.(*Conn).write(0x4000445500, 0x4001da0b40, 0x129, 0x140, 0x4001ce0900, 0x124, 0x180)
AdGuardHome[2417]:         /home/travis/.gimme/versions/go1.12.5.linux.amd64/src/crypto/tls/conn.go:896 +0xfc
AdGuardHome[2417]: crypto/tls.(*Conn).writeRecordLocked(0x4000445500, 0x735e16, 0x4001ce0900, 0x124, 0x180, 0x0, 0x0, 0x0)
AdGuardHome[2417]:         /home/travis/.gimme/versions/go1.12.5.linux.amd64/src/crypto/tls/conn.go:945 +0x1f4
AdGuardHome[2417]: crypto/tls.(*Conn).writeRecord(0x4000445500, 0x4001ce0916, 0x4001ce0900, 0x124, 0x180, 0x0, 0x0, 0x0)
AdGuardHome[2417]:         /home/travis/.gimme/versions/go1.12.5.linux.amd64/src/crypto/tls/conn.go:967 +0x90
AdGuardHome[2417]: crypto/tls.(*Conn).clientHandshake(0x4000445500, 0x0, 0x0)
AdGuardHome[2417]:         /home/travis/.gimme/versions/go1.12.5.linux.amd64/src/crypto/tls/handshake_client.go:167 +0x108
AdGuardHome[2417]: crypto/tls.(*Conn).Handshake(0x4000445500, 0x0, 0x0)
AdGuardHome[2417]:         /home/travis/.gimme/versions/go1.12.5.linux.amd64/src/crypto/tls/conn.go:1343 +0xdc
AdGuardHome[2417]: net/http.(*persistConn).addTLS.func2(0x0, 0x4000445500, 0x0, 0x4000241320)
AdGuardHome[2417]:         /home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/transport.go:1190 +0x38
AdGuardHome[2417]: created by net/http.(*persistConn).addTLS
AdGuardHome[2417]:         /home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/transport.go:1186 +0x154
systemd[1]: adguard.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: adguard.service: Unit entered failed state.
systemd[1]: adguard.service: Failed with result 'exit-code'.
```

**Comment by ameshkov** [comment] 2019-06-20 11:41
Duplicate of #831 

Upgrade to the latest beta version or switch to the `edge` branch if you're using docker.

**Closed by ameshkov** 2019-06-20 11:41 UTC
Labels: duplicate
