### ISSUE TITLE
Cache don't work with labelled device

### ISSUE THREAD

**Issue by tan-ty** [AdguardTeam/AdGuardHome#4882] opened 2022-09-01 06:38 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

stable 0.107.11

#### What did you do?
I set a big cache and enable optimistic cache,  getting some of my devices labelled. 
#### Expected result
Some requests are stored into cache, and the next time the stored requests come, it'll just response from the cache. And all the devices has separated cache to make edns-client-subnet work better.
#### Actual result
Those devices who is not labelled work just are using cache as normal, but those labelled don't'

**Comment by ainar-g** [comment] 2022-09-01 12:23
Good day.  What exactly do you mean by “labelled clients”?  Do you mean “persistent clients”?  If so, there is a known issue in one of our libraries, AdguardTeam/dnsproxy#169, but that one only concerns clients with custom upstreams.

**Comment by tan-ty** [comment] 2022-09-02 14:39
> Good day. What exactly do you mean by “labelled clients”? Do you mean “persistent clients”? If so, there is a known issue in one of our libraries, [AdguardTeam/dnsproxy#169](https://github.com/AdguardTeam/dnsproxy/issues/169), but that one only concerns clients with custom upstreams.

So when will your team fix the bug? I think cache per client is useful and is not too hard to engineer

**Comment by ainar-g** [comment] 2023-09-07 12:14
Closing as duplicate of https://github.com/AdguardTeam/dnsproxy/issues/169.

**Closed by ainar-g** 2023-09-07 12:14 UTC
Labels: waiting for data
