### ISSUE TITLE
Schedule blocked services 

### ISSUE THREAD

**Issue by guitarbird** [AdguardTeam/AdGuardHome#5753] opened 2023-04-19 15:40 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
Schedule blocked services 

#### Proposed solution
I would like to schedule the way I block tik tok or other services, so it will be blocked from 9pm to 7 am every day.
Thanks

**Comment by ainar-g** [comment] 2023-04-19 15:52
Duplicate of #951

**Closed by ainar-g** 2023-04-19 15:52 UTC
