### ISSUE TITLE
DNS重写优先级调整

### ISSUE THREAD

**Issue by qian9008** [AdguardTeam/AdGuardHome#5686] opened 2023-04-04 15:09 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Description

添加滑动上下调整，而不是删除再添加。

**Comment by ainar-g** [comment] 2023-04-06 17:03
Duplicate of #1577

**Closed by ainar-g** 2023-04-06 17:03 UTC
Labels: duplicate
