### ISSUE TITLE
Feature Request Suggestions

### ISSUE THREAD

**Issue by louis5974** [AdguardTeam/AdGuardHome#4350] opened 2022-03-02 08:56 UTC
Hi, I'm a user of AdGuard Home（v0.107.4） (Linux) and I really like the functionality of your design.
But I would like to make a few suggestions:

1.
Regarding the function of "optimistic cache", what is the specific explanation? Users can't understand.
DNS is cached to AdGuard Home and will not be refreshed until TTL time?
Or exceeds the number set by the cache, and the DNS cache will be discarded if it is not used for a long time?
Please explain to me officially, how to set TTL time and how to set "optimistic cache" when there is plenty?

2.
On the "Query logs" page, currently I need to check a certain day and a certain period of time. I can only check down from the current list directory, which takes a long time. There are many "Query logs" lists in AdGuard Home, which are very unfriendly to view. I really wish the AdGuard company would develop a button to set a specific time and view the logs for a certain time. It will save us a lot of time.

**Comment by louis5974** [comment] 2022-03-02 08:56
![optimistic cache](https://user-images.githubusercontent.com/53338257/156328593-047ec4e3-ece8-47bd-96e6-74a3c70afccc.jpg)
![Query logs](https://user-images.githubusercontent.com/53338257/156328608-8fd14265-c6d1-4bdb-8a24-1a9a00fa77c1.jpg)

**Comment by ainar-g** [comment] 2022-03-02 14:26
Duplicate of #4348

**Closed by ainar-g** 2022-03-02 14:26 UTC
