### ISSUE TITLE
Newest AdGuard Home cant setup.

### ISSUE THREAD

**Issue by Karmylr** [AdguardTeam/AdGuardHome#4479] opened 2022-04-11 10:07 UTC
![image](https://user-images.githubusercontent.com/69903376/162716252-4ea35d9b-999d-44e1-97b0-45c423ec1268.png)

**Comment by agneevX** [comment] 2022-04-11 17:22
Maybe make an effort to fill up the template and provide more context before you ask for help, OP?

**Comment by ainar-g** [comment] 2022-04-11 18:02
#4474 seems to have the same bug.

@IldarKamalov, please investigate.

**Comment by EugeneOne1** [comment] 2022-04-11 20:23
@Karmylr, what version of AdGuard Home are you using?

**Comment by Karmylr** [comment] 2022-04-12 03:19
> @Karmylr，您使用的是哪个版本的 AdGuard Home？



> 在您寻求帮助之前可以尝试重新刷新模板并提供更多时间，OP？

same as https://github.com/AdguardTeam/AdGuardHome/discussions/4474

**Comment by ainar-g** [comment] 2022-04-12 11:15
@Karmylr, @bertmelis, which exact version are you using?  I can't reproduce that with the latest `v0.108.0-a.108+9f0fdc5e`.  We had a bug in the installation for recently, but it has since been fixed.

**Comment by Karmylr** [comment] 2022-04-12 11:17
> @Karmylr, @bertmelis, which exact version are you using? I can't reproduce that with the latest `v0.108.0-a.108+9f0fdc5e`. We had a bug in the installation for recently, but it has since been fixed.


v0.108.0-a.102+c70f941b

**Comment by bertmelis** [comment] 2022-04-12 11:39
When I posted the issue in the discussion tab, I pulled the latest from the Docker hub: `v0.108.0-a.102+c70f941b`

**Comment by ainar-g** [comment] 2022-04-12 11:49
@bertmelis, thanks for testing!  I'll close this as a duplicate of #4465, where we fixed the aformentioned other issue.

**Closed by ainar-g** 2022-04-12 11:49 UTC
Labels: duplicate
