### ISSUE TITLE
Can you store malware/phishing somewhere else?

### ISSUE THREAD

**Issue by bcookatpcsd** [AdguardTeam/AdGuardHome#3935] opened 2021-12-13 18:16 UTC
When I check the dashboard and see there were malware/phishing events.. 

I would like to look at them.. 

Clicking on that graph results in a very delayed lookup time while sifting through the many logs.. 

Is there somewhere/somehow to store those results to retrieve them faster?

(it was seven full minutes - second time was a little faster)

![image](https://user-images.githubusercontent.com/55087301/145866234-cdd13704-314a-4a5b-aa60-b1b9384384fd.png)

Generally those are the most useful.. 

(banana for scale..) 
![image](https://user-images.githubusercontent.com/55087301/145865418-ce2ebcd9-a07b-41d6-9941-4bc269c2b7b1.png)

Bare metal machine
CPU: Intel i5-3470 (4) @ 3.600GHz
Memory: 1968MiB / 7845MiB
Disk: xfs sda sata drive

Thanks in advance either way for a great application.

Thank you for taking the time to read this..

**Comment by ainar-g** [comment] 2021-12-14 10:38
This is basically a duplicate of #2290.  The query log format currently is suboptimal for this case case of events that are few and far between.  Once we have a better log database, such queries should become faster.

**Closed by ainar-g** 2021-12-14 10:38 UTC
