### ISSUE TITLE
Persistent clients identified with MAC addresses don't have requests counts

### ISSUE THREAD

**Issue by xiaoyu2006** [AdguardTeam/AdGuardHome#6980] opened 2024-05-09 10:34 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.48

### Action

- Serve DNS through AdGuard Home DHCP server
- Add persistent clients with MAC addresses as identifiers

### Expected result

GUI shows requests count.

### Actual result

Request counts shows nothing while if clients were identified using IP addresses it would work properly.

<img width="1284" alt="截屏2024-05-09 18 31 23" src="https://github.com/AdguardTeam/AdGuardHome/assets/32544798/eee5007c-c6f2-4679-bbfa-2e036807d659">

### Additional information and/or screenshots

Clients are recognized though.

<img width="600" alt="截屏2024-05-09 18 31 32" src="https://github.com/AdguardTeam/AdGuardHome/assets/32544798/f1b543af-d69b-477e-b9c4-941cf0dfc796">

**Comment by yuukiAme** [comment] 2024-05-12 18:42
It's a weird bug I had. I delete that specific entry in the persistent client and remake it with a slightly different <Client ID>. 

Clear the query log and statistic log as well. It should work again.

**Comment by schzhn** [comment] 2024-05-13 13:13
Duplicate of #4649

**Closed by schzhn** 2024-05-13 13:13 UTC
