### ISSUE TITLE
[Request] Search Query Logs For IP

### ISSUE THREAD

**Issue by hbednar** [AdguardTeam/AdGuardHome#6496] opened 2023-12-05 11:03 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

At the moment you can only search for a domain or the ip of a client. 
I have been unable to search by the ip that has been resolved.

### Proposed solution

Beable to search for any ip that have been resolved not just the domain.

### Alternatives considered and additional information

As an example i can search the  query logs for `example.com` but i cannot search for `93.184.216.34`

**Comment by ainar-g** [comment] 2023-12-05 18:54
Duplicate of #1933

**Closed by ainar-g** 2023-12-05 18:54 UTC
Labels: feature request
