### ISSUE TITLE
Update with wrong version

### ISSUE THREAD

**Issue by bcseputetto** [AdguardTeam/AdGuardHome#4769] opened 2022-07-21 15:59 UTC
Sorry, I use software to translate English. There may be some problems in the description

* **Version of AdGuard Home server:**
  0.107.8
* **How did you install AdGuard Home:**
  GitHub releases
* **How did you setup DNS configuration:**
  System
* **If it's a router or IoT, please write device model:**
  none
* **CPU architecture:**
  x86_64
* **Operating system and version:**
  CentOS8

Currently running version 0.107.8, a new version is reminded, but the new version is 0.107.7

### Screenshots
![adghome](https://user-images.githubusercontent.com/29139573/180259420-9d31e57d-df9c-4657-b8bf-03d089f8a79e.png)

**Comment by ainar-g** [comment] 2022-07-21 16:08
Hello.  This looks like a duplicate of #4768.  The issue should be fixed now.  Please restart AdGuard Home and feel free tell us if it isn't fixed.

**Closed by ainar-g** 2022-07-21 16:08 UTC
