### ISSUE TITLE
Allowed clients Invalid

### ISSUE THREAD

**Issue by kaitongchow** [AdguardTeam/AdGuardHome#6965] opened 2024-05-04 04:55 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.48

### Action

Replace the following command with the one you're calling or a
description of the failing action:

```sh
nslookup -debug -type=a 'www.example.com' '$YOUR_AGH_ADDRESS'
```

### Expected result

In DNS settings->Access settings->Allowed clients, When setting IPv6 CIDRs，IPv4 CIDRs and ClientIDs simultaneously, they will become work.

### Actual result

In DNS settings->Access settings->Allowed clients, When setting IPv6 CIDRs IPv4 CIDRs and ClientIDs simultaneously, IPv6 CIDRs settings will become invalid.

**Comment by kaitongchow** [comment] 2024-05-04 07:06
> @kaitongchow thanks for the report. When you say invalid, what do you mean by that specifically?

@jslawler-gh  If set at the same time(IPv6 CIDRs IPv4 CIDRs and ClientIDs)Allowed clients, IPv6 CIDRs will not be allowed through, Still being blocked

**Comment by kaitongchow** [comment] 2024-05-04 07:18
> 感谢您的报告。当你说无效时，你具体是什么意思？

@jslawler-gh 
![1714807061501](https://github.com/AdguardTeam/AdGuardHome/assets/51440942/4778e0bf-e868-41ff-8143-336677d026bf)
IPv6 CIDR Not working

**Comment by schzhn** [comment] 2024-05-06 10:56
Duplicate of #6192
Fixed in [edge release](https://github.com/AdguardTeam/AdGuardHome/blob/master/README.md#test-unstable-versions) and upcoming v0.107.49.

**Closed by schzhn** 2024-05-06 10:56 UTC
Labels: waiting for data
