### ISSUE TITLE
Blocking mode does not seem to work correctly (NX Domain)

### ISSUE THREAD

**Issue by kungpao42** [AdguardTeam/AdGuardHome#1284] opened 2019-12-20 16:24 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
 0.100.5 * 
* **How did you setup DNS configuration:**
 IoT * 
* **If it's a router or IoT, please write device model:**
Raspberry Pi  * 
* **Operating system and version:**
 Dietpi 6.26.3 * 

### Expected Behavior

In NX Domain mode, I would expect all answers from Adguard Home (matching hostnames/domains) to respond with NX Domain.  

In Null IP mode, I would expect to see the response in the form of an A/AAAA record as 0.0.0.0.

### Actual Behavior

In selecting blocking mode under DNS Settings, I would expect the following behavior:

What I notice happens in actuality is this.  

In NX Domain mode AGH will respond with NX Domain if the blocklist source for that match does not have an IP associated with it on the same line.  If the blocklist source does have an IP address, then AGH will respond with that IP with a TTL of 10.  Thus theip specified in the blocklist is passed onward (ie 0.0.0.0 or 127.0.0.1) in most cases.

Obviously, this should probably not be the case.  I have not tested this behavior in Null IP mode, to see whether or not all IP addresses are standarized to 0.0.0.0.  

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by megaschatzi** [comment] 2019-12-21 19:13
Same here

**Comment by ameshkov** [comment] 2019-12-23 08:22
Yeah, that's the default behavior AGH was using from the very beginning. The setting name is simply wrong, though.

We should have called it "Default" and add a different option that will force NXDOMAIN for all types of rules.

**Comment by szolin** [comment] 2019-12-30 15:46
> We should have called it "Default"

Why do we need this behaviour?
If someone wants to set a custom IP for a host name - he should use Rewrites instead.
What's the use case here?

**Comment by ameshkov** [comment] 2019-12-31 15:30
@szolin the problem is #919, using custom hosts files is the only viable solution at the moment.

**Comment by ameshkov** [comment] 2020-01-10 12:09
@szolin here is the final list:

```
* Default - Respond with NXDOMAIN when blocked by Adblock-style rules and with the IP addresses specified in the rule for /etc/hosts-style blocklists;
* NXDOMAIN – Respond with NXDOMAIN code;
* Null IP – Respond with zero IP address (0.0.0.0 for A; :: for AAAA);
* Custom IP - Respond with a manually set IP address.
```

**Comment by kungpao42** [comment] 2020-01-11 16:34
Is this targeted for a particular release to get fixed?

**Comment by ameshkov** [comment] 2020-01-12 18:59
@kungpao42 yep, it's assigned to v0.101 and it's the next major update.

**Closed** 2020-01-20 16:17 UTC
Labels: P3: Medium, bug
