### ISSUE TITLE
Hope to add automatic refresh function of dashboard

### ISSUE THREAD

**Issue by HolyGu** [AdguardTeam/AdGuardHome#7107] opened 2024-07-02 21:49 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Currently, on the dashboard interface, we need to manually click the "Refresh Statistics" button to see the latest data. It is recommended to add an auto-refresh option so that the page can automatically display the data in real-time.

### Proposed solution

Updating page data in real-time using asynchronous refreshing.

**Comment by schzhn** [comment] 2024-07-03 10:14
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/1739

**Closed by schzhn** 2024-07-03 10:14 UTC
Labels: feature request
