### ISSUE TITLE
Query log: search by response codes

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#2226] opened 2020-10-27 09:19 UTC
See the discussion here:
https://github.com/AdguardTeam/AdGuardHome/issues/2223#issuecomment-716922235

**Comment by KizunaH** [comment] 2020-10-27 17:55
Possible duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/1933 https://github.com/AdguardTeam/AdGuardHome/issues/594

**Closed** 2023-12-05 18:54 UTC
Labels: feature request, P3: Medium
