### ISSUE TITLE
Server began to freeze after the last update

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#5661] opened 2023-03-30 20:02 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-b.31

#### What did you do?

Classic GH-script installation. Debian 11 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

Nothing special. Just updated to the last beta version and keep use as always. But now the server freezes. The verbose log is attached. Please start look from 22:43 MSK:
[log.txt](https://github.com/AdguardTeam/AdGuardHome/files/11115624/log.txt)

**Comment by cjom** [comment] 2023-03-30 23:09
It's not only the HTTP server stop responding, connected devices also start saying "no internet access" either new or already connected.

My AGH is running directly in router Xiaomi AX3600 with OpenWRT.
This happens some hours after reboot, but reboot does not always fixes issue.

**Comment by Aiolos-Wang** [comment] 2023-03-30 23:24
It is same for me.
After updated to latest version. server started to stuck in its web page. Connected devices can not query DNS request.
Rebooting the server only relieves it for a while.

**Comment by tomamplius** [comment] 2023-03-31 02:38
It is same for me.

**Comment by muok** [comment] 2023-03-31 03:29
Same issue here. There's a config file error. AGH modifies the config file and there's a syntax error.

**Comment by Gandulf78** [comment] 2023-03-31 05:38
Same here on ARMv7.

**Comment by Fooose** [comment] 2023-03-31 08:18
The error also occurs here, on an x86 Pfsense system.
AdGuard freezes and only a restart brings relief.

**Comment by ainar-g** [comment] 2023-03-31 10:08
Thanks for the reports, everyone.  We're investigating but cannot reproduce it so far.  Enabling and sharing [verbose logs] either here or through <devteam@adguard.com>, like OP did, would really help.

@ammnt, if it really is the query log, does disabling it fix the issue?  Also, are there any panics in e.g. `/var/log/AdGuardHome.err` and `/var/log/AdGuardHome.out`?

@mouk, could you please elaborate?  What kind of error do you see?  There shouldn't be any syntax errors, but if you were following Edge, you could be affected by #5627, which shouldn't affect Beta users.

**Comment by ammnt** [comment] 2023-03-31 10:21
@ainar-g, I have sent you the message just now. Check devteam@adguard.com mailbox please🙂

**Comment by ammnt** [comment] 2023-03-31 14:06
@ainar-g, I recorded a video with the problem reproducing and the log output at that point. I will send you this next 10 minutes.

**Comment by ainar-g** [comment] 2023-03-31 15:04
@ammnt, thanks for the information.  We have a few theories.  The latest Edge release contains a fix for one of them.  We're working on the other ones.

**Comment by qqsir-dev** [comment] 2023-04-01 11:52
same problem with v0.108.0-a.496+3575aa05
CONTAINER ID   IMAGE                      COMMAND                  CREATED         STATUS                     PORTS     NAMES
8733c87cb5fd   adguard/adguardhome:edge   "/sbin/tini -- /opt/…"   2 minutes ago   Up 2 minutes (unhealthy)             adguardhome

**Comment by fabricionaweb** [comment] 2023-04-01 22:37
It had happened to me 3 times today. `v0.108.0-b.31` running on OpenWRT 22.03.3.
I have turned verbose on to try to catch some logs. But nothing yet. I may back if I found anything useful

**Comment by ammnt** [comment] 2023-04-02 18:27
@ainar-g, I have not tested the latest version on the edge channel, but I can say that my server has not freezed over the past few days, since I did not use the web interface🤔

**Comment by qqsir-dev** [comment] 2023-04-03 13:29
I am running v0.108.0-a.496+3575aa05 on Ubuntu 22.04.2 with Docker, it runs several minutes and goes to unhealthy, please check. Thanks.

**Comment by qqsir-dev** [comment] 2023-04-03 14:30
> I am running v0.108.0-a.496+3575aa05 on Ubuntu 22.04.2 with Docker, it runs several minutes and goes to unhealthy, please check. Thanks.

same as Version: v0.108.0-a.497+2a0d0629
CONTAINER ID   IMAGE                      COMMAND                  CREATED         STATUS                     PORTS     NAMES
355ff4b31d43   adguard/adguardhome:edge   "/sbin/tini -- /opt/…"   3 minutes ago   Up 3 minutes (unhealthy)             adguardhome

**Comment by ammnt** [comment] 2023-04-03 14:47
@ainar-g, I am sure that the Docker container fall down itself, as healthcheck knocks on HTTP port. We must try to run the container without healthcheck and if it does not fall, then it is about HTTP processing and the library that is responsible for this.

**Comment by blamaz** [comment] 2023-04-03 19:03
Same problem here on openwrt master snapshot.

**Comment by qqsir-dev** [comment] 2023-04-04 00:42
> @qqsir-dev, please report Docker healthcheck issues to #3290. Thanks.
> 
> @ammnt, our current theory is that long-running querylog searches prevented new requests from being counted. We've made a few changes that address those issues. Were you (or anyone watching the issue) able to test the most recent Edge releases?

Thanks @ainar-g, I uninstall the latest version of docker engine and reinstall the old version (5:20.10.13~3-0~ubuntu-jammy) then problem gone!!!

**Comment by ammnt** [comment] 2023-04-04 16:48
@ainar-g, I checked the latest version of the Docker image now. There are no changes - the server still falls after a while. The logs are not unusual🤷🏻‍♂️

**Comment by ammnt** [comment] 2023-04-05 12:27
@ainar-g, unfortunately the same issue with disabled safesearch function. The verbose log is attached:
[log.txt](https://github.com/AdguardTeam/AdGuardHome/files/11158717/log.txt)

**Comment by ainar-g** [comment] 2023-04-05 13:10
Thanks for trying it out.  We are still investigating.

**Comment by fabricionaweb** [comment] 2023-04-05 13:14
I had rolled back to stable. But before it, if it does help, I had one client that uses safe-search. And I had indeed notice some "adults websites" being blocked and it can be related.

**Comment by ammnt** [comment] 2023-04-05 14:46
I have tested the latest beta build. Works really better for now. Keep trying to reproduce it🫡

**Comment by qqsir-dev** [comment] 2023-04-05 14:48
> I have tested the latest beta build. Works really better for now. Keep trying to reproduce it🫡

me too, its working good for about 10 more minutes.

**Comment by qqsir-dev** [comment] 2023-04-05 14:52
> But I completely disabled safesearch service as @ainar-g told before👆🏼

I didn't use safe search, its working good now.

**Comment by qqsir-dev** [comment] 2023-04-05 15:29
But, Encryption on/off will stop http service.

**Comment by ammnt** [comment] 2023-04-05 17:24
I don't use built-in encryption but it works fine now with the enabled safesearch too.

**Comment by virtualm2000** [comment] 2023-04-05 22:15
I've tried v0.108.0-b.32. I doesn't work if safe search is enabled in client settings. It will become non responsive as before.
If safe search is disabled everywhere then it seems it works.

**Comment by ainar-g** [comment] 2023-04-06 13:30
@ammnt, we've made a few improvements to safe search as well as the debugging API.  Could you please update to `v0.108.0-a.505+b1120221` or later and set `debug_pprof` to `true` in the config file?  Then, if you are able to reproduce the error, can you please save and send us the following files:

```
curl -o /tmp/goroutine.pprof 'http://localhost:6060/debug/pprof/goroutine?debug=1'
curl -o /tmp/mutex.pprof 'http://localhost:6060/debug/pprof/mutex?debug=1'
curl -o /tmp/block.pprof 'http://localhost:6060/debug/pprof/block?debug=1'
```

These three files will contain the information that should help us find out, what is causing the issue.  We're doing the same on our testing machines, but it'll help to have more data.

**Comment by ainar-g** [comment] 2023-04-06 16:57
Update: we had been able to reliably reproduce the freeze and have pushed a change that fixes the issue in our tests in Edge build `v0.108.0-a.506+5d5a7295`.

**Comment by virtualm2000** [comment] 2023-04-06 23:47
Running v0.108.0-a.506+5d5a7295 for about one hour and no issues anymore.

**Comment by Aiolos-Wang** [comment] 2023-04-06 23:52
I updated to v0.108.0-a.506+5d5a7295 of my ADguard in LXC. It is  runing over 1 hour and woks well till now

**Comment by blamaz** [comment] 2023-04-07 11:14
Updated to v0.108.0-a.506+5d5a7295 and running fine again

**Comment by cjom** [comment] 2023-04-08 10:31
Version: v0.108.0-a.508+15bba281 running in router Xiaomi 3600 with safe search enable
Running without issues for around 12h.

**Comment by ainar-g** [comment] 2023-04-10 10:12
Thanks everyone for testing!  Since a lot of people are indicating that AGH runs well after the fix, we'll close this issue.  The fix will be included into the next Beta and Release builds, which should come in the next few days.

**Closed by ainar-g** 2023-04-10 10:12 UTC
Labels: bug, P2: High
