### ISSUE TITLE
DNS leaking

### ISSUE THREAD

**Issue by Vansinnet** [AdguardTeam/AdGuardHome#511] opened 2019-01-01 11:39 UTC
### Steps to reproduce

1. Set AdGuard Home 0.92 to use 1.1.1.1 over TLS
2. Go to www.dnsleaktest.com after you've been browsing for a couple of minutes
3. Start the extended test
4. The test result shows both 1.1.1.1 as your DNS as well as your ISP:s. With Pi-Hole this didn't happen

### Expected behavior

Only 1.1.1.1 should show up as your DNS in the results.

### Actual behavior

Both the DNS of my ISP and Cloudflare are shown (and used when browsing?). AdGuard Home should not leak actual ISP DNS when 1.1.1.1 has been set.

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| 0.92
| How did you setup DNS configuration:| The official instructions for installation. Also pointed the router to use the Pi 3 Model B+ as DNS server.
| If it's a router or IoT, please write device model:| Raspberry Pi 3 Model B+
| Operating system and version:| Fully updated version of Rasbian.

**Comment by Vansinnet** [comment] 2019-01-01 16:42
I found out that the problem most likely occur because:

1) DNS-server (AdGuard Home) doesn't respond properly every now and then and then my router falls back on ISP DNS.
2) I can fix this by manually enforcing DNS locally to AdGuard Home (192.168.1.xx) on my Windows PC. No leaks now. BUT, whenever the DNS-server (AdGuard Home) doesn't respond properly I now get this error in Chrome:

Webbplatsen kan inte nås Webbsidan på https://mullvad.net/sv/blog/ kan ligga nere för tillfället eller kan ha flyttats permanent till en ny webbadress.
ERR_NAME_RESOLUTION_FAILED

So, my conclusion is that for some reason AdGuard Home doesn't respond like it should to all DNS queries. Never had this problem with Pi-Hole (it's exactly the same hardware too) so I reckon it's caused by the AdGuard Home software.

**Comment by Vansinnet** [comment] 2019-01-01 16:42
I found out that the problem most likely occur because:

1) DNS-server (AdGuard Home) doesn't respond properly every now and then and then my router falls back on ISP DNS.
2) I can fix this by manually enforcing DNS locally to AdGuard Home (192.168.1.xx) on my Windows PC. No leaks now. BUT, whenever the DNS-server (AdGuard Home) doesn't respond properly I now get this error in Chrome:

Webbplatsen kan inte nås Webbsidan på https://mullvad.net/sv/blog/ kan ligga nere för tillfället eller kan ha flyttats permanent till en ny webbadress.
ERR_NAME_RESOLUTION_FAILED

So, my conclusion is that for some reason AdGuard Home doesn't respond like it should to all DNS queries. Never had this problem with Pi-Hole (it's exactly the same hardware too) so I reckon it's caused by the AdGuard Home software.

**Comment by caio** [comment] 2019-01-02 11:12
The behavior you describe on your last comment is likely caused by the same issue that causes #505 - [This comment](https://github.com/AdguardTeam/AdGuardHome/issues/505#issuecomment-450643830) hints at what's going on.

**Comment by ameshkov** [comment] 2019-01-02 17:16
Marked as duplicate of #505

**Closed by ameshkov** 2019-01-02 17:16 UTC
Labels: duplicate
