### ISSUE TITLE
IPv6 not available when specify network interface

### ISSUE THREAD

**Issue by Fluqzy** [AdguardTeam/AdGuardHome#4462] opened 2022-04-03 21:40 UTC
Hey,
I recently installed Adguard Home. On the setup i choosed the web ui and the dns server should only work on one network interface.
In my case it is enp4s0. I picked the option and it only showed the IPv4 adress of this interface, but when i run `ip a` in my terminal, the same network interface shows my IPv4 Adress + multiple IPv6 adresses. Now here comes the tricky part. When i do not choose a specific network interface, my IPv6 adress is shown there and the DNS Server does work over this adress, but not when i specify the network interface.
I think this is a bug, that network adresses are not correctly set to the right network interface, but im not the expert to check if this is true.

**Comment by fernvenue** [comment] 2022-04-04 00:00
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/3635.

> Yes, it seems like currently the only way to get this working is with one or more IPv6 global unicast addresses in the config file. In the future, we should probably add an ability to put network interface names there instead of just IP addresses. --https://github.com/AdguardTeam/AdGuardHome/issues/3635#issuecomment-924888971

As @ainar-g said, it's still a feature request, for now you can edit configuration file `AdGuardHome.yaml` by yourself.

**Closed** 2022-04-05 12:16 UTC
Labels: duplicate
