### ISSUE TITLE
Dashboard - Click to Filter By

### ISSUE THREAD

**Issue by dcosborne** [AdguardTeam/AdGuardHome#1711] opened 2020-05-20 18:02 UTC
### Problem Description
The Dashboard has useful information, but it's difficult to transition from the info supplied to the actual queries referenced.

### Proposed Solution
For each line item in the statistics on the dashboard, add a "click to filter by" action. For example, clicking "Blocked adult websites" would take you to the Query Log, with all results filtered to that category. The same thing should happen when clicking a client or domain.

**Comment by ameshkov** [comment] 2020-05-20 19:24
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/1625

**Closed by ameshkov** 2020-05-20 19:24 UTC
