### ISSUE TITLE
Query Log layout view changes when switched back to site

### ISSUE THREAD

**Issue by agneevX** [AdguardTeam/AdGuardHome#3586] opened 2021-09-13 18:37 UTC
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  *  0.106.3
* **How did you install AdGuard Home:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * 
* **Operating system and version:**
  * 

### Details

Client: iPadOS 14.8 running Safari

The layout view changes when I switch back to the site. 

Screen recording: https://www.dropbox.com/s/8actok3uc30io4t/agh_ui_bug.mp4?dl=0

**Comment by ainar-g** [comment] 2021-09-14 10:34
Hi and thank you for the report.  I cannot reproduce this in Firefox on my PC, so perhaps it's a Safari issue.

@Chinaski1, please attempt to reproduce this on the latest beta when you have the time.

**Comment by Chinaski1** [comment] 2021-09-14 11:27
Hello @agneevX 

I try to reproduce your issue on the latest beta version and but I don't encounter the problem described.
But note that I checked with Safari 12.4.8

**Comment by agneevX** [comment] 2021-09-14 12:05
Current MobileSafari version is 14.1.2 on iOS/iPadOS 14.8.

**Comment by Birbber** [comment] 2022-09-02 11:53
This issue is being investigated in #4854. Closing this one as duplicate.

**Closed by Birbber** 2022-09-02 11:53 UTC
Labels: duplicate
