### ISSUE TITLE
how to let filters update connection use proxy?

### ISSUE THREAD

**Issue by Mosney** [AdguardTeam/AdGuardHome#1459] opened 2020-03-10 02:17 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I checked to make sure that this issue has not already been filed
- [x] I am running the latest version
- [x] I checked the documentation and found no answer

### Problem Description

It's hard to make a connection to GitHub raw file in China Mainland but most filter rules in here, so I'm looking a method to let update process use http proxy, and I found this https://github.com/AdguardTeam/AdGuardHome/issues/458#issuecomment-444059536 but it not work on my side. 
I search some ways to set environment variables in **OpenWrt** which use **init.d/service** to launcher daemon, for example: direct add `export HTTP_PROXY=http://proxy.lan:3128/` in [/etc/init.d/AdGuardHome](https://github.com/rufengsuixing/luci-app-adguardhome/blob/master/root/etc/init.d/AdGuardHome), but it not work.
So I need some help about that, very appreciate.

**Comment by ameshkov** [comment] 2020-03-11 13:45
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/458

Please upvote the original issue

**Closed by ameshkov** 2020-03-11 13:45 UTC
Labels: duplicate

**Comment by djdjfjfkeocj** [comment] 2024-03-29 05:08
我也一样，设置了但依旧不起作用
Me too, set it up but it still doesn't work
