### ISSUE TITLE
Fatal error while checking '/etc/hosts'

### ISSUE THREAD

**Issue by manciuszz** [AdguardTeam/AdGuardHome#3906] opened 2021-12-01 00:09 UTC
Versions after **v0.107.0-b.13** gives a fatal error

```sh
2021/11/30 23:48:01.173951 [info] AdGuard Home, version v0.107.0-b.15
2021/11/30 23:48:02.391389 [fatal] initing hosts container: hosts container: refreshing : checking "etc/hosts": attempted to read more than 1048576 bytes
```

Removing or clearing '/etc/hosts' file does solve the issue.

**Why is this file size check a thing?**

P.S. The '/etc/hosts/ file was automatically generated (by other software) and it was the size of 3MB.

**Comment by ainar-g** [comment] 2021-12-01 10:45
@EugeneOne1, please investigate to see if the check is really necessary in this case.

**Comment by EugeneOne1** [comment] 2021-12-01 13:51
@manciuszz, we've just pushed the build that should fix the issue to the edge channel.  Could you please install it and check if the problem is fixed for you?

**Comment by manciuszz** [comment] 2021-12-01 21:56
> @manciuszz, we've just pushed the build that should fix the issue to the edge channel. Could you please install it and check if the problem is fixed for you?

Can confirm that it works just fine ! Tested both with a clean '/etc/hosts' file and a 4MB one.

![chrome_R2SOnF61de](https://user-images.githubusercontent.com/2539661/144320296-e1e65fa2-82e2-4967-8eb6-a9008de3e91e.png)

Good job.

**Comment by EugeneOne1** [comment] 2021-12-02 08:32
@manciuszz, thanks for testing.  I'll close the issue for now.

**Closed by EugeneOne1** 2021-12-02 08:32 UTC
Labels: enhancement, P4: Low
