### ISSUE TITLE
100% CPU load

### ISSUE THREAD

**Issue by SCP-155** [AdguardTeam/AdGuardHome#4042] opened 2021-12-29 18:13 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.107.1
* **How did you install AdGuard Home:**
  * GitHub releases
* **How did you setup DNS configuration:**
  * DoT Resolver with static IPv4 & IPv6 on vServer
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Ubuntu 20.04.3 LTS

### Expected Behavior
Not utilizing 100% CPU power from `.../AdGuardHome -s run` process.

### Actual Behavior
AdGuardHome process is constantly using 100% CPU power (in my case 200% because the VM has 2 Cores). After manually restarting the process (`./AdGuardHome -s restart`) its using normal resources. After ~60 seconds its jumping back to 100% CPU load. RAM usage seems normal.

### Screenshots

<details><summary>Screenshot:</summary>

![cpu-usage](https://user-images.githubusercontent.com/64270850/147691268-4b5a8c28-dc55-48d2-a622-e4dc0cb93479.PNG)

</details>

### Additional Information
Problem only occurred after updating to v0.107.1
Please let me know if I can post any further information like logs, etc.

Edit: Restarting the whole Server does not help. CPU usage jumps to full utilization again.

**Comment by ainar-g** [comment] 2021-12-29 18:26
Hello and thank you for your report!  Can you please [enable verbose logs][1] and either attach them here or send them to devteam@adguard.com?  There's been a few reports about that recently, and we're already investigating.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by SCP-155** [comment] 2021-12-29 18:37
Here is the log. Containing the start of AdGuardHome and a spike to 100% CPU usage after a few seconds. 
[log.txt](https://github.com/AdguardTeam/AdGuardHome/files/7790168/log.txt)

**Comment by CordoWEB** [comment] 2021-12-29 18:41
I have the same issue on (x64 architecture) :
 - Ubuntu 20.04.3 LTS
 - Windows Server 2016
 
 All seems to be OK on Raspberry (PI4b a Pi Zero W).

**Comment by trenchcoatjedi** [comment] 2021-12-29 19:14
Exact same issue started today for me after upgrading to v0.108.0-a.20+380cff07 on Edge Channel.

OpenWRT 21.02.1 running on Raspberry Pi 4B

**Comment by ainar-g** [comment] 2021-12-29 19:27
@SCP-155, @CordoWEB, @trenchcoatjedi, @tuday2, we were able to reproduce the issue and posted a fix to the `edge` channel.  Direct link to the `edge` Linux build for the AMD64 arch:

<https://static.adguard.com/adguardhome/edge/AdGuardHome_linux_amd64.tar.gz>

Could any of you please verify that the fix works for you?  If so, we'll release v0.107.2 in an hour or so.

**Comment by trenchcoatjedi** [comment] 2021-12-29 19:32
@ainar-g 

Downloaded the new edge binary, stopped AGH home service, renamed old binary, copied new binary to AGH folder. Attempted to start the new AGH binary and get this error:

/opt/AdGuardHome/AdGuardHome: line 1: syntax error: unexpected end of file (expecting ")")

**Comment by ainar-g** [comment] 2021-12-29 19:35
@trenchcoatjedi, that was a link for an AMD64 binary.  Links to all `edge` builds are in the README.  Here's a direct one for **64-bit ARM:**

<https://static.adguard.com/adguardhome/edge/AdGuardHome_linux_arm64.tar.gz>

**Comment by SCP-155** [comment] 2021-12-29 19:39
Now running v0.108.0-a.23+a0bb5ce8 on AMD64. 
Seems to be fixed now. At least in the short period of time watching it. Will have my eyes on it for longer. But no issues so far.

**Comment by Tinuz97** [comment] 2021-12-29 19:46
No log, but same issue here after the update (v0.107.1)

**Comment by t3dium** [comment] 2021-12-29 19:47
same

**Comment by SCP-155** [comment] 2021-12-29 20:00
Update for me after 20 minutes: 
Still no issues. Tried restarting the service after 20 minutes just to play around with it. Still no issues. Looks like its fixed for me. Thanks for the blazing fast support!

**Comment by Tinuz97** [comment] 2021-12-29 20:08
Fixed with the new update v0.107.2 here also, normal CPU now.

**Comment by ainar-g** [comment] 2021-12-29 20:09
Thanks for testing and providing logs to all!

**Closed by ainar-g** 2021-12-29 20:09 UTC
Labels: bug, P1: Critical

**Comment by trenchcoatjedi** [comment] 2021-12-29 20:12
> @trenchcoatjedi, that was a link for an AMD64 binary. Links to all `edge` builds are in the README. Here's a direct one for **64-bit ARM:** 

> https://static.adguard.com/adguardhome/edge/AdGuardHome_linux_arm64.tar.gz

Now running v0.108.0-a.23+a0bb5ce8 **ARM64** version. After 30 min, usual metrics (mainly CPU utilization, IRQs and thermal) are back to baseline. Will report back if anything changes. Thanks for the help and support!

**Comment by tuday2** [comment] 2021-12-29 20:13
Fixed with 0.107.2 for me as well.

**Comment by wsltshh** [comment] 2021-12-31 00:01
v0.107.2
When using tcp to call adguard home dns service
Three error logs will appear every time adguard home is re-run, regardless of whether the communication with https://dns-family.adguard.com is normal or not
If the communication with https://dns-family.adguard.com is abnormal, the error log will be output continuously

[error] handling tcp: handling tcp request: talking to dns upstream: failed to check host "lati-af.opera.com": safe browsing: requesting https://dns-family.adguard.com:443/dns-query: Get "https://dns-family.adguard.com:443/dns-query?dns=_***": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[error] handling tcp: setting deadline: set tcp 192.168.1.6:53: use of closed network connection
[error] handling tcp: closing conn: close tcp 192.168.1.6:53->192.168.1.112:4587: use of closed network connection
