### ISSUE TITLE
Restarting PC Resets AdGuard Server Setup, While Stopping and Restarting Service from Docker Desktop works fine

### ISSUE THREAD

**Issue by chlw2123** [AdguardTeam/AdGuardHome#7132] opened 2024-07-14 07:39 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Windows, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

latest

### Action

Followed the guide here.

https://hub.docker.com/r/adguard/adguardhome

My setup: Windows 11 64bit running docker through WSL2

This is my docker run command:

    docker run --name adguardhome\
    --restart always\
    -v ~/adguardhome/work:/opt/adguardhome/work\
    -v ~/adguardhome/conf:/opt/adguardhome/conf\
    -p 53:53/tcp -p 53:53/udp\
    -p 67:67/udp -p 68:68/udp\
    -p 35351:80/tcp -p 35352:443/tcp -p 35353:443/udp -p 35354:3000/tcp\
    -p 853:853/tcp\
    -p 784:784/udp -p 853:853/udp -p 8853:8853/udp\
    -p 5443:5443/tcp -p 5443:5443/udp\
    -d adguard/adguardhome

### Expected result

So after running this and setting the DNS server address on my router to be my PC's local network address, and finishing with the setup on localhost:35354 which is mapped to port 3000. I can then access localhost:35351 which is mapped to port 80 and see the DNS queries made and some of the sites blocked working correctly. Also verified that the configuration files persisted in both directories both before and after a PC restart.
 
 -v ~/adguardhome/work
 -v ~/adguardhome/conf
 
 If I restart my PC and afterwards have the adguardhome service automatically starts with it, I expect to be able to access the dashboard, localhost:35351.

### Actual result

 However, after I restart the PC, and with the adguardhome service now running, I cannot access localhost:35351 anymore but I can access localhost:35354 which will prompt me to set up adguardhome once again but I did not have to do that. Stopping the adguardhome service and starting it back again allow access to the dashboard, localhost:35351 once again.
 
 Not too sure if there is anything wrong with my setup or it's just a known problem with WSL2?

**Comment by tjharman** [comment] 2024-07-14 19:01
I don't think this is an AdGuardHome problem, more likely an issue with docker.  Potentially when the PC/Server is starting up Docker isn't setting up ports/permissions properly, maybe some service Windows Docker requires hasn't started yet.  But then when you go to do it manually, it has and it works now.

Actually, I expect maybe the problem is the ~/ you have in your command.  On bootup how will Docker know what user you are, it has to wait until you're logged in to know that.  Try filling out c:\users\bob\ or whatever the WSL equivalent is and see if that resolves the issue.

**Comment by he-pennypacker** [comment] 2024-07-15 08:52
> Actually, I expect maybe the problem is the ~/ you have in your command. On bootup how will Docker know what user you are, it has to wait until you're logged in to know that. Try filling out c:\users\bob\ or whatever the WSL equivalent is and see if that resolves the issue.

Yes, that's my thought too. Set an absolute path

**Comment by chlw2123** [comment] 2024-07-15 18:32
@tjharman

Yup, the issues is fixed after turning off the auto-start option and changing the paths to paths to docker volumes instead.

**Comment by tjharman** [comment] 2024-07-15 20:55
Great, I will close this ticket.

**Closed** 2024-07-15 20:55 UTC
Labels: waiting for data, docker
