### ISSUE TITLE
Add an option to ignore local hosts file

### ISSUE THREAD

**Issue by AlexHighTower** [AdguardTeam/AdGuardHome#1947] opened 2020-07-26 07:51 UTC
Hello,

using latest 0.103.2 I found that it parse local /etc/hosts file and return addresses from it and return to clients wrong IP.
e.g., hosts have record 
127.0.0.1 domain.name
and when client request domain.name agh return 127.0.0.1 instead of forwarding query to upstream...
I need to disable reading local hosts file

**Comment by ameshkov** [comment] 2020-07-26 08:10
This is the intended behavior. Please explain why do you want to change it and why can't you edit the hosts file instead?

**Comment by AlexHighTower** [comment] 2020-07-26 10:20
I'd prefer to have possibility disable reading local hosts file

hosts have higher priority of dns for **local host** and I can override some hosts for some purposes. plus I prefer local host domain name point to 127.0.0.1 instead of static or dynamic ip.
and what you've done? - you translate local host setting to all agh clients...
this is not acceptable!

**Comment by AlexHighTower** [comment] 2020-07-26 10:45
in addition you broke another thing:
for example, there is domain example.com
it has A and MX records
if call host example.com
result will contain both A and MX records
if add example.com to /etc/hosts and ask host example.com
in this case only A record is returned and no MX

**Comment by Eyeborgs** [comment] 2020-07-26 18:40
> I'd prefer to have possibility disable reading local hosts file

I want to have a function like this too

**Comment by ammnt** [comment] 2020-07-27 09:17
@ameshkov, yes, it must be definitely optional. I use four IP addresses (two ipv4 and two ipv6), but because of the hosts file, essentially only one ipv4 address works when I access the domain😒

**Comment by ameshkov** [comment] 2020-07-30 12:32
Temporary solution - use AGH docker image

**Comment by KizunaH** [comment] 2020-10-04 02:47
> Temporary solution - use AGH docker image

I also interest for this topic. "Add an option to ignore local hosts file"
Docker instance too apply it's etc/hosts https://github.com/AdguardTeam/AdGuardHome/issues/2085

**Comment by EugeneOne1** [comment] 2021-04-13 12:04
The new option `--no-etc-hosts` was introduced in e671f43 and is available in the latest snapshots.  The [wiki section](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#command-line-arguments) about flags is also updated.  Could you please check if our solution works well for you?

**Comment by AlexHighTower** [comment] 2021-04-13 12:21
> The new option `--no-etc-hosts` was introduced in [e671f43](https://github.com/AdguardTeam/AdGuardHome/commit/e671f43a2fa8ebf860217936fd11e1b568154a30) and is available in the latest snapshots. The [wiki section](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#command-line-arguments) about flags is also updated. Could you please check if our solution works well for you?

I'd love to, but where can I get x64 linux binary for tests?

**Comment by EugeneOne1** [comment] 2021-04-16 09:54
@AlexHighTower, hi, just a heads-up, we've messed up the feature in the initial snapshot and beta 2, so you probably **shouldn't** install it.  Any `edge` release after 69f526b13 should be fine though.  We're planning to release beta 3 on Monday or Tuesday (19th or 20th of April) which will also contain the fixed version.  Apologies!

**Comment by EugeneOne1** [comment] 2021-04-21 11:44
We'll close the issue for now.  Please feel free to open new issues if the feature will cause any problems.

**Closed by EugeneOne1** 2021-04-21 11:44 UTC
Labels: P3: Medium, enhancement

**Comment by celevra** [comment] 2023-04-11 19:18
--no-etc-hosts is depricated now
what is the new way?

**Comment by vin047** [comment] 2023-10-03 17:20
`clients.runtime_sources.hosts` to `false` in the config file.

source: https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file

**Comment by tjharman** [comment] 2024-01-28 18:51
Hi,
This option ```clients.runtime_sources.hosts: false``` isn't working.
My AdGuardHome (v0.107.43) is still using my /etc/hosts

Should I log a seperate issue or keep it contained within this one?

Thanks!

**Comment by tjharman** [comment] 2024-01-28 20:20
Sorry ignore my update here, I can see that https://github.com/AdguardTeam/AdGuardHome/issues/6610 exists.
