### ISSUE TITLE
Client-based filtering settings do not work when filtering is turned off in the general settings

### ISSUE THREAD

**Issue by ZeroClover** [AdguardTeam/AdGuardHome#2875] opened 2021-03-25 15:07 UTC
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
v0.105.2
* **How did you install AdGuard Home:**
Snapcraft
* **How did you setup DNS configuration:**
Dedicated server
* **CPU architecture:**
AMD64
* **Operating system and version:**
Debian 10

---

I set up a new instance of AGH and want to disable filtering by default and enable it only for specific clients.

I disabled Filter in the general settings of AGH, then added a client with the name ADfilter and set the Identifier to adfilter and enabled filtering for this client.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/13190004/112494667-348eab80-8dbe-11eb-9351-76ec2400d3c3.png)

![image](https://user-images.githubusercontent.com/13190004/112494715-3d7f7d00-8dbe-11eb-9e3a-667db43147ce.png)

</details>

After that, I tried DNS queries through DoH (https://example.com/dns-query/adfilter) and DoT (tls://adfilter.example.com), and the ad domain resolves normally and is not filtered.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/13190004/112495272-b5e63e00-8dbe-11eb-9189-b876c7548e2f.png)

</details>

**Comment by ainar-g** [comment] 2021-03-25 15:31
Thanks for the report.  As far as I know, it “works as intended”, although I personally am not sure if that's what we want to go on doing.  @ameshkov, what would you say?

**Comment by ameshkov** [comment] 2021-03-26 10:02
@ainar-g actually, this looks like a bug to me.

**Comment by ZeroClover** [comment] 2021-03-29 01:00
> @ainar-g actually, this looks like a bug to me.

Does this mean that client-level filtering should remain in effect when global filtering settings are turned off?

Will AdGuard fix this?

Thanks.

**Comment by ainar-g** [comment] 2021-03-29 09:14
@ameshkov, I've seen the code that does this, so I just assumed that that was the correct behaviour.  If it is a bug, I'll see if I can fix it in the current cycle.

**Comment by ameshkov** [comment] 2021-03-29 12:12
@ainar-g well, note that I am talking about the global setting (settings -> general -> block domains using filters), not the "Disable/enable protection" button on the main screen.

**Comment by Jerrywang959** [comment] 2021-04-10 17:35
I have faced the same issue and hope it to be fixed

**Comment by EugeneOne1** [comment] 2021-05-13 11:57
Hello, @ZeroClover.  The snapshot that should fix this issue have been published to the edge channel.  Could please check, if our solution works for you?

**Comment by EugeneOne1** [comment] 2021-05-18 10:45
We'll close this issue for now.  Please, feel free to reopen it, if the problem remains.

**Comment by ZeroClover** [comment] 2021-05-20 21:48
@EugeneOne1 There seems to be a new problem.

After upgrading to v0.106.3, even if "Block domains using filters" is turned off in the global settings, it will still block domains using filters without matching any client rules.

I have tried this on multiple instances of my AGH and restarted AGH before each attempt.

**Comment by EugeneOne1** [comment] 2021-05-21 11:14
Hello, @ZeroClover.  It seems that the bug is related to the original issue.  Thanks for reporting, we're going to reopen it.

**Comment by EugeneOne1** [comment] 2021-05-26 14:35
Hello again, @ZeroClover.  The latest edge builds are already contain our solution.  Could you please try it and check if the problem is gone?

**Comment by ZeroClover** [comment] 2021-05-26 14:44
Hi @EugeneOne1 , I have tested on v0.107.0-a.45+755a5055 and confirmed that both issues mentioned in this issue had been fixed. Thank you for your prompt handling.

**Comment by EugeneOne1** [comment] 2021-05-26 14:48
Thank you for testing.  We'll close the issue for now.

**Closed by EugeneOne1** 2021-05-26 14:48 UTC
Labels: P3: Medium, bug
