### ISSUE TITLE
[Feature Request] Allow local network names to be resolved (from /etc/hosts?)

### ISSUE THREAD

**Issue by tonyklawrence** [AdguardTeam/AdGuardHome#783] opened 2019-05-30 17:15 UTC
I currently have many devices configured on my local network and it would be great if AdGuard would be allow me to configure these hostname/ip mappings and resolve them so that I can use the hostnames in my browser rather than IPs.

It is possible to add these and mount them in /etc/hosts so that they are resolved in the AdGuard UI, but the DNS server does not honour these.  Also, if they are added in the filters section then they resolve but appear as blocks domains.

Using Pi-hole I could either mount a separate dnsmasq config or override /etc/hosts.

I am also running this in docker on a Synology NAS using MACVLAN network driver.

**Comment by ameshkov** [comment] 2019-05-30 17:31
Sounds like a duplicate of #727 

This feature will be available in the upcoming update; hopefully, next week.

**Comment by ameshkov** [comment] 2019-05-30 17:32
Ah, my bad, I misread what you want.

Actually, you already can do it, just add these to your custom filtering rules.

**Comment by ameshkov** [comment] 2019-05-30 17:38
> Also, if they are added in the filters section then they resolve but appear as blocks domains.

Okay, I shouldn't hurry that much :)

**Comment by ameshkov** [comment] 2019-05-30 17:45
Also, these two look relevant: #461 #390

**Comment by myobfee** [comment] 2020-01-20 23:29
running 0.100.9 and local network name resolution doesn't appear to be working, am I correct in assuming this feature is not yet implemented?  Have tried adding a client by IP as well to no avail.

**Comment by ameshkov** [comment] 2020-01-21 08:55
@myobfee no, it's not implemented yet. If you need it, please upvote this feature request, that's how we choose what to do first.

For now, I suggest you use DNS rewrites feature (settings -> DNS -> scroll down).

**Comment by myobfee** [comment] 2020-01-21 11:39
> @myobfee no, it's not implemented yet. If you need it, please upvote this feature request, that's how we choose what to do first.
> 
> For now, I suggest you use DNS rewrites feature (settings -> DNS -> scroll down).

ok, thanks.  I'll mess with DNS rewrites but I don't think that will allow a hostname -> IP mapping without the full domain suffix.  Feature request upvoted.

**Comment by ameshkov** [comment] 2020-07-30 12:52
Implemented in v0.103

**Closed by ameshkov** 2020-07-30 12:52 UTC
Labels: P3: Medium, feature request
