### ISSUE TITLE
Hostnames for DHCP static leases are not retrieved

### ISSUE THREAD

**Issue by agneevX** [AdguardTeam/AdGuardHome#3166] opened 2021-05-22 13:08 UTC
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:** 0.106.3
* **How did you install AdGuard Home:** GH Releases
* **How did you setup DNS configuration:** Router/WAN DNS
* **If it's a router or IoT, please write device model:** N/A
* **CPU architecture:** arm64
* **Operating system and version:** Ubuntu 20.04 LTS

### Expected Behavior

Hostnames should be retrieved for DHCP leased devices, just like the behavior with any other DHCP-connected, non-leased device.

### Actual Behavior

It seems that the "filler hostname" feature that was introduced in v0.106.0 sets a hostname for clients which are added via DHCP leases, instead of actually querying with ARP.

### Screenshots

![image](https://user-images.githubusercontent.com/19761269/119227186-57bda900-bb2a-11eb-9d18-4dfd6574dc2d.png)

**Comment by ameshkov** [comment] 2021-05-23 13:49
I don't think this is the right way to resolve this.

When you add a static lease you're supposed to supply a hostname as well. The hostname that the device sends in the DHCP request will be ignored in this case.

**Comment by rysuq** [comment] 2021-05-23 20:11
The same issue after update to new version of AdGuardHome.

**Comment by agneevX** [comment] 2021-05-24 05:34
> When you add a static lease you're supposed to supply a hostname as well.

That sounds ridiculous. How am I supposed to know what the hostname is? I don't want to put a fancy custom hostname if that's what you mean. 

At best, this should be auto-generated.

**Comment by ameshkov** [comment] 2021-05-24 08:05
`10-0-0-2` is auto-generated hostname.

**Comment by agneevX** [comment] 2021-05-24 08:38
Sorry, I will clarify that when I meant "auto-generated", I referred to the automated ARP scan just like for every DHCP device. 

That should be used when the device does not have a host name. E.g. Pixel phones.

**Comment by ameshkov** [comment] 2021-05-24 08:41
ARP scan makes little sense for a DHCP server, we're receiving the hostname in a DHCP request anyway.

@ainar-g what do you think?

**Comment by agneevX** [comment] 2021-05-24 08:46
I was under the impression that all devices added via AGH acting as DHCP were scanned in via ARP, as denoted by the source column.

These devices are all added via DHCP (non-static leasing):

![image](https://user-images.githubusercontent.com/19761269/119321451-498e9a80-bc9a-11eb-9b37-e43e8963d599.png)

**Comment by ainar-g** [comment] 2021-05-24 10:28
@ameshkov, @EugeneOne1, we should already get the hostname if it's not taken, so I'm not really sure what is happening here.

@agneevX, could you please collect [verbose logs] after restarting AGH and post them here or to our email?  Thanks!

[verbose logs]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by agneevX** [comment] 2021-05-24 12:35
I've sent an email with the logs!

**Comment by agneevX** [comment] 2021-06-07 13:49
Sorry to interrupt but is there an update available here?

I've found that adding a DHCP client to a static lease instantly invalidates the hostname.

**Comment by ainar-g** [comment] 2021-06-07 15:29
This issue is next in the queue, but I can't give you all any precise ETAs, sorry.

**Comment by EugeneOne1** [comment] 2021-06-09 10:48
@agneevX, unfortunatelly, we can't reproduce the issue.  Could you please provide some details:
1. How the static leases from the original message were added?
1. What does the non-static leases table in "DHCP settings" contains?  Are devices' names there (received from **ARP**) differ from the ones in the "Clients settings"?

**Comment by agneevX** [comment] 2021-06-09 16:39
> How the static leases from the original message were added?

Not sure what you mean. Static leases were added via the UI with the hostname field being blank.

Note that the device was not connected via DHCP when it was added. Also AGH has been restarted since, which means that the hostname field was automatically populated with `10-0-0-` pattern. 

> Are devices' names there (received from ARP) differ from the ones in the "Clients settings"?

No they do not. They all have the `10-0-0-` pattern (even though these devices have valid hostnames).

> we can't reproduce the issue.

Try this:

**Scenario 1**:

1. Connect a device via AGH DHCP, without creating a lease
2. (Note the hostname displayed)
3. _Reset AGH_
4. Set up a static lease (hostname field blank) for that device, while leaving it disconnected
5. Connect device
6. Note that the device is not reachable via the hostname you noted down.

**Scenario 2**:

Hostname disappears when static lease is set

1. Note down the hostname of a particular device 
2. Confirm with a nslookup query
2. Add a static lease for a device that's connected, again leaving the hostname field blank
3. Try doing the nslookup again: `NXDOMAIN` probably 
4. Try doing a nslookup for the pattern hostname.

These could be related or you could open an issue for this one.

**Comment by EugeneOne1** [comment] 2021-06-10 12:44
@agneevX, thanks for your detailed report.

We've just published the new `edge` build.  It should prevent generating "filler hostname" for static leases loaded from database.  The hostname field of all such leases now should remain empty.  Note also, that the empty hostname is a feature, not a bug.  If you want to set the hostname for a static lease, you should set it manually.

Could you please check if it fixes the issue for you?

**Comment by agneevX** [comment] 2021-06-10 16:04
> The hostname field of all such leases now should remain empty. Note also, that the empty hostname is a feature, not a bug.

I'm sorry but this is not the way this feature generally works. 

A static lease is simply _a static lease_. If a user chooses to specify a custom hostname, that should be honored.

However, if the hostname is left empty, and AGH is able to retrieve the hostname, it should use it rather than discard it, which serves no purpose at all. I'm very curious as to why this is.

Also, am I correct in assuming that static leased clients that have an empty hostname field **do not** have a hostname _at all_?

> We've just published the new edge build

I'm sorry, but my environment does not allow me to test beta builds, especially since I've run into major issues with stable builds.

**Comment by ainar-g** [comment] 2021-06-10 16:19
> A static lease is simply a static lease. If a user chooses to specify a custom hostname, that should be honored.

The way it currently works is that if you add a static lease, you also decide its hostname, including having the ability to leave it empty.  We try to not modify static leases in any way.  Perhaps we could a separate setting that would mean “this is a static lease, but accept any hostname that the client will send”, but even that would significantly complicate an already complicated logic.  We will probably be able to properly return to this only in the v0.108.0 cycle.

> I'm sorry, but my environment does not allow me to test beta builds, especially since I've run into major issues with stable builds.

I see.  Hopefully, v0.107.0 will be an exception.

We'll close this issue for now.  Apologies for any inconveniences.

**Closed by ainar-g** 2021-06-10 16:19 UTC
Labels: P3: Medium, bug
