### ISSUE TITLE
imo.im social chat

### ISSUE THREAD

**Issue by tkmw1985** [AdguardTeam/AdGuardHome#4507] opened 2022-04-19 14:38 UTC
Hello please add  imo.im social chat in blocked services section.

**Comment by Aikatsui** [comment] 2022-06-25 05:10
Go here https://github.com/AdguardTeam/AdGuardHome/issues/2604

**Comment by Birbber** [comment] 2022-08-22 18:01
Closing as a duplicate of #2604.

**Closed by Birbber** 2022-08-22 18:01 UTC
Labels: duplicate
