### ISSUE TITLE
Error: control/safebrowsing/disable | only application/json is allowed | 415

### ISSUE THREAD

**Issue by allendustin** [AdguardTeam/AdGuardHome#4976] opened 2022-09-30 14:41 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

AMD64

### Installation

Other (please mention in the description)

### Setup

Other (please mention in the description)

### AdGuard Home version

Version: v0.107.14

#### What did you do?
I tried to disable "Use AdGuard browsing security web service", "Use AdGuard parental control web service" and "Use Safe Search" via the Firefox browser.
#### Expected result
They would be disabled.
#### Actual result
"Error: control/safebrowsing/disable | only application/json is allowed | 415"
#### Screenshots (if appli
![Screenshot from 2022-09-30 10-39-50](https://user-images.githubusercontent.com/40801564/193294642-656447d9-a131-416e-af3f-c30274bba76c.png)
cable)

#### Additional information
I am running two instances on a Raspberry Pi 4 and both are experiencing the same issue and it just recently started behaving this way.

**Comment by ainar-g** [comment] 2022-09-30 15:03
Duplicate of #4970

**Closed by ainar-g** 2022-09-30 15:03 UTC
Labels: duplicate
