### ISSUE TITLE
DHCP issue on 0.107.28

### ISSUE THREAD

**Issue by kour1er** [AdguardTeam/AdGuardHome#5712] opened 2023-04-12 16:47 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

macOS (aka Darwin)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.28

### Description

I updated to  v0.107.28 and DHCP seemed to stop working. This is with AdGuard Home running on a mac and working in an iOS and mac environment.

I rolled back to v0.107.27 and DHCP instantly started working again. Has anyone else seen this issue?

**Comment by kour1er** [comment] 2023-04-13 15:40
So I just put build 0.107.28 in verbose mode and this immediately jumped out:

`2023/04/13 16:16:25.122279 57486#34 [debug] dhcpv4: starting...

2023/04/13 16:16:25.122587 57486#34 [debug] dhcpv4: setting secondary dns ip to itself

2023/04/13 16:16:25.122662 57486#34 [debug] dhcpv4: got addresses [10.0.0.3 10.0.0.3] after 0 attempts

2023/04/13 16:16:25.122801 57486#34 [error] starting dhcp server: dhcpv4: creating raw udp connection: listen packet 00:3e:e1:c4:3b:eb: packet: not implemented on darwin
`

Might that be the issue?

**Comment by EugeneOne1** [comment] 2023-04-14 14:54
@kour1er, we've just rolled back the dependency, which caused the MacOS support for raw DHCP broadcasting disappear.  Could you please try the latest edge build?

**Comment by kour1er** [comment] 2023-04-14 17:36
Thanks for looking into this - just installed v0.108.0-a.529+6d402dc8 and seems to be working as expected!

**Comment by EugeneOne1** [comment] 2023-04-14 17:41
@kour1er, thanks for testing.  Closing for now.

**Closed by EugeneOne1** 2023-04-14 17:41 UTC
Labels: bug, P2: High, compatibility

**Comment by thirstyice** [comment] 2023-05-13 02:21
It seems that I'm having the same issue on freebsd on v0.107.29
Here's the text of the error I get in the ui:
`Error: control/dhcp/set_config | enabling dhcp: starting dhcp server: dhcpv4: creating raw udp connection: listen packet 1e:66:6d:a2:f8:fc: packet: not implemented on freebsd | 400`

**Comment by EugeneOne1** [comment] 2023-05-18 14:54
@Gobd, it seems, the update is only related to the `github.com/insomniacslk/dhcp/dhcpv4/nclient4` package, which is used in our Linux-specific code and should work as intended.  We didn't notice any DHCP malfunctioning on macOS so far, however, we'll monitor any related issues.  Thank you for your concern.
