### ISSUE TITLE
Optimistic caching is not working

### ISSUE THREAD

**Issue by castillofrancodamian** [AdguardTeam/AdGuardHome#5010] opened 2022-10-06 16:24 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.319+330ac303

### Description

Although I have the corresponding box checked, I don't see that it is working.

SO: Arch Linux.

![Screenshot_20221006_132308](https://user-images.githubusercontent.com/47670442/194367097-b6f91511-7799-4b7e-81e8-c77dc9c2f28a.png)

**Comment by ainar-g** [comment] 2022-10-07 10:48
Hello.  How do you determine if it's working or not?  It's not clear from the screenshot.

Also, do you have custom upstream settings for persistent clients?

**Comment by castillofrancodamian** [comment] 2022-10-07 16:07
Hello, I determine that it works if in the registry I see that there are queries with a "ping" of approximately 1 ms after having made the first query of the same domain previously. The error appeared alongside [this](https://github.com/AdguardTeam/AdGuardHome/issues/4970).

**Comment by ainar-g** [comment] 2022-10-11 12:03
So, it's just from the timing?  Do any of the responses have a *(served from cache)* label?  Also, what are your cache settings, and in particular, the size?

**Comment by castillofrancodamian** [comment] 2022-10-11 15:48
Neither is served from the cache.

![Screenshot_20221011_124355](https://user-images.githubusercontent.com/47670442/195138586-d9406a0b-fd20-455f-94d4-1bdb32892079.png)
![Screenshot_20221011_124410](https://user-images.githubusercontent.com/47670442/195138606-b7f4d61d-1b73-4921-8275-b17f2995e7bf.png)
![Screenshot_20221011_124430](https://user-images.githubusercontent.com/47670442/195138618-0b0f6daa-a3cb-4c85-a305-72a4633859d2.png)

I have never touched cache configuration.

![Screenshot_20221011_124512](https://user-images.githubusercontent.com/47670442/195138630-fa8681fa-99d4-45b3-b842-64273e0881fb.png)

**Comment by EugeneOne1** [comment] 2022-10-11 15:51
@castillofrancodamian, the settings actually seem touched since the "Cache size" field isn't empty by default, and the empty value disables any caching.

**Comment by castillofrancodamian** [comment] 2022-10-11 16:08
I have removed the current installation with sudo `sudo /opt/AdGuardHome/AdGuardHome -s stop`, `sudo /opt/AdGuardHome/AdGuardHome -s uninstall` and `sudo rm -r /opt/AdGuardHome/ `and reinstalled with `curl -s -S -L https: //raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -c edge`. `Cache size` is still empty. Same symptoms on new install.

**Comment by ainar-g** [comment] 2022-10-11 16:14
@EugeneOne1, I can reproduce that.  Assigning as a bug.

**Comment by EugeneOne1** [comment] 2022-10-11 17:12
@castillofrancodamian, sorry for messing it up.  We've just pushed the fixed build to the edge channel.  Could you please install it and check if cache size is now set properly?

**Comment by EugeneOne1** [comment] 2022-10-11 17:37
@castillofrancodamian, glad to see that.  I'll close the issue for now if you don't mind.  Thanks for reporting and testing.

**Closed by EugeneOne1** 2022-10-11 17:37 UTC
Labels: bug, P2: High
