### ISSUE TITLE
Regarding the custom filter domain name and IP binding in the filter does not take effect

### ISSUE THREAD

**Issue by GogogogoDAI** [AdguardTeam/AdGuardHome#5226] opened 2022-12-02 02:44 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

64-bit ARM

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-b.22

### Description

Including the current version has always had this problem
The custom filter domain name binding IP address in the filter does not take effect
The DNS rewrite binding domain name and IP in the filter can be used normally.

**Comment by ainar-g** [comment] 2022-12-16 13:18
Hello and apologies for the late response.  Could you show exactly which rule you're adding and how you're checking it?  For example, a `dig` or an `nslookup` command.

**Comment by GogogogoDAI** [comment] 2023-02-15 11:41
![屏幕截图_20230215_193914](https://user-images.githubusercontent.com/119642967/219017854-ac31ddd3-deeb-464a-8b65-70d7882ff098.png)
![屏幕截图_20230215_194004](https://user-images.githubusercontent.com/119642967/219017869-51350cf2-9c08-4a0d-9b43-f4af895328be.png)

**Comment by ainar-g** [comment] 2023-02-15 12:05
You've mentioned in the original post that your AGH is installed onto a Linux system, but the `nslookup` screenshot looks like it is from a Windows system, which queries `127.1.1.1`, which is a local address.  If AdGuard Home is installed on another system, please make sure that you've set up your Windows client correctly.

Also make sure that your *Blocking mode* is set to *Default.*

**Comment by GogogogoDAI** [comment] 2023-02-15 12:25
Yes, I installed the trial program on the windows system and found that the specified ip still cannot be resolved, ip 127.1.1.1 is the adguardhome address, and the blocked address is 127.10.0.0

**Comment by ainar-g** [comment] 2023-02-15 12:37
If your *Blocking mode* is set to *Custom IP* and that custom IP is `127.10.0.0` then everything is working as expected.  If you want to have other IP addresses for these domain names, use the newer and better supported `dnsrewrite` rules:

```adblock
|test.com$dnsrewrite=NOERROR;A;0.0.0.0,dnstype=A
```

**Comment by GogogogoDAI** [comment] 2023-02-15 13:42
Thank you very much for solving my problem, but can you add a mode to use the custom interception ip and the default mode using the /etc/hosts function together?

**Comment by ainar-g** [comment] 2023-02-15 13:49
I don't think that the support for the /etc/hosts format will expand.  We seriously encourage using the more powerful [`dnsrewrite` rules](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#dnsrewrite) for these types of rewrites.

I'll close this issue, as everything seems to work as intended.

**Closed by ainar-g** 2023-02-15 13:49 UTC
Labels: waiting for data
