### ISSUE TITLE
issue 1767 - reopen please

### ISSUE THREAD

**Issue by sanderlv** [AdguardTeam/AdGuardHome#5111] opened 2022-11-06 19:44 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.17

#### What did you do?
this works:
http://localip/
internal dns like http://aname.mydomain.com/
internal dns via nginx reverse proxy manager https://aname.mydomain.com/

all prompts me for the username password and logs me in.

When I add this to my homeassistant panel_iframe.yaml:

  adguard:
    title: AdGuard Home
    icon: mdi:shield-check
    url: https://aname.mydomain.com

I shows me the same login page but the credentials are not accepted, I cannot login that way.

What am I missing there?

UPDATE: it does work on my mobile companion app…

This is the same issue but it was closed:
https://github.com/AdguardTeam/AdGuardHome/issues/1767

#### Expected result
be able to open adguard behind nginx via iframe

**Comment by ainar-g** [comment] 2022-11-07 14:41
Duplicate of #2783.

**Closed by ainar-g** 2022-11-07 14:41 UTC
