### ISSUE TITLE
Cannot clear query records

### ISSUE THREAD

**Issue by talesam** [AdguardTeam/AdGuardHome#5058] opened 2022-10-21 02:29 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

64-bit ARM

### Installation

GitHub releases or script from README

### Setup

Other (please mention in the description)

### AdGuard Home version

v0.107.14

### Description

*Server Oracle - Ubuntu ARM64*

#### What did you do?
Tentei limpar o resgistro

#### Expected result
Apagar todo o registro

#### Actual result
`Error: control/querylog_clear | only application/json is allowed | 415`

#### Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/981368/197096835-89e71214-fdcf-4f2a-901c-524ede716154.png)

Note: Whenever a new version comes out, I update directly through the web interface, but now it's not updating, it asked to update manually, because it's giving an error.
It wasn't something I did, I haven't touched the server for months and it only runs Adguard Home.

**Comment by AAraonWPaul** [comment] 2022-10-21 02:32
Hello, this is a duplicate of #4970 and is fixed on 0.107.15 and above versions, please update and thank you for reporting issues

**Comment by ainar-g** [comment] 2022-10-21 10:49
Additionally, see #4987 for a tip on how to use the automatic update from 0.107.14 to a newer version.

**Closed by ainar-g** 2022-10-21 10:49 UTC
Labels: duplicate

**Comment by talesam** [comment] 2022-10-21 16:57
> Additionally, see #4987 for a tip on how to use the automatic update from 0.107.14 to a newer version.

It worked, thanks, can I always update this way?

**Comment by ainar-g** [comment] 2022-10-24 08:34
Yes, but omit the `-H 'Content-Type: application/json'` part.
