### ISSUE TITLE
Encryption guide does not allow for certificate on Ubuntu Core (UC)

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardHome#2442] opened 2020-12-15 08:28 UTC
Although Certbot officially supports the snapd environment, applying for a certbot certificate under Ubuntu Core does not work.
Following the steps within the [AdGuard Home documentation](https://github.com/AdguardTeam/AdGuardHome/wiki/Encryption) does not allow the user to get past step 3, and presents UC users with the following issue:
```
user@vmbox:~$ sudo snap install --classic certbot
error: snap "certbot" requires classic confinement which is only available on classic systems
```

A project that has implemented their own method under a UC environment, is the Nextcloud snap, seen [here](https://github.com/nextcloud/nextcloud-snap#httphttps-port-configuration).
I have tested this, and it works flawlessly with Nextcloud using a supplied domain.

Could the same method be implemented with AdGuard Home?

**Comment by ameshkov** [comment] 2020-12-15 08:57
Sounds like a duplicate of #1603.

Is it?

**Comment by jslawler** [comment] 2020-12-15 09:30
> Sounds like a duplicate of #1603.
> 
> Is it?

No, that looks to me like they're referring to the auto-renewal of ssl certificates. I'm referring to the inability to get one in the first place.

**Comment by ameshkov** [comment] 2020-12-15 09:36
Well, this is kinda the same thing, renewal process is basically the same as acquiring a new cert:)

**Comment by jslawler** [comment] 2020-12-15 10:06
Yes I agree. :)

I suppose it will come down to how it's implemented.
If it could be interacted with via the web interface to attain the SSL cert, and have it auto renew there onwards, that would solve both issues.

**Comment by ameshkov** [comment] 2020-12-15 20:58
I prefer DNS challenge when it's possible since it does not require having a public web server, but UI for this would be painfully hard to implement -- too many options: https://go-acme.github.io/lego/dns/

Anyways, closed as dup for now. Please upvote the older feature requests.

**Closed by ameshkov** 2020-12-15 20:58 UTC
