### ISSUE TITLE
Adblocker List Stats

### ISSUE THREAD

**Issue by xenstar** [AdguardTeam/AdGuardHome#4798] opened 2022-08-01 04:33 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
There are many adblocker lists available. But we can't identify which one is the best one and blocking most of the links according to our requirements. 

#### Proposed solution
It would be great if you can add a stats section in the dashboard area, where we can see which adblocker list blocking how many links, and their percentage based on days, weeks, months, and years. 

Sometimes we also add some duplicate lists, we can also remove them if we can get these stats.

**Comment by ainar-g** [comment] 2022-08-24 17:06
Duplicate of #4524

**Closed by ainar-g** 2022-08-24 17:06 UTC
Labels: duplicate
