### ISSUE TITLE
Top queried & Top blocked domains count not increasing

### ISSUE THREAD

**Issue by gyCfjSnO** [AdguardTeam/AdGuardHome#5542] opened 2023-02-27 08:15 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Other (please mention in the description)

### CPU architecture

64-bit ARM

### Installation

GitHub releases or script from README

### Setup

Other (please mention in the description)

### AdGuard Home version

v0.108.0-b.28

#### What did you do?
Looked at the Dashboard

#### Expected result
See a list of Top queried & Top blocked domains

#### Actual result
Most of the Top queried & Top blocked domains are showing a count of only '1'

#### Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/49738152/221510168-9b7a4e5a-06f9-4143-9022-1636d6c57ade.png)

#### Additional information
- Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-1024-raspi aarch64)
- Raspberry Pi 4 Model B Rev 1.2

**Comment by ainar-g** [comment] 2023-02-27 09:48
Hello.  Are you sure that this isn't the same issue as #5522?

**Comment by gyCfjSnO** [comment] 2023-02-27 10:11
> Hello. Are you sure that this isn't the same issue as #5522?

As you can see in my screenshot I already sorted from highest to lowest in anticipation for this response 😉😉

**Comment by ainar-g** [comment] 2023-02-27 10:18
I cannot reproduce that on my AGH.  What are the values in the `stats` object in your `AdGuardHome.yaml`?  Also, do you see any statistics warnings or errors in the [verbose log](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog)?

**Comment by gyCfjSnO** [comment] 2023-02-27 11:38
> I cannot reproduce that on my AGH. What are the values in the `stats` object in your `AdGuardHome.yaml`? Also, do you see any statistics warnings or errors in the [verbose log](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog)?

By ```stats``` I assume you mean the below?
```
statistics:
  enabled: true
  interval: 7
  ignored: []
```

Here is the beginning of my verbose log file, the rest is filled with DNS queries.
```
2023/02/27 21:27:42.875357 5685#35 [info] AdGuard Home, version v0.108.0-b.28
2023/02/27 21:27:42.875792 5685#35 [debug] current working directory is /opt/AdGuardHome
2023/02/27 21:27:42.875857 5685#35 [info] AdGuard Home is running as a service
2023/02/27 21:27:42.876041 5685#35 [debug] reading config file: /opt/AdGuardHome/AdGuardHome.yaml
2023/02/27 21:27:42.879084 5685#35 [debug] github.com/AdguardTeam/AdGuardHome/internal/home.upgradeConfig(): got schema version 16
2023/02/27 21:27:42.879351 5685#35 [debug] reading config file: /opt/AdGuardHome/AdGuardHome.yaml
2023/02/27 21:27:42.883658 5685#35 [info] tls: using default ciphers
2023/02/27 21:27:42.886936 5685#35 [debug] hosts container: starting
2023/02/27 21:27:42.887043 5685#35 [debug] hosts container: refreshing
2023/02/27 21:27:42.887354 5685#35 [debug] hosts container: added ip-host pair "127.0.0.1"-"localhost"
2023/02/27 21:27:42.887528 5685#35 [debug] hosts container: added ip-host pair "::1"-"ip6-localhost"
2023/02/27 21:27:42.887663 5685#35 [debug] hosts container: added ip-host pair "::1"-"ip6-loopback"
2023/02/27 21:27:42.887789 5685#35 [debug] hosts container: added ip-host pair "fe00::"-"ip6-localnet"
2023/02/27 21:27:42.887917 5685#35 [debug] hosts container: added ip-host pair "ff00::"-"ip6-mcastprefix"
2023/02/27 21:27:42.888063 5685#35 [debug] hosts container: added ip-host pair "ff02::1"-"ip6-allnodes"
2023/02/27 21:27:42.888191 5685#35 [debug] hosts container: added ip-host pair "ff02::2"-"ip6-allrouters"
2023/02/27 21:27:42.888313 5685#35 [debug] hosts container: added ip-host pair "ff02::3"-"ip6-allhosts"
2023/02/27 21:27:42.889080 5685#35 [debug] hosts container: sending upd
2023/02/27 21:27:42.892349 5685#35 [debug] filtering: initialized 50 services
2023/02/27 21:27:42.892611 5685#35 [debug] dhcpd: warning: creating dhcpv4 srv: dhcpv4: invalid IP is not an IPv4 address
2023/02/27 21:27:42.895621 5685#35 [debug] clients: added "RIPE Atlas Probe": ID:["192.168.0.4"] [1]
2023/02/27 21:27:42.895723 5685#35 [debug] clients: added "SamKnows": ID:["192.168.0.3"] [2]
2023/02/27 21:27:42.895804 5685#35 [debug] clients: added "TV": ID:["192.168.0.7"] [3]
2023/02/27 21:27:42.895886 5685#35 [debug] clients: added "Work": ID:["192.168.0.8" "192.168.0.9"] [4]
2023/02/27 21:27:42.895972 5685#35 [debug] clients: removed 0 client aliases
2023/02/27 21:27:42.896045 5685#35 [debug] clients: added 0 client aliases from dhcp
2023/02/27 21:27:42.896167 5685#35 [debug] writing config file "/opt/AdGuardHome/AdGuardHome.yaml"
2023/02/27 21:27:42.896320 5685#41 [debug] clients: removed 0 client aliases
2023/02/27 21:27:42.896586 5685#41 [debug] clients: added ::1 -> "ip6-localhost" [1]
2023/02/27 21:27:42.896660 5685#41 [debug] clients: added fe00:: -> "ip6-localnet" [2]
2023/02/27 21:27:42.896721 5685#41 [debug] clients: added ff00:: -> "ip6-mcastprefix" [3]
2023/02/27 21:27:42.896780 5685#41 [debug] clients: added ff02::1 -> "ip6-allnodes" [4]
2023/02/27 21:27:42.896840 5685#41 [debug] clients: added ff02::2 -> "ip6-allrouters" [5]
2023/02/27 21:27:42.896898 5685#41 [debug] clients: added ff02::3 -> "ip6-allhosts" [6]
2023/02/27 21:27:42.896955 5685#41 [debug] clients: added 127.0.0.1 -> "localhost" [7]
2023/02/27 21:27:42.897004 5685#41 [debug] clients: added 7 client aliases from system hosts file
2023/02/27 21:27:42.908916 5685#35 [info] Initializing auth module: /opt/AdGuardHome/data/sessions.db
2023/02/27 21:27:42.909300 5685#35 [debug] auth: loaded 4 sessions from DB (removed 0 expired)
2023/02/27 21:27:42.909369 5685#35 [info] auth: initialized.  users:1  sessions:4
2023/02/27 21:27:42.909483 5685#35 [info] web: initializing
2023/02/27 21:27:42.909624 5685#35 [debug] stats: opening database
2023/02/27 21:27:42.909835 5685#35 [debug] stats: database opened
2023/02/27 21:27:42.909907 5685#35 [debug] stats: deleting old units until id 465802
2023/02/27 21:27:42.910010 5685#35 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465971
2023/02/27 21:27:42.910619 5685#35 [debug] stats: initialized
2023/02/27 21:27:42.910960 5685#35 [debug] filtering: loading filter 1671124333 from /opt/AdGuardHome/data/filters/1671124333.txt
2023/02/27 21:27:42.911128 5685#35 [debug] filtering: file /opt/AdGuardHome/data/filters/1671124333.txt, id 1671124333, length 3015856
2023/02/27 21:27:43.135040 5685#35 [debug] filtering: loading filter 1671124334 from /opt/AdGuardHome/data/filters/1671124334.txt
2023/02/27 21:27:43.135545 5685#35 [debug] filtering: file /opt/AdGuardHome/data/filters/1671124334.txt, id 1671124334, length 6280422
2023/02/27 21:27:43.662893 5685#35 [debug] filtering: loading filter 1652239509 from /opt/AdGuardHome/data/filters/1652239509.txt
2023/02/27 21:27:43.663410 5685#35 [debug] filtering: file /opt/AdGuardHome/data/filters/1652239509.txt, id 1652239509, length 3678
2023/02/27 21:27:43.663956 5685#35 [debug] filtering: loading filter 1652239510 from /opt/AdGuardHome/data/filters/1652239510.txt
2023/02/27 21:27:43.664237 5685#35 [debug] filtering: file /opt/AdGuardHome/data/filters/1652239510.txt, id 1652239510, length 4706
2023/02/27 21:27:43.664813 5685#35 [debug] filtering: loading filter 1652239511 from /opt/AdGuardHome/data/filters/1652239511.txt
2023/02/27 21:27:43.665081 5685#35 [debug] filtering: file /opt/AdGuardHome/data/filters/1652239511.txt, id 1652239511, length 1232
2023/02/27 21:27:43.665416 5685#35 [debug] filtering: loading filter 1652239512 from /opt/AdGuardHome/data/filters/1652239512.txt
2023/02/27 21:27:43.665684 5685#35 [debug] filtering: file /opt/AdGuardHome/data/filters/1652239512.txt, id 1652239512, length 11677
2023/02/27 21:27:43.666694 5685#35 [debug] filtering: loading filter 1652239513 from /opt/AdGuardHome/data/filters/1652239513.txt
2023/02/27 21:27:43.666967 5685#35 [debug] filtering: file /opt/AdGuardHome/data/filters/1652239513.txt, id 1652239513, length 10551
2023/02/27 21:27:43.669891 5685#35 [debug] dnsforward: added 0 a and ptr entries from dhcp
2023/02/27 21:27:43.670207 5685#35 [debug] Bootstraps: [94.140.14.140 1.1.1.1 8.8.8.8 208.67.222.2]
2023/02/27 21:27:43.670537 5685#35 [debug] Upstream 0: 54.252.183.4:53 is reserved for next domains: tvnz-prod-01.brightcovecdn.com., tvnz.co.nz.
2023/02/27 21:27:43.670813 5685#35 [debug] Upstream 1: https://dns-unfiltered.adguard.com:443/dns-query
2023/02/27 21:27:43.671058 5685#35 [debug] Upstream 2: tls://dns-unfiltered.adguard.com:853
2023/02/27 21:27:43.671421 5685#35 [debug] Upstream 3: https://dns.cloudflare.com:443/dns-query
2023/02/27 21:27:43.671677 5685#35 [debug] Upstream 4: tls://1dot1dot1dot1.cloudflare-dns.com:853
2023/02/27 21:27:43.671915 5685#35 [debug] Upstream 5: https://dns.google:443/dns-query
2023/02/27 21:27:43.672147 5685#35 [debug] Upstream 6: tls://dns.google:853
2023/02/27 21:27:43.672380 5685#35 [debug] Upstream 7: https://sandbox.opendns.com:443/dns-query
2023/02/27 21:27:43.672627 5685#35 [info] dnsproxy: cache: enabled, size 4096 b
2023/02/27 21:27:43.672811 5685#35 [info] MaxGoroutines is set to 300
2023/02/27 21:27:43.673270 5685#35 [debug] upstreams to resolve PTR for local addresses: [192.168.0.1]
2023/02/27 21:27:43.673474 5685#35 [debug] Bootstraps: [94.140.14.140 1.1.1.1 8.8.8.8 208.67.222.2]
2023/02/27 21:27:43.673678 5685#35 [debug] Upstream 0: 192.168.0.1:53
2023/02/27 21:27:43.673959 5685#35 [debug] web: applying new tls configuration
2023/02/27 21:27:43.674128 5685#35 [info] AdGuard Home is available at the following addresses:
2023/02/27 21:27:43.674328 5685#35 [info] go to http://192.168.0.2:80
2023/02/27 21:27:54.960751 5685#53 [debug] initialized filtering engine
2023/02/27 21:27:54.961243 5685#53 [info] Starting the DNS proxy server
2023/02/27 21:27:54.961402 5685#53 [info] The server is configured to refuse ANY requests
2023/02/27 21:27:54.961553 5685#53 [info] dnsproxy: cache: disabled
2023/02/27 21:27:54.961693 5685#53 [info] MaxGoroutines is set to 300
2023/02/27 21:27:54.961880 5685#53 [info] Creating the UDP server socket
2023/02/27 21:27:54.962066 5685#56 [debug] clients: removed 0 client aliases
2023/02/27 21:27:54.962303 5685#56 [debug] clients: added 192.168.0.233 -> "" [8]
2023/02/27 21:27:54.962381 5685#53 [info] Listening to udp://192.168.0.2:53
2023/02/27 21:27:54.962628 5685#53 [info] Creating a TCP server socket
2023/02/27 21:27:54.962472 5685#56 [debug] clients: added 192.168.0.97 -> "" [9]
2023/02/27 21:27:54.963041 5685#53 [info] Listening to tcp://192.168.0.2:53
2023/02/27 21:27:54.963129 5685#56 [debug] clients: added 192.168.0.10 -> "" [10]
2023/02/27 21:27:54.963343 5685#56 [debug] clients: added 192.168.0.5 -> "" [11]
2023/02/27 21:27:54.963405 5685#57 [info] Entering the UDP listener loop on 192.168.0.2:53
2023/02/27 21:27:54.963613 5685#56 [debug] clients: added 192.168.0.210 -> "" [12]
2023/02/27 21:27:54.963701 5685#58 [info] Entering the tcp listener loop on 192.168.0.2:53
2023/02/27 21:27:54.963773 5685#56 [debug] clients: added 192.168.0.3 -> "" [13]
2023/02/27 21:27:54.963942 5685#60 [debug] filtering: updating...
2023/02/27 21:27:54.964017 5685#56 [debug] clients: added 192.168.0.9 -> "" [14]
2023/02/27 21:27:54.964198 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465925
2023/02/27 21:27:54.964284 5685#56 [debug] clients: added 192.168.0.4 -> "" [15]
2023/02/27 21:27:54.964451 5685#56 [debug] clients: added 192.168.0.7 -> "" [16]
2023/02/27 21:27:54.964510 5685#62 [debug] querylog: the oldest log entry: 2023-02-25T23:54:27.68238333+10:00
2023/02/27 21:27:54.964602 5685#56 [debug] clients: added 192.168.0.43 -> "" [17]
2023/02/27 21:27:54.964245 5685#60 [debug] filtering: update finished
2023/02/27 21:27:54.964765 5685#62 [debug] querylog: 2023-02-27T21:27:54+10:00 <= 2023-05-26T23:54:27+10:00, not rotating
2023/02/27 21:27:54.964805 5685#56 [debug] clients: added 192.168.0.27 -> "" [18]
2023/02/27 21:27:54.965170 5685#56 [debug] clients: added 192.168.0.54 -> "" [19]
2023/02/27 21:27:54.965328 5685#56 [debug] clients: added 192.168.0.223 -> "" [20]
2023/02/27 21:27:54.965579 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465926
2023/02/27 21:27:54.965593 5685#56 [debug] clients: added 192.168.0.240 -> "" [21]
2023/02/27 21:27:54.965951 5685#56 [debug] clients: added 192.168.0.6 -> "" [22]
2023/02/27 21:27:54.966099 5685#56 [debug] clients: added 192.168.0.1 -> "" [23]
2023/02/27 21:27:54.966246 5685#56 [debug] clients: added 192.168.0.167 -> "" [24]
2023/02/27 21:27:54.966366 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465927
2023/02/27 21:27:54.966414 5685#56 [debug] clients: added 17 client aliases from arp neighborhood
2023/02/27 21:27:54.967032 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465928
2023/02/27 21:27:54.967754 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465929
2023/02/27 21:27:54.968422 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465930
2023/02/27 21:27:54.969122 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465931
2023/02/27 21:27:54.969792 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465932
2023/02/27 21:27:54.970490 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465933
2023/02/27 21:27:54.971241 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465934
2023/02/27 21:27:54.972014 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465935
2023/02/27 21:27:54.972741 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465936
2023/02/27 21:27:54.973462 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465937
2023/02/27 21:27:54.974237 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465938
2023/02/27 21:27:54.975373 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465939
2023/02/27 21:27:54.976111 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465940
2023/02/27 21:27:54.976772 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465941
2023/02/27 21:27:54.977524 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465942
2023/02/27 21:27:54.978331 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465943
2023/02/27 21:27:54.978995 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465944
2023/02/27 21:27:54.979774 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465945
2023/02/27 21:27:54.980514 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465946
2023/02/27 21:27:54.981206 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465947
2023/02/27 21:27:54.981926 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465948
2023/02/27 21:27:54.982643 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465949
2023/02/27 21:27:54.983296 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465950
2023/02/27 21:27:54.984101 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465951
2023/02/27 21:27:54.984787 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465952
2023/02/27 21:27:54.985528 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465953
2023/02/27 21:27:54.986272 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465954
2023/02/27 21:27:54.987008 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465955
2023/02/27 21:27:54.987721 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465956
2023/02/27 21:27:54.988472 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465957
2023/02/27 21:27:54.989174 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465958
2023/02/27 21:27:54.989975 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465959
2023/02/27 21:27:54.990793 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465960
2023/02/27 21:27:54.991519 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465961
2023/02/27 21:27:54.992194 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465962
2023/02/27 21:27:54.992935 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465963
2023/02/27 21:27:54.993692 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465964
2023/02/27 21:27:54.994389 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465965
2023/02/27 21:27:54.995609 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465966
2023/02/27 21:27:54.996409 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465967
2023/02/27 21:27:54.997149 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465968
2023/02/27 21:27:54.997930 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465969
2023/02/27 21:27:54.998655 5685#53 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.loadUnitFromDB(): Loading unit 465970
```

**Comment by ammnt** [comment] 2023-02-28 18:17
I have the same issue on the last beta build. What I have in config:
```
querylog:
  enabled: true
  file_enabled: true
  interval: 720h
  size_memory: 1000
  ignored: []
statistics:
  enabled: true
  interval: 30
  ignored: []
```

**Comment by ainar-g** [comment] 2023-02-28 18:29
@ammnt, have you tried the latest Edge?  Since these show only the top 100 results (which are really the bottom 100 because of the aforementioned bug fixed on Edge), you're likely to see only ones.

**Comment by ammnt** [comment] 2023-03-01 12:24
@ainar-g, looks fixed now👍🏼

**Comment by ainar-g** [comment] 2023-03-01 13:35
@gyCfjSnO, does the latest beta fix the issue for you as well?

**Comment by gyCfjSnO** [comment] 2023-03-02 20:03
> @gyCfjSnO, does the latest beta fix the issue for you as well?

My issue, which is separate to the other issue people were reporting, appears to have been fixed.

**Closed** 2023-03-03 09:02 UTC
Labels: waiting for data
