### ISSUE TITLE
Redirect *.domain.com to a given IP

### ISSUE THREAD

**Issue by KamistixX** [AdguardTeam/AdGuardHome#922] opened 2019-08-08 08:42 UTC
- [x] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
Docker container version 0.97.1 on Synology NAS, running in Host network mode
* **Operating system and version:**
Synology DSM 6.2

### Expected Behavior
In the Custom filtering rules section, I added a line in the following pattern **_`"192.168.1.100 *.domain.com"`_**. I then type `"nslookup subdomain.domain.com"` in a terminal on a client and expect to get "192.168.1.100" as an answer.

### Actual Behavior
The AdGuard DNS server does not match my rule and resolves after an external DNS query (in my case tls://1.1.1.1) which of course does not give the intranet IP I would like.

Adding a line **_`"192.168.1.100 subdomain.domain.com"`_** works, but I would need to add dozens of subdomains like this, and will have to do the same when I create more subdomains in the future.

Is there any possibility to add wildcard domains in this list ? Maybe I am not using the right syntax ?

Thanks for your help :)

**Comment by DandelionSprout** [comment] 2019-08-08 13:20
Just for the record, I know that ordinary wildcard blockage with `||*.domain.com^` and `*.domain.com` is possible, but I don't think the AdGuard Home team has decided to expand on the standard *Hosts* syntax in order to make that kind of entry support wildcards yet.

**Comment by alexsannikov** [comment] 2019-08-23 01:04
HOSTS-type records don't support wildcard in domain names. This looks like what you want to get exactly. Not an AGHome issue.

**Comment by KamistixX** [comment] 2019-08-23 05:54
I would like to add an A-type record for a wildcard demain.

For example Synology DNS server package allows to do that, by taking into account the * symbol and correctly redirecting all requests to the  chosen IP.

**Comment by lordraiden** [comment] 2019-09-02 07:18
This should be high priority, most people running adguard home at home will have other vm's or dockers running, so this is very useful, in fact is one of the things that keeps me on pihole.

**Comment by ameshkov** [comment] 2019-09-02 20:41
Guys, please not just comment but also upvote the task

**Comment by devinslick** [comment] 2019-10-04 12:30
Agreed with increasing the priority here.  The only current workaround is setting up a secondary dns server that supports wildcards and forwarding requests for that zone.

**Comment by ameshkov** [comment] 2019-10-04 13:09
Thanks for the upvotes, the issue is assigned to v0.101 release now.

**Comment by PSSGCSim** [comment] 2019-11-10 20:19
This would be a great feature for [Steam cache/lan cache](https://hub.docker.com/r/lancachenet/monolithic) that needs to redirect wildcarded domains. For example this is [the list](https://github.com/uklans/cache-domains/blob/master/steam.txt) of what domains you need to redirect for caching Steam library. It would be nice if this feature would work in both the "custom filters" field and in the URL downloaded filters.

Thank you for planning on implementing this feature as only workaround now is to setup your DNS as:
Steam Cache/Lan Cache DNS Proxy -> AdGuard Home -> DNS Resolver...

**Comment by PSSGCSim** [comment] 2019-12-26 21:29
Works like a charm! Thank you very much for implementing this.

**Comment by KamistixX** [comment] 2019-12-26 23:54
Great work !

However it seems that if we set up something like this : 
   - *.domain.com -> 192.168.0.10
   - cloud.domain.com -> 192.168.0.11

Then an nslookup cloud.domain.com will get two A-type answers : 192.168.0.10 and 192.168.0.11

I would like the 192.168.0.11 answer to be the only one, since this is an exception I would like to create in this case.

**Closed** 2020-01-16 09:51 UTC
Labels: P3: Medium, feature request

**Comment by jdawgzim** [comment] 2020-12-28 17:38
> Works like a charm! Thank you very much for implementing this.

Did you get Lancache working with adguard?  Can you post your syntax and where it goes?

**Comment by PSSGCSim** [comment] 2020-12-28 18:01
@jdawgzim Lan cache is not supported out of the box if you don't want to use their DNS forwarder as an upstream. I use two scripts one fetches lists of domains from https://github.com/uklans/cache-domains.git and assigns my cache's IP. And second one that feeds AGH by calling it's API, adding new records and removing old ones.

**Comment by ameshkov** [comment] 2020-12-28 19:45
In the edge build it is now possible to use $dnsrewrite modifier:
https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#dnsrewrite

**Comment by PSSGCSim** [comment] 2020-12-28 20:23
@ameshkov great! That will make it way easier. Gotta try it out when it arrives into stable. Thank you for the heads up.

**Comment by mrdeadlocked** [comment] 2021-06-04 11:49
@PSSGCSim Did you get a chance to get dnsrewrite working with lancache? If so, could you post what you had to do?

**Comment by Deanosim** [comment] 2022-03-13 13:11
I'd also love to know if people managed to get lancache/cache-domains working with AdGuard Home, I tried using [HostlistCompiler](https://github.com/AdguardTeam/HostlistCompiler) with [github actions](https://github.com/Deanosim/dns-lists) to make a list, but never managed to get anything to work.

**Comment by PSSGCSim** [comment] 2022-03-13 13:49
I use rather simple bash script that pulls the cache domains repo (uklans/cache-domains) and converts all the domain lists into one AGH filter file. I run it periodically using cron and pull it into AGH from my local HTTP server.
https://gist.github.com/PSSGCSim/abd99f2fe65d9c4cc0443c6fb69daf40

**Comment by mrdeadlocked** [comment] 2022-04-04 17:28
> I use rather simple bash script that pulls the cache domains repo (uklans/cache-domains) and converts all the domain lists into one AGH filter file. I run it periodically using cron and pull it into AGH from my local HTTP server. https://gist.github.com/PSSGCSim/abd99f2fe65d9c4cc0443c6fb69daf40

This worked great! I ran it on my PC using the WSL subsystem then copied the out.txt data into my custom filters.

**Comment by Dont-ask-for-it** [comment] 2023-03-28 22:50
Version: 
v0.106.3 

Not working for a wilcard here. I still have to specify each subdomain. See here :

![3-28-2023 (18-48-53)](https://user-images.githubusercontent.com/5061749/228384147-2c29cae6-6da3-4d27-a6d9-f5eabbf8da7a.gif)

**Comment by akrigator** [comment] 2023-11-30 18:50
@Dont-ask-for-it it looks you should use `||wikipedia.com^$dnsrewrite=192.168.2.100` in regards with https://adguard-dns.io/kb/general/dns-filtering-syntax/#dnsrewrite 
This works for me but there was another issue: first nslookup call shows  valid ip, but second wrong. The issue was caused by a router setting: DNS is set to Adguard, but also there was Dynamic DNS provisioned by provider. So the last should be disabled
