### ISSUE TITLE
[Feature] Use Public Resolver List

### ISSUE THREAD

**Issue by hbednar** [AdguardTeam/AdGuardHome#6090] opened 2023-08-09 13:41 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

At the moment users are left to find and research reliable DNS servers they can use.

### Proposed solution

There is a list of public DNS servers maintained by the DNSCrypt project which has information about each service like, logging, blocking and supported protocols.
Can you integrate this list into Adguard so users can select one or more servers they want to use, like the add block list. Also, having filter options for this list would be great.

https://dnscrypt.info/public-servers/

**Comment by ainar-g** [comment] 2023-08-09 14:02
Duplicate of #724

**Closed by ainar-g** 2023-08-09 14:02 UTC
Labels: feature request
