### ISSUE TITLE
Blocking mode to a specific domain http/https or add custom text/html code

### ISSUE THREAD

**Issue by CYAsistemas** [AdguardTeam/AdGuardHome#6167] opened 2023-09-04 19:14 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

The current specific blocking modes are too technical for end users or the ip option fails in almost all browsers because it is not possible to use an ssl certificate in all cases.

### Proposed solution

I propose two options:

1.- Modify the current specific IP option to accept domains (http or https), to render a web, perhaps it is the easy solution.
2.- Add text area to attach html or small text to render in web browser (use adguard as web server to render html page).

![image](https://github.com/AdguardTeam/AdGuardHome/assets/140634218/cdef5cab-ca86-4a10-b36d-28af67f35895)

Like:  https://family-block.dns.adguard.com/ in adult content.

**Comment by fernvenue** [comment] 2023-09-05 05:52
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/6070.

**Comment by ainar-g** [comment] 2023-09-05 10:06
Of #1165, actually, where OP had already commented before creating this duplicate.  OP, please don't do that.  Just use the :+1: emote on the original issue.

**Closed by ainar-g** 2023-09-05 10:06 UTC
Labels: feature request
