### ISSUE TITLE
/etc/hosts does not reload when changed

### ISSUE THREAD

**Issue by hwilson-dev** [AdguardTeam/AdGuardHome#6711] opened 2024-02-06 20:57 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS), AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.44

### Action

When I make a change the /etc/hosts, I expect it to show in the 'runtime clients' table and I expect the configured IP address to be returned when querying it.

### Expected result

I expect the newly configured data to be show and used.

### Actual result

The change in /etc/hosts does not become active until I restart the AdguardHome process.

By looking at the code and turning on debug, I see that an FSWatcher is instantiated for the file. But it never seem to recive any change notifications from the OS. I tried both macOS and Windows.

I cloned the fsnotify repo and ran their test application. It works as expected. So I suspect the issue is with the AdguardHome use of that code.

Please take a look.

**Comment by hwilson-dev** [comment] 2024-02-06 21:48
I was able to get it to work on macOS by using:

`//go:build darwin

package aghnet

func defaultHostsPaths() (paths []string) {
        return []string{"private/etc/hosts"}
}`

So I needed to use "private/" in front of "etc/hosts".

**Comment by hwilson-dev** [comment] 2024-02-06 22:12
I also needed this change in fswatcher.go:

```
-       return w.w.Add(filepath.Join("/", name))
+       return w.w.Add(filepath.Dir(filepath.Join("/", name)))
```

See the "Watching a file doesn't work well" comment in the README of the fsnotify repo.

**Comment by EugeneOne1** [comment] 2024-02-07 10:26
@hwilson-dev, hello and thanks for the report.  What version of macOS do you use?  It seems, the `/etc` directory is actually a symlink to the `/private/etc` directory.  However, I can't reproduce the issue on my macOS 12.4 machine, trying to edit both `/etc/hosts` and `/private/etc/hosts` files.  Did previous versions of AdGuard Home receive these notifications?

**Comment by hwilson-dev** [comment] 2024-02-07 15:27
@EugeneOne1 I'm on macOS 13.5.1. I started with v0.107.36 and am now on v0.107.44.

Without the changes mentioned above, it never worked for me on Windows or macOS.

**Comment by EugeneOne1** [comment] 2024-02-07 17:16
@hwilson-dev, do you happen to find out, which if these changes are required on Windows to fix the issue?  AFAIK, at least, the file location isn't that tricky there.

**Comment by hwilson-dev** [comment] 2024-02-07 17:25
@EugeneOne1 The fswatcher.go change above:

```
-       return w.w.Add(filepath.Join("/", name))
+       return w.w.Add(filepath.Dir(filepath.Join("/", name)))
```

Made it work on Windows for me.

**Comment by EugeneOne1** [comment] 2024-02-13 10:54
@hwilson-dev, hello again.  We've pushed the edge release that implements the suggested fixes, could you please check if it now tracks changes to the hosts file?  Thanks for your participation.

**Comment by EugeneOne1** [comment] 2024-02-16 10:18
@hwilson-dev, we're going to close the issue for now, feel free to reopen it if the problem reoccurs.

**Closed by EugeneOne1** 2024-02-16 10:18 UTC
Labels: bug, compatibility
