### ISSUE TITLE
Block button is displayed over other UI elements

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdGuardHome#2906] opened 2021-04-01 15:56 UTC
Provided that the browser window to which the AdGuard Home interface is opened is reduced 

Look at [the screenshot](https://uploads.adguard.com/Chinaski4dohv.png) to see example

**Comment by Aikatsui** [comment] 2021-04-01 20:18
Duplicate of #2075

**Closed** 2021-04-02 09:29 UTC
Labels: duplicate
