### ISSUE TITLE
Encryption settings: validating certificate pair: certificate has no IP addresses, this may cause issues with DNS-over-TLS clients

### ISSUE THREAD

**Issue by kokesh** [AdguardTeam/AdGuardHome#5123] opened 2022-11-09 09:27 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

Snap

### Setup

On one machine

### AdGuard Home version

0.107.18

### Description

Everything was fine until yesterday. Using AGH as a Private DNS on Android, it stopped working suddenly.

I've got the following under certificate settings:

validating certificate pair: certificate has no IP addresses, this may cause issues with DNS-over-TLS clients
The certificates are fine and working LetsEncrypt. I've even renewed them to try if it helps somehow, it doesn't.

**Comment by CDzungx** [comment] 2022-11-09 12:15
Using Edge version, the same error but everything works fine.

**Comment by scallaway** [comment] 2022-11-09 13:22
This is the error that I was just coming to the issues to ask about!

I'm going to have to wait for another release as I'm no where near as adventurous as @CDzungx to try and use the edge version!

**Comment by CDzungx** [comment] 2022-11-09 13:51
> This is the error that I was just coming to the issues to ask about! I am seeing the same thing when trying to setup DoH and DoT.
> 
> I haven't tried the edge version, although I'm not really inclined to do so.

If your DNS work fine, just ignore that error.

**Comment by scallaway** [comment] 2022-11-09 13:59
> > This is the error that I was just coming to the issues to ask about! I am seeing the same thing when trying to setup DoH and DoT.
> > I haven't tried the edge version, although I'm not really inclined to do so.
> 
> If your DNS work fine, just ignore that ~error~ warning.

Yeah my DNS is working fine, although when I go to https://1.1.1.1/help I see the following;

<table>
<tr>
	<td>Connected to 1.1.1.1</td>
	<td>Yes</td>
<tr>
	<td>Using DNS over HTTPS (DoH)</td>
	<td>Yes</td>
<tr>
	<td>Using DNS over TLS (DoT)</td>
	<td>No</td>
<tr>
	<td>Using DNS over WARP</td>
	<td>No</td>
</table>

So I have a feeling that there is still something a bit wrong with the certificate, as I was really looking to get DoT enabled.

**Comment by CDzungx** [comment] 2022-11-09 14:05
What do you mean 😂😂 What can be wrong with your Cert. I'm using my DNS and all is _No_. I think it's about the DNS setting.

**Comment by stenginaut** [comment] 2022-11-09 20:37
I use a FRITZ!Box 5530 Fiber and my DNS stopped working entirely ever since this error message has popped up.

Everything was running fine under v0.107.17 but then I upgraded to v0.107.18 and it broke.
I tried the edge version, I tried going back to v0.107.17 without success.

Is there any solution to this?

**Comment by CDzungx** [comment] 2022-11-10 04:51
> I use a FRITZ!Box 5530 Fiber and my DNS stopped working entirely ever since this error message has popped up.
> 
> Everything was running fine under v0.107.17 but then I upgraded to v0.107.18 and it broke. I tried the edge version, I tried going back to v0.107.17, without any form of success.
> 
> Is there any solution to this issue? I'm using Let's Encrypt certificates to secure the instance. AdGuard is running on a VPS and only allows connections from my clients.

Maybe try other DDNS service like DuckDNS

**Comment by stenginaut** [comment] 2022-11-10 10:16
Let me change my statement a bit. The DNS server is working, however DoT is causing problems. The FRITZ!Box (my router) can't seem to handle it anymore. I haven't followed the changelogs of the last releases, but something must have changed.

My iPhone and my MacBook which are set up via .mobileconfig using DoT do not have any problems.
Only my router can't handle it and therefore all devices on the network. 

What I did as a workaround is to remove the restriction to my clients (home network, iPhone and MacBook).
So my DNS is now accessible to everyone, but at least it works via normal DNS, so no DoT at the moment.

**Comment by BobWs** [comment] 2022-11-10 14:11
Same error notification after updating to v107.18 before this update everything was fine!

**Comment by scallaway** [comment] 2022-11-10 14:47
@CDzungx 

> You use DoH for Cloudflare in your DNS setting?

I have both DoH and DoT setup in my DNS settings pointing at Cloudflare. Which is why I believe the IP address problem to be a cause of my issues as well.

**Comment by bluetoothfx** [comment] 2022-11-10 17:46
I'm having this issue on v107.17 also.

**Comment by stenginaut** [comment] 2022-11-10 18:35
> I'm having this issue on v107.17 also.

Can confirm. v107.17 shows the message, v107.16 doesn't.

**Comment by kokesh** [comment] 2022-11-10 19:17
Just to clarify what my setup is:
Tiny HP thin client running Ubuntu with Homeassistant running on it, later I've added Adguard running beside HA.
I've got a domain, pointed to my home public IP via Cloudflare nameservers. No proxying, or anything like that on Cloudflare side. My modem does NAT to my little Linux machine for web, Homeassistant and Adguard.
All was fine until few days ago, as I wrote in this issue.

**Comment by Szene** [comment] 2022-11-11 01:00
I have the same issue with a new docker installation with version v107.18.
It just doesn't let me save the certificat paths.

I can confirm that in v107.16 image everything works fine.

**Comment by kokesh** [comment] 2022-11-11 14:37
I've switched to v0.108.0-a.382+167b1125 (Edge) version via Snap. No change whatsoever. Everything works, except DNS-over-TLS.

**Comment by Eyeborgs** [comment] 2022-11-12 00:32
Please return everything as it was in V0.107.16 because I can’t use a new version due to this error and I had to roll it back ..

**Comment by CDzungx** [comment] 2022-11-12 09:47
> Everything works, except DNS-over-TLS.

It's weird that my DoT still working like a champ 😂 (Edge)
![Screenshot_2022-11-12-16-46-07-969_app intra-edit](https://user-images.githubusercontent.com/59353870/201468542-d61059de-a146-4100-b821-86c0003684b2.jpg)

**Comment by CDzungx** [comment] 2022-11-12 09:54
> It just doesn't let me save the certificate paths for my Let's Encrypt certificates

Saved normally on Edge 
![IMG_20221112_165309](https://user-images.githubusercontent.com/59353870/201468762-a0158985-0cf6-4c1d-8d9f-fb5e6dc6b716.jpg)


> Everything works, except DNS-over-TLS.
Mine DoT working fine Edge version too.
![Screenshot_2022-11-12-16-46-07-969_app intra-edit](https://user-images.githubusercontent.com/59353870/201468789-a1531304-0114-4d62-8cb5-0e215cf9e42e.jpg)

**Comment by guidocioni** [comment] 2022-11-14 09:39
having the same issue as well

**Comment by manfahrer** [comment] 2022-11-15 16:36
I have the same error

**Comment by kokesh** [comment] 2022-11-19 11:34
Current edge version, DNS over TLS is still broken.

v0.108.0-a.383+93882d68

**Comment by CDzungx** [comment] 2022-11-20 05:10
> * Google apparently requires you to use X1.

Isn't the current default signing chain (R3) using X1?
https://letsencrypt.org/certificates/
https://letsencrypt.org/2020/09/17/new-root-and-intermediates.html

**Comment by CDzungx** [comment] 2022-11-20 05:16
> * Google apparently requires you to use X1.
Isn't the default (R3) using X1? 😂
![image](https://user-images.githubusercontent.com/59353870/202886854-501cf78e-af95-4d3f-bd2b-12dbfb2996fb.png)
https://letsencrypt.org/certificates/

**Comment by Szene** [comment] 2022-12-09 20:58
It's a little bit changed in v0.107.20, now the message is visually less alarming.
![image](https://user-images.githubusercontent.com/71387543/206794985-5fd2ecb4-0b3d-459a-903e-dda9a584c334.png)

**Comment by Birbber** [comment] 2022-12-27 15:27
Closing this issue as completed. Please re-open if needed.

**Closed by Birbber** 2022-12-27 15:27 UTC
Labels: question

**Comment by filisdiez** [comment] 2023-01-18 21:06
I confirm that the same error is present! If you use a certificate for an ip address, then the error disappears, but for some reason it does not work with a domain certificate. I use Adguard Home on an asus router with merlin firmware.

**Comment by PVasileff** [comment] 2023-01-22 05:17
Same here. Installed Adguard Home on VM with Debian 11, on my Proxmox. Configured static dhcp ip for ADH on my MikroTik RB4011

**Comment by jeromelarras** [comment] 2023-01-24 23:31
Hi there

My adguard home on synology nas claim same issue : 

Attention: validating certificate pair: certificates has no IP addresses; DNS-over-TLS won't be advertised via DDR

I'm using DNS-over-HTTPS as upstream, so i think i don't need to take care about this half warning message.

What do you think about that ?
Thanks

**Comment by breathless19** [comment] 2023-02-19 19:27
I'm getting this message too ("no ip address" and "won't be advertised over ddr"), and DNS over TLS isn't working.   I'm using Adguard Home in my Asus Router with Merlin.   Everything is working as expected filter wise except encryption.   My certificate was generated within my Asus router by LetsEncrypt and is working fine with all other services that require a certificate.   

I can confirm that encryption isn't working because my RustDesk server is set to not make a connection unless it's a secure connection.   Using Adguard DNS.io with my router restores encryption / connectivity.    When disabling Adguard dns.io and enabling Adguard Home on my router, connections within my Lan and outside my Lan no longer work unless I have the Adguard desktop or Adguard mobile client app installed and enabled.   Copying / pasting the certificate vs giving the exact path makes no difference, but I currently have it set to the exact path.   This needs a fix....

**Comment by eric8bits** [comment] 2023-03-13 21:25
Same issue. AdGuard Home on a VPS with a domain.

**Comment by stylemessiah** [comment] 2023-03-15 08:51
Same error on Windows version. nothing wrong with certifcates....

**Comment by Issam2204** [comment] 2023-03-20 17:28
Same issue over here.

**Comment by breathless19** [comment] 2023-03-20 19:32
Same here as well. 

They could easily avoid this (assuming that the issue here is simply that Let's Encrypt certificates don't include I.P. addresses) by removing the disturbing verbiage and instead making a little checkbox underneath that says "advertise TLS via DDR" that is uncheckable if your certificate is from Let's Encrypt or any other service that doesn't include IP addresses, and give a little explanation next to the checkbox stating as such (IE: "TLS cannot advertise via DDR when certificates do not contain IP addresses").    Then people will at least understand that the "issue" is because of the cert that they chose and will thereby not be pissed off by scary words and flocking to the forum.

**Comment by AmIBeingObtuse** [comment] 2024-02-04 21:35
Did anyone manage to resolve this? Or have a suggested course of action. I'm trying to get adguard home encryption setup on the encryption page. I already use DOH for upstream servers but wanted to try using DOH from device to adguard also. Also does anyone know any good guides for this. I can't seem to find one. Thanks.

**Comment by like33** [comment] 2024-02-22 09:52
![image](https://github.com/AdguardTeam/AdGuardHome/assets/92007593/b80b849f-f18c-4ae4-b3a8-033aa209f602)

This problem makes my tls unusable.

**Comment by jcleng** [comment] 2024-02-25 04:08
same +1 , than how to open and use DoT, on android phone must a domain not ip. no solution?

**Comment by benkap** [comment] 2024-04-25 14:51
same here... DoT is not working. should be reopened

**Comment by securitasis** [comment] 2024-06-25 23:10
I'm experiencing the same exact issue. I've confirmed it is not working because if I uncheck "Enable plain DNS" under Encryption settings, all DNS traffic stops under the DNSD Query Logs.. Also, every log entry shows types "A, Plain DNS" or "HTTPS, Plain DNS"  Has anyone tried another Certificate Authority that allows an IP address or IP alias?

**Comment by RosensRauk** [comment] 2024-07-29 19:14
This is weird! 

When plain DNS is on;
DNS-server
Name.cloudflare-gateway.com:53
Time:
54 ms
Answer:
A: 188.114.97.1 (ttl=2400)
A: 188.114.96.1 (ttl=2400)
NOERROR

Everything works and if i check security in my browser it says it is safe.

When plain DNS is off, only encrypted:
Nothing. I can't even get online! And nothing shows in the Adguard home logg.

**Comment by jaybauson** [comment] 2024-08-01 07:29
> This is weird!
> 
> When plain DNS is on; Type: https DNS-server: Name.cloudflare-gateway.com:53 Time: 54 ms Answer: A: 188.114.97.1 (ttl=2400) A: 188.114.96.1 (ttl=2400) NOERROR
> 
> Everything works and if i check security in my browser it says it is safe.
> 
> When plain DNS is off, only encrypted: Nothing. I can't even get online! And nothing shows in the Adguard home logg.

I was a Pi-Hole user until yesterday, and I have the same exact error. Now I am stuck, I will probably wait for an update so I can turn the encryption on.

**Comment by Honglan233** [comment] 2024-08-02 10:15
> This is weird!
> 
> When plain DNS is on; Type: https DNS-server: Name.cloudflare-gateway.com:53 Time: 54 ms Answer: A: 188.114.97.1 (ttl=2400) A: 188.114.96.1 (ttl=2400) NOERROR
> 
> Everything works and if i check security in my browser it says it is safe.
> 
> When plain DNS is off, only encrypted: Nothing. I can't even get online! And nothing shows in the Adguard home logg.

I have the same problem today, which is strange

**Comment by cx51** [comment] 2024-08-06 15:40
> > This is weird!
> > When plain DNS is on; Type: https DNS-server: Name.cloudflare-gateway.com:53 Time: 54 ms Answer: A: 188.114.97.1 (ttl=2400) A: 188.114.96.1 (ttl=2400) NOERROR
> > Everything works and if i check security in my browser it says it is safe.
> > When plain DNS is off, only encrypted: Nothing. I can't even get online! And nothing shows in the Adguard home logg.
> 
> I have the same problem today, which is strange

Same here. Did you find any solution?
At my end DoH/DoT don't work at all, shows cert chain is valid. Plain DNS works fine, if I disable it then nothing works.

**Comment by Honglan233** [comment] 2024-08-06 15:46
> > > This is weird!
> > > When plain DNS is on; Type: https DNS-server: Name.cloudflare-gateway.com:53 Time: 54 ms Answer: A: 188.114.97.1 (ttl=2400) A: 188.114.96.1 (ttl=2400) NOERROR
> > > Everything works and if i check security in my browser it says it is safe.
> > > When plain DNS is off, only encrypted: Nothing. I can't even get online! And nothing shows in the Adguard home logg.
> > 
> > 
> > I have the same problem today, which is strange
> 
> Same here. Did you find any solution? At my end DoH/DoT don't work at all, shows cert chain is valid. Plain DNS works fine, if I disable it then nothing works.

If you are in PRC, please note that the GFW blocks port 853 on most foreign servers, which is the main reason I found

**Comment by cx51** [comment] 2024-08-06 16:12
> > > > This is weird!
> > > > When plain DNS is on; Type: https DNS-server: Name.cloudflare-gateway.com:53 Time: 54 ms Answer: A: 188.114.97.1 (ttl=2400) A: 188.114.96.1 (ttl=2400) NOERROR
> > > > Everything works and if i check security in my browser it says it is safe.
> > > > When plain DNS is off, only encrypted: Nothing. I can't even get online! And nothing shows in the Adguard home logg.
> > > 
> > > 
> > > I have the same problem today, which is strange
> > 
> > 
> > Same here. Did you find any solution? At my end DoH/DoT don't work at all, shows cert chain is valid. Plain DNS works fine, if I disable it then nothing works.
> 
> If you are in PRC, please note that the GFW blocks port 853 on most foreign servers, which is the main reason I found

After reading recent comments here. It looks like DoT doesn't work for most regardless If one is in PRC or using a server in different jurisdiction. Another issue is when if I turn off **plain DNS ** and enforce encryption, it breaks everything (fails to make any query)
Only DoT isn't working for most. For me DoH/DoQ is dead too. Ports are open, certs are valid, IP is set correctly.

What I did was, I installed Wireguard and added AdGuard DNS in my WG client config. If I'm outside or say I want encryption between clients. I enable Wireguard with ad blocking.

**Comment by amir0ff** [comment] 2024-11-17 13:16
**Warning still persists. Please reopen!**

![image](https://github.com/user-attachments/assets/afb39f56-02d3-4b04-b73e-5bf4e1cc4358)

My DoT works fine with this warning but I would like to know how to resolve it? How do we add an IP address to a certificate say for example using `certbot`?

I did: `certbot certonly --standalone --agree-tos --email myemail@mail.com -d my.domain.com -i MY_IP_ADDRESS`

But the warning is still there...

**Comment by RosensRauk** [comment] 2024-11-18 13:01
I made a mistake in my original configuration.
Sorted it out by adding both ip and DNS-Subdomain to the clientID.
I had totally missed that it is possible to add several IDs.

Did this fix your problem?

**Comment by wuxingzhidi** [comment] 2024-11-18 17:41
I don't quite understand what you mean. I have already filled in the relevant information. Do I still need to add the client ID on the server side? Isn't it assumed that any protocol can be used if it is blank? In China, it is almost impossible to get a fixed IP address. IP addresses are dynamic. How do I add the client IP on the server side?

**Comment by wuxingzhidi** [comment] 2024-11-18 17:43
The main reason is that the doh protocol can still be used, but DOT cannot be used. In the open source proxy software, DOT is not stable, but DOH is stable enough. I am very confused!

**Comment by JoSoG89** [comment] 2025-01-06 06:02
Any new?
I have same problem...

**Comment by popy2k14** [comment] 2025-06-29 18:58
I have the same warning with an let's encrypt cert but DoT is working for me on port 853 and with an pixel 8 pro.
So i guess it's ok in my case.

Can i block clients from DoT with an certain subdomain?
I want adguard-1234.my.duckdns.org to access the server and block all other.

thx
