### ISSUE TITLE
Network Error  while trying to add new clients

### ISSUE THREAD

**Issue by nixmomo** [AdguardTeam/AdGuardHome#5949] opened 2023-06-30 10:19 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.586+2069eddf

### Action

Adding a client manually with the "new client" dialouge via webinterface

### Expected result

aded client 

### Actual result

i get a network error if i hit the save button

### Additional information and/or screenshots

i have installed adguard home via docker with this image adguard/adguardhome:latest 
Clients are connected fine and i have not found any other issues right now but if i add a new client manualy and enter all the informations and hit save i get a network error

![image](https://github.com/AdguardTeam/AdGuardHome/assets/8502506/0f8e1320-4b6b-4ae1-bfe8-dde140e6d953)

**Comment by nixmomo** [comment] 2023-06-30 10:21
here is the same issue from another user
https://www.reddit.com/r/Adguard/comments/14mf42v/network_error_while_trying_to_add_new_clients/

**Comment by ainar-g** [comment] 2023-06-30 10:27
Duplicate of #5946

**Closed by ainar-g** 2023-06-30 10:27 UTC
