### ISSUE TITLE
给Adguard home新增一个功能

### ISSUE THREAD

**Issue by xiulou23** [AdguardTeam/AdGuardHome#5844] opened 2023-05-24 06:26 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### Additional information
我建议你们给Adguard home加上Protect from DPI功能，Windows版电脑就有这一个功能，我觉得挺重要的，对隐私安全有好处

**Comment by fernvenue** [comment] 2023-05-25 14:26
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/5833, please don't abuse issue tickets.

**Closed** 2024-04-02 23:27 UTC
