### ISSUE TITLE
DNS-over-HTTP/3 (DoH3)

### ISSUE THREAD

**Issue by cuiver** [AdguardTeam/AdGuardHome#4766] opened 2022-07-20 16:02 UTC
- [X] I am running the latest version (v0.108.0-b.10)
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Feature request
With the release to the public of **DNS-over-HTTP/3 (DoH3) native support in Android 11+** (https://security.googleblog.com/2022/07/dns-over-http3-in-android.html), is there a timeline of when DoH3 will be added to AdGuard Home?

I know you guys must have more pressing matters to address, but it would be nice to be able to use this natively on Android devices (avoiding less reliable dummy VPN/other non-native alternatives for DoH support, since DoT - which is natively supported on Android - is getting blocked more and more frequently in public WiFi settings, besides the obvious advantages of using QUIC).

Thanks for considering!

**Comment by ammnt** [comment] 2022-07-20 17:12
Duplicate of:
https://github.com/AdguardTeam/AdGuardHome/issues/3955

**Closed** 2022-07-25 13:36 UTC
