### ISSUE TITLE
[Beta] DoH & DoT bootstrap addresses shouldn't be copied to iOS/macOS mobile config profile as bootstrap addresses

### ISSUE THREAD

**Issue by emlimap** [AdguardTeam/AdGuardHome#3617] opened 2021-09-17 12:47 UTC
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.107.0-b.11
* **How did you install AdGuard Home:**
  * Github Releases
* **How did you setup DNS configuration:**
  * Router/DHCP
* **If it's a router or IoT, please write device model:**
  * Virtual Machine
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Ubuntu 20.04.3

### Expected Behavior

Generate a new mobile config profile for iOS from Adguard home and be able to install it

### Actual Behavior

Profile installation fails with error message `The DNS setting service encountered an internal error`. Beta 10 doesn't have this issue and on further investigation, the issue occurs since the fix for https://github.com/AdguardTeam/AdGuardHome/issues/3568.

I have DoT & DoH addresses for bootstrap along with an entry for NextDNS CLI running on port number `5454`. They are being copied to the mobile config file which is causing iOS to fail to import the profile. If I remove the bootstrap addresses manually and import again, it works.

Looking at [Apple documentation](https://developer.apple.com/documentation/devicemanagement/dnssettings/dnssettings), `ServerAddresses` should be a list of IPv4/6 address. So DoT, DoH & and IP addresses with port number wouldn't be accepted, and I happen to set everything that isn't accepted by iOS as bootstrap servers.
```
<key>ServerAddresses</key>
<array>
        <string>https://8.8.8.8/dns-query</string>
        <string>tls://8.8.8.8</string>
        <string>tls://9.9.9.9</string>
        <string>[::1]:5454</string>
</array>
```

Steps to reproduce the issue.

1. Add the following addresses to bootstrap DNS servers section.
```
https://8.8.8.8/dns-query
tls://8.8.8.8
tls://9.9.9.9
[::1]:5454
```
2. Generate a mobile config file within AGH and try to import it on iPhone running iOS 14.8.

### Additional Information

The part I am confused about is the `ServerAddresses`. As per [Apple documentation](https://developer.apple.com/documentation/devicemanagement/dnssettings/dnssettings), it can be used to provide the IP addresses of your server to avoid DNS lookup for DoH/DoT hostname or at least the way I understand it from their documentation. So this should be the IPv4 and/or IPv6 addresses of AGH instance rather than a public DNS resolver.

The following wording exists in help text for both `ServerName` and `ServerURL` where former is for DoT and latter is used for DoH

```If no ServerAddresses are provided, the hostname will be used to determine the server addresses```

**Comment by ainar-g** [comment] 2021-09-17 12:53
Duplicate of #3607, merging in.

**Closed by ainar-g** 2021-09-17 12:53 UTC
