### ISSUE TITLE
Empty IP in response for AAAA rewrites

### ISSUE THREAD

**Issue by psunde** [AdguardTeam/AdGuardHome#1040] opened 2019-10-01 14:02 UTC
### Issue Details

* **Version of AdGuard Home server:**
  * v0.98.1
* **How did you setup DNS configuration:**
  * Router
* **Operating system and version:**
  * Alpine (Docker)

### Expected Behavior
I send a AAAA query (via dig in this case) to the AdGuardHome DNS server. The server reports rewritten record:
`[debug] Rewrite: AAAA for myipv6domain.net is 4424:a743:2e0e:dfba:ad6c:5548:6b9:e489`
DNS answer contains AAAA section with address from above:
```
[...]
;; ANSWER SECTION:
myipv6domain.net.	10	IN	AAAA	4424:a743:2e0e:dfba:ad6c:5548:6b9:e489
```

### Actual Behavior
AdGuardHome log file contains the message for rewritten record:
`[debug] Rewrite: AAAA for myipv6domain.net is 4424:a743:2e0e:dfba:ad6c:5548:6b9:e489`
But Query Log shows no IP address (see screenshot).
Also the DNS answer does not contain the expected IP address:
```
[debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): OUT: ;; opcode: QUERY, status: NOERROR, id: 41259
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;myipv6domain.net.	IN	 AAAA

;; ANSWER SECTION:
myipv6domain.net.	10	IN	AAAA	
```

### Screenshots
<details><summary>Screenshot:</summary>
[image](https://user-images.githubusercontent.com/28060168/65969062-af8a3680-e453-11e9-9829-15ed94718fbc.png)
https://user-images.githubusercontent.com/28060168/65969062-af8a3680-e453-11e9-9829-15ed94718fbc.png
</details>

**Comment by ameshkov** [comment] 2019-10-01 14:03
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/989

This issue is fixed in the beta version

**Closed by ameshkov** 2019-10-01 14:03 UTC
Labels: duplicate
