### ISSUE TITLE
integrate the change of username and password

### ISSUE THREAD

**Issue by marcus83ita** [AdguardTeam/AdGuardHome#7519] opened 2024-12-21 06:48 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

integrate the change of username and password

### Proposed solution

Why don't you integrate the change of username and password directly via WebIf into the next update?

**Comment by ainar-g** [comment] 2024-12-23 09:13
Duplicate of #997.

**Closed by ainar-g** 2024-12-23 09:13 UTC
Labels: feature request
