### ISSUE TITLE
Unable to respond to root request

### ISSUE THREAD

**Issue by lixiangzhong** [AdguardTeam/AdGuardHome#2994] opened 2021-04-22 04:31 UTC
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * AdGuard Home, version v0.105.2, channel release, arch linux amd64

* **How did you install AdGuard Home:**
  *  docker run --name adguardhome \
    -v /data/adguardhome:/opt/adguardhome/work \
    -v /etc/adguardhome:/opt/adguardhome/conf \
    -p 53:53/tcp -p 53:53/udp \
    -p 3000:3000/tcp \
    -p 853:853/tcp \
    -d adguard/adguardhome
* **How did you setup DNS configuration:**
  * nameserver 127.0.0.1
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Linux  3.10.0-1160.6.1.el7.x86_64 

### Expected Behavior
```
[root@myserver~]# dig

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.2 <<>> 
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24737
;; flags: qr rd ra; QUERY: 1, ANSWER: 13, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;.				IN	NS

;; ANSWER SECTION:
.			396	IN	NS	b.root-servers.net.
.			396	IN	NS	j.root-servers.net.
.			396	IN	NS	d.root-servers.net.
.			396	IN	NS	i.root-servers.net.
.			396	IN	NS	a.root-servers.net.
.			396	IN	NS	m.root-servers.net.
.			396	IN	NS	f.root-servers.net.
.			396	IN	NS	k.root-servers.net.
.			396	IN	NS	g.root-servers.net.
.			396	IN	NS	h.root-servers.net.
.			396	IN	NS	c.root-servers.net.
.			396	IN	NS	l.root-servers.net.
.			396	IN	NS	e.root-servers.net.

;; Query time: 24 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Apr 22 12:30:08 CST 2021
;; MSG SIZE  rcvd: 239

```

### Actual Behavior
```
[root@myserver ~]# dig

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.2 <<>> .
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 47807
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;.				IN	A

;; Query time: 1 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Apr 22 12:28:06 CST 2021
;; MSG SIZE  rcvd: 17
```

**Comment by ainar-g** [comment] 2021-04-22 10:31
Hi, and thank you for the thorough report.  Unfortunately we cannot reproduce that behaviour.  Can you [configure] AdGuard Home to collect logs by setting  `verbose` to `true` and post logs here as an attachment?  Also, are there any custom filtering rules that could cause that?  Thanks!

[configure]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by lixiangzhong** [comment] 2021-04-23 01:02
```bash
2021/04/23 01:00:13 1#82 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(): Start handling new UDP packet from 192.168.21.56:57693
2021/04/23 01:00:13 1#82 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): IN: ;; opcode: QUERY, status: NOERROR, id: 53565
;; flags: rd ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;.	IN	 A

;; ADDITIONAL SECTION:

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: ; udp: 4096

2021/04/23 01:00:13 1#82 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(): RTT: 0 ms
2021/04/23 01:00:13 1#82 [debug] ipset: starting processing
2021/04/23 01:00:13 1#82 [debug] ipset: skipped processing for request
2021/04/23 01:00:13 1#82 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): OUT: ;; opcode: QUERY, status: SERVFAIL, id: 53565
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;.	IN	 A

2021/04/23 01:00:14 1#71 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(): Start handling new UDP packet from 192.168.21.56:54877
2021/04/23 01:00:14 1#71 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): IN: ;; opcode: QUERY, status: NOERROR, id: 54788
;; flags: rd ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;.	IN	 A

;; ADDITIONAL SECTION:

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: ; udp: 4096

2021/04/23 01:00:14 1#71 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(): RTT: 0 ms
2021/04/23 01:00:14 1#71 [debug] ipset: starting processing
2021/04/23 01:00:14 1#71 [debug] ipset: skipped processing for request
2021/04/23 01:00:14 1#71 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): OUT: ;; opcode: QUERY, status: SERVFAIL, id: 54788
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;.	IN	 A

2021/04/23 01:00:14 1#72 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(): Start handling new UDP packet from 192.168.21.56:58377
2021/04/23 01:00:14 1#72 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): IN: ;; opcode: QUERY, status: NOERROR, id: 4374
;; flags: rd ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;.	IN	 A

;; ADDITIONAL SECTION:

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: ; udp: 4096

2021/04/23 01:00:14 1#72 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(): RTT: 0 ms
2021/04/23 01:00:14 1#72 [debug] ipset: starting processing
2021/04/23 01:00:14 1#72 [debug] ipset: skipped processing for request
2021/04/23 01:00:14 1#72 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): OUT: ;; opcode: QUERY, status: SERVFAIL, id: 4374
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;.	IN	 A

```

**Comment by lixiangzhong** [comment] 2021-04-23 01:04
AdGuardHome.yaml
```yaml
bind_host: 0.0.0.0
bind_port: 3000
beta_bind_port: 0
users:
- name: dns
  password: $2a$10$agfzpxKaWgIoPnHxUxuedudirT.yZvmhhxXns1qpiE7vb8U76CZki
http_proxy: ""
language: ""
rlimit_nofile: 0
debug_pprof: false
web_session_ttl: 720
dns:
  bind_host: 0.0.0.0
  port: 53
  statistics_interval: 1
  querylog_enabled: true
  querylog_file_enabled: true
  querylog_interval: 1
  querylog_size_memory: 1000
  anonymize_client_ip: false
  protection_enabled: true
  blocking_mode: default
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_response_ttl: 10
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  ratelimit: 0
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
  - 114.114.114.114
  - 218.85.152.99
  - '[/akamai.net/]tls://94.140.14.140'
  upstream_dns_file: ""
  bootstrap_dns:
  - 9.9.9.10
  - 149.112.112.10
  - 2620:fe::10
  - 2620:fe::fe:10
  all_servers: false
  fastest_addr: false
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts: []
  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: false
  edns_client_subnet: false
  max_goroutines: 300
  ipset: []
  filtering_enabled: true
  filters_update_interval: 72
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  rewrites: []
  blocked_services: []
  customresolver: null
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 784
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  strict_sni_check: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
filters:
- enabled: false
  url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
  name: AdGuard DNS filter
  id: 1
- enabled: false
  url: https://adaway.org/hosts.txt
  name: AdAway Default Blocklist
  id: 2
- enabled: false
  url: https://www.malwaredomainlist.com/hostslist/hosts.txt
  name: MalwareDomainList.com Hosts List
  id: 4
whitelist_filters: []
user_rules: []
dhcp:
  enabled: false
  interface_name: ""
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
clients: []
log_compress: false
log_localtime: false
log_max_backups: 0
log_max_size: 100
log_max_age: 3
log_file: test.log
verbose: true
schema_version: 7
```

**Comment by lixiangzhong** [comment] 2021-04-23 01:42
```
  upstream_dns:
 ...
  - '[/akamai.net/]tls://94.140.14.140'   //If I delete this line, I can respond normally
```

**Comment by ainar-g** [comment] 2021-04-23 11:00
Thank you for the information!  We can now reproduce the issue.  We'll try to fix it by the next beta.

**Comment by ainar-g** [comment] 2021-04-23 14:28
The fix is out on the `edge` channel.  It will be released with the next beta sometime next week.  In the meantime you could test the fix on `edge`, including with docker.

**Comment by ainar-g** [comment] 2021-04-28 13:35
We'll close this issue for now.  Feel free to open a new one if there are any problems!

**Closed by ainar-g** 2021-04-28 13:35 UTC
Labels: P3: Medium, bug
