### ISSUE TITLE
Change Password

### ISSUE THREAD

**Issue by asheroto** [AdguardTeam/AdGuardHome#2715] opened 2021-02-20 02:43 UTC
Hello,

Simple request - ability to change the password.

I ended up just spinning a local instance up, copying the password line from AdGuardHome.yaml into my remote server.

:-)

Thanks!

**Comment by bv6rLw** [comment] 2021-02-20 08:58
Duplicate of #1321

**Comment by ameshkov** [comment] 2021-02-23 12:49
Please upvote #1321

**Closed by ameshkov** 2021-02-23 12:49 UTC
Labels: duplicate
