### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by TheCableGuy99** [AdguardTeam/AdGuardHome#7010] opened 2024-05-20 10:34 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.48

### Action

Apologies for using this form but I posted a question in the discussions 5 days ago and no one is replying. I just have a question about SSL certificates. Please can someone take a look at:
https://github.com/AdguardTeam/AdGuardHome/discussions/6999

Thank you.

### Expected result

Looking for help with the above link.

### Actual result

Looking for help with the above link.

**Comment by tjharman** [comment] 2024-05-25 04:04
Duplicate of https://github.com/AdguardTeam/AdGuardHome/discussions/6999

**Closed by tjharman** 2024-05-25 04:04 UTC
