### ISSUE TITLE
Backup Settings

### ISSUE THREAD

**Issue by marcus83ita** [AdguardTeam/AdGuardHome#6676] opened 2024-01-25 10:10 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

no problem, it's just an improvement

### Proposed solution

it would be nice to introduce a backup of the settings, and then restore them, in case of reinstallation, so that the data and settings are not lost.

**Comment by ainar-g** [comment] 2024-01-25 13:31
Duplicate of #1147

**Closed by ainar-g** 2024-01-25 13:31 UTC
Labels: feature request
