### ISSUE TITLE
Disable protection, on a timer

### ISSUE THREAD

**Issue by OttoMan28** [AdguardTeam/AdGuardHome#5107] opened 2022-11-06 09:24 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
Some times you need to disable protection for a time, e.g. if you want to do some shopping then the direct products links in e.g. google/bring get stopped due to provider they use (tradetracker.net ect)
So i turn off the AdGuard...... But i might forget to turn in on

#### Proposed solution
It would be nice if you can have a "disable protection" where you select a predefinded time, e.g. 5 min, 30 min, 60 min 12 h, 

#### Additional information
If you take a look at Pihole you can see how its implemented.

**Comment by fernvenue** [comment] 2022-11-06 15:40
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/1203.

**Comment by Birbber** [comment] 2022-12-20 15:45
Closing as a duplicate.

**Closed by Birbber** 2022-12-20 15:45 UTC
Labels: duplicate
