### ISSUE TITLE
指定客户端使用特定解析A or AAAA

### ISSUE THREAD

**Issue by yuxuan0107** [AdguardTeam/AdGuardHome#4253] opened 2022-02-06 03:31 UTC
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ √] I am running the latest version
- [ √] I checked the documentation and found no answer
- [√ ] I checked to make sure that this issue has not already been filed

### Problem Description

部分老旧设备无法支持AAAA解析记录/Some old devices cannot support AAAA parsing records

### Proposed Solution

能否指定客户端使用特定的解析方式比如指定某一客户端使用A记录或指定某一客户端使用AAAA记录/Can you specify a client to use a specific resolution method, such as specifying a client to use  record or specifying a client to use AAAA or ''A ''record

**Comment by agneevX** [comment] 2022-02-06 16:37
How old? You could always choose to enable the option that drops AAAA queries.

**Comment by yuxuan0107** [comment] 2022-02-07 02:41
> How old? You could always choose to enable the option that drops AAAA queries.

部分只能家居设备,智能物联网设备目前只支持IPV4,所以需要对特定设备只解析A记录,但是日常手机 电脑是可以使用IPV6的

**Comment by ainar-g** [comment] 2022-02-07 12:05
@yuxuan0107, hello.  I don't quite understand what the issue is.  AdGuard Home cannot “push” records to devices.  If the device doesn't request `AAAA` records, it won't receive them.

**Comment by yuxuan0107** [comment] 2022-02-07 12:32
> 
简单来讲,能否指定一个客户端只使用IPV6或者IPV4的解析
In short, can you specify that a client only uses IPv6 or IPv4 parsing

**Comment by yuxuan0107** [comment] 2022-02-07 12:33
> @yuxuan0107, hello. I don't quite understand what the issue is. AdGuard Home cannot “push” records to devices. If the device doesn't request `AAAA` records, it won't receive them.

hello!
简单来讲,能否指定一个客户端只使用IPV6或者IPV4的解析
In short, can you specify that a client only uses IPv6 or IPv4 parsing

**Comment by ainar-g** [comment] 2022-02-07 12:46
You can use the [`dnsrewrite` modifier][1] together with the `dnstype` ones to do something like:

```none
*$client=BadDevice,dnstype=AAAA,dnsrewrite=NOERROR;;
```

This exact form works starting with the beta version v0.108.0-b.2, but in previous versions you can also use `REFUSED`.  Or just remove the `dnsrewrite` modifier and only use `dnstype`, which will result in zero IP reslonse.

But still, this is a rather weird situation, and I recommend that you inspect, if there is anything else wrong with the devices.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#dnsrewrite

**Comment by yuxuan0107** [comment] 2022-02-07 12:59
> You can use the [`dnsrewrite` modifier](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#dnsrewrite) together with the `dnstype` ones to do something like:
> 
> ```
> *$client=BadDevice,dnstype=AAAA,dnsrewrite=NOERROR;;
> ```
> 
> This exact form works starting with the beta version v0.108.0-b.2, but in previous versions you can also use `REFUSED`. Or just remove the `dnsrewrite` modifier and only use `dnstype`, which will result in zero IP reslonse.
> 
> But still, this is a rather weird situation, and I recommend that you inspect, if there is anything else wrong with the devices.

感谢您的答复,我将会尝试你说的方法.同时我也会在这个问题下面反馈情况.请暂时保留这个问题,再次感谢,
Thank you for your reply. I will try what you said At the same time, I will also give feedback under this question Please keep this question for the time being. Thank you again

**Comment by ainar-g** [comment] 2022-02-07 13:07
@yuxuan0107, it can be an IP address, a CIDR network, or the name of the client that you have entered when creating it on the “Settings → Client settings” page.  Please refer to our [`client` modifier documentation][1].

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#client

**Comment by yuxuan0107** [comment] 2022-02-07 13:24
> @yuxuan0107, it can be an IP address, a CIDR network, or the name of the client that you have entered when creating it on the “Settings → Client settings” page. Please refer to our [`client` modifier documentation](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#client).

Thanks!

**Comment by yuxuan0107** [comment] 2022-02-09 08:40
> @yuxuan0107, it can be an IP address, a CIDR network, or the name of the client that you have entered when creating it on the “Settings → Client settings” page. Please refer to our [`client` modifier documentation](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#client).


So far it seems that the way you gave is feasible, thank you
My scenario is as follows: Client 1 only has one IPv4 address to initiate a domain name request, and the DNS server will return an A record and an AAAA record. In this case, the client will not be able to access it normally. If the AAAA record is blocked in ADGUADRHOME, the client can access normally. But there are only some special devices in my network that don't support IPv6, so I need to do IPv4 A parsing for one device, others can keep the default AAAA or A parsing, from Google Translate

目前看来你给的方式是可行的，谢谢
我的场景如下：客户端1只有一个IPv4地址发起域名请求，DNS服务器会返回一条A记录和一条AAAA记录。 在这种情况下，客户端将无法正常访问它。 如果 AAAA 记录在 ADGUADRHOME 中被阻止，客户端可以正常访问。 但是我的网络中只有一些特殊的设备不支持 IPv6，所以我需要对某个设备进行 IPv4 A 解析，其他设备可以保持默认的 AAAA 或 A 解析，来自谷歌翻译

**Comment by ainar-g** [comment] 2022-02-09 12:17
@agneevX, I'm glad that we could help.  If the solution works for you, does this mean that we can close this issue?

**Comment by yuxuan0107** [comment] 2022-02-10 03:08
> 

good. no problem

**Comment by yuxuan0107** [comment] 2022-02-10 03:09
> @yuxuan0107, I'm glad that we could help. If the solution works for you, does this mean that we can close this issue?

good. no problem

**Closed** 2022-02-10 11:08 UTC
Labels: waiting for data
