### ISSUE TITLE
希望可以指定上游DNS的ip版本

### ISSUE THREAD

**Issue by qian9008** [AdguardTeam/AdGuardHome#5681] opened 2023-04-04 04:30 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Description

例如
1.1.1.1  -4
8.8.8.8 -6
这些虽然是v4dns服务器，可以同时解析ipv6和ipv4

**Comment by fernvenue** [comment] 2023-04-04 07:19
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/4489.

**Closed** 2023-04-04 07:40 UTC
