### ISSUE TITLE
Snap 1052 cannot bind DHCP to network interface

### ISSUE THREAD

**Issue by marxjohnson** [AdguardTeam/AdGuardHome#2228] opened 2020-10-28 20:55 UTC
### Issue Details

* **Version of AdGuard Home server:**
  * 0.104.0
* **How did you setup DNS configuration:**
  * System
* **Operating system and version:**
  * Ubuntu 18.04.5

### Expected Behavior
Before the snap refreshed (snap rev 606/adguard version 0.103.3), DHCP was enabled and working. After it updated, I expected it to continue working.

### Actual Behavior
DHCP stopped working after the refresh. Attempting to disable and re-enable the service resulted in the following error:
`Error: control/dhcp/set_config | Failed to start DHCP server: cannot bind to interface enp3s0: operation not permitted | 400`

**Comment by marxjohnson** [comment] 2020-10-28 21:41
As a workaround until a fix is published, running `snap revert adguard-home` restored the previous version.

**Comment by Tloram** [comment] 2020-10-29 08:34
Same issue here. DHCP stopped working over night when the snap updated to 0.104

Network is now down. Oh dear.

**Comment by ameshkov** [comment] 2020-10-29 09:26
We're looking into it, don't worry.

Meanwhile, could you please post the `dhcp:` section of your config files? (`AdGuardHome.yaml`)

**Comment by marxjohnson** [comment] 2020-10-29 10:00
Here is the `dchp` section of mine:
Snap rev 606 (working):
```
dhcp:
  enabled: true
  interface_name: enp3s0
  gateway_ip: 192.168.0.1
  subnet_mask: 255.255.255.0
  range_start: 192.168.0.50
  range_end: 192.168.0.150
  lease_duration: 86400
  icmp_timeout_msec: 1000
```

Snap rev 1052 (not working):
```
dhcp:
  enabled: true
  interface_name: enp3s0
  dhcpv4:
    gateway_ip: 192.168.0.1
    subnet_mask: 255.255.255.0
    range_start: 192.168.0.50
    range_end: 192.168.0.150
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
```

**Comment by ainar-g** [comment] 2020-10-29 12:53
<p>Good&#xA0;day, @marxjohnson!&#x2003;Thank you
for&#xA0;the&#xA0;report.&#x2003;I&#xA0;was able to&#xA0;reproduce
the&#xA0;bug.&#x2003;Apparently, the&#xA0;new way we filter packets to&#xA0;only get
the&#xA0;ones from&#xA0;the&#xA0;required interface on&#xA0;<i>Linux</i>
requires more permissions than&#xA0;before.&#x2003;We're investigating
how&#xA0;to&#xA0;fix&#xA0;this.</p>

**Comment by ameshkov** [comment] 2020-10-29 18:09
@marxjohnson @Tloram please try installing AGH snap from the edge channel, the issue should be gone now.

`snap refresh adguard-home --channel edge`

**Comment by marxjohnson** [comment] 2020-10-29 20:58
Hi @ameshkov, I just tried that:
`adguard-home (edge) v0.104.0-SNAPSHOT-9761f133 from AdGuard (ameshkov✓) refreshed`
Unfortunately, the problem still persists.

**Comment by ameshkov** [comment] 2020-10-29 20:59
Weird, we'll double-check.

**Comment by mccw** [comment] 2020-10-30 14:33
I have the same issue on a brand new install of .104. I could never get Snap install working on Raspberry Pi. Is there a way to revert to a previous version using the RPI install instructions?

**Comment by ameshkov** [comment] 2020-10-30 18:29
The problem is that the new version requires `CAP_NET_RAW` to be able to run the DHCP server. However, it's unclear how to add this capability to our snap. We tried adding `network-manager` to plugs (and then slots), but nevertheless, we're facing this "operation not permitted" issue.

@popey could you please take a look, what we're doing wrong?

**Comment by Tloram** [comment] 2020-11-01 11:23
Just to confirm, also still getting the same issue.

**Comment by ameshkov** [comment] 2020-11-01 19:05
@ainar-g check this out, sounds relevant: https://bugs.launchpad.net/snappy/+bug/1823988

**Comment by ainar-g** [comment] 2020-11-05 13:14
<p>We're&#xA0;still
<a href="https://forum.snapcraft.io/t/how-to-have-cap-net-raw-added-to-our-binary/20941?u=a.garipov">figuring this out</a>,
sorry for&#xA0;the&#xA0;inconcenience!&#x2003;In&#xA0;the&#xA0;meantime,
if&#xA0;you update the&#xA0;snap package with&#xA0;(maybe
with&#xA0;<code>sudo</code>):</p>

<pre>$ snap refresh --channel edge --devmode adguard-home</pre>

<p>Does&#xA0;DHCP work&#xA0;again?  If&#xA0;it does, that&#xA0;might be
a&#xA0;workaround until&#xA0;we actually understand, why&#xA0;doesn't snap grant
us the&#xA0;required&#xA0;capabilities.</p>

**Comment by ainar-g** [comment] 2020-11-06 09:39
<p>@Tloram&#x2003;Can&#xA0;you please check the&#xA0;new solution I've described
above as&#xA0;well?</p>

**Comment by Tloram** [comment] 2020-11-06 09:49
@ainar-g Sure, will try this tonight and report back here.

**Comment by ameshkov** [comment] 2020-11-09 11:57
@Tloram did it help?

**Comment by Tloram** [comment] 2020-11-09 12:00
Sorry guys, I didn't get around to testing this yet (Covid related problems have got in the way).

**Comment by ameshkov** [comment] 2020-11-09 12:11
No problem, be safe!

We're almost sure that the issue is resolved in the "edge" channel, but you'll need to manually call `snap connect adguard-home:network-control` for now.

Please comment or reopen if this doesn't help.

**Closed by ameshkov** 2020-11-09 12:11 UTC
Labels: P3: Medium, bug

**Comment by marxjohnson** [comment] 2020-11-11 20:23
I can confirm than running the edge channel and manually connecting adguard-home:network-control has resolved the issue, thanks!

**Comment by ameshkov** [comment] 2020-11-11 20:48
@ainar-g have you contacted Snap Store people about autoconnect or should I do that?

**Comment by Tloram** [comment] 2020-11-12 11:06
@ameshkov   Ok so I have now tried both the edge channel (using the commands you showed to manually call the connect of network-control) and the latest standard release and it does not seem to be working on either for me I'm afraid.

The commands seem to execute ok on the cli, no errors but then in the Adguard GUI clicking on the disable/enable dhcp server does nothing, the button seems to be disabled...

**Comment by ainar-g** [comment] 2020-11-12 14:11
<p>@ameshkov&#x2003;<a href="https://forum.snapcraft.io/t/auto-connect-of-network-control-was-how-to-have-cap-net-raw-added-to-our-binary/20941">Yes</a>,
so&#xA0;far there was no&#xA0;response.</p>
