### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by gyCfjSnO** [AdguardTeam/AdGuardHome#3215] opened 2021-05-31 02:19 UTC
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Problem Description
Web page is very bright when viewing at night

### Proposed Solution
Have a dark mode to reduce brightness

### Alternatives Considered
N/A

### Additional Information
N/A

**Comment by Aikatsui** [comment] 2021-05-31 02:34
Duplicate of #613

**Closed** 2021-05-31 07:53 UTC
Labels: duplicate
