### ISSUE TITLE
Filter query log to show unfiltered requests

### ISSUE THREAD

**Issue by FrengerH** [AdguardTeam/AdGuardHome#1248] opened 2019-12-11 14:01 UTC
### Problem Description
At the moment when at the query log page you can choose to show all dns queries, or only show the filtered dns queries. I would love to also be able to show only unfiltered dns queries. This will make it easier to see which dns queries get through when a lot of filters are applied.

### Proposed Solution
Add a filter to the query log to show all unfiltered dns queries

### Alternatives Considered
-

### Additional Information
-

**Comment by ameshkov** [comment] 2019-12-15 20:24
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/882#issuecomment-511571911

**Closed by ameshkov** 2019-12-15 20:24 UTC
