### ISSUE TITLE
Using dns file No support for h3 protocol I don't see any h3 protocol in the ui panel.

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/AdGuardHome#6161] opened 2023-09-01 06:38 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

  v0.108.0-a.673+a325c9b6

### Action

no

### Expected result

Using dns files Support for h3 protocol You see the h3 protocol in the ui panel.

### Actual result

Using dns files Support for h3 protocol You see the h3 protocol in the ui panel.

**Comment by ainar-g** [comment] 2023-09-01 10:03
Duplicate of #5501

**Closed by ainar-g** 2023-09-01 10:03 UTC
