### ISSUE TITLE
All IPv6 interfaces missing in the "Setup guide" tab

### ISSUE THREAD

**Issue by pattyland** [AdguardTeam/AdGuardHome#1543] opened 2020-04-03 15:46 UTC
### Issue Details

* **Version of AdGuard Home server:**
  * v0.101.0
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * FRITZ!Box
* **Operating system and version:**
  * HassOS + Docker

### Expected Behavior
IPv6 address listet in "Setup guide" tab

### Actual Behavior
All IPv6 interfaces missing in the "Setup guide" tab

### Additional Information
The address seems to be missing since the last update. I found issue #1481 but this was only about link-local interfaces. At least one IPv6 address in container has Scope:Global.

Best Regards
Sören

**Comment by ammnt** [comment] 2020-04-03 16:48
https://github.com/AdguardTeam/AdGuardHome/issues/1481

**Comment by ameshkov** [comment] 2020-04-06 22:31
Looks like a duplicate of #1481 

Guys, could you please check the latest beta? As I understand, the fix is already there

**Closed by ameshkov** 2020-04-06 22:31 UTC
