### ISSUE TITLE
custom page block site

### ISSUE THREAD

**Issue by githubsharezone** [AdguardTeam/AdGuardHome#3856] opened 2021-11-19 15:42 UTC
why not appear a page site for domain blocked ?

**Comment by EugeneOne1** [comment] 2021-11-19 22:37
@githubsharezone, not quite sure what exactly do you mean?  Feel free to describe the problem or fill a template in any language you're comfortable in.

**Comment by ainar-g** [comment] 2021-11-22 12:08
Duplicate of #3176

**Closed** 2021-11-22 12:09 UTC
Labels: waiting for data
