### ISSUE TITLE
Reboot of Raspberry PI Breaks Ad-blocking

### ISSUE THREAD

**Issue by Irken-Skoodge** [AdguardTeam/AdGuardHome#421] opened 2018-10-23 00:41 UTC
### Steps to reproduce
1. Reboot Raspberry PI
2. See ads aren't blocked correctly and filter screen shows 2 filters with zero filter counts
3. Run sudo systemctl stop adguard-home
4. Run sudo systemctl start adguard-home
5. Ads are properly blocked and everything works fine

### Expected behavior
Reboot of Raspberry pi should continue blocking ads.

### Actual behavior
Upon reboot of my Rasperry pi the web ui works but on the filter page it shows the block lists AdGuard simplified domain and adaway as 0 rule counts. Then when browsing sites that used to have blocked ads, there are now ads.

<details><summary>Screenshot:</summary>

<img width="1231" alt="screen shot 2018-10-22 at 8 33 31 pm" src="https://user-images.githubusercontent.com/44384328/47327141-fd8a9d80-d639-11e8-8b5f-1c6af37e41da.png">

</details>

|   Description  |     Value    |
| -------------- | ------------ |
| AdGuard Home server:| v0.9-hotfix1
| DNS Setup:| Router
| Device:| Raspberry Pi 3 Model B
| Operating system and version:| MacOS Mojave

**Comment by kpaax** [comment] 2018-10-23 21:01
Hi there,
Confirming this on raspberry pi, reboot stops the service. After reboot there is no process /home/pi/AdGuardHome/AdGuardHome, needs to be started manually. 
Thanks

**Comment by planet0** [comment] 2018-10-23 21:35
Also confirming this is happening as well on Raspbian Lite on a Pi 3 Model B+. Issuing a `sudo reboot` on the Pi shows the web interface with 0 rules counted after starting. This wasn't happening earlier for me until today, perhaps the txt file has some recent typo or mistake update for it to show 0 @ameshkov?

![capture](https://user-images.githubusercontent.com/42660125/47391938-d8477d80-d766-11e8-8872-21ab83327fef.PNG)

**Comment by ameshkov** [comment] 2018-10-23 21:39
Reproduced. The root cause is that when Pi starts up there's no network connection, the filter update fails and instead of doing nothing it replaces the filters contents with an empty string.

**Comment by planet0** [comment] 2018-10-23 21:48
I used `sudo raspi-config` > `Boot Options` > `Wait for Network` > `Yes` at Boot in the past and this was working for me so it waited for an active network connection before booting. This allowed Pi Hole and AdGuard Home to function as expected after booting up.

Now I can't get this setting to stick, it keeps undoing my choice. This is probably why I'm only starting to experience this now. Going to figure out what has gone wrong.

**Comment by planet0** [comment] 2018-10-23 22:19
I can reproduce this now by simply stopping and starting the service via `sudo systemctl stop adguard-home` and `sudo systemctl start adguard-home`.

Refreshing after doing this produces this new error.

`Error: control/version.json | Couldn't get querylog from coredns: *url.Error Get https://adguardteam.github.io/AdGuardHome/version.json: dial tcp: lookup adguardteam.github.io on 0.0.0.0:53: read udp 127.0.0.1:46561->127.0.0.1:53: read: connection refused | 502`

**Comment by planet0** [comment] 2018-10-23 22:35
So this will sound odd, but by uninstalling AdGuard Home from the Pi - disabling the service and deleting the folder, and then unpacking it again from the tar.gz and reenabling the service -- AdGuard Home is working again as expected, including after rebooting it.

**Comment by kpaax** [comment] 2018-10-24 22:07
@planet0 there was your comment here, can't see it now
sudo raspi-config > Boot Options > Wait for Network > Yes at Boot 
anyway thanks! that helped to fix my issue - AdGuardHome process didn't start after reboot

**Comment by planet0** [comment] 2018-10-24 22:17
Thanks @kpaax, forgot to leave that here. I've continued to have no issues when setting the Pi to wait for network on boot, and since fresh reinstalling AdGuard Home.

Would be good to provide this step in the wiki for new installs, and eventually automate this setting for #425

**Comment by ameshkov** [comment] 2018-10-30 16:19
Resolved by https://github.com/AdguardTeam/AdGuardHome/commit/32d4e80c93cba5b3ef4bb96c79f7256b5cb4d913

**Closed by ameshkov** 2018-10-30 16:19 UTC
Labels: P2: High, bug

**Comment by DevEstacion** [comment] 2019-12-08 06:41
@ameshkov 

I was able to reproduce this by plugging the pi on the USB port of my router. Basically everytime i reboot the router it breaks the pi.

**Comment by ameshkov** [comment] 2019-12-08 18:37
@DevEstacion 

Could you please explain what exactly is broken?
Consider filing a new bug report and attach AGH logs there.
