### ISSUE TITLE
runtime error: invalid memory address

### ISSUE THREAD

**Issue by welcomereality** [AdguardTeam/AdGuardHome#4013] opened 2021-12-24 19:26 UTC
### Issue Details

* **Version of AdGuard Home server:**
     AdGuard Home, version v0.107.0
* **How did you install AdGuard Home:**
  * Installed from the script in the tutorial
* **Operating system and version:**
  *  Ubuntu 20.04.3 LTS

After installing it with the script, i can't even finish the setup properly, as i keep getting these errors: "Error: control/install/check_config | Network Error"

Here are the debug logs:

2021/12/24 22:22:41.273249 173974#28 [debug] web: plain: http: panic serving 192.168.1.75:6039: runtime error: invalid memory address or nil pointer dereference
goroutine 28 [running]:
net/http.(*conn).serve.func1(0xc0000f3680)
        net/http/server.go:1805 +0x153
panic(0xd0c120, 0x26cff80)
        runtime/panic.go:971 +0x499
github.com/AdguardTeam/AdGuardHome/internal/aghnet.closePortChecker(...)
        github.com/AdguardTeam/AdGuardHome/internal/aghnet/net_unix.go:14
github.com/AdguardTeam/AdGuardHome/internal/aghnet.CheckPort(0xe11e07, 0x3, 0xc00027c2b0, 0x10, 0x10, 0x50, 0x0, 0x0)
        github.com/AdguardTeam/AdGuardHome/internal/aghnet/net.go:203 +0x11c
github.com/AdguardTeam/AdGuardHome/internal/home.(*Web).handleInstallCheckConfig(0xc0002ca0e0, 0x21dfd50, 0xc0001d8380, 0xc00016a900)
        github.com/AdguardTeam/AdGuardHome/internal/home/controlinstall.go:109 +0x954
github.com/AdguardTeam/AdGuardHome/internal/home.ensure.func1(0x21dfd50, 0xc0001d8380, 0xc00016a900)
        github.com/AdguardTeam/AdGuardHome/internal/home/control.go:219 +0x214
github.com/AdguardTeam/AdGuardHome/internal/home.preInstall.func1(0x21dfd50, 0xc0001d8380, 0xc00016a900)
        github.com/AdguardTeam/AdGuardHome/internal/home/control.go:254 +0x50
net/http.HandlerFunc.ServeHTTP(0xc000096fa0, 0x21dfd50, 0xc0001d8380, 0xc00016a900)
        net/http/server.go:2050 +0x44
net/http.(*ServeMux).ServeHTTP(0xc000090040, 0x21dfd50, 0xc0001d8380, 0xc00016a900)
        net/http/server.go:2429 +0x1ad
github.com/AdguardTeam/AdGuardHome/internal/home.limitRequestBody.func1(0x21dfd50, 0xc0001d8380, 0xc00016a700)
        github.com/AdguardTeam/AdGuardHome/internal/home/middlewares.go:75 +0x27f
net/http.HandlerFunc.ServeHTTP(0xc000298378, 0x21dfd50, 0xc0001d8380, 0xc00016a700)
        net/http/server.go:2050 +0x44
net/http.serverHandler.ServeHTTP(0xc0002ca2a0, 0x21dfd50, 0xc0001d8380, 0xc00016a700)
        net/http/server.go:2868 +0xa3
net/http.(*conn).serve(0xc0000f3680, 0x21e2fd0, 0xc000248040)
        net/http/server.go:1933 +0x8cd
created by net/http.(*Server).Serve
        net/http/server.go:2994 +0x39b

### Expected Behavior
A successful installation

### Actual Behavior
networking errors

**Comment by ainar-g** [comment] 2021-12-24 19:28
Thanks for the report.  Looks like a duplicate of #3987.

**Closed by ainar-g** 2021-12-24 19:28 UTC
