### ISSUE TITLE
添加根据国家拒绝ip请求解析的功能

### ISSUE THREAD

**Issue by sym090701** [AdguardTeam/AdGuardHome#6285] opened 2023-10-07 06:58 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

我的服务器在公网 所以有一些不受我控制的访问来占用我的资源 但我无法批量封禁那些ip

### Proposed solution

通过geo库判断ip地址的地理位置义阻止他们的请求

### Alternatives considered and additional information

添加白名单ip

**Comment by fernvenue** [comment] 2023-10-08 09:17
You should do this on your firewall, not AdGuardHome itself.

**Comment by ainar-g** [comment] 2023-10-12 15:26
Duplicate of #352

**Closed by ainar-g** 2023-10-12 15:26 UTC
Labels: feature request
