### ISSUE TITLE
scanning filter contents: bufio.Scanner:token too long 400

### ISSUE THREAD

**Issue by yyysuo** [AdguardTeam/AdGuardHome#6009] opened 2023-07-14 03:27 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux/AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.34

### Action

add filter use url:

https://raw.githubusercontent.com/BlueSkyXN/AdGuardHomeRules/master/all.txt

### Expected result

add filter successfully

### Actual result

error message:
scanning filter contents:
bufio.Scanner:token too long 400

![image](https://github.com/AdguardTeam/AdGuardHome/assets/10081071/2b2d98ee-f4b1-497b-9c7a-0b321cf34f56)

**Comment by yyysuo** [comment] 2023-07-14 03:29
https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad-pc.txt
Error: control/filtering/set_url | scanning filter contents: bufio.Scanner: token too long | 400

_Originally posted by @Rain113113 in https://github.com/AdguardTeam/AdGuardHome/issues/6008#issuecomment-1635135730_

**Comment by ppfeufer** [comment] 2023-07-14 06:13
See https://github.com/AdguardTeam/AdGuardHome/issues/6003

**Comment by ainar-g** [comment] 2023-07-14 10:07
Duplicate of #6003

**Closed by ainar-g** 2023-07-14 10:07 UTC
