### ISSUE TITLE
Query logs from Chart logs

### ISSUE THREAD

**Issue by Zarawee** [AdguardTeam/AdGuardHome#3843] opened 2021-11-14 13:23 UTC
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Problem Description

can we have like this dash board, to query the logs from the chart :

![image](https://user-images.githubusercontent.com/63293681/141682829-e00171a6-a6c6-4e26-83d5-413c1e990659.png)

currently I have this:

![image](https://user-images.githubusercontent.com/63293681/141682936-2bdadd9c-2e7f-4140-a19e-8954b94cb877.png)

**Comment by ainar-g** [comment] 2021-11-15 11:45
Duplicate of #3245

**Closed by ainar-g** 2021-11-15 11:45 UTC
