### ISSUE TITLE
Speed up query log filtering

### ISSUE THREAD

**Issue by Dubz** [AdguardTeam/AdGuardHome#3338] opened 2021-07-11 20:07 UTC
Running AdGuard via docker on a RasPi that's running Hypriot.

Querying DNS logs seems to take quite some time. As in, at least a few minutes, just to choose a preset filter. There's currently about half a million logs it's pulling, and only a few that are flagged as malicious/adult. Those are what I'm trying to pull essentially.
I think there should be some level of indexing for categories like this, since there is a much lower number of blocks overall. Mind you that I've only been running this for about a week or two.

Perhaps maybe increase log retention rules so blocks could be held longer than accepted? For instance, limit accepted domains to three days, while blocks could be thirty days. User customizable so we can decide based on our situation.

*I know different/better hardware would help some, but I don't think this should take that long to pull. I know I've had issues with querying PiHole on my gaming rig, experiencing similar results. I know that's a different platform entirely, but the overall performance is pretty similar with searching (so I'd imagine AdGuard would be slow as well).

**Comment by ainar-g** [comment] 2021-07-12 09:23
This is mostly a duplicate of #2290.  The current implementation of the query log has major disadvantages, one of which is performance whenever a lot of data has to be scanned, and we won't be able to do anything about that until we change the storage engine behind it.  I'll merge this issue into that one, if you don't mind.

**Closed by ainar-g** 2021-07-12 09:23 UTC
