### ISSUE TITLE
AGH is broken since v0.107.27

### ISSUE THREAD

**Issue by Vexz00** [AdguardTeam/AdGuardHome#5721] opened 2023-04-13 11:40 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

FreeBSD

### CPU architecture

AMD64

### Installation

Other (please mention in the description)

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v.107.26

#### What did you do?
Update to v0.107.27 or v0.107.28.

#### Expected result
AGH working just fine after an update from the web UI.

#### Actual result
AGH starts for like 10 seconds, query log loads but the statistics in the dashboard are empty. No queries are sent to the upstream DNS servers so DNS resolution doesn't work. Then the instance stops abruptly.

#### Screenshots (if applicable)
No screenshot necessary.

#### Additional information
I installed AGH on my OPNsense via the [community repo by mimugmail](https://forum.opnsense.org/index.php?topic=20827.0) and it's been working flawless until (including) v0.107.26. I always update AGH on the AGH's web UI. Since v0.107.27 the above explained behaviour happens, even with v0.107.28. I'm not sure whether this is an individual problem or a bug but reinstalling with a fresh configuration didn't help fix the problem.

Here's my `./AdGuardHome --verbose` output:
https://pastebin.com/S8byD9N1

**Comment by ainar-g** [comment] 2023-04-13 11:52
Another bug in the `github.com/ameshkov/dnscrypt` library, see #5557.  The panic seems to arise because the certificate with the provider name `2.dnscrypt-cert.dct-at1.` seems to have an invalid signature, so the immediate workaround is to exclude that stamp.  We'll fix the library soon.

/cc @ameshkov

**Comment by ainar-g** [comment] 2023-04-13 13:07
@Vexz00, can you please check the latest Edge version, `v0.108.0-a.523+d78a3edb`?

**Comment by Vexz00** [comment] 2023-04-13 14:40
Sorry, I'm only willing to use versions considered stable.

I removed that one entry from my upstream DNS servers list and now it's working fine with v0.107.28. Thanks for the help.

**Comment by ainar-g** [comment] 2023-04-13 16:59
I see.  We'll close this issue then.  Please reopen if the issue is still there in the next release.

**Closed by ainar-g** 2023-04-13 16:59 UTC
Labels: bug, P2: High, external libs

**Comment by AlexanderSalge** [comment] 2023-06-12 14:35
Still an issue on v0.107.31
