### ISSUE TITLE
Updating AGH Resets Upstream DNS to Default

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardHome#739] opened 2019-04-25 04:49 UTC
### Steps to reproduce

1. Download the new AdGuard Home binary.
2. Replace the old file with the new one.
3. Restart AdGuard Home.

<details><summary>Screenshot:</summary>

<img width="267" alt="Screen Shot 2019-04-25 at 14 45 38" src="https://user-images.githubusercontent.com/6005161/56710344-2d178100-6715-11e9-86d2-bbb4258dea10.png">
<img width="721" alt="Screen Shot 2019-04-25 at 14 45 52" src="https://user-images.githubusercontent.com/6005161/56710348-2ee14480-6715-11e9-80b2-d99623ea6a69.png">

</details>

### Expected behavior
Upstream DNS servers remain as they were in the version prior.

### Actual behavior
Upstream DNS server reverts to tls://1dot1dot1dot1.cloudflare-dns.com when using the browser GUI however the yaml displays what you used prior to update.

To fix the issue, AGH has to be restarted after being started after the update.

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| 0.95 hotfix
| How did you setup DNS configuration:| IoT
| If it's a router or IoT, please write device model:| Raspberry Pi 3 Model B
| Operating system and version:| Latest

**Comment by jslawler** [comment] 2019-04-25 04:54
Some additional on this.
I did not test whether restarting AGH via the restart command instead of the start command produced a different result.
To confirm, my order of steps was as following:
```
./AdGuardHome -s stop
<Replace AGH>
./AdGuardHome -s start
<issue occurance>
./AdGuardHome -s restart
```

**Comment by szolin** [comment] 2019-04-30 14:15
I couldn't reproduce the problem.

I had a v0.95 up and running with an upstream server `https://dns.adguard.com/dns-query`.
I stopped it with `-s stop`.
Then I downloaded v0.95-hotfix and replaced the binary.
I started it up with `-s start`.
And I still see `https://dns.adguard.com/dns-query` in UI.

Can you reproduce it on your side once again with the previous steps?  Or was it just a one time issue?
It's very unlikely that a new binary file could affect the settings because they are stored in a separate file.

**Comment by CWo42** [comment] 2019-04-30 15:23
I had a similar isssue seen on my machine - but there it was just "wrong" showing in web ui - yaml showed the correct and after a restart of agh the web ui also showed the correct

**Comment by ameshkov** [comment] 2019-05-21 09:11
Assigned to v0.97. We should see how the update from 0.95 to 0.96 will go.

**Comment by ameshkov** [comment] 2019-06-25 09:03
Hi all, any update on this issue?

**Comment by jslawler** [comment] 2019-07-04 18:57
> Hi all, any update on this issue?

Issue has not existed on my machine since the original report. I feel this can be closed.

**Comment by ameshkov** [comment] 2019-07-04 21:18
@jslawler thank you!

**Closed by ameshkov** 2019-07-04 21:18 UTC
Labels: cannot reproduce
