### ISSUE TITLE
DNS Block List Update

### ISSUE THREAD

**Issue by LS-Greenhorn** [AdguardTeam/AdGuardHome#5769] opened 2023-04-24 23:42 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
I would like to update my DNS block lists periodically to get the latest updates

#### Proposed solution
add an update option to add a job to update DNS block lists, every 15 days, 30 days, or 60 days

**Comment by LS-Greenhorn** [comment] 2023-04-24 23:43
new feature request to add a scheduled job to update DNS block list on a few different intervals

**Comment by talonric332** [comment] 2023-04-25 03:17
Why? There is already the options for an hour, 12 hours, 24 hours, 3 days or 7 days. If you want to wait a longer time to update the lists, you can disable the automatic filter updates and do it manually by going into the web UI every time you want to update them.

**Comment by ev4x** [comment] 2023-04-25 16:17
I would like to have something between 1hour to 12 hour maybe 6.

**Comment by ainar-g** [comment] 2023-08-22 11:02
Duplicate of #3044

**Closed by ainar-g** 2023-08-22 11:02 UTC
Labels: feature request
