### ISSUE TITLE
Sites misclassified as Adult 

### ISSUE THREAD

**Issue by rschuetzler** [AdguardTeam/AdGuardHome#5691] opened 2023-04-05 19:00 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Other (please mention in the description)

### CPU architecture

64-bit ARM

### Installation

Other (please mention in the description)

### Setup

On one machine

### AdGuard Home version

v0.107.26

### Description

AdGuard Home, installed on a Home Assistant Blue via the Home Assistant add-on. 

#### What did you do?
Visited the Dashboard in Adguard home to find that ~5% of DNS queries are "Blocked adult websites". These are spread throughout the day, with occasional spikes. Investigation revealed many domains mistakenly being classified as adult, when I think they should be on the tracker list. For example: 
- prov-lg.alphonso.tv
- metrics.icloud.com
- googleads4.g.doubleclick.net
- disney.my.sentry.io
- Many others

#### Expected result
These sites should probably be blocked by filters, and not classified as adult

#### Actual result
they are classified as adult.

#### Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/600775/230179090-9484ddbc-fe1b-4c35-826d-46748718384d.png)

![image](https://user-images.githubusercontent.com/600775/230179126-830b4041-d21a-44d0-8a6d-5b28ed4f479a.png)

**Comment by jaytay79** [comment] 2023-04-05 20:00
I have the same issue and was just coming here to report it. It started for me on 29th March 
<img width="291" alt="Screenshot 2023-04-05 at 20 59 44" src="https://user-images.githubusercontent.com/10902647/230194476-e0057d01-f385-40ea-b43e-f344b8e4ddd4.png">

**Comment by ameshkov** [comment] 2023-04-05 20:34
We're looking into it, thank you for reporting!

**Comment by ameshkov** [comment] 2023-04-05 20:46
The issue has been found, things will get back in a few hours when everything is updated.

The problem is that the parental control list on the server side got merged with the ad blocking list, hence we got into this.

**Closed by ameshkov** 2023-04-05 20:46 UTC
