### ISSUE TITLE
UI errors: only application/json is allowed | 415

### ISSUE THREAD

**Issue by pendie** [AdguardTeam/AdGuardHome#4970] opened 2022-09-29 17:16 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

ARMv7

### Installation

Custom port

### Setup

On a router, DHCP is handled by AdGuard Home

### AdGuard Home version

AdGuard Home v0.107.14

### Description

Error: control/querylog_clear | only application/json is allowed | 415

**Comment by ainar-g** [comment] 2022-09-29 17:21
Thanks for reporting!  We'll try to fix these ASAP.

**Comment by kiwilad-nz** [comment] 2022-09-29 17:27
Can confirm after updating in the last 5 minutes, this is preventing me from clearing the query log.

**Comment by 7ArxS2PrqAUF9Gom** [comment] 2022-09-29 20:26
Same issue after today's update.

**Comment by n7lmf** [comment] 2022-09-29 22:18
Same issue. Affects the "Use AdGuard browsing security web service", "Use AdGuard parental control web service", and "Use Safe Search" buttons as well.

**Comment by fengyuclub** [comment] 2022-09-30 02:12
Had the same problem just after the update

**Comment by pendie** [comment] 2022-09-30 02:20
how to disable adguard notification update

**Comment by Disqu3-mirOir-qt** [comment] 2022-09-30 04:01
@ainar-g 

probably because this:


![Screenshot_20220930-055345_1.jpg](https://user-images.githubusercontent.com/41585567/193187550-a0048cab-37e9-4171-b6eb-bd60b13251eb.jpg)


 
 
```
// WriteJSONResponse sets the content-type header in w.Header() to 
 // "application/json", encodes resp to w, calls Error on any returned error, and 
 // returns it as well. 
 func WriteJSONResponse(w http.ResponseWriter, r *http.Request, resp any) (err error) { 
         w.Header().Set(HdrNameContentType, HdrValApplicationJSON) 
         err = json.NewEncoder(w).Encode(resp) 
         if err != nil { 
                 Error(r, w, http.StatusInternalServerError, "encoding resp: %s", err) 
         } 
  
         return err 
 }
```

**Comment by Disqu3-mirOir-qt** [comment] 2022-09-30 04:02
w.Header().Set("Content-Type", "text/html")

maybe can solved issue

**Comment by hsdbql** [comment] 2022-09-30 04:22
I installed adguard home on an amd64-architected Debian 10 server, And ran into the same problem. So I installed it again on the Arm64 board, and it's still the same.

**Comment by eroxrodriguez** [comment] 2022-09-30 06:48
Same here. Cant deactivate Ad Guard. And some other featrures like a tik brings error messages. have updated and restarted my ubuntu. nothing helps.

**Comment by yyysuo** [comment] 2022-09-30 07:06
same problem.

**Comment by reggieds** [comment] 2022-09-30 09:01
Update to v0.107.14. Still have same issue.

**Comment by Hanfei799** [comment] 2022-09-30 09:31
same problem.

**Comment by ainar-g** [comment] 2022-09-30 12:23
This should be fixed on the Edge channel starting from version `v0.108.0-a.307+4d404b88`.  Please verify that the fix is working for you.  If it does, we plan to release it along with some other fixes.

**Comment by MiKing233** [comment] 2022-09-30 20:29
i got same problem on my armv8 devices, v0.107.14

**Comment by njiangk** [comment] 2022-09-30 23:59
same issue

**Comment by dimdedsec** [comment] 2022-10-01 03:28
Got same issue here, have updated core to
 v0.108.0-b.16 on amlogic s905x openwrt device but the problem is not fix yet.

**Comment by alfinauzikri** [comment] 2022-10-01 04:14
Same issue after today's update..

**Comment by SurikasZen** [comment] 2022-10-01 05:29
Same ussue with use safe search and use adguard parental control web services. When you try turn off you get Error.  Error: control/safesearch/disable | only application/json is allowed | 415

**Comment by fernvenue** [comment] 2022-10-01 07:17
> This should be fixed on the Edge channel starting from version `v0.108.0-a.307+4d404b88`. Please verify that the fix is working for you. If it does, we plan to release it along with some other fixes.

Tested, works fine :)

**Comment by 911realbeb** [comment] 2022-10-01 11:06
Same error here 
armv7l device , Version: v0.107.14
Error: control/querylog_clear | only application/json is allowed | 415

**Comment by Threefish4096** [comment] 2022-10-01 11:16
Same problem in beta 
![immagine](https://user-images.githubusercontent.com/43168947/193406897-69679f14-fc20-4c49-9d71-efbd0d886e66.png)
And in stable 
![immagine](https://user-images.githubusercontent.com/43168947/193406904-0bc03181-4373-41bb-9495-9630d6a1164b.png)

**Comment by tzaky** [comment] 2022-10-01 12:38
Same problem. CentOS 7: 
- Error: control/safebrowsing/enable | only application/json is allowed | 415
- Error: control/parental/enable | only application/json is allowed | 415
- Error: control/safesearch/enable | only application/json is allowed | 415

**Comment by hsdbql** [comment] 2022-10-01 14:17
Edge version v0.108.0-a.308+2ffea605 has fixed this issue, it works fine.

**Comment by castillofrancodamian** [comment] 2022-10-01 22:33
Here v0.107.14

**Comment by tzaky** [comment] 2022-10-01 22:48
FIX: Install the EDGE version: "curl -s -S -L https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -c edge"

**Comment by vger74656** [comment] 2022-10-02 00:04
> FIX: Install the EDGE version: "curl -s -S -L https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -c edge"

This doesn't work for me, it just asks me if I want to reinstall or uninstall, if I put -r at the end, it borks up the install and I had to recover from backups.

**Comment by tzaky** [comment] 2022-10-02 00:09
> > FIX: Install the EDGE version: "curl -s -S -L https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -c edge"
> 
> This doesn't work for me, it just asks me if I want to reinstall or uninstall, if I put -r at the end, it borks up the install and I had to recover from backups.

uninstall the current version and install the edge version.

**Comment by vger74656** [comment] 2022-10-02 02:49
Tried this, the web interface is still broken after edge installation, refuses to connect on port 3000

**Comment by Glassertje** [comment] 2022-10-02 09:47
> FIX: Install the EDGE version: "curl -s -S -L https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -c edge"

Thaks for the fix. Works like a charm.

@vger74656  I have a raspberry pi 4 and did it:

`sudo ./AdGuardHome -s uninstall`
`curl -s -S -L https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -c edge -r`

After that i could acces via port 3000 and configurate it again.
First i was getting an error but that was becourse i had no internet, so i first changed the dns after that in my router.

**Comment by lchagnoleau** [comment] 2022-10-02 20:04
Hi, I'm running AdGuard over Docker and docker-compose on Raspberry pi. I do not understand how I can fix it. If someone know it :)
Here is my conf:
```yaml
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    volumes:
      - ${CONFIG}/adguard:/opt/adguardhome/conf
      - ${DATA}/adguard:/opt/adguardhome/work
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 853:853/tcp
      - 853:853/udp
      - 784:784/udp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
      - 3000:80/tcp
```

**Comment by toby1991** [comment] 2022-10-03 04:31
+1 facing the same problem

**Comment by skl283** [comment] 2022-10-03 12:46
> This should be fixed on the Edge channel starting from version `v0.108.0-a.307+4d404b88`. Please verify that the fix is working for you. If it does, we plan to release it along with some other fixes.

any news to a new stable Release with these fixes?

**Comment by ainar-g** [comment] 2022-10-03 15:54
We're planning to release the fix to Beta and Release channels today.

**Closed by ainar-g** 2022-10-03 15:54 UTC
Labels: bug, P2: High, UI

**Comment by kiwilad-nz** [comment] 2022-10-03 17:43
Thank you guys! Appears to be working so far with no errors.

**Comment by lchagnoleau** [comment] 2022-10-03 18:41
Works for me too !
A lot of thanks :)

**Comment by Al4ndil** [comment] 2022-10-03 19:10
Works for me too :)
Thx a lot !

**Comment by arivelli** [comment] 2022-11-28 15:09
it isn't working for me neither (from a fresh HomeAsistant OS instalation)

**Comment by fernvenue** [comment] 2022-12-05 13:49
Still shows on v0.107.19 armv7.

**Comment by mhellsten** [comment] 2023-03-01 03:59
This is still broken on "Custom filtering rules page" in the latest and edge builds:
`Error: control/filtering/set_rules | only content-type application/json is allowed | 415`

**Comment by itsthejb** [comment] 2024-02-10 08:53
Just got this trying to clear stats on v0.107.44

<img width="390" alt="Screenshot 2024-02-10 at 08 53 14" src="https://github.com/AdguardTeam/AdGuardHome/assets/557391/22b5eb74-664e-490b-89e5-67d0666c9d57">

**Comment by RyderCragie** [comment] 2024-02-10 15:42
![Screenshot 2024-02-10 at 15 42 10](https://github.com/AdguardTeam/AdGuardHome/assets/69316364/9b76ef3f-2fb8-48d2-a202-783e725bba2f)
