### ISSUE TITLE
Add an edit option for DNS rewrites

### ISSUE THREAD

**Issue by TheCableGuy99** [AdguardTeam/AdGuardHome#5600] opened 2023-03-16 05:52 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
Fed up of re-adding changing dns records as I'm always editing them

#### Proposed solution
Just add an option to edit them rather than delete and re-create them

#### Alternatives considered
Hanging myself!

#### Additional information
And import and export for bulk edits would be nice as well

**Comment by ainar-g** [comment] 2023-03-16 10:36
Duplicate of #1577

**Comment by ainar-g** [comment] 2023-03-16 10:36
The current workaround for both easier editing and export/import is using rules with the [`dnsrewrite`/`dnstype` modifiers][1] either in a separate list or in your *Custom filtering rules* input.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#dnsrewrite

**Closed by ainar-g** 2023-03-16 10:36 UTC
