### ISSUE TITLE
Impossible to modify a DHCP static leases

### ISSUE THREAD

**Issue by AndrzejBurzynski** [AdguardTeam/AdGuardHome#6572] opened 2023-12-21 14:52 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS), AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

Promox VM

### Action

-

### Expected result

-

### Actual result

-

### Additional information and/or screenshots

 dsfsdf

**Comment by schzhn** [comment] 2023-12-21 17:37
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/6534
Fixed in the the [edge release](https://github.com/AdguardTeam/AdGuardHome/blob/master/README.md#test-unstable-versions).

**Closed by schzhn** 2023-12-21 17:37 UTC
