### ISSUE TITLE
[Feature Request] Dashboard Auto Refresh

### ISSUE THREAD

**Issue by jdpg2** [AdguardTeam/AdGuardHome#1840] opened 2020-06-28 15:56 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Problem Description

Dashboard doesn't auto refresh and required a click on "Refresh Statisics"

### Proposed Solution

Auto refresh the Dashboard on key events.. much like Pi-Hole does

**Comment by mHatsune** [comment] 2020-06-29 05:36
Duplicate of #1739

**Closed** 2020-06-29 11:54 UTC
Labels: duplicate
