### ISSUE TITLE
The Client Settings session does NOT work with ipv6

### ISSUE THREAD

**Issue by olivamauricio** [AdguardTeam/AdGuardHome#2216] opened 2020-10-23 15:13 UTC
Dear, I use the latest version of Adguard, but the blocking of clients on my local network does not work. On my local network I have the ipv4 and ipv6 stack working together. When I block websites for a client using ipv4, Ok, everything works. But as this client also has ipv6 and ipv6 always precedes consultations, I cannot perform blocking. Is there any alternative or magic to achieve blocking?

**Comment by ameshkov** [comment] 2020-10-23 15:18
Hi, what exact version do you use? Have you tried the latest beta version?

Also, how exactly do you block websites for a client? Could you please show the exact rule that you're using?

**Comment by olivamauricio** [comment] 2020-10-23 17:43
Dear friend, how are you? I am using Version: 0.104.0-beta3. In fact what I wanted to say is that the block is not effective with mac address. In my local network I am using the DHCP v4 server from Adguard and DHCP v6 from the router. All with dynamic IPs, which makes blocking difficult. So I would like to use MAC, but it doesn't work.

How I do? In the Client Settings section, I add a host to the list and place the MAC ADDRESS and ask to block specific services like Youtube, Netflix, etc.
The service only works when I put the ipv6 address, something that is impossible due to constant changes.

**Comment by olivamauricio** [comment] 2020-10-23 17:50
[https://drive.google.com/file/d/15nkd3DcnwHy22wo-ol1Il3r2i6asBVCg/view?usp=sharing](url)

**Comment by ameshkov** [comment] 2020-10-26 23:20
Okay, now I got it.

But why don't you use the DHCP6 server of AdGuard Home?

**Comment by olivamauricio** [comment] 2020-10-27 17:48
Dear Andrey Meshkov, how are you?

Initially thanks for the reply. Well, why don't I use DHCP6 from AdGuard Home itself? Here on my local network my router, in the IPv6 settings, I can't disable the DHCPv6 client settings, so I don't use Adguard as a DHCPv6 server.

I even tried, putting the option "Pass Through" as "Internet Connection Type" on my router, but I couldn't get customers to access the Internet with the IPv6 address, it appears "no route". I ran a radvdump, configured radvd.conf and started the service, but customers are unable to access the Internet with ipv6.

After several unsuccessful tests, the way was to get everything back as it was before. Configure my router as a DHCPv6 server.

The only thing you would want would be to use Adguard to block some websites by their "MAC address". So I would not be held hostage if the client's address was ipv4 or ipv6. This function is fantastic, but it only works when I have a single IP stack working on the network. And another detail, it is not feasible to block by ipv6, precisely because the client uses several temporary version 6 IPs.

Thanks in advance for any proposal / help.

**Comment by ameshkov** [comment] 2020-10-28 08:21
Well, there's not much we can do.

If we implement #961, this may help. Actually, your issue looks like a duplicate of #961.

Please upvote it if you want us to make it sooner

**Closed by ameshkov** 2020-10-28 08:21 UTC

**Comment by olivamauricio** [comment] 2020-10-28 17:52
Perfect, I understand the need to use Adguard's DHCP server to efficiently filter a website and the inability to filter when DHCP is not used, the lack of synchronism that can occur when trying to filter websites by the MAC ADDRESS address, as you mentioned in the article # 961. But here is a question: why not use this lock in client settings only for clients using "DHCP static leases". This would not need an Adguard check and there would be no false positive, since it is the responsibility of the administrator user to use this feature.

It would be great to use mac address blocking using DHCP static leases

Here's the tip!
