### ISSUE TITLE
Error with adding static lease

### ISSUE THREAD

**Issue by pascalwinters** [AdguardTeam/AdGuardHome#3127] opened 2021-05-11 08:26 UTC
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.106.2
* **How did you install AdGuard Home:**
  * Docker

### Expected Behavior
DHCP leases would get added.

### Actual Behavior
DHCP leases aren't getting added...

### Screenshots
![Schermafbeelding 2021-05-11 102737](https://user-images.githubusercontent.com/69316923/117784192-92c6ff00-b243-11eb-9342-32835fa5f20e.png)

### Additional Information
The client is already exists in the DHCP leases

**Comment by ainar-g** [comment] 2021-05-11 12:21
Looks like the feature of turning dynamic leases into static has accidentally been impacted by some recent changes.  We'll fix this soon, thanks.

**Comment by ainar-g** [comment] 2021-05-13 13:06
This should be fixed on the `edge` channel as of revision c890f5c1.  Could you please check if the problem is gone?

**Comment by pascalwinters** [comment] 2021-05-13 16:16
@ainar-g I just checked it, and it works as expected. Good work!

**Closed** 2021-05-13 16:45 UTC
Labels: P3: Medium, bug
