### ISSUE TITLE
设置过屏蔽yotube后会一直屏蔽yotube视频，播放不了

### ISSUE THREAD

**Issue by bianhua123** [AdguardTeam/AdGuardHome#1506] opened 2020-03-24 09:26 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ArchiveBase** [comment] 2020-04-01 19:15
Duplicate of #1508

**Comment by ameshkov** [comment] 2020-04-02 18:48
这是重复的https://github.com/AdguardTeam/AdGuardHome/issues/1508

**Closed by ameshkov** 2020-04-02 18:48 UTC
Labels: duplicate
