### ISSUE TITLE
Feature request: Blocking a site by category

### ISSUE THREAD

**Issue by nitinjs** [AdguardTeam/AdGuardHome#7150] opened 2024-07-25 09:16 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

I want to block all sites by its category.

e.g. blocking all news sites or blocking all chat sites

[Categories](https://steveshank.com/images/a/048_01.png)

### Proposed solution

I am not sure how opendns has implemented this

### Alternatives considered and additional information

opendns

**Comment by ainar-g** [comment] 2024-07-25 11:31
Duplicate of #2230 and most likely ultimately needs to be done on the https://github.com/AdguardTeam/HostlistsRegistry level first.

**Closed by ainar-g** 2024-07-25 11:31 UTC
Labels: feature request, potential-duplicate
