### ISSUE TITLE
Adding dark mode for AdGuard.

### ISSUE THREAD

**Issue by HarryDotMYx** [AdguardTeam/AdGuardHome#4370] opened 2022-03-06 23:53 UTC
Hi, This is just my suggestion to put dark mode AdGuard. Hopefully this proposal is accepted by the community. Thank you.

**Comment by fernvenue** [comment] 2022-03-08 10:48
> Well, the UI is not our top priority at the moment, but we'll take this feature request into account once we start working on the final design. -- https://github.com/AdguardTeam/AdGuardHome/issues/613#issuecomment-469146714.

I think you should check first if someone has suggested.

**Comment by EugeneOne1** [comment] 2022-03-14 10:47
@HarryDotMYx, hello.  As @fernvenue correctly noticed, this is a duplicate of #613.

**Closed by EugeneOne1** 2022-03-14 10:47 UTC
