### ISSUE TITLE
Custom filter rules hosts old specified domain name ip address is invalid

### ISSUE THREAD

**Issue by GogogogoDAI** [AdguardTeam/AdGuardHome#5487] opened 2023-02-15 11:36 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Windows

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

  v0.108.0-b.26

### Description

I use the old-fashioned hosts method in the custom filter rules to make the domain name specified ip still invalid, and the corresponding address is intercepted ip

**Comment by ainar-g** [comment] 2023-02-15 12:06
Duplicate of #5226

**Closed by ainar-g** 2023-02-15 12:06 UTC
