### ISSUE TITLE
Allow Client names to be set based on MAC address even when DHCP is not enabled

### ISSUE THREAD

**Issue by developerbuzz** [AdguardTeam/AdGuardHome#6319] opened 2023-10-17 08:38 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

I have an external DHCP server which controls IP allocation to a number of VNETs within my homelab.  This is used to separate out and isolate the various application networks from end user traffic.

I have set up AdGuard to provide DNS and DNS rewriting facilities.  I have also added a number of key resources to the settings-> client settings using the MAC address to identify each device, however when I look at the top clients list on the dashboard the devices are  only showing their IP addresses rather than the 'Client name' as configured in the client settings section.

I would like to be able to identify resources via their mac address without having to assign static ip addresses and use Adguards DHCP facility.

### Proposed solution

Allow clients to be identified by mac address even when DHCP is not configured in Adguard.  This will allow me to quickly identify key resources that have no static ip address by a human readable name rather than by IP address.

**Comment by ainar-g** [comment] 2023-10-17 12:37
Duplicate of #961

**Closed by ainar-g** 2023-10-17 12:37 UTC
Labels: feature request
