### ISSUE TITLE
SSL for the webinterface

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdGuardHome#447] opened 2018-11-01 04:25 UTC
Can we have SSL for the webinterface just in case some guest wants to sniff someone logging into it?

**Comment by Bluscream** [comment] 2019-04-23 18:53
Isn't this kinda done now?

**Comment by ameshkov** [comment] 2019-04-24 08:30
Yeah, thx

Duplicate of #285

**Closed by ameshkov** 2019-04-24 08:30 UTC
Labels: duplicate
