### ISSUE TITLE
Add a option to see how much each individual filter blocked in Total

### ISSUE THREAD

**Issue by GR1Nx** [AdguardTeam/AdGuardHome#5523] opened 2023-02-21 17:19 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
To see what of my many filters is working and what is doing nothing so I can take them out/disable them to streamline the  DNS blocklist
#### Proposed solution
An easy way to see a summary of all my individual DNS block list filters total blocks
#### Alternatives considered
An information window on the dashboard to show what filters are blocking and what filters is doing nothing
#### Additional information
i have added a lot of DNS Blocklists Filters and i am not sure which ones work and which ones just sits there and does noting but add to the rule count

Thanks and Thank You 
PS sorry if you don't understand me, english is not my first language

**Comment by ainar-g** [comment] 2023-02-21 17:21
Duplicate of #4524

**Closed by ainar-g** 2023-02-21 17:21 UTC
