### ISSUE TITLE
Just add proxy

### ISSUE THREAD

**Issue by githubissocool** [AdguardTeam/AdGuardHome#5167] opened 2022-11-20 01:24 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
I know that there is already an issue about proxy but I cannot submit this request without checking all boxes.
My problem? Blocking youtube, twitch, and other ads with adguardhome which a dns is not enough. So the proxy comes in place. You guys mentioned something about a reverse proxy in the README. You even created a repo called gomitmproxy specifically for adguardhome. But my request is, just add it to the code! The proxy is only able to filter http since there is no generated cert. And I don't even know how to setup go and the gomitmproxy. You guys said you would add the reverse proxy feature 3 YEARS AGO!
#### Proposed solution

Edit the code so gomitmproxy is easy to setup with AdGuardHome. Also generate a certificate for the proxy

#### Alternatives considered
None available 
#### Additional information
None

**Comment by fernvenue** [comment] 2022-11-20 10:46
If you checked milestones, you will find that there are so many things dev teams need to do now. MITM proxy is not an easy feature, if you really need it in AdGuardHome, PR welcome.

**Comment by ainar-g** [comment] 2022-12-26 15:01
Duplicate of #1228

**Closed by ainar-g** 2022-12-26 15:01 UTC
