### ISSUE TITLE
Add custom Block page like PiHole

### ISSUE THREAD

**Issue by afi-dev** [AdguardTeam/AdGuardHome#3893] opened 2021-11-28 15:44 UTC
📌 I propose to add the fact that we can add a **custom blocking page** that we can modify in the configuration and replaced by an html page, when a dns request is blocked, it would be nice 👍, more intuitive 🤔 and easier to demonstrate than to display an error from the browser. 

Especially that would be very interesting because PiHole already offers it as demonstrated on this blog: [http://knowcitrix.com/pihole-custom-block-page](http://knowcitrix.com/pihole-custom-block-page). I also know that this is something totally feasible with Nginx Proxy Manager on the following github repo: [https://github.com/jc21/nginx-proxy-manager](https://github.com/jc21/nginx-proxy-manager). I'm really sure that it could add something more concrete to the project that is already Adguard Home by allowing to display a page that would indicate the reason of the blocking and that would be clear to the users

**Comment by ainar-g** [comment] 2021-11-29 11:48
Duplicate of #3176

**Closed by ainar-g** 2021-11-29 11:48 UTC
