### ISSUE TITLE
Implement Block MAC address list

### ISSUE THREAD

**Issue by Stanojoski** [AdguardTeam/AdGuardHome#6148] opened 2023-08-23 20:35 UTC
### Issue Details

I use heavily DHCP server from Adguard, I know it is not its primary function, but it works very well, but..
My TV box keeps getting an IP from my AdGuard DHCP server. It should get it from the ISP.

### Proposed solution

Create block MAC address list.
The MAC addresses on that list wont get IP address from DHCP.

**Comment by ainar-g** [comment] 2023-08-28 10:16
Duplicate of #4037

**Closed by ainar-g** 2023-08-28 10:16 UTC
