### ISSUE TITLE
Settings can’t be turned on

### ISSUE THREAD

**Issue by quintenbuijs2006** [AdguardTeam/AdGuardHome#5252] opened 2022-12-09 14:48 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [x] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

AMD64

### Installation

Other (please mention in the description)

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.17

#### What did you do?
Try to turn on some functions in genera settings like parental functions safe search etc. And clear statistics etc.
#### Expected result
That it turns on and works
#### Actual result
Doesn’t turn on and gives error
#### Screenshots (if applicable)
![21579654-96A9-4D02-B91F-7CF2E4A4539C](https://user-images.githubusercontent.com/61926657/206693167-1d2b7e72-6a24-43d0-8782-a93cda307b2a.png)

#### Additional information
Homeassistant install

**Comment by ainar-g** [comment] 2022-12-09 14:56
Duplicate of #5116

**Closed by ainar-g** 2022-12-09 14:56 UTC
