### ISSUE TITLE
[BUG] DNS blocklists - last time updated

### ISSUE THREAD

**Issue by Onepamopa** [AdguardTeam/AdGuardHome#2208] opened 2020-10-21 16:59 UTC
### Prerequisites
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details
Last time updated field updates the date, even though the site/list is unreachable (404):
Working example: https://hosts-file.net/ad_servers.txt
Last time updated: 21 October 2020, 19:58

@ the log:
2020/10/21 19:58:36 [info] Got status code 404 from URL https://hosts-file.net/ad_servers.txt, skipping
2020/10/21 19:58:36 [info] Failed to update filter https://hosts-file.net/ad_servers.txt: got status code != 200: 404

* **Version of AdGuard Home server:**
Latest
* **How did you setup DNS configuration:**
System
* **If it's a router or IoT, please write device model:**
System
* **Operating system and version:**
Windows 10 2004

### Expected Behavior
Error shown?

### Actual Behavior
Date updated

### Additional Information
None

**Comment by ameshkov** [comment] 2020-10-22 10:35
This is intended, we use this field to avoid checking blocklists updates too often.

We'll need to add a different field for that and this, surprisingly, is not that easy. Merged to #2075

**Closed by ameshkov** 2020-10-22 10:35 UTC
Labels: question

**Comment by KizunaH** [comment] 2020-10-24 13:32
Duplicate of #1791 ><#2075
