### ISSUE TITLE
AGH Windows permissions break randomly after latest version

### ISSUE THREAD

**Issue by vfxraven19** [AdguardTeam/AdGuardHome#7433] opened 2024-11-12 21:05 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

OpenBSD, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.54

### Action

The installation folder permissions break, and when I try to run a cmd of AGH's status, I get Access Denied. Same access denied if I try to stop the service. Even browsing to the install folder, all the ACL permissions break.

I have verified this on even a new installation.

### Expected result

The installation folder permissions break, and when I try to run a cmd of AGH's status, I get Access Denied. Same access denied if I try to stop the service. Even browsing to the install folder, all the ACL permissions break.

I have verified this on even a new installation.

### Actual result

The installation folder permissions break, and when I try to run a cmd of AGH's status, I get Access Denied. Same access denied if I try to stop the service. Even browsing to the install folder, all the ACL permissions break.

I have verified this on even a new installation.

**Comment by 4285f4** [comment] 2024-11-13 03:49
same here.

**Comment by 88keyz** [comment] 2024-11-13 04:44
Duplicate of [7400](https://github.com/AdguardTeam/AdGuardHome/issues/7400).

**Closed** 2024-11-13 20:12 UTC
Labels: duplicate
