### ISSUE TITLE
Make it possible to add entries for DNS rewrites in third-party filterlists

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#2172] opened 2020-10-10 20:46 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version (0.104.0-beta1)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.104.0-beta1
* **How did you setup DNS configuration:**
  * N/A
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4
* **Operating system and version:**
  * Raspberry Pi OS Bullseye 32-bit

### Expected Behavior
"DNS rewrites" is able to redirect IP addresses as well as domains to other domains. However, when it comes to third-party filterlists, only IP addresses can currently be redirected to domains through e.g. `123.45.67.89 example.org`.

I therefore propose making it possible for listmakers of subscribable lists to redirect domains to other domains, something like this:
```
redirect: 0.us.pool.ntp.org 0.no.pool.ntp.org
redirect: 1.us.pool.ntp.org 1.no.pool.ntp.org
redirect: 2.us.pool.ntp.org 2.no.pool.ntp.org
redirect: 3.us.pool.ntp.org 3.no.pool.ntp.org
```

### Actual Behavior
There are currently no apparent way to create third-party filterlists that contain domain-to-domain redirects of the sort seen in "DNS rewrites".

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/95664649-359e8a00-0b4a-11eb-9fbd-5cf43f5d90cb.png)

</details>

### Additional Information
My motivation for this request, is that I realised today after 16 months that domain-to-domain redirects was the only plausible way to prevent my Motorola and Lenovo phones from sending requests to `*.us.pool.ntp.org` 25 times per day despite me having been in Europe my entire life.

**Comment by ameshkov** [comment] 2020-10-11 18:32
Sounds like a duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/2102

**Closed by ameshkov** 2020-10-11 18:32 UTC
