### ISSUE TITLE
禁止指定的DNS服务器解析IPv6地址 / Forbid the specified DNS server to resolve the IPv6 address

### ISSUE THREAD

**Issue by yaozijin** [AdguardTeam/AdGuardHome#5138] opened 2022-11-12 10:29 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Description

在中国，一些本土的公共DNS服务器可能会对国外网站输出错误的IPv6地址，而向Google DNS之类的DNS在中国大陆速度不佳，所以我想仅让一部分的DNS服务器能解析出IPv6地址。

---------------------------------------------------------
In China, some local public DNS servers may output wrong ipv6 addresses to foreign websites, and DNS such as Google DNS is not very fast in mainland China, so I want to only allow some DNS servers to resolve IPv6 addresses。

**Comment by fernvenue** [comment] 2022-11-13 04:39
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/4489.

By the way, as [documentation](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#loading-upstreams-from-file) said, you can use [felixonmars/dnsmasq-china-list](https://github.com/felixonmars/dnsmasq-china-list) with AdGuardHome like [fernvenue/adguardhome-upstream](https://github.com/fernvenue/adguardhome-upstream) to accelerate internet in China, it will be work better.

**Comment by yaozijin** [comment] 2022-11-22 08:46
> #4489 的副本。
> 
> 顺便说一下，正如[文档](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#loading-upstreams-from-file)所说，你可以使用[felixonmars/dnsmasq-china-list](https://github.com/felixonmars/dnsmasq-china-list)和AdGuardHome，比如[fernvenue/adguardhome-upstream](https://github.com/fernvenue/adguardhome-upstream)来加速中国的互联网，它会更好地工作。

It maybe doesn't work in windows.

**Comment by fernvenue** [comment] 2022-11-22 08:56
> It maybe doesn't work in windows.

Actually, it works fine on Windows, AdGuardHome has `upstream_dns_file` feature on Windows also.

**Closed** 2022-12-09 12:32 UTC

**Comment by fernvenue** [comment] 2022-12-09 12:45
@yaozijin I don't think that's a better plan, If you read [this report](https://gfwatch.org/censored_domains), it's not hard to see that the number of censored domains is always increasing, and you only try to add them to the list after they are actually affected. This is obviously not a reasonable approach, and it is undoubtedly better for DNS behavior to be classified according to the region to which its Name Server belongs.
