### ISSUE TITLE
Ability to edit "DNS rewrites" IP entries

### ISSUE THREAD

**Issue by jitdor** [AdguardTeam/AdGuardHome#1577] opened 2020-04-13 07:06 UTC
I wanted to use Adguard Home's "DNS rewrites" function to redirect DNS requests to specific SNI proxies. However, once a rewrite rule is added, there is no easy way to edit it (which needs to happen when the SNI proxy IP changes). The only solution now is to remove all entries and re-enter them under DNS rewrites, or host an additional DNSmasq server serving those custom records and then specify it under the upstream DNS server in the `[/domain-to-proxy.com/]ip_of_dnsmasq` method.

It would be great if the rewrite rules' IP can be easily edited.

**Comment by Archive5** [comment] 2020-04-28 04:39
Duplicate of #1374

**Comment by ameshkov** [comment] 2020-04-28 23:11
@Archive5 let's keep this one as it got more upvotes

**Comment by ragnaroks** [comment] 2020-07-08 03:12
i think "DNS block list" item can add a field "ActionType",include "Block"/"Rewrite"

if the item is "Block",`||domain.com^` will return `0.0.0.0`

if the item is "Rewrite",`||domain.com^=>192.168.12.34`will return `192.168.12.34`

**Comment by ragnaroks** [comment] 2020-07-08 03:19
or no "ActionType",just try find `=>` to decide "Block"/"Rewrite"

**Comment by ragnaroks** [comment] 2020-07-08 03:50
![snipaste_20200708_114920](https://user-images.githubusercontent.com/7598199/86873592-3110a280-c111-11ea-866f-277f253a5870.png)

**Comment by ameshkov** [comment] 2020-07-08 07:28
But there's already "DNS rewrites", it seems natural to extend it, and not the blocklists.

**Comment by ZeroClover** [comment] 2020-09-01 10:32
Maybe load DNS rewrite entries from files as DNS Filter does? This will have a higher level of maintainability, especially when managing multiple AGH instances.

**Comment by ainar-g** [comment] 2021-06-03 14:50
We'll probably ship this functionality together with the new API and UI redesign.

**Comment by jrickter88** [comment] 2022-02-02 14:23
We really need the ability to edit the re-write dns entries we've made.

**Comment by jffz** [comment] 2022-07-06 07:27
I see that this was planned for 0.104.0, is there any news about this feature ?

**Comment by jrickter88** [comment] 2022-10-02 02:39
anything? please?

**Closed** 2023-07-03 13:30 UTC
Labels: feature request, P3: Medium
