### ISSUE TITLE
Requests count not sorting correctly when filtered.

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardHome#1286] opened 2019-12-21 13:08 UTC
### Issue Details
* **Version of AdGuard Home server:**
  * v0.100.6
* **How did you setup DNS configuration:**
  * IoT
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 3 Model B
* **Operating system and version:**
  * Raspian 10.2

### Expected Behavior
Request count is sorted in numerical order when filtered (0-9, or 9-0).

### Actual Behavior
Request count does not appear to be sorted in any logical order.

### Screenshots

<details><summary>Screenshot:</summary>

<img width="141" alt="Screen Shot 2019-12-21 at 11 07 00 pm" src="https://user-images.githubusercontent.com/6005161/71308325-b28b3680-2446-11ea-8305-bf68bf1f77ba.png">

</details>

### Additional Information
This occurs for all columns of the name "Request count"

**Comment by ameshkov** [comment] 2019-12-23 08:45
Duplicate of #1253

**Closed by ameshkov** 2019-12-23 08:45 UTC
