### ISSUE TITLE
Is it possbile to add an option/param to enable the time range control for the Hosts Blocklists

### ISSUE THREAD

**Issue by GreatMichaelLee** [AdguardTeam/AdGuardHome#4746] opened 2022-07-16 06:15 UTC
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Problem Description

It is incovinence that there is no time range control(allow/deny) for the host blocklists, so if once I enable it ,it will be applied all day until if I disable or remove it. In some case, I have to enable/disable those rules by day or night situation and seems for now there is no way to implement this. (if there is, please let me know).

### Proposed Solution

If it is possilbe that to implement an addition parameter to be parsed that which can control this custom filtering rules enable/disable regarding to the configured time range? like this
||google.com^$time='22:00-07:00'  --> by default it is all day, and if configured, then only the specified time is effective.

### Alternatives Considered

if it is possible that I can private define the "blocked service" to implement this is also ok. 

### Additional Information

NA

**Comment by ainar-g** [comment] 2022-08-24 17:13
Duplicate of #1203 and many other similar issues.  This is should at least partially be implemented in the v0.108 cycle.

**Closed by ainar-g** 2022-08-24 17:13 UTC
Labels: feature request
