### ISSUE TITLE
Stats get corrupted after flood of queries

### ISSUE THREAD

**Issue by cadusilva** [AdguardTeam/AdGuardHome#4358] opened 2022-03-04 11:51 UTC
### Issue Details
 * **Version of AdGuard Home server:**
   
   * v0.107.4
 * **How did you install AdGuard Home:**
   
   * GitHub releases
 * **How did you setup DNS configuration:**
   
   * System
 * **CPU architecture:**
   
   * ARM64/aarch64
 * **Operating system and version:**
   
   * Debian 11
 
 ### Expected Behavior
 Stats page working normally showing all the info it shows.
 
 ### Actual Behavior
From time to time the stats page shows zero everywhere and empty domains lists (most blocked, most queried, etc). When accessing the page at the time it happens, an error appears at the right bottom corner saying:
```
Error: control/clients/find?ip0=127.0.0.1&ip1=206.42.33.166&ip2=10.0.0.3&ip3=45.164.223.2&ip4=motog&ip5=joaouerj&ip6=131.159.24.242&ip7=179.190.172.16&ip8=220.180.241.26&ip9=177.25.155.98&ip10=177.25.153.160&ip11=177.25.150.57&ip12=154.202.55.217&ip13=177.25.153.142&ip14=45.205.48.180&ip15=185.249.221.238&ip16=183.90.186.240&ip17=177.25.156.157&ip18=177.25.144.182&ip19=154.198.205.174&ip20=45.205.35.196&ip21=156.229.9.224&ip22=154.198.219.21&ip23=177.25.153.187&ip24=177.25.144.89&ip25=177.25.150.41&ip26=10.0.0.1&ip27=177.25.153.233&ip28=177.25.159.130&ip29=177.25.159.162&ip30=191.47.16.69&ip31=177.25.153.174&ip32=177.25.155.148&ip33=177.25.144.221&ip34=177.25.153.216&ip35=177.25.156.1&ip36=177.25.159.132&ip37=177.25.155.166&ip38=177.25.145.82&ip39=177.25.151.167&ip40=177.25.150.32&ip41=88.80.186.137&ip42=177.25.156.159&ip43=177.25.153.172&ip44=177.25.155.73&ip45=177.25.145.50&ip46=177.25.157.85&ip47=14.1.112.177&ip48=170.106.176.49&ip49=177.25.150.119&ip50=131.159.25.7&ip51=146.88.240.4&ip52=103.203.59.3&ip53=209.141.45.192&ip54=39.129.8.129&ip55=45.83.67.25&ip56=177.25.156.143&ip57=129.250.206.86&ip58=174.138.40.30&ip59=162.142.125.133&ip60=71.6.232.7&ip61=141.22.28.227&ip62=27.98.224.20&ip63=184.105.139.117&ip64=64.62.197.37&ip65=45.79.15.228&ip66=37.44.239.30&ip67=159.89.194.175&ip68=202.112.238.56&ip69=177.25.156.77&ip70=185.180.143.142&ip71=185.180.143.73&ip72=162.142.125.212&ip73=54.173.29.204&ip74=185.180.143.76&ip75=146.88.240.12&ip76=141.212.123.193 | Network Error
```
AdGuard continues to work normally apparently and resolving names with other pages working also, but the stats page gets broken. My guess is after a flood of queries from a bunch of CN/HK/SG addresses, the stats info file gets corrupt somehow.

The last batch was repeatedly composed of queries like that:
```
{"T":"2022-03-04T02:39:59.960278275-03:00","QH":"microsoft.com","QT":"TXT","QC":"IN","CP":"","Answer":"APyBgAABABAAAAABCW1pY3Jvc29mdANjb20AABAAAcAMABAAAQAADR8AKyphcHBsZS1kb21haW4tdmVyaWZpY2F0aW9uPTBnTWVhWXlZeTZHTFZpR2/ADAAQAAEAAA0fAEVEZ29vZ2xlLXNpdGUtdmVyaWZpY2F0aW9uPXBqUE9hdVNQY3JmWE9aUzlqblBQYTVheG93Y0hHQ0RBbDFfODZkQ3FGcGvADAAQAAEAAA0fABsaZmcydDBnb3Y5NDI0cDJ0ZGN1bzk0Z29lOWrADAAQAAEAAA0fABsadDdzZWJlZTUxanJqN3ZtOTMyazUzMWhpcGHADAAQAAEAAA0fAEVEZ29vZ2xlLXNpdGUtdmVyaWZpY2F0aW9uPU0tLUNWZm5fWXdzVi0yRkdiQ3BfSEZhRWoyM0JtVDBjVEY0bDhoWGdwdk3ADAAQAAEAAA0fACEgcGJjcGN3ODRzZms3dzRuaG03ZHd5ZzJrM2d4MHQ0eHLADAAQAAEAAA0fAC4tZG9jdXNpZ249ZDVhMzczN2MtYzIzYy00YmQwLTkwOTUtZDJmZjYyMWYyODQwwAwAEAABAAANHwC+vXY9c3BmMSBpbmNsdWRlOl9zcGYtYS5taWNyb3NvZnQuY29tIGluY2x1ZGU6X3NwZi1iLm1pY3Jvc29mdC5jb20gaW5jbHVkZTpfc3BmLWMubWljcm9zb2Z0LmNvbSBpbmNsdWRlOl9zcGYtc3NnLWEubWljcm9zb2Z0LmNvbSBpbmNsdWRlOnNwZi1hLmhvdG1haWwuY29tIGluY2x1ZGU6X3NwZjEtbWVvLm1pY3Jvc29mdC5jb20gLWFsbMAMABAAAQAADR8AODdhZG9iZS1zaWduLXZlcmlmaWNhdGlvbj1jMWZlYTliNGNkZDRkZjBkNTc3ODUxN2YyOWUwOTM0wAwAEAABAAANHwAuLWRvY3VzaWduPTUyOTk4NDgyLTM5M2QtNDZmNy05NWQ0LTE1YWM2NTA5YmZkZMAMABAAAQAADR8AXVxhZG9iZS1pZHAtc2l0ZS12ZXJpZmljYXRpb249OGFhMzVjNTI4YWY1ZDcyYmViMTliMWJkM2VkOWI4NmQ4N2VhN2YyNGIyYmEzYzk5ZmZjZDAwYzI3ZTlkODA5Y8AMABAAAQAADR8AJSRkMzY1bWt0a2V5PTRkOGJueWN4NDBmeTM1ODFwZXR0YTRnc2bADAAQAAEAAA0fAFlYOFJQRFhqQnpCUzl0dTdQYnlzdTdxQ0FDcndYUG9EVjhadExmdGhUbkM0eTlWSkZMZDg0aXQ1c1FsRUlUZ1NMSjRLT0lBOHBCWnhteXZQdWp1VXZoT2c9PcAMABAAAQAADR8ARURnb29nbGUtc2l0ZS12ZXJpZmljYXRpb249MVRlSzhxME96aUZsNFQxdEYtUVI2NUprekhaMXJjZGdOY2NERnA3OGlUa8AMABAAAQAADR8AJSRkMzY1bWt0a2V5PTN1YzFjZjgyY3B2NzUwbHprNzB2OWJ2ZjLADAAQAAEAAA0fADw7ZmFjZWJvb2stZG9tYWluLXZlcmlmaWNhdGlvbj1md3p3aGJiendtZzVmemdvdGMyZ281MW9sYzM1NjYAACkQAAAAAAAAAA==","Result":{},"Upstream":"127.0.0.1:5300","IP":"156.229.9.224","Elapsed":1031547,"Cached":true}
```

 ### Additional Information
The upstream is Unbound  1.13.1. If possible, please provide an e-mail where I can forward the more sensitive info like query and stats file for analysis if needed.

**Comment by EugeneOne1** [comment] 2022-04-05 12:02
@cadusilva, hello and apologies for a late response.  To troubleshoot the issue we'd like to check your verbose log.  Could you please reproduce the issue and [collect it](https://github.com/adguardTeam/adGuardHome/wiki/FAQ#verboselog)?  You may send it to devteam@adguard.com with something like "Issue 4358" in the subject.  It'd also be really helpful if you attach the query log file as well and the corrupted `stats.db` file.

**Comment by cadusilva** [comment] 2022-04-06 10:53
hello @EugeneOne1, currently my installation is set to answer queries only from a limited list of CIDR ranges (from my country). Since then, I didn't see the problem surface again. I'll clear the list of CIDRs and wait to see if the problem comes back again. Also, there's already an e-mail that I sent some weeks ago that contains part of the info requested in your reply. As soon as the problem appears again, I'll send another e-mail. Thank you!

**Comment by cadusilva** [comment] 2022-04-07 12:26
Hello again, here's a follow-up: as soon as the CIDR list was cleared, the issue surfaced again and the e-mail with the files is on its way. Today I saw that the stats were corrupted again. The only catch is that the query log only contains the data from the last 6 hours as I forgot to expand the retention window. But I hope it helps anyway. Any extra step or additional info, just say the word.

**Comment by EugeneOne1** [comment] 2022-04-07 12:54
@cadusilva, we've received and investigating it, thanks.

**Comment by EugeneOne1** [comment] 2022-04-25 13:11
@cadusilva, hello again. Unfortunatelly, we can't reproduce the issue.  Could you please answer a couple of questions to shed some light on the problem:

1.  What kind of machine is running AGH?  Is it a router?
1.  What do you mean by "gets corrupt somehow"?  Did the problem occured strictly after the flood of queries?

Also, could you please collect the browser's logs next time you'll catch it?  This would really help up.  Thanks

**Comment by cadusilva** [comment] 2022-04-25 13:33
> @cadusilva, hello again. Unfortunatelly, we can't reproduce the issue. Could you please answer a couple of questions to shed some light on the problem:
> 
>     1. What kind of machine is running AGH?  Is it a router?
> 
>     2. What do you mean by "gets corrupt somehow"?  Did the problem occured strictly after the flood of queries?
> 
> 
> Also, could you please collect the browser's logs next time you'll catch it? This would really help up. Thanks.

Hello @EugeneOne1,

1) AGH is currently running in a Raspberry Pi 4B 8 GB RAM with the official Raspberry Pi OS x64 based on Debian 11.3.

2) This is because I'm not quite sure how the queries get corrupted, hence the "somehow". Initially, when this corruption first occurred, there was a flood of queries type `TXT` to `microsoft.com` from APAC IPs, but since then I'm not so sure how it keep getting corrupted after some time and who is to blame.

Currently, even limiting the CIDRs that can query my server to accept only IPs from Brazil isn't preventing the stats from being corrupted, as some foreing queries shows up in the stats.

All I know is, from time to time, when I access the AGH WebUI, everything is zeroed and there's an error message at the corner. At the moment there's no CIDR filtering in place, so I'm just waiting for the next time the stats get corrupted. Then I'll send the browser console logs to you guys.

This can be confusing and I'm not sure how it all happens, but it does happen. What I can send in the form of logs will be sent.

**Comment by cadusilva** [comment] 2022-04-26 02:52
Hello @EugeneOne1, I just sent a new e-mail with an also new set of files including the console log from Chrome. I noticed few minutes ago that the problem happened again so I immediately gathered the files and sent the new e-mail. Hope this helps. Thank you.

![image](https://user-images.githubusercontent.com/8684263/165210189-64db4656-5e51-4344-a7c3-b03f63940c23.png)

**Comment by EugeneOne1** [comment] 2022-04-26 10:13
@cadusilva, we've received the data, many thanks.  The issue seems kind of nontrivial, we'll dig further.

**Comment by cadusilva** [comment] 2022-05-30 20:41
> @cadusilva, hello again and apologies for the long wait. Are the sent logs has been recorded while the issue occured? And also if flushing the statistics fixes the issue for some noticable period of time?

Hello there! Yes, I set the verbose log on and waited for the problem to happen. I don't know if flushing the statistics from the webui fixes it, but I just delete the `stats.db` when the problem happens. It occurred again once or twice since the last post.

**Comment by EugeneOne1** [comment] 2022-08-04 16:34
@cadusilva, hello again and apologies for delayed response.  We've finally improved the concurrent logic in the statistics module to make it work with shared memory more carefully.  Could you please check the last build in the `edge` channel and tell if it works properly and doesn't spoil the database file?  Thanks.

FIY, our tests didn't show any significant performance losses relatively to the old version, but we'd like to get your feedback as well.

**Comment by cadusilva** [comment] 2022-08-04 16:54
Hello @EugeneOne1, no problem. I just installed version `v0.108.0-a.189+4293cf59` and will report back if the issue happens again. I'll keep an eye on the performance as well. Thank _you_!

**Comment by cadusilva** [comment] 2022-08-09 11:10
Bad news @EugeneOne1: it happened again.

![image](https://user-images.githubusercontent.com/8684263/183632808-f47804af-116b-4244-b782-3907fd251c14.png)

Yesterday everything was fine, then a few minutes ago I accessed the WebUI and the stats were corrupted again. Unfortunatelly, the verbose log wasn't enabled this time.

**Comment by EugeneOne1** [comment] 2022-08-09 12:06
@cadusilva, thanks for the time you're contributing.  We're going to investigate it further.

**Comment by cadusilva** [comment] 2022-08-09 12:11
> @cadusilva, thanks for the time you're contributing. We're going to investigate it further.

Thank _you_ Eugene for looking into it. I have now enabled verbose log so when it happens again I'll have more details for you guys to debug the issue.

**Comment by cadusilva** [comment] 2022-08-15 13:17
Hello @EugeneOne1, I've just sent another e-mail with a tarball containing everything including logs so you guys can take a look into the latest occurrence. Thank you!

**Comment by EugeneOne1** [comment] 2022-08-15 13:35
@cadusilva, we've received it and looking into, thanks.

**Comment by EugeneOne1** [comment] 2022-08-17 15:16
@cadusilva, hello.  We've made a few more improvements both to concurrent logic and to logging.  Those are included into the latest edge build (71b8e7513812ca76df00ad66b2f3be06cd3ea550).  We're sorry it takes so many iterations but could you please check if the issue occurs there?  In case it is, the verbose log is still appreciated.  Thanks again.

**Comment by cadusilva** [comment] 2022-08-17 15:25
> @cadusilva, hello. We've made a few more improvements both to concurrent logic and to logging. Those are included into the latest edge build ([71b8e75](https://github.com/AdguardTeam/AdGuardHome/commit/71b8e7513812ca76df00ad66b2f3be06cd3ea550)). We're sorry it takes so many iterations but could you please check if the issue occurs there? In case it is, the verbose log is still appreciated. Thanks again.

Hello there, I've just updated to `v0.108.0-a.203+71b8e751` and will keep watching to see if the issue happens again. The verbose log is also still running, and in the event of any new occurrence I'll send a new email and reply in here. For the time being, I'll also keep using the Edge release. Thank you!

**Comment by cadusilva** [comment] 2022-08-21 00:16
Hello @EugeneOne1, there's already another email on the way for you guys to check it out. Thank you.

**Comment by EugeneOne1** [comment] 2022-08-24 11:23
@cadusilva, hello again.  We're still working on it but I'd like to clarify few more things.  As far as I got it, the error sometimes appear while simple dashboard access.  What happens next?  Does reloading the page fix it or the statistics remain empty?

Honestly, I'm suspecting the frontend logic in the dashboard since it's quite heavy.

**Comment by cadusilva** [comment] 2022-08-24 11:33
> @cadusilva, hello again. We're still working on it but I'd like to clarify few more things. As far as I got it, the error sometimes appear while simple dashboard access. What happens next? Does reloading the page fix it or the statistics remain empty?
> 
> Honestly, I'm suspecting the frontend logic in the dashboard since it's quite heavy.

Hi there, yes, I noticed it too. Sometimes when I access the dashboard and for some reason left before everything loads, it may throw an error and "pretend" the stats were corrupted but in this cases a simple refresh fixes it and the stats are all there.

But when the real problem happens, tho, everything is already zeroed when I access the dashboard and there's the red error at the corner, just refreshing in this case does nothing to solve.

**Comment by EugeneOne1** [comment] 2022-08-24 12:44
>  ... just refreshing in this case does nothing to solve.

So restarting the AdGuard Home also doesn't help?  Are you reseting the statistics each time?

**Comment by cadusilva** [comment] 2022-08-24 12:46
> > ... just refreshing in this case does nothing to solve.
> 
> So restarting the AdGuard Home also doesn't help? Are you reseting the statistics each time?

That's right, once the problem happens, the only way for AdGuard to start counting stats again is to clear the statistics via General Settings page or to delete the stats db.

**Comment by cadusilva** [comment] 2022-08-25 15:03
hello @EugeneOne1, there's now another batch of files on the way for futher investigating. Thank you!

**Comment by EugeneOne1** [comment] 2022-08-25 15:40
@cadusilva, thanks, we appreciate your help.

**Comment by EugeneOne1** [comment] 2022-09-02 15:55
@cadusilva, hello.  FIY, we're still receiving your data and inspecting it.  A few more questions to clarify:

 *  Are these `stats.db` files suspected of being "corrupted"?  I mean, does AGH show zeroes when using those?
 *  Have you got some kind of proxy behind the AGH's web interface?

**Comment by cadusilva** [comment] 2022-09-02 16:06
> @cadusilva, hello. FIY, we're still receiving your data and inspecting it. A few more questions to clarify:
> 
>     * Are these `stats.db` files suspected of being "corrupted"?  I mean, does AGH show zeroes when using those?
> 
>     * Have you got some kind of proxy behind the AGH's web interface?

Hello Eugene,

- I guess I'd say they work just fine until the issue happens and then every statistic is zeroed in the dashboard and there's the red error at the corner. So as a layman I'd say the file somehow could get corrupted when the problem happens.
- Yes, my installation works behind `nginx`.

Here's the configuration currently used:

```server {
	listen					80;
	listen					[::]:80;
	server_name				dns.alto.win *.dns.alto.win;
	return 301				https://$host$request_uri;
}

server {
	listen					443 ssl http2;
	listen					[::]:443 ssl http2;
	server_name				dns.alto.win *.dns.alto.win;
	
	ssl_certificate				/etc/nginx/secure.d/alto/alto.pem;
	ssl_certificate_key			/etc/nginx/secure.d/alto/alto.key;

	brotli					off;

	location / {
		proxy_pass			http://127.0.0.1:8081;
		proxy_set_header		X-Forwarded-For		$proxy_add_x_forwarded_for;
		proxy_buffering			off;
		proxy_redirect			off;
	}
	
	location /dns-query {
		proxy_set_header		Host			$http_host;
		proxy_set_header		X-Real-IP		$realip_remote_addr;
		proxy_set_header		X-Forwarded-For		$proxy_add_x_forwarded_for;
		proxy_redirect			off;
		proxy_buffering			off;
		proxy_http_version		1.1;
		proxy_read_timeout		6s;
		proxy_connect_timeout		6s;
		proxy_pass			https://dns_doh_servers;
	}

	include					/etc/nginx/conf.d/error-pages.conf;
}
```

About `proxy_pass https://dns_doh_servers`, there's also `upstream dns_doh_servers { server 127.0.0.1:4430; }` in the `nginx.conf` file.

Thank you.

**Comment by EugeneOne1** [comment] 2022-09-02 22:16
@cadusilva, thanks for the info.  Actually, I meant the `stats.db` files which you sent us.  Does your AGH instance starts up when using them?  If yes, does it shows zeroes in the web UI?

**Comment by cadusilva** [comment] 2022-09-02 23:24
> @cadusilva, thanks for the info. Actually, I meant the `stats.db` files which you sent us. Does your AGH instance starts up when using them? If yes, does it shows zeroes in the web UI?

@EugeneOne1 oh, now I understood it better. Here's the outcome: I just replaced the `stats.db` from a working installation with the `stats.db` I sent you after the issue happened. When I restarted the AdGuard Home service, this was the result:

![image](https://user-images.githubusercontent.com/8684263/188245702-d512f18d-8bca-4e56-95b7-0c0fbaded507.png)

Everything was zeroed and there was the error bubble at the corner. Then I deleted the problematic `stats.db` and put back the file from the current working installation. Everything was back to normal once I restarted the AGH service.

**Comment by EugeneOne1** [comment] 2022-09-05 11:05
@cadusilva, could you please also try to access the Web UI directly (bypassing the Nginx) while using the same "bad" file?  If the issue reproduces?  If yes, if it reproduces within another browsers?

**Comment by cadusilva** [comment] 2022-09-05 12:14
> @cadusilva, could you please also try to access the Web UI directly (bypassing the Nginx) while using the same "bad" file? If the issue reproduces? If yes, if it reproduces within another browsers?

Sure, tonight I'll make the tests and when I get the results, I'll will post them here @EugeneOne1.

**Comment by cadusilva** [comment] 2022-09-06 01:32
Hello @EugeneOne1, I just did some tests and found interesting results. By the way, the issue just happened so I downloaded the "corrupted" installation and cleaned the zeroed statistics via dashboard so it started to count queries again.

Great, so next thing I did was to rename `stats.db` to `stats.db.bak` and to upload the "corrupted" `stats.db` file I had downloaded previously.

Then I stopped nginx and AdGuardHome services and changed the AGH ports so it would listen on 80 and 443, besides the other default ports for DNS over HTTPS, DNS over TLS and DNS over QUIC.

Next I restarted the AdGuardHome to apply the new port settings and to use the "corrupted" `stats.db` file. For my surprise, all the stats were back! Then I undone the port settings in the YAML file and started nginx again.

Then everything was zeroed. To be sure, I stopped nginx one more time and restarted AGH set to use ports 80 and 443 directly instead of being reverse-proxied by nginx. And there was all the stats from the "corrupt" `stats.db` file.

For closure, I did these steps for a third time and yes, the "corrupt" `stats.db` file works just fine when AGH dashboard is accessed directly (AGH uses ports 80 and 443) and shows as zeroed when nginx is the middleman.

Here are some pictures:

AdGuard Home directly:
![image](https://user-images.githubusercontent.com/8684263/188527350-c3c1f506-51ac-4e90-bbf9-c79620cff7c7.png)

AdGuard Home via nginx:
![image](https://user-images.githubusercontent.com/8684263/188527412-270dc36b-1a56-42b3-9870-e2cd6cc7bc2d.png)

**Comment by EugeneOne1** [comment] 2022-09-06 11:31
@cadusilva, it seems, we've finally found a source of the issue.  I'd say you may want to revisit your Nginx configuration.  I'm not really familiar with it, but we've received a couple of related issues (e.g. #4727).

Perhaps, you may configure Nginx to collect some logs and possibly let us see it so that we could enhance the documentation about using the reverse proxy.

**Comment by cadusilva** [comment] 2022-09-06 13:52
> @cadusilva, it seems, we've finally found a source of the issue. I'd say you may want to revisit your Nginx configuration. I'm not really familiar with it, but we've received a couple of related issues (e.g. #4727).
> 
> Perhaps, you may configure Nginx to collect some logs and possibly let us see it so that we could enhance the documentation about using the reverse proxy.

Hello @EugeneOne1, what kind of logs do you guys want? Currently there's already an error log going on. Would it suffice? Next time the issue happens, I'll send both AGH and nginx logs so you guys can investigate. I'm also not very familiar with nginx configs to pinpoint the problem and set things right but maybe with these logs a direction can be found.

Thank you.

**Comment by cadusilva** [comment] 2022-09-06 14:09
First thing I did was to change [my configuration](https://github.com/AdguardTeam/AdGuardHome/issues/4358#issuecomment-1235674294).

The line `proxy_pass	https://dns_doh_servers;` became `proxy_pass	http://127.0.0.1:4430;`. Also, in the AGH YAML file, I changed `allow_unencrypted_doh` to `true`, so nginx can handle the HTTPS stuff alone.

To test, I set Firefox to use encrypted DNS and everything works fine and quicker so far. By the way, as a result, AGH log doesn't see the query as encrypted anymore and shows it as "Plain DNS". But I think this is expected, as nginx is the one handling encryption right now and communicating with AGH without encrypting anything in `localhost`. Let's see what happens.

**Comment by cadusilva** [comment] 2022-09-06 15:54
@EugeneOne1 so these are the initial findings, it seems that most clients and the server itself don't go along with the changes in the configuration, including AGH reseting the connection, it seems. Firefox, for some reason, is one of a kind and doesn't complain.

**Comment by cadusilva** [comment] 2022-09-06 18:13
Based `[on this blog post](https://www.nginx.com/blog/using-nginx-as-dot-doh-gateway/)` by Nginx staff, I did some other changes.

**dns.conf:**
The new entry for `/dns-query` is as follows:

```
	location /dns-query {
		proxy_http_version		1.1;
		proxy_set_header		Connection "";
		proxy_cache			doh_cache;
		proxy_cache_key			$scheme$proxy_host$uri$is_args$args$request_body;
		proxy_cache_methods		GET POST;
		proxy_pass			https://dohloop;
	}
```

**nginx.conf:**
The `upstream` directive is now as follows:

```
	upstream dohloop {
		zone dohloop			64k;
		server				127.0.0.1:4430;
		keepalive_timeout		60s;
		keepalive_requests		100;
		keepalive			10;
	}
```

There's also this cache thingy but the specified folder remains empty.

```
	proxy_cache_path				/mnt/ram/nginx/doh_cache levels=1:2 keys_zone=doh_cache:10m;
```

I'll keep an eye now to see how everything works. Now the `proxy_pass` uses `https://` again, so there's currently no problem with clients.

**Comment by cadusilva** [comment] 2022-09-10 13:52
Hello @EugeneOne1, unfortunately the changes didn't solve the problem. I just became aware that it happened again. It always happens not too far beyond 100k queries. Should I send the files to the e-mail once more? Thank you.

**Comment by EugeneOne1** [comment] 2022-09-10 13:59
@cadusilva, hello.  Just to ensure, is it happened without Nginx proxy?  We'll dig further then.

**Comment by cadusilva** [comment] 2022-09-10 14:08
> @cadusilva, hello. Just to ensure, is it happened without Nginx proxy? We'll dig further then.

It happened with nginx as middleman, I cannot bypass nginx or the other sites will become offline. I was testing the new nginx settings to see if it'd solve the problem without taking nginx out of the equation.

**Comment by EugeneOne1** [comment] 2022-09-12 12:25
@cadusilva, I've looked through the Nginx docs came up with a few suggestions:

 *  the [large_client_header_buffers](http://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers) defaults to `4` buffers `8k` each.  Perhaps, setting it to something about `4 16k` may help;
 *  enabling [proxy_buffering](https://nginx.org/ru/docs/http/ngx_http_proxy_module.html#proxy_buffering) also may help, but the sizes of buffers should be chosen properly.

Also, I've just noticed you've mentioned the Nginx log.  Is it possible somehow to get the part of it with the error occurence?

**Comment by cadusilva** [comment] 2022-09-12 13:06
Hello @EugeneOne1, I've just applied your suggestions. Here are the relevant bits:

`nginx.conf`
```
	proxy_buffering				on;
	proxy_request_buffering			on;
	proxy_buffers				8 4k;
	proxy_buffer_size			4k; 
	proxy_busy_buffers_size			16k;
```

In this file there's also `proxy_set_header Early-Data $ssl_early_data;`. Do you think it may help break the stats when viewing them with nginx as middleman?

`dns.conf`
```
	location / {
		proxy_pass			http://127.0.0.1:8081;
		proxy_set_header		X-Forwarded-For		$proxy_add_x_forwarded_for;
#		proxy_buffering			off;
#		proxy_redirect			off;
	}

	location /dns-query {
		proxy_http_version		1.1;
		proxy_set_header		Connection "";
		proxy_set_header		Host			$http_host;
		proxy_set_header		X-Real-IP		$realip_remote_addr;
		proxy_set_header		X-Forwarded-For		$proxy_add_x_forwarded_for;
		proxy_cache			doh_cache;
		proxy_cache_key			$scheme$proxy_host$uri$is_args$args$request_body;
		proxy_cache_methods		GET POST;
		proxy_pass			https://dohloop;
	}
```

About the end of your last message, I sent an e-mail two days ago with a few files including the nginx log but I couldn't find myself any relevant bit about the error. I guess I'll check the log level and watch to see what happens now with the edits to the files.

Thank you.

**Comment by EugeneOne1** [comment] 2022-09-12 13:57
>  In this file there's also `proxy_set_header Early-Data $ssl_early_data;`. Do you think it may help break the stats when viewing them with nginx as middleman?

I'm afraid I can't tell for sure.  Actually, the main suspect for the moment is the `GET /control/stats` endpoint's API.  It intends the huge number of paramemters which significantly increases the URL length.

**Comment by cadusilva** [comment] 2022-09-15 10:31
> > In this file there's also `proxy_set_header Early-Data $ssl_early_data;`. Do you think it may help break the stats when viewing them with nginx as middleman?
> 
> I'm afraid I can't tell for sure. Actually, the main suspect for the moment is the `GET /control/stats` endpoint's API. It intends the huge number of paramemters which significantly increases the URL length.

@EugeneOne1 I'm still monitoring to see if the issue happens again. But I'm not sure if it will, as I am now running AdGuardHome in a machine way more powerfull than previous Raspberry Pi (now sold to someone else). It's now a Ryzen 5 3550H, soon-to-have 24 GB of DDR4 2400 MHz RAM.

If the problem doesn't come back, maybe the issue has to do with the RPi not being powerful enough to deal with this `GET /control/stats` thingy, alongside with a big list of clients (as it was and is my case).

I'll keep watching and will comment here if something new happens.

**Comment by EugeneOne1** [comment] 2022-09-15 10:45
@cadusilva, I'd be surprised if this was the actual cause, since the out-of-resources kind of problem usually causes issues is all parts of the system.  Although, extra usage data never harms, so you're always welcome to share your findings.

Besides, there is a quick way to check it out by simply replacing the stats and query log data files in the current setup, creating backups of the existing data beforehand.

**Comment by cadusilva** [comment] 2022-09-23 00:02
Hello @EugeneOne1, so far there's no new occurrences. I'm almost at 300.000 queries on record, but zero new issues. Maybe the number of clients and its CIDRs, blocklists and the weight of the dashboard are too much for the Raspberry Pi to handle when these three factors come together. It's just a theory.

**Comment by EugeneOne1** [comment] 2022-09-23 12:34
@cadusilva, I didn't recall if you've told already, but does Nginx runs on the same machine as AGH?

**Comment by cadusilva** [comment] 2022-09-23 12:36
> @cadusilva, I didn't recall if you've told already, but does Nginx runs on the same machine as AGH?

Yes, everything is in the same machine and nginx acts as a reverse proxy.

**Comment by ainar-g** [comment] 2022-09-29 14:58
If there were no new occurrences, I'd say that it was an HTTP proxy issue.  We'll close this issue, if you don't mind.

**Closed by ainar-g** 2022-09-29 14:58 UTC
Labels: bug, P3: Medium

**Comment by cadusilva** [comment] 2022-09-29 15:30
> If there were no new occurrences, I'd say that it was an HTTP proxy issue. We'll close this issue, if you don't mind.

It's okay, there's really no new occurrences so far. They were gone after I moved from a Raspberry Pi, 8 GB, SSD to a Ryzen 5 3550H, 16 GB RAM and NVMe (as of now). The setup is the same, with HTTP proxy and everything in between, but the hardware has changed to a much more powerful one and the problem is now gone.

Thank you guys for looking into it, if it ever happens again I'll let you know.
