### ISSUE TITLE
Supports out-of-order DNS request processing for DNS-over-TCP and DNS-over-TLS protocols

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#6524] opened 2023-12-10 13:43 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Response Reordering

[RFC 1035](https://www.rfc-editor.org/rfc/rfc1035) is ambiguous on the question of whether TCP responses may be reordered -- the only relevant text is in [Section 4.2.1](https://www.rfc-editor.org/rfc/rfc7766#section-4.2.1), which relates to UDP:

      Queries or their responses may be reordered by the network, or by
      processing in name servers, so resolvers should not depend on them
      being returned in order.

### Proposed solution

Proposed solution:
https://www.rfc-editor.org/rfc/rfc7766#section-7

**Comment by ainar-g** [comment] 2023-12-12 11:24
Duplicate of #6314

**Closed by ainar-g** 2023-12-12 11:24 UTC
Labels: feature request
