### ISSUE TITLE
v0.107.20 no longer recognizes enabled lists

### ISSUE THREAD

**Issue by timkgh** [AdguardTeam/AdGuardHome#5238] opened 2022-12-08 01:31 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

64-bit MIPS

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.20

### Description

v0.107.20 UI no longer recognizes lists that are already enabled

E.g. all Security lists are enabled but when I click "Add blocklist" none of the checkboxes are checked.

<img width="951" alt="image" src="https://user-images.githubusercontent.com/23507658/206333983-2bebea00-860e-4d70-a0ef-fef17e3c450a.png">

**Comment by ainar-g** [comment] 2022-12-08 10:46
Thanks for the report!  This is probably caused by the same change that fixed the URLs of the vetted blocklists.  We have changed the default lists to point to the same backup copies that AdGuard DNS uses, so for most blocklists you can just readd them or leave them as-is.

But the default lists' URLs haven't been properly updated, and we should fix that.  We'll try to roll out the fix to the Edge channel soon.

**Comment by ainar-g** [comment] 2023-01-27 10:12
The default configuration has been fixed in v0.107.21.  We've also added the way to fix the issue on older installations to the [release notes][1].

[1]: https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.21

**Closed by ainar-g** 2023-01-27 10:12 UTC
Labels: bug, P3: Medium
