### ISSUE TITLE
Query log: Allow for log export from UI

### ISSUE THREAD

**Issue by twcau** [AdguardTeam/AdGuardHome#1847] opened 2020-06-30 01:09 UTC
### Problem Description
At present, Query log shows paginated data from querylog.json.

However, there is no easy way (that I can find) to bulk extract the log data via the Web UI. To do this, you're going to have fun at the command line for your installation or device, and that's a hassle that people might just not be geared up for.

This means that if I want to perform some bulk analysis, i.e. de-duplicating the list to narrow down my focus for finding odd domains leaking data, it's going to take me a little longer to get that done.

### Proposed Solution
From the Query Log screen, offer a new functionality, being Download Query Log; accessed by pressing on a new button to the right of the existing on-page refresh button.

The functionality would transform the data within adguardinstallpath/data/querylog.json from JSON to CSV, then present the resulting file to the user for downloading to their device so they can do what they wish.

### Alternatives Considered
None identified.

### Additional Information
N/A

**Comment by SharpX2016** [comment] 2020-06-30 07:15
支持

**Comment by mHatsune** [comment] 2020-06-30 13:31
Duplicate of #1176 
See if this helps https://github.com/AdguardTeam/AdGuardHome/issues/1164

**Comment by ameshkov** [comment] 2020-07-02 11:59
Please upvote #1176 if you want it

**Closed** 2020-07-02 11:58 UTC
