### ISSUE TITLE
[Feature Request] Update selected filters manually

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardHome#820] opened 2019-06-07 17:29 UTC
Currently AdGuardHome update added filters frequently  [Edit:] and i noticed https://github.com/AdguardTeam/AdGuardHome/issues/641#issuecomment-518006293 (v0.99 milestone) described a option to disable it so i modified this feature request as mentioned on title.

**Comment by Aikatsui** [comment] 2020-11-17 18:40
Duplicate of #2000

**Closed** 2020-11-18 08:14 UTC
Labels: duplicate
