### ISSUE TITLE
Per client and per app blocks for scheduled time

### ISSUE THREAD

**Issue by ishanjain28** [AdguardTeam/AdGuardHome#1887] opened 2020-07-15 17:25 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

So, Right now adguardhome has a list of apps, One can block any of those apps for any(or all) clients. But, There is no way to automatically enable/disable(i.e. Schedule) those blocks for specific period of time. 

### Proposed Solution

Add another option so users can configure each block for each client by setting the Start/End Day and Time. Setting this for each client and each app may be tedious and complicate everything so, One approach I have in mind is to have profiles. 

A profile should be an independent entity that can be attached to any(or all) clients. Users can add any number of apps to a profile and then profile can be configured to allow/deny access to an app within the profile depending on the time of day. 

Since, The timezone I am in and the time zone in which adguard home is running, There should also be an option to configure the timezone. (I use UTC on my servers where adguard home is hosted and live in +0530). 

### Alternatives Considered

I do not have an alternative in mind. 

### Additional Information

None

**Comment by mHatsune** [comment] 2020-07-16 01:59
Duplicate of #951(#1692) and consider vote them.

**Comment by ameshkov** [comment] 2020-07-16 11:22
Closed as dup

**Closed by ameshkov** 2020-07-16 11:22 UTC
Labels: duplicate
