### ISSUE TITLE
Add beta/pre-release toggle for updater

### ISSUE THREAD

**Issue by MichaIng** [AdguardTeam/AdGuardHome#4828] opened 2022-08-09 04:05 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
A simpler way for users to switch to beta/pre-releases.

#### Proposed solution
A toggle in AGH GUI to have the updater upgrading to beta/pre-releases, resp. switch back to get stable releases offered.

#### Alternatives considered
A yaml config option would be an alternative.

**Comment by agneevX** [comment] 2022-08-09 06:29
For critical software such as this, it should not be that easy to upgrade to pre-releases.

**Comment by MichaIng** [comment] 2022-08-09 06:36
That is an argument. On the other hand, with a clear warning, it might lead to more testers for a safer/more stable final release.

Just a suggestion as a user on our forum came up with the question how to apply to beta 🙂. But you are right that for any production server, DNS is too critical for experiments.

**Comment by ainar-g** [comment] 2022-08-09 12:24
Duplicate of #2420

**Closed by ainar-g** 2022-08-09 12:24 UTC
