### ISSUE TITLE
Home Assistant is unable to control Adguard Home

### ISSUE THREAD

**Issue by apedance** [AdguardTeam/AdGuardHome#1910] opened 2020-07-23 12:24 UTC
### Prerequisites

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * AdGuard Home v0.103.0-beta3
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * pfSense
* **Operating system and version:**
  * Debian 10

### Expected Behavior
I am able to control Adguard Home within Home Assistant with hickups.
Hickup = [https://github.com/home-assistant/core/issues/36197](url)
### Actual Behavior
I can not control Adguard Home anymore within Home Assistant.

### Home Assistant report
The actual error Home Assistant is throwing:
[https://github.com/home-assistant/core/issues/38112](url)

### Screenshots
![error](https://user-images.githubusercontent.com/4264240/88285772-f3ef0780-ccef-11ea-8cec-1c4857bad7bb.jpg)

</details>

**Comment by ameshkov** [comment] 2020-07-23 12:28
I am not sure if this should be reported to us and not to Hassio.

@frenck is there any issue on our side or is there anything we can do to help with this?

**Comment by frenck** [comment] 2020-07-23 12:40
This is not an Hassio issue (please note, Hassio does not exist anymore, it is just Home Assistant now). This part is of the integration inside Home Assistant and should not have been reported in here. Sorry to have our issues being end up on your issues tracker @ameshkov.

I haven't played with the beta yet. I guess the version string returned by the API for the beta is none standard. When adding AdGuard to Home Assistant, it will do a version checked, to ensure the version you are running is compatible with what Home Assistant expects in terms of API.

Min version: <https://github.com/home-assistant/core/blob/dev/homeassistant/components/adguard/const.py#L10>

Version check: <https://github.com/home-assistant/core/blob/4001eabafa25f090bfa8eccb60603b00957e8407/homeassistant/components/adguard/config_flow.py#L81-L94>

This to prevent older version of AdGuard being used and ending up not working. The version comparison seems to fail for the beta. Probably it fails to parse the version number used in the beta.

**Comment by ameshkov** [comment] 2020-07-23 12:52
@frenck thank you!

Due to some CI changes "v" prefix in the version is not consistent.

We have it in the edge channel builds, but there's no prefix in beta and releases anymore.

We may deal with it later, but anyway, it'd be safer to strip it when doing versions comparison.

**Comment by frenck** [comment] 2020-07-23 14:47
Yeah, that is probably the root cause.

I've got some debug information in the issue @ the Home Assistant core, will be picking it up from there.

Feel free to close this issue, as this is not something you guys should be bothered with.

**Closed** 2020-07-23 14:48 UTC
