### ISSUE TITLE
Bug Limpar Registro Consulta

### ISSUE THREAD

**Issue by tanynel** [AdguardTeam/AdGuardHome#4984] opened 2022-10-03 12:44 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

x86

### Installation

Other (please mention in the description)

### Setup

On a router, DHCP is handled by AdGuard Home

### AdGuard Home version

v0.107.14

### Description

O que você fez?

Realizei a limpeza dos registros de consulta, apresentou "error: Control/querylog_clear | only application/Json is Allowed | 415 " depois da atualização v0.107.14 

#### Resultado esperado
Limpeza

#### Resultado real
error: Control/querylog_clear | only application/Json is Allowed | 415

#### Capturas de tela (se aplicável)
![image](https://user-images.githubusercontent.com/114696023/193579428-45e2619d-376b-4a34-bbb3-0f07272a97ef.png)

#### Informações adicionais

What did you do?

I cleaned the query logs, it showed "error: Control/querylog_clear | only application/Json is Allowed | 415 " after v0.107.14 update

#### Expected outcome
Cleaning

#### Actual result
error: Control/querylog_clear | only application/Json is Allowed | 415

#### Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/114696023/193579428-45e2619d-376b-4a34-bbb3-0f07272a97ef.png)

#### Additional Information

**Comment by ainar-g** [comment] 2022-10-03 15:09
Duplicate of #4970

**Closed by ainar-g** 2022-10-03 15:09 UTC
