### ISSUE TITLE
Unblock a Block Services for a Certain Time Period

### ISSUE THREAD

**Issue by xenstar** [AdguardTeam/AdGuardHome#3498] opened 2021-08-24 10:49 UTC
I have a feature request, can you add an option in Blocked Services, e.g we can allow certain services to be accessible for a certain period/time every day. Rather than block always.

e.g Facebook, we can set a period, it can be accessed 5 minutes, every two hours. Then we can browse it for 5 minute, then the service will be blocked.

**Comment by ainar-g** [comment] 2021-08-24 11:04
Largely a duplicate of #951 and #1203.

**Closed by ainar-g** 2021-08-24 11:04 UTC
