### ISSUE TITLE
Using api to set ipv6 range unexpectedly affect the ra_slaac_only and ra_allow_slaac settings

### ISSUE THREAD

**Issue by LinaChong** [AdguardTeam/AdGuardHome#2653] opened 2021-02-08 04:29 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [√] I am running the latest version
- [√] I checked the documentation and found no answer
- [√] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
 v0.105.0-beta.3
* **How did you install AdGuard Home:**
via the install script
* **How did you setup DNS configuration:**
Router
* **If it's a router or IoT, please write device model:**
Nano pi R4S
* **Operating system and version:**
Armbian 21.02.1 Buster with Linux 5.10.12-rockchip64

### Expected Behavior
setting ipv6 range doesn't affect the ra_slaac_only and ra_allow_slaac settings

### Actual Behavior
Setting unexpectedly affect the ra_slaac_only and ra_allow_slaac settings , making both of them false.

### Additional Information
My ISP gives me dynamic prefix, so i need to get my prefix and set the prefix via AdGuard Home api.
I have tried appending "ra_allow_slaac": true  to the json, but it was changed to false too.

**Comment by ameshkov** [comment] 2021-02-08 07:03
Could you please show how exactly do you use the API?

**Comment by LinaChong** [comment] 2021-02-08 09:37
> Could you please show how exactly do you use the API?

I call the api using curl.
`curl -u user:pw -H "Content-type: application/json" -X POST http://[::1]/control/dhcp/set_config -d '{"v6":{"range_start":"3::","lease_duration":7200, "ra_allow_slaac": true}}'`
the range 3:: is just for testing, the prefix was updated correctly. 
I keep only the "v6" key in my request, and it works well. Including other keys making no differences, I tried.

**Comment by ainar-g** [comment] 2021-02-08 11:33
Looks like a real bug to me.  Thanks for reporting!

**Comment by ainar-g** [comment] 2021-02-11 17:50
I've just pushed 2eb21ef, which should fix this issue.  Could you please update and see if that fix works for you?  Thanks!

**Comment by ainar-g** [comment] 2021-02-15 09:56
I'll close this issue for now.  Please feel free to reopen with more details if the issue isn't fixed.  Thanks!

**Closed by ainar-g** 2021-02-15 09:56 UTC
Labels: P3: Medium, bug
