### ISSUE TITLE
Block for tag not work in website

### ISSUE THREAD

**Issue by viniribeirossa** [AdguardTeam/AdGuardHome#1707] opened 2020-05-19 22:19 UTC
I can't block the **g1.globo.com** website in any way by tags. Everyone else but you

**Comment by ameshkov** [comment] 2020-05-19 22:21
What tags do you mean?

**Comment by viniribeirossa** [comment] 2020-05-19 22:29
Except the ip with the tag, but this site does not block

**||g1.com.br^$ctag=device_phone**

**Comment by ameshkov** [comment] 2020-05-19 22:30
Ah, got it.

Have you added a client that is marked with that tag?

**Comment by viniribeirossa** [comment] 2020-05-19 22:35
Yes

**Comment by viniribeirossa** [comment] 2020-05-19 22:43
![image](https://user-images.githubusercontent.com/57050698/82385646-f2137a00-9a08-11ea-82e8-abdd0b7f7996.png)

**Comment by s3frank** [comment] 2020-05-25 07:05
I appear to be having the same issue with ctag notation.
I have the following setting:

||aliexpress.com^$ctag=~user_admin|~user_regular

But it doesn't block anything no matter the client.
When I remove the entire ctag line the blocking works but without client filter.
I have multiple IPs assigned to the ctags.

**Comment by szolin** [comment] 2020-05-26 11:54
I can't reproduce the issue.
Please post section `user_rules:`  and `clients:` from your yaml file here.
You may also provide debug logs.  There should be something like this when a rule is applied:
> Filtering: found rule for host 'facebook.com': '||facebook.com^$ctag=~device_phone|~user_regular'

**Comment by s3frank** [comment] 2020-05-26 14:54
Here you go the content of yaml file. I am on version v0.102.0

user_rules:
- '# Blocking Amazon and AliExpress unless you are in the regular user category'
- '||aliexpress.com^$ctag=~user_admin|~user_regular'
- '||amazon.sg^$ctag=~user_admin|~user_regular'

My clients section is very large so I am just putting a few in there for your reference. I inserted these using the REST API as I drive my config from a google sheet that builds these calls in a bash script. I do not have per client upstreams for anyone. 

My rules are set to block and only allow if you are in admin or regular tag. However no matter where you are tagged you will always be allowed access.

I am NOT using your DHCP server, only DNS. I wonder if that has something to do with it?

Here is an example of my wife's phone where these website should be working.
- name: marije-phone
  tags:
  - user_regular
  ids:
  - 192.168.10.20
  use_global_settings: false
  filtering_enabled: true
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: true
  use_global_blocked_services: false
  blocked_services:
  - twitch
  - discord
  - origin
  - ok
  - vk
  - mail_ru
  - tiktok

**Closed** 2020-05-26 16:42 UTC
Labels: P2: High, bug

**Comment by s3frank** [comment] 2020-05-27 04:32
His sorry but can you let me know how I can test this for you and confirm if the fix is working? Not sure if there is a nightly build or something I can play with?

**Comment by szolin** [comment] 2020-05-27 07:31
It will be available in the next beta version, as soon as we build it.

**Comment by ameshkov** [comment] 2020-05-27 08:09
@s3frank 

> His sorry but can you let me know how I can test this for you and confirm if the fix is working? Not sure if there is a nightly build or something I can play with?

There are two options to test the master branch:

1. `edge` tag on Docker hub
2. `edge` channel on Snapstore
