### ISSUE TITLE
Don't display malware/phishing and adult graphs on dashboard if adguard web service disabled

### ISSUE THREAD

**Issue by vituperative** [AdguardTeam/AdGuardHome#2369] opened 2020-11-29 07:23 UTC
The graphs for malware/phishing and adult sites should be hidden if the Adguard web service feature is disabled. Additionally, the related general statistics entries should be removed.

**Comment by Aikatsui** [comment] 2020-11-29 20:00
Duplicate of #689

**Closed** 2020-11-30 10:35 UTC
Labels: duplicate
