### ISSUE TITLE
v0.107.54 cannot be updated to automatically and manually doing so sets wrong AdGuard folder permissions and also filters stop working

### ISSUE THREAD

**Issue by Arthur-Kenichi-Condino** [AdguardTeam/AdGuardHome#7439] opened 2024-11-15 07:39 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Windows, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.54

### Action

1. AdGuard can't be updated automatically on Windows, it fails

2. doing it manually succeeds, but the new AdGuard stable version sets wrong permissions and makes AdGuard unusable: it sets only Write permission in many files and folders, and the result is that the user cannot access the AdGuard folder anymore and the executable cannot be run on startup, nor through PowerShell: even with administrator privileges

3. if you set the right permissions, AdGuard runs once and resets to the wrong ones again

4. if you set permissions of full control for Administrators for everything except data and the yaml file, AdGuard runs but on an unstable mode: it doesn't filter DNS requests anymore

### Expected result

just a normal AdGuard update without it changing permissions in a too much restrictive way that causes the program to not be able to run, even with Administrator rights

### Actual result

AdGuard blocks itself from ever being executed again after the updated first run 

### Additional information and/or screenshots

Some users reported this issue:
https://www.reddit.com/r/AdGuardHome/comments/1gn4rjt/windows_failure_on_10754/?show=original
https://www.reddit.com/r/Adguard/comments/1gmyn38/adguard_home_after_update_cannot_access/

**Comment by Arthur-Kenichi-Condino** [comment] 2024-11-16 01:02
sorry if this looks like a duplicate of issue #7314, but the problem happens in this specific manner, so I started this new Issue. My AdGuardHome installation is located at C:\AdGuardHome; I'm the only user in my machine. The auto permission settings are broken to the point even the Administrators accounts can't start AdGuardHome; doing through services.msc or PowerShell causes Access Denied errors. Also, AdGuard blocks itself from running and/or reading its own files.

**Comment by 88keyz** [comment] 2024-11-16 01:25
Check out issue [7400](https://github.com/AdguardTeam/AdGuardHome/issues/7400).

**Comment by Arthur-Kenichi-Condino** [comment] 2024-11-16 01:35
> Check out issue [7400](https://github.com/AdguardTeam/AdGuardHome/issues/7400).
thank you, I think #7400 is not exactly the same, but it covers almost everything in my Issue. The only thing that is not mentioned is the item 4 in my Issue, but it is also permissions related, so maybe if 7400 has a fix, I think it'll fix this Issue too.

**Comment by tanmoumou252** [comment] 2024-11-16 11:09
Exact match, after the update last night, the computer did not restart.

Today, after restarting, the DNS is malfunctioning

Manually reopening the AdGuardHome service or checking files in the AdGuardHome installation directory will be denied

Removing the installation directory using `rd /s/q *path*` will show that some files are in use and cannot be accessed

Fortunately, there's a backup. I've rolled back to the previous version now

**Comment by EugeneOne1** [comment] 2024-11-25 11:57
Still looks like a duplicate of #7400.  We've introduced the feature switch for this, see https://github.com/adguardTeam/adGuardHome/issues/7400#issuecomment-2493996658.  @Arthur-Kenichi-Condino, please consider filing a new issue about DNS filtering, if the workaround described doesn't help.

**Closed by EugeneOne1** 2024-11-25 11:57 UTC
