### ISSUE TITLE
domains(s).localhome

### ISSUE THREAD

**Issue by Freebase394** [AdguardTeam/AdGuardHome#6052] opened 2023-07-27 22:34 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

Version:  v0.107.35

### Action

```sh
nslookup -debug -type=a 'www.google.com' '192.168.50.89'
```
RESULT:
PS C:\Users\MyUserName> nslookup -debug -type=a 'www.google.com' '192.168.50.89'
------------
Got answer:
    HEADER:
        opcode = QUERY, id = 1, rcode = NOERROR
        header flags:  response, want recursion, recursion avail.
        questions = 1,  answers = 2,  authority records = 0,  additional = 0

    QUESTIONS:
        89.50.168.192.in-addr.arpa, type = PTR, class = IN
    ANSWERS:
    ->  89.50.168.192.in-addr.arpa
        name = adguardhome.localhome
        ttl = 10 (10 secs)
    ->  89.50.168.192.in-addr.arpa
        name = adguardhome
        ttl = 10 (10 secs)

------------
Server:  adguardhome.localhome
Address:  192.168.50.89

------------
Got answer:
    HEADER:
        opcode = QUERY, id = 2, rcode = NXDOMAIN
        header flags:  response, want recursion, recursion avail.
        questions = 1,  answers = 0,  authority records = 1,  additional = 0

    QUESTIONS:
        www.google.com.localhome, type = A, class = IN
    AUTHORITY RECORDS:
    ->  (root)
        ttl = 2721 (45 mins 21 secs)
        primary name server = a.root-servers.net
        responsible mail addr = nstld.verisign-grs.com
        serial  = 2023072703
        refresh = 1800 (30 mins)
        retry   = 900 (15 mins)
        expire  = 604800 (7 days)
        default TTL = 86400 (1 day)

------------
------------
Got answer:
    HEADER:
        opcode = QUERY, id = 3, rcode = NOERROR
        header flags:  response, want recursion, recursion avail.
        questions = 1,  answers = 1,  authority records = 0,  additional = 0

    QUESTIONS:
        www.google.com, type = A, class = IN
    ANSWERS:
    ->  www.google.com
        internet address = 216.239.38.120
        ttl = 10 (10 secs)

------------
Non-authoritative answer:
Name:    www.google.com
Address:  216.239.38.120

### Expected result

I ask AGH to block some specific apps, Roblox, among others....

You would expect those apps to be blocked...

### Actual result

I try to block some services like Roblox, YouTube among others ... But for some reason they are not blocked because the DNS requests are this way as in the image below.

### Additional information and/or screenshots

What kind of request is this? 
What is the Cryptography category?
** These requests whenever they are made, they manage to evade network blocks!** 
Where and how do I find the device that forms this hostname?
And how do I kill all these requests through this type of requests?

![image](https://github.com/AdguardTeam/AdGuardHome/assets/19652056/e1539301-212e-4c4a-a294-72a15de343ba)

**Comment by ainar-g** [comment] 2023-07-28 09:44
It's a Windows' `nslookup` thing.  See <https://serverfault.com/q/74067/>.  Use `nslookup -debug -type=a 'www.google.com.' '192.168.50.89'` (N.B. the dot after `com`) or just use `dig`.

Duplicate of #4510

**Closed by ainar-g** 2023-07-28 09:44 UTC

**Comment by Freebase394** [comment] 2023-07-28 17:15
Thanks! 👏
