### ISSUE TITLE
May I ask when I can solve the problem of AdGuardHome running on fixom k3? 

### ISSUE THREAD

**Issue by zxlhhyccc** [AdguardTeam/AdGuardHome#937] opened 2019-08-17 04:31 UTC
At present, all versions cannot run on k3, because k3 CPU has no FBU, the architecture is arm_cortex-a9, and the smartdns cannot run on k3 at the early stage. Later, the binary compiled by the original author after switching the architecture can run perfectly on k3!

**Comment by zxlhhyccc** [comment] 2019-08-17 04:34
![K A$ME89SI7R}D5F(IY5S1R](https://user-images.githubusercontent.com/45259624/63206652-59ec0b80-c0eb-11e9-8cab-5027f53daf7a.png)
![JZT~P43UYXPO@LGLV@CGU J](https://user-images.githubusercontent.com/45259624/63206657-6a03eb00-c0eb-11e9-8d74-1d65954491a4.png)

**Comment by ameshkov** [comment] 2019-08-18 21:00
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/913

As I've said, we don't have access to such device, and we need help from anyone who has and can try compiling AGH with different flags.

**Closed by ameshkov** 2019-08-18 21:00 UTC
Labels: duplicate
