### ISSUE TITLE
Add link to "Query Log" result page

### ISSUE THREAD

**Issue by yegle** [AdguardTeam/AdGuardHome#1738] opened 2020-05-27 07:26 UTC
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

I came from PiHole and was spoiled by PiHole's web UI.

Specifically the web UI of PiHole has the following feature:
1. In the Top Client section, each client is a link to the log query page filtering down to that client
2. In the Top Blocked and Top Allowed domain section, each domain is a link to the log query page filtering down to that domain name.

### Proposed Solution

1. As a prerequisite: "Query Log" page should accept query string, e.g. `/logs?ip=127.0.0.1` and `/logs?domain=example.com&filtered=true`.
2. In `Top clients` section: each IP shoud be a link to `/logs?client=$IP`
3. In `Top queried domains` section, each domain should be a link to `/logs?domain=$DOMAIN`
4. In `Top blocked domains` section, each domain should be a link to `/logs?domain=$DOMAIN&filtered=true`.

### Alternatives Considered

n/a

**Comment by Archive5** [comment] 2020-05-27 07:47
Look like new features. those requested from AG last year 

Duplicate of #1368 > https://github.com/AdguardTeam/AdGuardHome/issues/1625 (v0.103)

**Comment by ameshkov** [comment] 2020-05-27 08:06
Yeah, seems to be a dup, #1625 coming soon

**Closed by ameshkov** 2020-05-27 08:06 UTC
Labels: duplicate
