### ISSUE TITLE
Scroll issue on mobile UI

### ISSUE THREAD

**Issue by uservictor** [AdguardTeam/AdGuardHome#2425] opened 2020-12-12 21:20 UTC
Hello, I am using the version 104.3 of AGH on Raspberry Pi. 

There is an scroll issue on the main page of AdGuardHome, if you try to scroll touching the statistic graph area then it dont work (red marked areas on picture).

It just work while touching the space between those chart boxes.

Maybe you can look on it.

![sketch-1607808565693](https://user-images.githubusercontent.com/56163305/101995377-b81e0400-3cc9-11eb-87a2-8aff05f3108e.jpg)

**Comment by Aikatsui** [comment] 2020-12-14 07:52
Duplicate of #2152

**Comment by ameshkov** [comment] 2020-12-14 07:59
We'll try to handle it in the re-designed version.

**Closed by ameshkov** 2020-12-14 07:59 UTC
Labels: duplicate
