### ISSUE TITLE
Auto-update Feature Fix

### ISSUE THREAD

**Issue by hl2guide** [AdguardTeam/AdGuardHome#4628] opened 2022-06-04 01:51 UTC
### Issue Details

* **Version of AdGuard Home server:**
  * v0.108.0-b.8
* **How did you install AdGuard Home:**
  * GitHub releases
* **How did you setup DNS configuration:**
  * System
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Windows 11 Pro 21H2

### Expected Behavior
Auto-update applies new version of AdGuard Home successfully.

### Actual Behavior
Auto-update fails to apply and suggests a manual update.

_No auto-update has succeeded for me for at least 6 versions._

### Screenshots

<details><summary>Screenshot:</summary>

![a](https://user-images.githubusercontent.com/17044982/171971930-0f0aeb77-7763-4098-8548-6fd4d63be233.jpg)

![1](https://user-images.githubusercontent.com/17044982/171971882-d188bcf4-d116-4b05-8930-ee5221b9c204.jpg)

</details>

### Additional Information
None

**Comment by Disqu3-mirOir-qt** [comment] 2022-06-04 06:15
not realy complex just replace binary take 15 second

**Comment by hl2guide** [comment] 2022-06-04 06:28
> 

nope it is:
- annoying
- manual
- requires Windows service to be stopped

**Comment by ainar-g** [comment] 2022-06-06 16:34
@hl2guide, can you please collect [verbose logs][1] of what happens when you try to update and either add attach them here or send them to devteam@adguard.com?  Thanks.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by hl2guide** [comment] 2022-06-07 01:25
@ainar-g will do, the next stable release will allow me to test this. I'll post then.

**Comment by ainar-g** [comment] 2022-09-07 14:01
@hl2guide, sorry for the long silence.  There have been quite a few fixes to  the autoupdate function recently.  Do you still experience the issues?

**Comment by hl2guide** [comment] 2022-09-07 18:32
> 

I'll test it in the next stable release.

**Comment by hl2guide** [comment] 2022-09-15 02:59
Seems resolved for me, last autoupdate finally worked 😀 @ainar-g

**Comment by ainar-g** [comment] 2022-09-15 11:47
Hooray!  Thank you for checking!  Marking as duplicate, since this seems to have been caused by some other issue that had been fixed.

**Closed by ainar-g** 2022-09-15 11:47 UTC
Labels: duplicate
