### ISSUE TITLE
When the domain name is used as the upstream, adguardhome will not retrieve the ttI of the upstream domain name after the TTL value of the domain name itself ends.

### ISSUE THREAD

**Issue by qingxiaoxinrou** [AdguardTeam/AdGuardHome#6566] opened 2023-12-20 07:36 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.796+4fc6bf50

### Action

udp://dns.example.com:5353
When using this kind of upstream, for example, when the TTL of the DNS. Example. Com is exhausted, adguardhone will not update the IP address of this domain name, unless you click the application button below again, you can get the latest IP of this upstream domain name. Can you make the upstream domain name comply with the TTL of domain?

### Expected result

I hope that when the upstream domain name IP is updated, adguardhome can synchronize the upstream IP address in time to request a query.

### Actual result

The IP corresponding to the upstream domain name has not been updated for a long time after the change of the upstream domain namThe IP corresponding to the upstream domain name is not updated for a long time after the upstream domain name is changed

**Comment by schzhn** [comment] 2023-12-20 10:15
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/6321

**Closed by schzhn** 2023-12-20 10:15 UTC
