### ISSUE TITLE
Able to Block requests by Clients CIDR / geoip

### ISSUE THREAD

**Issue by Barsovski** [AdguardTeam/AdGuardHome#6715] opened 2024-02-08 08:03 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

On my server there are 13.5 million spam requests just in the last few days to the servers cisco.com, atlassian.com, globo.com. And ~50k requests from normal users.
All spam requests come from an IP in Brazil. I added a user named SPAM with a dozen CIDRs for blocking requests by rule like 
`||*^$client='SPAM'`
But new IP ranges come in periodically and adding CIDRs to user SPAM takes some time. And most of the IP addresses from AS28126 list.
By the way, in Brazil, according to ip2location.com, there are 20746 CIDR ranges. I definitely don’t want to add this with my own hands.
The Adguard Home system really needs a locking system with ability to block requests by CIDR/IP from the downloaded list, or by geoip. 
And check clients IPs for blocking. 
With this we could more easily avoid participating in spam

If such a possibility already exists, please tell me how to do it)

### Proposed solution

The system user should be able to add blocking lists (from files with lists too) for requestst via CIDR/IP/AS, but not through the “Users” section, as I am forced to do now.

**Comment by NikolaiT** [comment] 2024-02-08 11:53
Shameless self promotion: https://ipapi.is/ is very good with IP reputation.

Usually, blocking by geolocation is a bad idea. Even blocking by ASN's, since you have too many false positives.

It is much better to block certain IP addresses or, if you have to as a last resort, certain inetnums/NetRanges (networks)

**Comment by ainar-g** [comment] 2024-02-08 14:19
Duplicate of #1487

**Closed by ainar-g** 2024-02-08 14:19 UTC
Labels: duplicate
