### ISSUE TITLE
从 v0.107.0-b.14 起，没有正确查询域名

### ISSUE THREAD

**Issue by ShuiHuo** [AdguardTeam/AdGuardHome#3946] opened 2021-12-16 00:29 UTC
I do not speak English, so I will use simplified Chinese for feedback

### Issue Details

* **Version of AdGuard Home server:**
  * v0.107.0-b.14
  * v0.107.0-b.15
  * v0.107.0-b.16 / RC1 
* **How did you install AdGuard Home:**
  * GitHub releases
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * Newifi-D2
* **CPU architecture:**
  * MIPS
* **Operating system and version:**
  *OpenWrt 21.02-SNAPSHOT r16335-4b0f87729c

### Expected Behavior
查询域名并返回正确的地址

### Actual Behavior
所有域名都变成了重写项

### Screenshots

<details><summary>Screenshot:</summary>

![2021-12-16_08-12](https://user-images.githubusercontent.com/7471938/146285350-33b5b1a8-83d8-41e8-8621-24e2cbcb28cc.png)

</details>

### Additional Information

v0.107.0-b.13 时是正常的，使用完全相同的配置，仅 AdguardHome 软件版本不同。

**Comment by two-dogs** [comment] 2021-12-16 02:24
i thought i would help, the translation from @ShuiHuo expected and actual behavior according to DDG is, 
expect: querying the domain name and returning the correct address 
actual: The domain name becomes a rewrite entry

**Comment by ainar-g** [comment] 2021-12-16 12:16
Thanks for the report!  It seems like the issue at hand is that if the `/etc/hosts` file contains invalid hostnames, in this case `*`, they become rules that rewrite everything.  We'll fix it in RC2.

**Comment by ainar-g** [comment] 2021-12-16 13:28
@ShuiHuo, should be fixed in version `v0.107.0-a.240+4be69d35` on the `edge` release channel.  Could you please check if this works for you?

**Comment by ShuiHuo** [comment] 2021-12-16 21:32
> @ShuiHuo, should be fixed in version `v0.107.0-a.240+4be69d35` on the `edge` release channel. Could you please check if this works for you?

Where can I download binaries

**Comment by ShuiHuo** [comment] 2021-12-16 22:02
https://static.adguard.com/adguardhome/edge/AdGuardHome_linux_mipsle_softfloat.tar.gz

`v0.107.0-a.240+4be69d35`

Custom filtering rules  are not controlled by the global protection button, and are filtered regardless of whether protection is enabled or disabled![Screenshot_20211217_055701](https://user-images.githubusercontent.com/7471938/146455310-0716b93d-f2a5-4fbc-a22b-980ab7113df1.jpg)

**Comment by ameshkov** [comment] 2021-12-17 08:44
> Custom filtering rules are not controlled by the global protection button, and are filtered regardless of whether protection is enabled or disabled

This is by design: #3356

**Comment by ShuiHuo** [comment] 2021-12-17 10:42
> > Custom filtering rules are not controlled by the global protection button, and are filtered regardless of whether protection is enabled or disabled
> 
> This is by design: #1558

How can I quickly switch the status of custom filtering rules on or off?

**Comment by ainar-g** [comment] 2021-12-17 10:59
@ShuiHuo, there are several ways:

1.  Uncheck the “Block domains using filters and hosts files” on the “Settings → General settings” page.  This will disable all filtering based on filtering lists and rewrites.

2.  Just comment them out.  The rules syntax supports comments with the `#` character.

3.  Make these rules apply only for clients by using the [`$client` modifier][1].

There isn't currently one flag to completely disable them, but there are related feature requests: #1765, #2551.

We'll close this issue for now, since the original problem seems to be resolved on the `edge` release channel.  Please feel free to ask questions on the Discussions page or open new issues about bugs.  Thanks.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#client

**Closed by ainar-g** 2021-12-17 10:59 UTC
Labels: bug, P2: High

**Comment by lex-obrien** [comment] 2022-05-19 07:25
Interesting side effect of this is that domains with "_"s are also ignored as well.  It makes sense as public domains cannot have underscores, but it was bothering me seeing all of those error messages in my logs.  I'll just change my host names, but I wanted to drop the note in case anyone else runs into this ;)
