### ISSUE TITLE
please add querylog.max_size like log.max_size

### ISSUE THREAD

**Issue by a904055262** [AdguardTeam/AdGuardHome#6139] opened 2023-08-26 07:44 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

The querylog can easily become very large and often fills up the memory of the router

### Proposed solution

Add querylog.max_size option to limit log file size

**Comment by ainar-g** [comment] 2023-08-28 09:38
Duplicate of #4284

**Closed by ainar-g** 2023-08-28 09:38 UTC
Labels: feature request
