### ISSUE TITLE
Per-client upstream not work if "Anonymize client IP" is enabled

### ISSUE THREAD

**Issue by MkQtS** [AdguardTeam/AdGuardHome#3888] opened 2021-11-27 13:04 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

There are two source DNS request IP in my network. One is `172.16.16.16#127`, another is `127.0.0.1#127` (127 is the correct port). I want to set different DNS upstreams for these two source. So I plan to set `172.16.16.16#127` as a client and appoint `tls://8.8.4.4:853` as the upsteram DNS.

If *Anonymize client IP* option is enabled, I can only set `172.16.0.0`, not `172.16.16.16`, as a client. When I set `tls://8.8.4.4:853` as the only upsteram DNS, DNS request from `172.16.16.16#127` still use other upstream DNS. If *Anonymize client IP* option is disabled, I can just set `172.16.16.16` as a client, and then the appointed upstream for `172.16.16.16#127` works well.

I don't know if there are some bugs with *Anonymize client IP* and clients seperated by IP address. If it's normal, not a bug, maybe you should add some tips under *Anonymize client IP*.

* **Version of AdGuard Home server:**
  * v0.107.0-b.15
* **How did you install AdGuard Home:**
  * GitHub releases
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * x86 computer
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * LuCI openwrt-18.06-k5.4 branch (git-21.322.62925-ea9b160)

**Comment by EugeneOne1** [comment] 2021-11-29 11:21
@MkQtS, hello and thanks for the report.  We can't reproduce the issue unfortunately.  What do you mean by "I can only set `172.16.0.0`"?  Are there any error messages appeared?  Also could you please provide some screenshots of the client's settings which are problematic.

The *Anonymize client IP* option is only used to mask the actual address in query log and statistics so it shouldn't affect processing of a request.

**Comment by MkQtS** [comment] 2021-11-29 13:23
Thank you for your response. I've disabled *Anonymize client IP* and set two clients. One is `127.0.0.1`, another is `172.16.0.0`, each one has only one upstream DNS. Pic 1 & 2 shows my settings.

In pic3, you can see all query are from `127.0.0.0` and `172.16.0.0`, Client`127.0.0.1` didn't catch any DNS request.

Also in pic3, the mouse pointer, request from `172.16.0.0` did not use `tls://9.9.9.9:853` as the upstream DNS server.

![pic1](https://user-images.githubusercontent.com/81752398/143875094-38b7b7d4-37c1-4163-962b-26a807fe7bad.png)
![pic2](https://user-images.githubusercontent.com/81752398/143875222-71eae153-dd64-4c4a-8a6d-50f2b9a4ff22.png)
![pic3](https://user-images.githubusercontent.com/81752398/143875271-11563f45-634e-4942-ac9a-d33641610a93.png)

**Comment by EugeneOne1** [comment] 2021-11-29 13:36
@MkQtS, well, this is an expected behavior.  As I mentioned earlier, the *Anonymize client IP* feature only affect the client's appearance in the query log and the statistics.  So if you want to specify an upstream for the client, the client itself should has the address from which actual requests are coming (I suppose it to be `172.16.16.16` in your case).  It's also [possible](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients#idclient) to specify the upstream for a whole subnet with CIDR notation.

I'll close the issue for now since it seems to be resolved.

**Closed by EugeneOne1** 2021-11-29 13:36 UTC
Labels: waiting for data

**Comment by MkQtS** [comment] 2021-11-29 13:55
@EugeneOne1, Understood. But since client `172.16.0.0` doesn't match requests from `172.16.16.16`, query log should not mark the request from `172.16.16.16` with the client `172.16.0.0`. It would make users confused.

**Comment by EugeneOne1** [comment] 2021-11-29 15:33
@MkQtS, such zero-tailed addresses aren't usually valid in regular networks since those are often interpreted as the address of the subnetwork itself.

**Comment by MkQtS** [comment] 2021-11-29 16:25
@EugeneOne1 , I got it. DNS request from `172.16.16.16` can be shown as `172.16.0.0`. But since the appointed upstream DNS for client`172.16.0.0` would not apply to `172.16.16.16`, I don't think it's appropriate to mark the requests **not from the client** as **from the client**. I mean that since the rules for the client were not efective for a request, we should not mark that request with the client's name in the query log.
