### ISSUE TITLE
AdGuard Home Default Filter Names

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardHome#690] opened 2019-03-29 23:25 UTC
As you can see from the AdGuardHome.yaml export below, only 1 of the 4 filters that come default with AdGuardHome have a name set.
I'd suggest adding a name for the remaining 3.
The list of names should be:

1. AdGuard Simplified Domain Names filter
2. AdAway default blocklist
3. hpHosts - Ad and Tracking servers only
4. MalwareDomainList.com Hosts List

```
filters:
- enabled: true
  url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
  name: AdGuard Simplified Domain Names filter
  id: 1
- enabled: true
  url: https://adaway.org/hosts.txt
  name: ""
  id: 2
- enabled: true
  url: https://hosts-file.net/ad_servers.txt
  name: ""
  id: 3
- enabled: true
  url: https://www.malwaredomainlist.com/hostslist/hosts.txt
  name: ""
  id: 4
```

**Comment by furunos** [comment] 2019-03-30 07:30
I solve this problem with the following code:

```
--- AdGuardHome/filter.go.orig
+++ AdGuardHome/filter.go
@@ -236,7 +236,9 @@
 
 			log.Info("Updated filter #%d.  Rules: %d -> %d",
 				f.ID, f.RulesCount, uf.RulesCount)
-			f.Name = uf.Name
+			if uf.Name != "" {
+				f.Name = uf.Name
+			}
 			f.Rules = uf.Rules
 			f.RulesCount = uf.RulesCount
 			f.checksum = uf.checksum
```

**Comment by adrianh-za** [comment] 2019-03-30 09:51
Maybe this is related to my bug #661

**Comment by ameshkov** [comment] 2019-04-01 08:37
Yeah, this is a duplicate of #661. 

We'll soon update the master branch, there are some bugs which are already fixed.

**Closed by ameshkov** 2019-04-01 08:37 UTC
