### ISSUE TITLE
Do not show 'port 443 is not available' error notification if encryption is not enabled

### ISSUE THREAD

**Issue by rfgamaral** [AdguardTeam/AdGuardHome#700] opened 2019-04-02 12:48 UTC
### Steps to reproduce
1. Install AdGuard Home on a system where port `443` is already in use.
2. Open AdGuard Home settings page.
4. Observe the red error notification with the message "Error: control/tls/validate | port 443 is not available, cannot enable HTTPS on it | 400".

### Expected behavior
If "Enable Encryption" option is disabled, do not show any error notifications related to unavailable ports specified on this section.

### Actual behavior
If "Enable Encryption" option is disabled, error notifications related to unavailable ports specified on this section are still shown even though the option is disabled and not being used.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/96476/55403235-4b8ec000-554d-11e9-9c87-11e3e4e8a67c.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| (e.g. v0.94)

**Comment by ameshkov** [comment] 2019-04-03 07:50
@szolin this should be relatively easy to fix, assigned to v0.95

**Comment by Karmylr** [comment] 2021-12-09 10:55
fixed?

**Comment by EugeneOne1** [comment] 2021-12-09 14:50
@Karmylr, yep.

**Comment by baoang** [comment] 2022-02-09 07:04
![librewolf_4laT1HJVDa](https://user-images.githubusercontent.com/17093525/153138766-36d17809-fb96-4cea-9d4b-8b2767255d04.png)

AGH v0.107.3
Debian Buster
Nginx reverse proxy

Seems it still pops out the alert.

**Comment by EugeneOne1** [comment] 2022-02-09 09:47
@baoang, what version of AdGuard Home are you using?

**Comment by baoang** [comment] 2022-02-09 10:54
Version: v0.107.3, as shown at the bottom of the page.

**Comment by mav808** [comment] 2022-02-17 12:02
@EugeneOne1 I'm also getting this popup error on a fresh install of v0.107.3.

**Comment by EugeneOne1** [comment] 2022-02-18 10:26
@baoang, @mav808, we've been able to reproduce it, thanks.  We'll fix it soon.

**Comment by baoang** [comment] 2022-02-18 13:54
> @baoang, @mav808, we've been able to reproduce it, thanks. We'll fix it soon.

My pleasure. Hope I can do more.

**Comment by ainar-g** [comment] 2022-04-08 16:34
@baoang, we've recently released a fix for this on the edge channel.  Could you please check if it works for you?

**Closed** 2022-04-13 13:33 UTC
Labels: bug, P4: Low

**Comment by BenChueh** [comment] 2022-08-01 10:50
hmm so which port should i forward from 443 to ?

**Comment by xliang76** [comment] 2024-03-12 14:12
Looks like this still happening in v0.107.45

**Comment by Monoboy4ik** [comment] 2024-05-16 11:28
hi!
have this too, adguard via docker on synology, built-in reverse-proxy on synology
![image](https://github.com/AdguardTeam/AdGuardHome/assets/157120967/0610bfb5-78ee-4434-bf5b-44cbe0851d59)

**Comment by levontumanyan** [comment] 2025-02-03 15:29
have the same issue why is this closed?

**Comment by Ahmad-Drak** [comment] 2025-03-04 20:53
same issue on Flint 2
