### ISSUE TITLE
DNS rewrites Add enable and disable option

### ISSUE THREAD

**Issue by luweijun1992** [AdguardTeam/AdGuardHome#6423] opened 2023-11-15 01:19 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

DNS rewrites Add enable and disable option

### Proposed solution

DNS rewrites Add enable and disable option

**Comment by ainar-g** [comment] 2023-11-15 10:53
Duplicate of #1765

**Closed by ainar-g** 2023-11-15 10:53 UTC
Labels: feature request
