### ISSUE TITLE
No unblock button for blocked domains (custom filtering rules and blocklists)

### ISSUE THREAD

**Issue by Aikatsui** [AdguardTeam/AdGuardHome#2437] opened 2020-12-14 14:37 UTC
v0.105.0-SNAPSHOT-e2738fdf

**Comment by ainar-g** [comment] 2020-12-14 18:58
<p>This&#xA0;could also be caused by the bug we've fixed in a2d39c81.</p>

**Closed** 2020-12-15 08:15 UTC
Labels: P3: Medium, UI, bug
