### ISSUE TITLE
Can I add the function to save the configuration?

### ISSUE THREAD

**Issue by panyichen48737** [AdguardTeam/AdGuardHome#6431] opened 2023-11-17 11:12 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Since I update my device so often, transferring the configuration is a hassle. I know I can find the configuration file in the directory in Ad Guard Home, but I need to connect the device to download the file, which is a hassle. Can I add the option to download the configuration file in the background of the page?

### Proposed solution

Added the option to download the configuration file in the background of the page.

**Comment by ainar-g** [comment] 2023-11-17 11:16
Duplicate of #1147

**Closed by ainar-g** 2023-11-17 11:16 UTC
Labels: feature request
