### ISSUE TITLE
无法添加黑名单

### ISSUE THREAD

**Issue by duckxx** [AdguardTeam/AdGuardHome#6018] opened 2023-07-15 19:01 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux/ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

107.34

### Action

在拦截列表后发现了一个为0的黑名单。
107.34版本以前是可以添加成功。
重新启用该列表后，提示错误。
重新添加也是提示该错误。
尝试将文件下载到服务器，依然无法添加。

https://raw.githubusercontent.com/E7KMbb/AD-hosts/master/system/etc/hosts

![IMG_20230716_025350](https://github.com/AdguardTeam/AdGuardHome/assets/116968444/fd8ad76d-d1bb-45bf-b8cb-74c9b2e33ec5)

### Expected result

成功触发，触发率很高。

### Actual result

经过本地修改文件。删除了提示的错误行。竟然添加成功了。

**Comment by duckxx** [comment] 2023-07-17 02:24
> 你在国内，你用加速工具，无效的问题

把添加成功后的截图看看？

**Comment by ainar-g** [comment] 2023-07-17 13:43
Duplicate of #6003

**Closed by ainar-g** 2023-07-17 13:43 UTC

**Comment by leon202405** [comment] 2024-06-03 05:55
![111](https://github.com/AdguardTeam/AdGuardHome/assets/169430756/c6374fa6-8bdf-45b9-8ddc-2dc113cd6dc4)
我的出现400错误，不知道从何入手解决，有高手指点一下么？

**Comment by leon202405** [comment] 2024-06-03 06:04
![image](https://github.com/AdguardTeam/AdGuardHome/assets/169430756/e99d2641-23e1-4993-9d50-8f6638100e01)
我手动下载到指定目录，再添加也提示错误。
I manually downloaded to the specified directory, and then added an error message
