### ISSUE TITLE
Filter Use and Popularity

### ISSUE THREAD

**Issue by rashidjehangir** [AdguardTeam/AdGuardHome#939] opened 2019-08-18 13:21 UTC
Hi Guys, it would be awesome to get stats on which filters are being used and what the count is. 

I have many filters installed and have no idea if some of them are overkill or not useful. Do multiple filter lists slow browsing down?

Thanks

**Comment by ameshkov** [comment] 2019-08-18 20:52
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/580

> I have many filters installed and have no idea if some of them are overkill or not useful. Do multiple filter lists slow browsing down?

Tbh, not really. The only problem is the memory usage.

**Closed by ameshkov** 2019-08-18 20:52 UTC
Labels: duplicate
