### ISSUE TITLE
Block button remaining even after blocked client and duplicate block entries

### ISSUE THREAD

**Issue by KizunaH** [AdguardTeam/AdGuardHome#2150] opened 2020-10-04 02:03 UTC
#### Issue Details

1. Block button remaining even after blocked client 
Go to top clients in dashboard and block a client then you'll able to see client still remain with block button 

2. Duplicate block entries
If you block it again then it add new entry one more time to disallowed client list

* See the enhancement related block/unblock clients https://github.com/AdguardTeam/AdGuardHome/issues/1808 
 Already clients management related features has in three places. 
   - Dashboard - top clients (block/unblock)
   - Access settings  - allowed/disallowed clients
   - Clients settings - clients and clients (runtime)

I guess it's not convinient to add one more place for clients then it's possible to add tabs under top clients as "Connected clients" and "Blocked clients" then it'll be easier for users to move between tabs and block/unblock clients.
However it's possible to implement something different design by combining above 2 or 3 sections related clients. Consider to address this issue rather than only fix above mentioned bugs.

v0.104.0-beta1 | Ubuntu

**Comment by ameshkov** [comment] 2020-10-04 21:37
> Block button remaining even after blocked client
> Go to top clients in dashboard and block a client then you'll able to see client still remain with block button
> Duplicate block entries
> If you block it again then it add new entry one more time to disallowed client list

These seem to be fixed in the current edge build

Regarding displaying blocked clients, merged it to https://github.com/AdguardTeam/AdGuardHome/issues/2150

**Closed by ameshkov** 2020-10-04 21:37 UTC
Labels: duplicate

**Comment by KizunaH** [comment] 2020-10-05 01:25
https://github.com/AdguardTeam/AdGuardHome/issues/2075

**Comment by KizunaH** [comment] 2020-10-08 12:49
>These seem to be fixed in the current edge build

No

**Comment by ameshkov** [comment] 2020-10-08 13:04
I can't reproduce it then. When I block it on the dashboard, it's changed to "unblock"

**Comment by KizunaH** [comment] 2020-10-08 13:34
> I can't reproduce it then. When I block it on the dashboard, it's changed to "unblock"

I checked https://github.com/AdguardTeam/AdGuardHome#test-unstable-version on ubuntu and latest edge build available on docker (2 days ago) 

v0.104.0-beta1-SNAPSHOT-78814064

**Comment by ameshkov** [comment] 2020-10-08 13:36
Could you record a video? I don't understand what could be the issue

**Comment by KizunaH** [comment] 2020-10-08 13:55
No, i can be explain.

1. Go to "Top clients" component on the dashboard and block any client then you should see that client still remain on same location and block button appear when hover mouse near it (not the unblock button).
2. Block the same client one more time and go to DNS settings > access settings > disallowed clients then you can be see duplicate entries in that box.

v0.104.0-beta1-SNAPSHOT-1a3d98d3

**Comment by KizunaH** [comment] 2020-10-08 14:36
I tested same version on windows 8.1

**Comment by ameshkov** [comment] 2020-10-08 14:37
@ArtemBaskal please check if you can reproduce this.
