### ISSUE TITLE
Requests count for clients with CIDR IP addresses

### ISSUE THREAD

**Issue by inkss** [AdguardTeam/AdGuardHome#1824] opened 2020-06-23 02:31 UTC
### Prerequisites

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

(●'◡'●)

### Expected Behavior

- 已经配置到客户端设置里的设备，依旧显示在 ‘使用 Adguard Home 但未存储在配置中的客户端上的数据’ 里。
- Devices that have been configured in the client settings are still displayed in ‘Data on the clients that use AdGuard Home, but not stored in the configuration’.

### Actual Behavior
- 使用子网配置的客户端列表，例如 `192.168.0.0/16` ，但是 `192.168.100.1` 并未统计在设备列表中（请求数之类的）。
- A client list configured with a subnet, such as `192.168.0.0/16`, but `192.168.100.1` is not counted in the device list (number of requests, etc.)

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31947043/85353800-a9853a00-b53b-11ea-98ad-27065c879064.png)
![image](https://user-images.githubusercontent.com/31947043/85353924-f23cf300-b53b-11ea-8b30-b271067edd8b.png)

</details>

### Additional Information
Content translation via Google Translate~

**Comment by ameshkov** [comment] 2020-06-26 13:00
The root cause of the issue is that you're using CIDR (IP range) to configure the client ID.

It seems the UI cannot properly calculate the requests count.

**Comment by bruvv** [comment] 2020-07-18 15:52
I am also missing this issue. Since I am not sure what the language is used here I made an issue but did close it. @ameshkov perhaps open mine since it is english and close this one?
This is mine: https://github.com/AdguardTeam/AdGuardHome/issues/1895

**Comment by mHatsune** [comment] 2020-07-18 17:38
No. every languages are better to use not only english. additionally above contain translation for each details with screenshot about the problem as well. In this cause, you can consider to install multi-language extension on web browser similar google translate.

**Comment by bruvv** [comment] 2020-07-20 12:12
Well if you have it writen in english it is most of the times a bitter better to read than have it translated from other sources ;) ps: since I degoogled most of my life I use deepl as a translator.

**Comment by ArtemBaskal** [comment] 2020-10-01 18:08
Duplicate https://github.com/AdguardTeam/AdGuardHome/issues/2037

**Closed by ArtemBaskal** 2020-10-01 18:08 UTC
Labels: P4: Low, bug
