### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by Iconology** [AdguardTeam/AdGuardHome#2205] opened 2020-10-20 19:16 UTC
Just a low-priority feature request. Is it possible to add a section where it shows per block lists how many queries it blocked. Same system as the `Top blocked domains for the last 24 hours` but for the block lists themselves in order to trim down active lists that either aren't preforming or haven't been used to block any requests.

Thank you for all your work.

**Comment by ameshkov** [comment] 2020-10-21 11:49
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/580

**Closed by ameshkov** 2020-10-21 11:49 UTC
Labels: duplicate
