### ISSUE TITLE
Custom Block Page

### ISSUE THREAD

**Issue by iptvcld** [AdguardTeam/AdGuardHome#7027] opened 2024-05-24 21:52 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

When setting an IP for the custom block page a nginx or Apache web server, clients get a message that the connection is not secure.  How can I configure the web server to work by just using an IP? I am willing to even import a cert for all home users just like nextdns and controlD

### Proposed solution

Provide detailed instructions on how this can be done on a web server or even on the same server that AGH is installed on.

**Comment by tjharman** [comment] 2024-05-25 04:02
This isn't really an AdGuardHome issue I'm sorry.  You can do something like [this](https://medium.com/@antelle/how-to-generate-a-self-signed-ssl-certificate-for-an-ip-address-f0dd8dddf754) - generate a certificate and install it on all PCs etc.  The problem is this is just how SSL works.  Even just [Googling this](https://www.google.com/search?q=generate+self+signed+certificate+for+ip+address) should give you enough details to do what you're after with a bit of reading and playing around.
  
I'm going to close this as a duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/5640

**Closed by tjharman** 2024-05-25 04:02 UTC
Labels: feature request

**Comment by iptvcld** [comment] 2024-05-25 20:35
thank you @tjharman I was hoping there would be some built in feature that I would enable and then just install the certs on the devices. I have been going nuts for a week now trying different things to get this going. I have install nginx on the same ubuntu VM as AGH and now also followed the guide to generate a SSL for the IP, bit its always a miss.

**Comment by ainar-g** [comment] 2024-05-27 09:45
#6781 is the issue tracking one possible solution.  Also see our [FAQ entry](https://adguard-dns.io/kb/adguard-home/faq/#customblock) on another possible solution that needs browser support first.

**Comment by iptvcld** [comment] 2024-05-27 11:06
> #6781 is the issue tracking one possible solution. Also see our [FAQ entry](https://adguard-dns.io/kb/adguard-home/faq/#customblock) on another possible solution that needs browser support first.

Thanks, I wonder how nextdns and controld dns are able to make this work? They have their own cert that you need to install on each device but it works..

**Comment by tjharman** [comment] 2024-05-27 21:04
> They have their own cert that you need to install on each device but it works..

That's how they make it work.  You have to deploy their certificate, so they can present a valid SSL certificate for any domain they wish.  Note that it still won't work for [certificate pinned](https://www.ssl.com/blogs/what-is-certificate-pinning/) sites.

**Comment by iptvcld** [comment] 2024-05-27 21:07
> > They have their own cert that you need to install on each device but it works..
> 
> That's how they make it work. You have to deploy their certificate, so they can present a valid SSL certificate for any domain they wish. Note that it still won't work for [certificate pinned](https://www.ssl.com/blogs/what-is-certificate-pinning/) sites.

I am trying to do the same with AGH, with a nginx http server and a cert or that is self signed but ah man I have been at it for a week now (no lie) and just cannot get it.
