### ISSUE TITLE
DNS-over-QUIC Problem in AdGuardHome

### ISSUE THREAD

**Issue by YoshiKill** [AdguardTeam/AdGuardHome#7217] opened 2024-08-27 09:01 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARMv7

### Installation

Pre install with firmware 

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.46

### Action

Hello i have an issues with use DNS-over-QUIC. 
I use Adguard Home in my router GliNet ax1800(openwrt)with preinstalled AdguardHome v0.107.46
When i try add DNS-over-QUIC like: quic://dns.adguard-dns.com
I have an error: Server "quic://dns.adguard-dns.com:853": could not be used, please check that you've written it correctly
![Screenshot 2024-08-27 at 11-59-17 AdGuard Home](https://github.com/user-attachments/assets/14996527-0f30-41d5-80fa-48eb987349c4)

### Expected result

no error with use DNS-over-QUIC.

### Actual result

have an error: Server "quic://dns.adguard-dns.com:853": could not be used, please check that you've written it correctly

### Additional information and/or screenshots

This is my setting for DNS 
![Screenshot 2024-08-27 at 11-59-34 AdGuard Home](https://github.com/user-attachments/assets/73843043-322b-45b7-b0c0-9bbfc84f8283)

**Comment by ainar-g** [comment] 2024-08-27 17:00
Most likely a duplicate of #6422, please update your AGH.

**Closed by ainar-g** 2024-08-27 17:00 UTC
