### ISSUE TITLE
More stats on custom lists

### ISSUE THREAD

**Issue by evoke0** [AdguardTeam/AdGuardHome#6157] opened 2023-08-30 22:06 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

At this moment, there are no stats regarding custom lists that you add to filter traffic. I can add several lists but have no idea if they are really useful with my traffic, just adding on process time.

### Proposed solution

Log hits on each list you add to make sure you only keep those more effective. Let's say I have 5 lists loaded, next to each list, add a history counter of how many times it has blocked a request. This way you can remove lists not suitable for your traffic or not being that useful since you don't make much requests to URLs contained in the list. Therefore, you will be able to reduce the processing time.

![Captura desde 2023-08-30 23-57-23](https://github.com/AdguardTeam/AdGuardHome/assets/59049954/a217d988-0c39-4b36-9b0a-1af84fa6d1ab)

**Comment by ainar-g** [comment] 2023-08-31 10:47
Duplicate of #4524

**Closed by ainar-g** 2023-08-31 10:47 UTC
Labels: feature request
