### ISSUE TITLE
Allow users to set up a specific “EDNS Client Subnet” if possible.

### ISSUE THREAD

**Issue by grantterra** [AdguardTeam/AdGuardHome#2660] opened 2021-02-10 16:55 UTC
I have multiple Internet connections and seem no way to specification the EDNS Client Subnet that I want.

Please allow the users to set up a specific Client Subnet if possible, thank you.

**Comment by ameshkov** [comment] 2021-02-11 08:19
Seems like a duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/1472

Please upvote that feature request.

**Closed by ameshkov** 2021-02-11 08:19 UTC
Labels: duplicate
