### ISSUE TITLE
Backup DNS delay too high

### ISSUE THREAD

**Issue by duckxx** [AdguardTeam/AdGuardHome#6287] opened 2023-10-07 15:21 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-b.46

### Action

未知原因，后备DNS延迟非常高。

![Screenshot_20231007_231543](https://github.com/AdguardTeam/AdGuardHome/assets/116968444/d3255868-e670-4426-97b8-71fedc1eb1db)
![Screenshot_20231007_232006](https://github.com/AdguardTeam/AdGuardHome/assets/116968444/cb94237a-bd03-47a5-9463-e96d6f979538)

### Expected result

无

### Actual result

无

**Comment by fernvenue** [comment] 2023-10-08 09:25
You can enable verbose log to see what's happen, and I think that might just because there is no enough data, as you can see your backup DNS just handled 0.01% of your requests, that's quite normal actually.

**Comment by ainar-g** [comment] 2023-10-12 15:05
Duplicate of #6220

**Closed by ainar-g** 2023-10-12 15:05 UTC
