### ISSUE TITLE
control AdGuard Home service from network

### ISSUE THREAD

**Issue by Kleinhirn** [AdguardTeam/AdGuardHome#444] opened 2018-10-30 19:05 UTC
control AdGuard Home service in network

| Version of AdGuard Home server:| AdGuardHome_v0.9-hotfix1_linux_arm
| How did you setup DNS configuration:| Router
| If it's a router or IoT, please write device model:| Raspberry Pi 3 Model B+
| Operating system and version:| Raspbian Stretch with desktop  4.14

I do not know if this is a issue, but i can not access the controlpage from AdGuard Home service in network from my devices.
I set up the raspberry and can use the controlpage from AdGuard Home service on my raspberry, but if i want to open the controlpage on my PC (Windows 10 with Firefox 63.0) to raspberry ip 192.168.2.153:3000 it did not work.

I want to set up filter/blacklist/whitelist from my network on the controlpage from my AdGuard Home service.

If this is not a issue, i want to make a feature request for it.

Thanks

**Comment by pizdec** [comment] 2018-10-31 08:00
https://github.com/AdguardTeam/AdGuardHome/issues/395

**Comment by ameshkov** [comment] 2018-10-31 10:30
Yeah, looks like a duplicate of #395 

We should handle it automatically as a part of #425

**Closed by ameshkov** 2018-10-31 10:30 UTC
Labels: duplicate
