### ISSUE TITLE
Backup settings

### ISSUE THREAD

**Issue by Codgi-123** [AdguardTeam/AdGuardHome#4189] opened 2022-01-23 15:10 UTC
need a feature that can back up current settings for easy migration and restoration

**Comment by ppfeufer** [comment] 2022-01-23 16:37
Cronjob » `cp /opt/AdGuardHome/AdGuardHome.yaml /to/where/ever/you/want/`

**Comment by Codgi-123** [comment] 2022-01-24 04:09
> Cronjob » `cp /opt/AdGuardHome/AdGuardHome.yaml /to/where/ever/you/want/`

Thanks, this is indeed a good approach, but a visual approach might be better

**Comment by kerryland** [comment] 2022-01-24 10:22
Also not true. This does not backup dhcp static leases. You really need to backup the entire AdGuardHome directory.

**Comment by ainar-g** [comment] 2022-01-24 11:09
Duplicate of #1147

**Closed by ainar-g** 2022-01-24 11:09 UTC
