### ISSUE TITLE
Loading DNS Rewrite Lists from Files

### ISSUE THREAD

**Issue by ZeroClover** [AdguardTeam/AdGuardHome#2070] opened 2020-09-05 16:08 UTC
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
I have noticed other users using AGH for SNI proxy purposes #1577 . This means more DNS rewrite entries.

I am using it for that type of use, and also rewrite the DNS resolving results of some CDN domains to get better network performance. But when managing multiple AGH instances, I have to configure them by copying the YAML configuration file. Otherwise I would have to add them one by one to the Web GUI of multiple AGH instances.

### Proposed Solution
It would be better maintainability if these entries could be loaded from remote files as well as blocklists.

### Alternatives Considered
Not yet.

### Additional Information
None

**Comment by KizunaH** [comment] 2020-09-06 00:59
Duplicate of #919

**Comment by ameshkov** [comment] 2020-09-06 21:33
Closing as dup. Please consider upvoting #919.

**Closed by ameshkov** 2020-09-06 21:33 UTC
