### ISSUE TITLE
Add support for client identification via hardware address without local dhcp

### ISSUE THREAD

**Issue by maihacke** [AdguardTeam/AdGuardHome#1358] opened 2020-01-17 10:23 UTC
Currently adguard tells that client identification via hardware adress ist only possible if the integrated dhcp is used.
From the code it seams, that at least "arp -a" is used to identify clients using IPv4.
Similar to that it should be possible to use something like "ip neighbour show" to identify clients using IPv6. If the command is run cyclic it will even be possible to identify clients via hw adress with privacy extension enabled.

**Comment by gnimor** [comment] 2020-01-17 20:32
My vote as well! This would be a really helpful feature.

**Comment by Slipi089** [comment] 2020-01-18 00:00
+1

**Comment by ameshkov** [comment] 2020-01-19 13:21
The problem here is that `arp` is executed asynchronously so the first couple of DNS queries the client might be unidentified.

**Comment by gnimor** [comment] 2020-01-19 19:32
Hmm, even then it would be a useful feature. In addition wouldn't it be possible to do the first request for an unknown client synchronously. The arp request should be fast in a local network.

**Comment by ameshkov** [comment] 2020-01-20 09:39
> In addition wouldn't it be possible to do the first request for an unknown client synchronously. The arp request should be fast in a local network.

In theory, yes, we can do it. But it would add an additional layer of complexity that could backfire when we expect it the least.

Anyways, generally, I like the idea. Not everyone can or want to use AGH as a DHCP server.

**Comment by ArchiveBase** [comment] 2020-01-21 12:34
Duplicate of #961

**Comment by ameshkov** [comment] 2020-01-21 12:49
@ArchiveBase thanks, this is a duplicate indeed. Merging it there.

@gnimor @maihacke plz upvote #961

**Closed by ameshkov** 2020-01-21 12:49 UTC
Labels: P3: Medium, feature request
