### ISSUE TITLE
How to set optimistic cache not to cache a specific domain name

### ISSUE THREAD

**Issue by chenyajunai** [AdguardTeam/AdGuardHome#4780] opened 2022-07-26 03:42 UTC
How to set optimistic cache not to cache a specific domain name

**Comment by fernvenue** [comment] 2022-07-27 23:08
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/4197.

**Comment by chenyajunai** [comment] 2022-07-28 00:50
> #4197的副本。

thank you

**Closed** 2022-07-28 12:36 UTC
Labels: duplicate
