### ISSUE TITLE
Clearing Logs and Stats Crashing AdguardHome v0.107.39

### ISSUE THREAD

**Issue by kiwilad-nz** [AdguardTeam/AdGuardHome#6308] opened 2023-10-12 19:13 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

FreeBSD, AMD64 (aka x86_64)

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.39

### Action

Clearing Logs and Stats

### Expected result

Logs and Stats to be cleared - requiring no reboot or restart of service or reboot.

### Actual result

AdguardHome crashes.

### Additional information and/or screenshots

pfSense
23.05.1-RELEASE (amd64)built on Wed Jun 28 03:57:27 UTC 2023FreeBSD 14.0-CURRENT

Have this when going immediately to dashboard. Unsure if this is my reverse proxy becoming an issue to the problem when Adguard crashes. Once this shows, refreshing doesn't take me to Adguard anymore and I simply reboot pfSense.

![image](https://github.com/AdguardTeam/AdGuardHome/assets/50952231/bf950249-3393-4a00-9fe5-bd4fa87e5f8c)

**Comment by EugeneOne1** [comment] 2023-10-12 19:14
Duplicate of #6304.

**Closed by EugeneOne1** 2023-10-12 19:14 UTC
