### ISSUE TITLE
update filter problem

### ISSUE THREAD

**Issue by jkle112** [AdguardTeam/AdGuardHome#1308] opened 2019-12-25 22:37 UTC
![Image 3](https://user-images.githubusercontent.com/17021524/71471552-c51cbb80-280a-11ea-954c-be18f237b3be.png)

![Image 2](https://user-images.githubusercontent.com/17021524/71471555-c8b04280-280a-11ea-8460-28a71fa94b70.png)

![Image 1](https://user-images.githubusercontent.com/17021524/71471558-cb129c80-280a-11ea-9668-372fd1d0d048.png)

2019/12/26 18:11:15 [fatal] Couldn't start forwarding DNS server, cause: couldn't listen to UDP socket, cause: listen udp 0.0.0.0:10153: socket: too many open files
2019/12/26 18:11:15 [info] Creating the UDP server socket
2019/12/26 18:11:15 [info] DNS cache is enabled
2019/12/26 18:11:15 [info] The server is configured to refuse ANY requests
2019/12/26 18:11:15 [info] Starting the DNS proxy server
2019/12/26 18:11:15 [error] Can't initialize filtering subsystem: filterlist.NewFileRuleList(): /usr/bin/AdGuardHome/data/filters/1575619179.txt: open /usr/bin/AdGuardHome/data/filters/1575619179.txt: too many open files
2019/12/26 18:11:15 [info] Go to http://10.0.0.1:3000
2019/12/26 18:11:15 [info] Go to http://127.0.0.1:3000
2019/12/26 18:11:15 [info] AdGuard Home is available on the following addresses:
2019/12/26 18:11:14 [error] Couldn't load filter 1575670894 contents due to stat /usr/bin/AdGuardHome/data/filters/1575670894.txt: no such file or directory
2019/12/26 18:11:14 [error] Couldn't load filter 1575619185 contents due to stat /usr/bin/AdGuardHome/data/filters/1575619185.txt: no such file or directory
2019/12/26 18:11:14 [info] Upstream 2: https://1.0.0.1:443/dns-query
2019/12/26 18:11:14 [info] Upstream 1: https://1.1.1.1:443/dns-query

**Comment by ameshkov** [comment] 2019-12-25 22:38
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by rufengsuixing** [comment] 2019-12-27 10:16
too many open files， i will try to set open files  to unlimited

**Comment by jkle112** [comment] 2019-12-28 00:07
Hope do it quickly!
Support latest openssl,libsodium,arp-scan-database ,arp-scan ,ca-bundle ,ca-certificates,for security.
Use wget with ssl or curl to download.

**Comment by jkle112** [comment] 2019-12-28 23:06
rufengsuixing/luci-app-adguardhome@a7c6b0e
change two files ,but it it not running ,need to upgrade fix

**Comment by jkle112** [comment] 2019-12-31 10:38
The problem:"AdGuardHome NOT RUNNINGNot redirect "could not to deal with .
I find a problem:the adguardhome bin file 14192kb changed to 14212kb,it is upgrade to a beta version?
So some firmware could not add adguardhome

**Comment by jkle112** [comment] 2020-01-05 00:14
2020/01/04 23:37:49 9631#1 [info] AdGuard Home is available on the following addresses:
2020/01/04 23:37:49 9631#1 [info] Go to http://127.0.0.1:3000
2020/01/04 23:37:49 9631#1 [info] Go to http://192.168.100.6:3000
2020/01/04 23:37:49 9631#1 [info] Go to http://10.0.0.1:3000
2020/01/04 23:37:49 9631#1 [info] Go to http://172.17.0.1:3000
2020/01/04 23:37:49 9631#66 [error] Can't initialize filtering subsystem: filterlist.NewFileRuleList(): /usr/bin/AdGuardHome/data/filters/1578034658.txt: open /usr/bin/AdGuardHome/data/filters/1578034658.txt: too many open files
2020/01/04 23:37:49 9631#66 [info] Starting the DNS proxy server
2020/01/04 23:37:49 9631#66 [info] The server is configured to refuse ANY requests
2020/01/04 23:37:49 9631#66 [info] DNS cache is enabled
2020/01/04 23:37:49 9631#66 [info] Creating the UDP server socket
2020/01/04 23:37:49 9631#66 [fatal] Couldn't start forwarding DNS server, cause: couldn't listen to UDP socket, cause: listen udp 0.0.0.0:11153: socket: too many open files

**Comment by jkle112** [comment] 2020-01-05 00:16
[ad.log](https://github.com/AdguardTeam/AdGuardHome/files/4022755/ad.log)


AdGuardHome NOT RUNNINGNot redirect

**Comment by rufengsuixing** [comment] 2020-01-05 03:11
you can try this to see the files limit
root@OpenWrt:~# ubus call service list
{
        "AdGuardHome": {
                "instances": {
                        "instance1": {
                                "running": true,
                                "pid": 29770,
                                "command": [
                                        "/usr/bin/AdGuardHome/AdGuardHome",
                                        "-c",
                                        "/etc/AdGuardHome.yaml",
                                        "-w",
                                        "/tmp/AdGdata",
                                        "-p",
                                        "3000",
                                        "-l",
                                        "/tmp/AdGuardHome.log"
                                ],
                                "term_timeout": 5,
                                "env": {
                                        "TZ": "UTC"
                                },
                                "limits": {
                                        "core": "unlimited",
                                        "nofile": "unlimited"
                                },
                                "respawn": {
                                        "threshold": 3600,
                                        "timeout": 5,
                                        "retry": 5
                                }
                        }
                }
        }

**Comment by rufengsuixing** [comment] 2020-01-05 03:33
i found the process still use 1024 as default，maybe try to change it as https://www.tecmint.com/increase-set-open-file-limits-in-linux/
root@OpenWrt:/proc/29770# cat limits
Limit                     Soft Limit           Hard Limit           Units    
Max cpu time              unlimited            unlimited            seconds  
Max file size             unlimited            unlimited            bytes    
Max data size             unlimited            unlimited            bytes    
Max stack size            8388608              unlimited            bytes    
Max core file size        unlimited            unlimited            bytes    
Max open files            1024                 4096                 files    
Max address space         unlimited            unlimited            bytes    
Max resident set          unlimited            unlimited            bytes    
Max processes             1965                 1965                 processes
Max locked memory         65536                65536                bytes    
Max file locks            unlimited            unlimited            locks    
Max pending signals       1965                 1965                 signals  
Max msgqueue size         819200               819200               bytes    
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us

**Comment by rufengsuixing** [comment] 2020-01-05 03:46
i will fix later ，as https://github.com/wongsyrone/openwrt-Pcap_DNSProxy/issues/46

**Comment by jkle112** [comment] 2020-01-05 06:19
如何彻底解决高并发时 file descriptor 不够的问题
wongsyrone/openwrt-Pcap_DNSProxy#46,
something is changed ,so could not find how to change system config.
![Image 1](https://user-images.githubusercontent.com/17021524/71776078-453ee000-2fc6-11ea-9ae2-9055660d2b70.png)

![Image 2](https://user-images.githubusercontent.com/17021524/71776079-4839d080-2fc6-11ea-85f6-b28c3dc1d2ea.png)

![Image 3](https://user-images.githubusercontent.com/17021524/71776081-4b34c100-2fc6-11ea-8a42-94d00e6b4bce.png)

![Image 4](https://user-images.githubusercontent.com/17021524/71776084-4e2fb180-2fc6-11ea-9cbc-76dfa99352dc.png)

![Image 5](https://user-images.githubusercontent.com/17021524/71776086-4ff97500-2fc6-11ea-85fa-368ed2e4b935.png)

![Image 6](https://user-images.githubusercontent.com/17021524/71776087-51c33880-2fc6-11ea-9f7e-3f94035dc9a7.png)

![Image 7](https://user-images.githubusercontent.com/17021524/71776088-54be2900-2fc6-11ea-8b11-c75c0de45349.png)

**Comment by ameshkov** [comment] 2020-01-06 19:28
Closed as this is not a bug of AdGuard Home.

You need to find a way to increase the ulimit on your device.

**Closed by ameshkov** 2020-01-06 19:28 UTC
