### ISSUE TITLE
Clearing the query log will cause the ADGH service to restart unexpectedly

### ISSUE THREAD

**Issue by MiKing233** [AdguardTeam/AdGuardHome#6305] opened 2023-10-12 16:35 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On one machine

### AdGuard Home version

v0.107.39

### Action

我習慣性在設備重新啓動后手動清除DNS的查詢日志和統計日志, 但在v0.107.39中, 這出現了嚴重的問題, 對於在設置-常規設置-清除查詢日志按鈕

### Expected result

ADGH將清除查詢日志並在此期間持續保持服務運行

### Actual result

當點擊后, 會提示查询日志已成功清除, 但此時立刻刷新瀏覽器, 會發現ADGH已經在點擊按鈕后挂掉
![image](https://github.com/AdguardTeam/AdGuardHome/assets/26044744/d85e62fe-caa8-4b9a-8f74-5a30797542cb)
再次刷新會發現正在啓動
![image](https://github.com/AdguardTeam/AdGuardHome/assets/26044744/08709527-2592-4011-8fc7-992c9fb436ca)
這顯示了ADGH在清除查詢日志按鈕點擊後發生了意外重啓的情況, 我經常使用這個功能, 這是在以往版本中不會發生的, 并且這樣的服務重啓將導致網域内的短暫性網路中斷, 這是個嚴重的問題
在OpenWrt, ADGH還輸出了以下log
![image](https://github.com/AdguardTeam/AdGuardHome/assets/26044744/e80b79f8-e8d0-41b0-9641-02bd6ca4c6d8)

**Comment by ainar-g** [comment] 2023-10-12 16:37
Duplicate of #6305

**Closed by ainar-g** 2023-10-12 16:37 UTC
