### ISSUE TITLE
The query log randomly jumps back to the top during scrolling (Possibly Linux ARM64-specific)

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#2285] opened 2020-11-09 00:31 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version (0.104.0)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.104.0
* **How did you setup DNS configuration:**
  * N/A
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4 4GB
* **Operating system and version:**
  * Raspberry Pi OS Buster 64-bit Beta (booted from USB 3.0 stick)

### Expected Behavior
Scrolling down on the Query Log page will keep loading more older sets of 40 requests infinitely, stretching back several thousand or even tens of thousands of queries.

Alternately that the pagenumber system for the Query Log is brought back.

### Actual Behavior
This one is pretty difficult to describe. But essentially, scrolling down on the Query Log page to load older sets of 40 requests, has a random-percent chance of instead jumping back to the top and unloading all sets that had been loaded until then.

Once a set is known to trigger the jump, it'll trigger the jump every time it is reached, making it impossible to scroll down to queries that are more than a few hours old.

I cannot recall that this was a problem on ARMv6 with the nightly builds leading up to 0.104.0, so I can only presume it's ARM64-specific.

### Screenshots

<details><summary>Screenshot:</summary>

![a](https://user-images.githubusercontent.com/22780683/98489336-d78ac280-222d-11eb-89e8-da37f481305d.gif)

</details>

### Additional Information
For some weeks I thought the problem was specific to how I was using an extremely tall monitor (1440x2560 in portrait mode), but the problem was still there when I used a smaller browser window. In fact, if the window was small enough, if a jump was triggered, and the mouse wheel wasn't used afterwards, the page would infinitely scroll down and loop until the mouse wheel was used to stop it, as seen in the screenshot above.

**Comment by KizunaH** [comment] 2020-11-09 04:53
Seems duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/2103

**Comment by ArtemBaskal** [comment] 2020-11-10 09:34
the same server error https://github.com/AdguardTeam/AdGuardHome/issues/2229

**Closed by ArtemBaskal** 2020-11-10 09:34 UTC
Labels: UI, bug
