### ISSUE TITLE
AdGuardHome freezes at least once a day

### ISSUE THREAD

**Issue by rmandjes** [AdguardTeam/AdGuardHome#2225] opened 2020-10-27 06:31 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi Zero W Rev 1.1
* **Operating system and version:**
  * Raspbian Buster

### Expected Behavior
I expect that Adguard keeps running smootly.

### Actual Behavior
Several time my raspberry CPU is at 100%. AdhomeGuard is then consuming all my CPU power. I've to restart the AdGuardHome service and the problem is solved. It started always in the morning if clients are connecting to the server

### Screenshots

![image](https://user-images.githubusercontent.com/55132855/97265105-5d6a3f00-1826-11eb-8e30-7ae889816123.png)

</details>

**Comment by rmandjes** [comment] 2020-10-27 06:34
The screenshot show when AdGuard is running normally. AdGuard is the only installed additional package on this raspberry.

**Comment by rmandjes** [comment] 2020-10-27 07:44
![image](https://user-images.githubusercontent.com/55132855/97271153-81cb1900-1830-11eb-9696-77daea557553.png)
 And now the system is very busy

**Comment by rmandjes** [comment] 2020-10-27 07:57
Maybe safebrowsing is causing the problems:
2020/10/27 08:40:59 [info] SafeBrowsing: failed: couldn't read body contents for 'https://dns-family.adguard.com:443/dns-query', cause: context deadline exceeded
2020/10/27 08:41:09 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=jOkBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": context deadline exceeded
2020/10/27 08:41:09 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 3009 ms
2020/10/27 08:41:12 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=kv4BAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": context deadline exceeded
2020/10/27 08:41:12 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 5905 ms
2020/10/27 08:41:12 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 3318 ms
2020/10/27 08:41:12 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 3318 ms
2020/10/27 08:41:12 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 3235 ms
2020/10/27 08:41:12 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 3223 ms
2020/10/27 08:41:15 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=xSYBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": context deadline exceeded
2020/10/27 08:41:15 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 3574 ms
2020/10/27 08:41:15 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 3583 ms
2020/10/27 08:41:20 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=NyIBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": context deadline exceeded
2020/10/27 08:41:20 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 6397 ms
2020/10/27 08:41:20 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 4048 ms

And

2020/10/27 07:20:00 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 6527 ms
2020/10/27 07:20:00 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 6527 ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0x40abc0]

goroutine 7691 [running]:
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(0x0, 0x234f570, 0x0, 0x0)
	/root/go/pkg/mod/github.com/!adguard!team/dnsproxy@v0.29.1/proxy/proxy.go:253 +0x14
github.com/AdguardTeam/AdGuardHome/dnsforward.processUpstream(0x2059340, 0x0)
	/build/dnsforward/handle_dns.go:224 +0x68
github.com/AdguardTeam/AdGuardHome/dnsforward.(*Server).handleDNSRequest(0x1851180, 0x18ac900, 0x234f570, 0x0, 0x0)
	/build/dnsforward/handle_dns.go:53 +0x114
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleDNSRequest(0x18ac900, 0x234f570, 0x27, 0x27)
	/root/go/pkg/mod/github.com/!adguard!team/dnsproxy@v0.29.1/proxy/server.go:145 +0x1d8
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(0x18ac900, 0x20c7110, 0x27, 0x27, 0x1b55490, 0x10, 0x10, 0x24275e0, 0x1a44128)
	/root/go/pkg/mod/github.com/!adguard!team/dnsproxy@v0.29.1/proxy/server_udp.go:85 +0x1d0
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpPacketLoop.func1(0x18ac900, 0x20c7110, 0x27, 0x27, 0x1b55490, 0x10, 0x10, 0x24275e0, 0x1a44128)
	/root/go/pkg/mod/github.com/!adguard!team/dnsproxy@v0.29.1/proxy/server_udp.go:52 +0x5c
created by github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpPacketLoop
	/root/go/pkg/mod/github.com/!adguard!team/dnsproxy@v0.29.1/proxy/server_udp.go:51 +0x364
t or transport, cause: timeout exceeded: 6634 ms
2020/10/26 13:12:33 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 6629 ms

**Comment by rmandjes** [comment] 2020-10-28 06:44
See now different erro messages:
2020/10/28 07:40:26 [info] error while responding to a DNS request: udpWrite() returned error, cause: write udp [::]:53->192.168.178.28:57014: sendmsg: network is unreachable
2020/10/28 07:40:26 [info] error while responding to a DNS request: udpWrite() returned error, cause: write udp [::]:53->192.168.178.28:57282: sendmsg: network is unreachable
2020/10/28 07:40:26 [info] error while responding to a DNS request: udpWrite() returned error, cause: write udp [::]:53->192.168.178.28:61987: sendmsg: network is unreachable
2020/10/28 07:40:26 [info] error while responding to a DNS request: udpWrite() returned error, cause: write udp [::]:53->192.168.178.28:60411: sendmsg: network is unreachable
2

And there are a lot of these lines.

**Comment by maxtar** [comment] 2020-10-28 13:50
Looks like I have the same trouble.

**Comment by ookangzheng** [comment] 2020-10-30 01:54
I got this wired error after this update
AdGuardHome[562578]: 2020/10/30 09:53:29 [info] error while responding to a DNS request: conn.Write() returned error, cause: write tcp 127.0.0.1:50->127.0.0.1:30756: write: broken pipe

**Comment by Laibalion** [comment] 2020-11-06 21:55
I'm also having this issue.
`
2020/11/06 23:52:48 [info] couldn't communicate with DNS server https://dns-family.adguard.com/dns-query: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=Yv8BAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": context deadline exceeded
2020/11/06 23:52:48 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=kksBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": context deadline exceeded
2020/11/06 23:52:48 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 5871 ms
2020/11/06 23:52:48 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 5870 ms
2020/11/06 23:52:48 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 4906 ms
2020/11/06 23:52:48 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 4864 ms
2020/11/06 23:52:48 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 4863 ms
2020/11/06 23:52:48 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 4213 ms
2020/11/06 23:52:48 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 3142 ms
2020/11/06 23:52:51 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=Lg4BAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": context deadline exceeded
2020/11/06 23:52:54 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=12kBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": context deadline exceeded
2020/11/06 23:52:54 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 4981 ms
2020/11/06 23:52:57 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=DTsBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2020/11/06 23:53:00 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=XLkBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": context deadline exceeded
2020/11/06 23:53:13 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=TzsBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": context deadline exceeded
2020/11/06 23:53:16 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=rBsBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2020/11/06 23:53:19 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=OjkBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2020/11/06 23:53:19 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 5351 ms
2020/11/06 23:53:19 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 4513 ms
2020/11/06 23:53:19 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 3554 ms
2020/11/06 23:53:22 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=grYBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": context deadline exceeded
2020/11/06 23:53:22 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 4759 ms
2020/11/06 23:53:22 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 3930 ms
2020/11/06 23:53:22 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 3918 ms
2020/11/06 23:53:22 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 3918 ms
2020/11/06 23:53:22 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 3919 ms
2020/11/06 23:53:22 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 3907 ms
2020/11/06 23:53:22 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 3892 ms
2020/11/06 23:53:22 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 3856 ms
2020/11/06 23:53:22 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 3854 ms
2020/11/06 23:53:25 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=eZEBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": context deadline exceeded
2020/11/06 23:53:33 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=weoBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": context deadline exceeded
2020/11/06 23:53:46 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=iEIBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2020/11/06 23:53:54 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=80sBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2020/11/06 23:53:57 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=G4kBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2020/11/06 23:54:00 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=UbIBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2020/11/06 23:54:00 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 5388 ms
2020/11/06 23:54:00 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 5147 ms
2020/11/06 23:54:00 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 5147 ms
2020/11/06 23:54:00 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 4793 ms
2020/11/06 23:54:00 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 4793 ms
2020/11/06 23:54:00 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 4357 ms
2020/11/06 23:54:00 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 4357 ms
2020/11/06 23:54:00 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 3789 ms
2020/11/06 23:54:00 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 3790 ms
2020/11/06 23:54:03 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=hmUBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": context deadline exceeded
2020/11/06 23:54:03 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 3413 ms
2020/11/06 23:54:03 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 3383 ms
2020/11/06 23:54:06 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=tsMBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": context deadline exceeded
2020/11/06 23:54:06 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 3921 ms
2020/11/06 23:54:06 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 3422 ms
2020/11/06 23:54:09 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=kHkBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2020/11/06 23:54:12 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=I-IBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2020/11/06 23:54:15 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=Yq8BAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": context deadline exceeded
`

**Comment by Laibalion** [comment] 2020-11-06 21:59
Adding https://dns-family.adguard.com:443/dns-query to the upstream server list also causes the 'Test Upstreams' to fail on that DNS server.
Actually, seems like using any adguard dns server as upstream fails, so most likely this is all connected to the same issue.

**Comment by m5x** [comment] 2020-11-06 22:04
+1

I am also experiencing this problem right now.

**Comment by ameshkov** [comment] 2020-11-06 22:09
Could you please test it again one more time now?

**Comment by Laibalion** [comment] 2020-11-06 22:11
> Could you please test it again one more time now?

Working as expected now. What happened?

**Comment by ameshkov** [comment] 2020-11-06 22:28
Very quick and incomplete analysis is here: https://status.adguard.com/incidents/l6d37hdv5g81

**Comment by Laibalion** [comment] 2020-11-06 22:33
Aha I see. Much appreciated

**Comment by EugeneOne1** [comment] 2020-12-14 16:07
@rmandjes, could you please check if your issue still appears in recent releases?  It would also be really helpful if you could attach the full log file.

**Comment by EugeneOne1** [comment] 2020-12-17 12:00
This should be fixed as of snapshot fd7b061.  Could you please check if our
solution fixes the issue for you?

**Comment by rmandjes** [comment] 2020-12-17 15:43
I'm currently not using this product, because of the problem and I needed a stable solution. Must I do something to use the snapshot?

**Comment by EugeneOne1** [comment] 2020-12-17 16:19
@rmandjes, we didn't find any information about installation method in the original message.  Please run the following command (you should also make sure that directory `/opt/AdGuardHome` doesn't exist):
```$ curl -sSL https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s edge```

**Comment by rmandjes** [comment] 2020-12-21 10:48
Hi,

I've instlalled this version and used it for a few days. It looks like the
problem is gone.😀
There are no new entry's in the out and err log file.

Kind regards,

Ron

>

**Comment by EugeneOne1** [comment] 2020-12-21 11:14
We're glad our solution have fixed your issue :)
Please, feel free to reopen the issue, if it shows itself again.

**Closed by EugeneOne1** 2020-12-21 11:14 UTC
Labels: P3: Medium, bug

**Comment by maxtar** [comment] 2020-12-24 10:54
@EugeneOne1 am I correct, that this fix will included to the next release?

**Comment by EugeneOne1** [comment] 2020-12-24 11:50
@maxtar, yes.  The fix itself was referred to the [dnsproxy](https://github.com/AdguardTeam/dnsproxy) library and already has been included to the v0.33.6 release.  The next upcoming beta version of AdGuard Home including the fix is v0.105.0-beta.2 and the next upcoming release version is v.0.105.0.

**Comment by maxtar** [comment] 2020-12-24 14:18
@EugeneOne1 thanx, will wait. )

**Comment by PussAzuki** [comment] 2020-12-26 04:40
I encountered a similar problem: the dnsproxy-based client mosdns worked before, and then yesterday began to pop up madly related errors related to the above (I found this through google) Everything is fine on Windows, but it keeps playing wrong on openwrt, and the error is on the DNS upstream of IPv6, and then the clash written in go indicates to me that you can't use the DoH upstream of IPv6 but can use the DoT upstream of IPv6. So is there something wrong with go's dns at a lower level?

**Comment by IrineSistiana** [comment] 2020-12-27 01:49
Hi @PussAzuki, I also find that mosdns acts weird on openwrt and found this through google. Would you mind opening a new issue at mosdns repo?

**Comment by PussAzuki** [comment] 2020-12-27 06:42
> Hi @PussAzuki, I also find that mosdns acts weird on openwrt and found this through google. Would you mind opening a new issue at mosdns repo?

I think it's the problem with dnsproxy or the network problem like TCPMSS/OFFLOAD on openwrt because I tried to work properly on any host under the router. If you find that you have errors on any host under the router, then the problem is really caused by dnsproxy, otherwise it is the problem of openwrt. I don't have that many openwrt devices to verify this. If possible, I'd like to have more samples.

**Comment by PussAzuki** [comment] 2020-12-31 10:12
I solved the problem I encountered earlier and found that it was the VLAN problem on the edma driver. The SOC of the machine I use is the ipq40xx series.

**Comment by EugeneOne1** [comment] 2020-12-31 10:17
@PussAzuki, we are glad your issue is solved!  Happy New Year :)

**Comment by PussAzuki** [comment] 2020-12-31 10:20
Happy New Year, too
