### ISSUE TITLE
Persistent clients not working using MAC Address (DHCP Server Runing)

### ISSUE THREAD

**Issue by lutfor-diu** [AdguardTeam/AdGuardHome#6412] opened 2023-11-11 09:31 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARMv6

### Installation

Other (please mention in the description)

### Setup

On one machine

### AdGuard Home version

v0.107.40

### Action

Persistent clients not working using MAC Address (DHCP Server Runing). Request Count not showing any data or stats.

follow:
1. go to client setting
2. set client
3. MAC address as client identifier 
4. save.

![Web capture_11-11-2023_153030_192 168 31 58](https://github.com/AdguardTeam/AdGuardHome/assets/32225836/b3322162-f537-4382-80d1-83eba2dd8d0b)

### Expected result

should work and shows client stats. 

### Actual result

not showing any stats
![Web capture_11-11-2023_152747_192 168 31 58](https://github.com/AdguardTeam/AdGuardHome/assets/32225836/c9c622f9-bb69-4422-a7f8-34c6f41a11b0)

### Additional information and/or screenshots

dietpi os

**Comment by ainar-g** [comment] 2023-11-13 10:22
Duplicate of #4649

**Closed by ainar-g** 2023-11-13 10:22 UTC
