### ISSUE TITLE
Feature request: requests domain IP and custom DNS server by IP-CIDR list

### ISSUE THREAD

**Issue by ky0nch3ng** [AdguardTeam/AdGuardHome#455] opened 2018-11-07 08:51 UTC
### Expected behavior

Local DNS or foreign DNS record data is the difference, In Mainland China  Internet environment effect by DNS cache poisoning, In order to resolve this problem, can filter local IP or foreign IP by IP-CIDR list to avoid DNS data pollution.

![](https://i.imgur.com/8UUqh8D.png)

Opensource project reference:

https://github.com/shadowsocks/ChinaDNS

![](https://img.moegirl.org/common/f/f0/%E6%88%91%E5%A4%A7%E6%B8%85%E8%87%AA%E6%9C%89%E5%9B%BD%E6%83%85%E5%9C%A8%E6%AD%A4.jpg)

**Comment by ameshkov** [comment] 2018-11-07 20:49
How can we split lookups by IP as we don't know the IP addresses before doing the actual lookup?

> The second way is to maintain a list of domains of which you want to resolve from local DNS or foreign DNS. This list changes too often, taking too much effort to maintain.

Is this the main idea? In this case this is a duplicate of #445

**Closed** 2019-08-09 13:04 UTC
Labels: wontfix
