### ISSUE TITLE
Auto refresh Query Log

### ISSUE THREAD

**Issue by nikeshjauhari** [AdguardTeam/AdGuardHome#5734] opened 2023-04-14 18:14 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Description

Hello,

Can we feature where query Logs page / section gets auto refresh instead of pressing the "refresh" icon all times.
setup some sort of refresh time (refresh every 1 or 2 or 3 secs) so that we can view the live flow of logs.

**Comment by agneevX** [comment] 2023-04-15 12:39
Duplicate of #3612, #5080.

>  I have searched other issues and found no duplicates

Could you like actually search for existing issues instead of blindly checking a box!?

**Closed** 2023-04-17 11:45 UTC
