### ISSUE TITLE
Is it possible to add a feature to check the certificate and reload the web server?

### ISSUE THREAD

**Issue by pass12335** [AdguardTeam/AdGuardHome#6163] opened 2023-09-02 17:15 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Is it possible to incorporate a feature to periodically check certificate content and restart the web server?

I am currently using Synology's NAS DS420+ and the Docker version of AdGuard Home. I utilize Synology's DDNS and have Let's Encrypt automatically generate the relevant certificates. 

I use a script to copy these certificates to the AdGuard Home's read path weekly, and I can see from the web page that the related information has been updated. However, recently when opening the AdGuard Home page in the browser, I've been alerted that the certificate in use is nearing expiration. I asked a question in the Q&A section and was informed that I need to manually restart the web server. (https://github.com/AdguardTeam/AdGuardHome/discussions/6162#discussion-5584714)

### Proposed solution

It would be fantastic if there could be a feature allowing users to define a period to check if certificate content has changed and to restart the web server at a specified time!

The certificates obtained from Let's Encrypt have a validity period of 90 days. If this feature could be added, it would be great to allow users to select the time interval (for example: monthly or weekly) and choose a specific reload time (e.g., 4 a.m. every Monday or 10 p.m. on the first day of each month) to facilitate automation and minimize impact on the service.

**Comment by ainar-g** [comment] 2023-09-04 11:21
Duplicate of #3962

**Closed by ainar-g** 2023-09-04 11:21 UTC
Labels: feature request
