### ISSUE TITLE
When internet drops, Adguard stops serving all DNS requests, including rewrites.

### ISSUE THREAD

**Issue by norgan** [AdguardTeam/AdGuardHome#2657] opened 2021-02-10 01:51 UTC
* **Version of AdGuard Home server:**
  * 
* **How did you install AdGuard Home:**
Docker
* **How did you setup DNS configuration:**
dns over tls and https for upstream, half a dozen local rewrites
* **If it's a router or IoT, please write device model:**
  Raspi 4
* **Operating system and version:**
  Raspbian 64bit

### Expected Behavior
Like a real DNs server, queries should be delivered from local zones and cached lookups, even when upstream servers are down. 

### Actual Behavior
All DNS queries fail and clients panic

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by norgan** [comment] 2021-02-10 01:54
AdGuard Home v0.104.3

**Comment by ainar-g** [comment] 2021-02-10 09:30
Hi, and thank you for your report.

@ameshkov, do we have an issue about an “offline mode”?  I think we've discussed that before somewhere, but I can't find the related issue.

**Comment by ameshkov** [comment] 2021-02-10 10:19
@ainar-g we don't, and the problem is caused by the `max_goroutines` limit, and yes, there was a ticket about that already.

We could lift the limit or set it to a higher value, this would help.

**Comment by tezgno** [comment] 2021-03-26 14:15
This is definitely causing issues when there are ISP outages or on power related restarts. Is there any update on this one?

**Comment by KF5JWC** [comment] 2021-04-14 22:36
Migrated away from Adguard due to this issue :(

**Comment by timcappalli** [comment] 2021-04-14 22:45
Why is this flagged as feature request? This is a core deficiency.

**Comment by ameshkov** [comment] 2021-04-15 09:31
The easy solution to this issue is to set `max_goroutines` to 0 in `AdGuardHome.yaml`.

**Comment by Aikatsui** [comment] 2021-04-17 12:58
https://github.com/AdguardTeam/AdGuardHome/issues/1558

**Comment by rhraziel** [comment] 2021-04-20 15:47
I'm not sure if this ticket means no local dns look ups work just while upstream dns servers are unavailable or if it means it doesn't work even when they become available again (my issues is the latter). If my internet goes down, I have to reboot my pi or restart the adguard service for it to process DNS requests again. I thought it just happened when I was using DoH upstream servers but now it happens for unencrypted upstream servers as well. max_goroutines set to 0 didn't fix it for me.

**Comment by ameshkov** [comment] 2021-04-20 15:55
> If my internet goes down, I have to reboot my pi or restart the adguard service for it to process DNS requests again.

This one is definitely something new, not related to this ticket.

**Comment by SanderGit** [comment] 2021-04-20 16:34
> > If my internet goes down, I have to reboot my pi or restart the adguard service for it to process DNS requests again.
> 
> This one is definitely something new, not related to this ticket.

Sorry for that, because it was my impression as well that this is the case and @KF5JWC seems to refer to the same. I have this both on a RPi and in docker, with my own unbound as root server (which keeps working). After the connection drops and returns, AGH still does not work.

**Comment by ameshkov** [comment] 2021-04-20 19:48
@rhraziel @SanderGit it would help a lot if you could record verbose-level log of this issue for us.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) AdGuard Home to write verbose-level log.
2. Reproduce the issue.
3. Post the log file here.

**Comment by KF5JWC** [comment] 2021-04-20 19:55
> > > If my internet goes down, I have to reboot my pi or restart the adguard service for it to process DNS requests again.
> > 
> > This one is definitely something new, not related to this ticket.
> 
> Sorry for that, because it was my impression as well that this is the case and @KF5JWC seems to refer to the same. I have this both on a RPi and in docker, with my own unbound as root server (which keeps working). After the connection drops and returns, AGH still does not work. 

This is an accurate understanding of the issues I ran into.

**Comment by tezgno** [comment] 2021-04-20 20:58
This is the same issue I have as well. If I go and unplug my modem, for example, I can no longer resolve any DNS entries including those locally served/rewrites.

**Comment by rhraziel** [comment] 2021-04-20 21:20
> @rhraziel @SanderGit it would help a lot if you could record verbose-level log of this issue for us.

I apologize, I hope someone else can provide logs for this. I've already moved off of Adguard for now and my Linux knowledge is a bit limited.

**Comment by kvervo** [comment] 2021-04-22 07:59
For @rhraziel issue, I came across a similar report in #2058
However, I was not able to reproduce the problem 0.105.2

However, I can confirm a similar behavior when disabling protection, DNS rewrites would also stop working. Which I believe should not be the case. 

Overall the scenario I believe should be implemented is the following:
* DNS Rewrites should continue to work if 'Protection is disabled'
* DNS Rewrites should continue to work if Internet Outage is ongoing

**Comment by rhraziel** [comment] 2021-04-27 13:29
> @rhraziel @SanderGit it would help a lot if you could record verbose-level log of this issue for us.

FYI, I've emailed logs to the devteam email address in regards to this.

**Comment by rhraziel** [comment] 2021-04-29 17:02
I've done a little more testing on this and I'm narrowing down what causes the issue (at least for me). If I use a DoH DNS provider OR I use the "browsing web security service" or the "parental control service", DNS resolution does not come back after an internet outage. If I'm not using DoH or web security or parental control, everything works fine after the internet outage. I added Adguard's ipv4 DNS servers to the bootstrap list but that didn't seem to resolve it. I'm just avoiding using DoH and the security/parental services for now but it would be nice to enable them if it didn't cause the resolution recovery issue.

**Comment by Salvora** [comment] 2021-05-01 16:46
I am suffering from the same problem. 
I advertise adguard home ip address for the primary DNS from my router. I have local domains that I use consistently but when the internet connection gets interrupted, the whole network is confused.

**Comment by gabxav** [comment] 2021-05-16 22:59
Same error on AdGuard Home v0.106.2

**Comment by amishv** [comment] 2021-06-28 13:47
Same issue is seen on MWAN3 switchover on OpenWRT. When the main WAN goes down AdGuard home stops serving the DNS request till I restart the application. I have tried both OpenWRT version on my router and Docker version on my NAS.
**dig @AdGuard_ip google.com** takes a long time before failing with "no dns server found" ,
a parallel **dig @8.8.4.4 google.com** almost instantly returns the IP of google.com.

**Comment by a1ad** [comment] 2021-06-28 15:51
Got the same problem! WAN down > adguard refuses to work until i restart adguard. Tested on Docker, linux native and opnsense. v0.106.3

**Comment by ikifar2012** [comment] 2021-06-28 18:31
Yep we have had issues with our ISP as well and I had to make a script to kill-9 the adguard process then start the service because the whole process seems to hang

**Comment by ameshkov** [comment] 2021-07-05 11:39
Hi all, could you please try the edge channel build?

Probably, this issue is a duplicate of #3217 which seems to be fixed there.

**Comment by amishv** [comment] 2021-07-05 12:08
> Hi all, could you please try the edge channel build?
> 
> Probably, this issue is a duplicate of #3217 which seems to be fixed there.

@ameshkov , I do not see this issue, yet,  in Version: v0.107.0-a.95+e113b276. The build is up for more than 30 hours.

**Comment by ikifar2012** [comment] 2021-07-06 04:17
> Hi all, could you please try the edge channel build?
> 
> Probably, this issue is a duplicate of #3217 which seems to be fixed there.

What's the best way to switch my current install to edge?

**Comment by ameshkov** [comment] 2021-07-06 08:15
Depends on your setup.

If you're using snapcraft or docker, just switch to the "edge" tag.
If you're using a binary, download one from the edge channel, replace the old one and restart AdGuard Home.

Binaries links:
https://github.com/AdguardTeam/AdGuardHome#test-unstable-versions

**Comment by ikifar2012** [comment] 2021-07-07 20:33
> Depends on your setup.
> 
> If you're using snapcraft or docker, just switch to the "edge" tag.
> If you're using a binary, download one from the edge channel, replace the old one and restart AdGuard Home.
> 
> Binaries links:
> https://github.com/AdguardTeam/AdGuardHome#test-unstable-versions

Just had to find the binary on the releases page, I have been running for two days and my ISP is having issues so our internet has dropped at least 50 times, it seems to be doing fine

**Comment by jdeluyck** [comment] 2021-07-27 11:16
Deployed today's edge after my ISP was playing ping-pong, seems to work.

**Comment by ainar-g** [comment] 2021-12-09 10:45
@EugeneOne1, I think that your fix for #1558 might have fixed this one as well.  Can you look into it?

**Comment by EugeneOne1** [comment] 2021-12-09 14:50
@ainar-g, it seems the issue has been fixed even earlier.  @norgan, @a1ad, could you please check if the issue reoccurs in the latest `edge`/`beta`-channel builds?

**Comment by a1ad** [comment] 2021-12-09 15:19
Its working fine here

**Comment by ainar-g** [comment] 2021-12-13 11:24
We'll close this issue then.  If anyone has similar issues with the latest beta and edge releases, please open a new issue.  Thanks everyone.

**Closed by ainar-g** 2021-12-13 11:24 UTC
Labels: feature request, P3: Medium

**Comment by handcoding** [comment] 2022-03-06 04:15
Does anyone know when this fix might be landing on the main trunk? 

I stopped using AdGuard Home a few months ago because of this issue, but I’d love to come back if by chance this might be fixed on the main branch soon.

**Comment by rhraziel** [comment] 2022-03-07 22:53
> Does anyone know when this fix might be landing on the main trunk?
> 
> I stopped using AdGuard Home a few months ago because of this issue, but I’d love to come back if by chance this might be fixed on the main branch soon.

Its been fixed as of version 107

**Comment by handcoding** [comment] 2022-03-08 20:52
Good to know—thanks, @rhraziel!

**Comment by abdalians** [comment] 2022-07-12 15:33
After weeks of struggling with this issue I finally decided to search and came across this thread. 
Setup: 
- Dual Failover Internet Setup on Ubiquiti ERX 
- AGH 107.7 running as primary dns server on the network with a local named instance to resolve any local domains. 
Problem: 
- When the internet fails over to the secondary connection, AGH services need to be turned off for it to resolve anything (local or internet). 
<img width="653" alt="image" src="https://user-images.githubusercontent.com/9934227/178528400-c4a759e9-e263-4b44-b4a8-b82e178762f7.png">

**Comment by s1lviu** [comment] 2022-07-19 12:18
I can confirm I have this issue too on the latest AGH version.

**Comment by ainar-g** [comment] 2022-07-22 14:49
@abdalians, @s1lviu, apologies for the late response.  Can you collect the verbose logs as EugeneOne1 suggested above?  Also, what kind of upstream are you using?  DoH, DoT, or DoQ?

**Comment by abdalians** [comment] 2022-07-22 15:58
I tried DoT and DoH - both of these had issues. I have AdGuard filtering services turned off at the moment. I will try and capture logs over the weekend.

**Comment by dinosoup1** [comment] 2022-08-03 18:37
Commenting to maintain visibility on this issue - I have had to stop using AdGuard as my ISP is basically useless and anytime my network goes out, AdGuard ruins everything locally.

**Comment by conradseba** [comment] 2022-08-04 10:58
I can also confirm that v0.108.0-b.11 does *not* address this issue either.

**Comment by abdalians** [comment] 2022-08-04 15:16
the ticket status still remains closed, can we reopen this or do we need to open a new issue and reference this?

**Comment by levz0r** [comment] 2023-04-15 16:34
Same issue happens on v0.107.28

**Comment by sammyke007** [comment] 2023-05-10 11:08
Still an issue

**Comment by yurividal** [comment] 2023-05-23 14:28
Is there a fix or workarround for this?
My ISP was doing some maintanance yesterday, and i noticed none of my local rewrites were resolving while my LAN was offline. 
This makes no sense. Local rewrites with private domains and local IP addresses on the LAN should not need internet access in order to resolve.

**Comment by daygr** [comment] 2023-05-30 18:29
I ran into this issue today while dealing with a prolonged ISP outage. I did a bit of testing and realized that if a low volume of DNS requests hit AGH, it worked as intended, so as suggested above, I set `max_goroutines: 0` in `AdGuardHome.yaml`. It seems that higher volumes of failed upstream DNS requests slow AGH to the point where rewrites fail to respond.

**Comment by merlink01** [comment] 2023-06-29 06:39
For me this error still exists: Version: v0.107.32
Setting max_goroutines: 0 did not help.
Because my home automation is using local DNS this is really critical.

What could we do?

**Comment by Qhilm** [comment] 2023-08-22 06:27
In my case, AGH does not even start if internet is down. I'm running it on opnsense. If there's a power outage, it's possible the router reboots while Internet is still not available, in this case, adguard does not even come up, which is quite annoying.

Is that a separate issue?

**Comment by RedFoxy** [comment] 2023-11-29 06:48
> This is the same issue I have as well. If I go and unplug my modem, for example, I can no longer resolve any DNS entries including those locally served/rewrites.

Same here! And it's a really big trouble when internet goes down and you can't resolve local dns, I've ADGuard in Docker and I've max_goroutines: 0 in AdGuardHome.yaml but nothing goes when I'm offline

**Comment by Qhilm** [comment] 2023-11-29 13:02
So far I have been using Unbound as upstream DNS on AGH and that solved two problems:
* AGH not starting if internet is down
* AGH not answering DNS queries for local network when internet is down

I have not tested this thoroughly to be fair, but everything looked good the last 2 times I had Internet down on the ISP side.

**Comment by Qhilm** [comment] 2023-12-02 21:28
I mean configure upstream DNS like here: https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams

I run unbound on port 5353 on the same machine, and I configured 127.0.0.1:5353 as upstream DNS for AGH simply.

**Comment by yurividal** [comment] 2023-12-04 17:14
Just to be clear: running a local unbound instance as an upstream for AGH is a workaround for the issue, but should definitely not be considered a fix. 
There is no reason why AGH should be trying to resolve upstream names if it has local rewrites.

**Comment by merlink01** [comment] 2023-12-05 09:08
Yes, this is not fixed, after a lot of testing, I do now use Opensense as dns and connect to adguard as the upstream DNS Server.

A bad workaround, but I don't want to get my internal network and IOT systems go down on short internet outage. 

I think this should have high priority, because it seems like an kritical issue.

A missing internet connection should never cause an internal dns overwrite to be not delivered correctly.

**Comment by mcrapts** [comment] 2024-01-02 15:45
The solution/workaround in this comment works:
https://github.com/AdguardTeam/AdGuardHome/issues/4825#issuecomment-1866318615

> My home internet is currently down. Wasn't able to access my network via local DNS. If I disabled AGH protection, local DNS works. My solution was to add @@||mydomain.tld^ to the custom filtering rules. Immediately started resolving again.

Basically you're whitelisting your own domains from any blocklist. Your DNS rewrites that match the exclusion will then resolve even without an internet connection.

**Comment by GentleHoneyLover** [comment] 2024-11-21 11:12
> The solution/workaround in this comment works: [#4825 (comment)](https://github.com/AdguardTeam/AdGuardHome/issues/4825#issuecomment-1866318615)
> 
> > My home internet is currently down. Wasn't able to access my network via local DNS. If I disabled AGH protection, local DNS works. My solution was to add @@||mydomain.tld^ to the custom filtering rules. Immediately started resolving again.
> 
> Basically you're whitelisting your own domains from any blocklist. Your DNS rewrites that match the exclusion will then resolve even without an internet connection.

That's definitely a workaround, not a solution :)

**Comment by derekpurdy** [comment] 2025-03-06 03:42
Seen the same issue tonight on the latest build. Is this still ongoing?

**Comment by zhouguiheng** [comment] 2025-03-24 01:15
This issue still persists with the latest build. The custom filter workaround above doesn't work for me.

AGH just refuses to resolve my local domains when offline, the home page UI doesn't load correctly either, and I won't be able to update the settings using UI when Internet is down. I put the workaround @@||mydomain.tld^ directly into the yaml file and restart AGH, no luck.

It seems that AGH is overloaded with pending DoH requests and the log is flooded with many timeout requests.

Can we reopen this bug?

**Comment by abdalians** [comment] 2025-03-24 04:03
I personally gave up on this long time ago and spawned a named container which is my primary dns for local domain and agh is the forwarded to the named. This way I always resolve my local domains and get the filtering. The only thing missing is the per client filteting which I dont care about. 

Yahoo Mail – Email Simplified 
 
  On Sun., 23 Mar. 2025 at 9:16 p.m., ***@***.***> wrote:    
This issue still persists with the latest build. The custom filter workaround above doesn't work for me.

AGH just refuses to resolve my local domains when offline, the home page UI doesn't load correctly either, and I won't be able to update the settings using UI when Internet is down. I put the workaround @@||mydomain.tld^ directly into the yaml file and restart AGH, no luck.

It seems that AGH is overloaded with pending DoH requests and the log is flooded with many timeout requests.

Can we reopen this bug?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>
zhouguiheng left a comment (AdguardTeam/AdGuardHome#2657)
This issue still persists with the latest build. The custom filter workaround above doesn't work for me.

AGH just refuses to resolve my local domains when offline, the home page UI doesn't load correctly either, and I won't be able to update the settings using UI when Internet is down. I put the workaround @@||mydomain.tld^ directly into the yaml file and restart AGH, no luck.

It seems that AGH is overloaded with pending DoH requests and the log is flooded with many timeout requests.

Can we reopen this bug?

**Comment by bvandevliet** [comment] 2025-03-24 05:53
> I personally gave up on this long time ago and spawned a named container which is my primary dns for local domain and agh is the forwarded to the named. This way I always resolve my local domains and get the filtering. The only thing missing is the per client filteting which I dont care about.
> 
> Yahoo Mail – Email Simplified
> 
>   On Sun., 23 Mar. 2025 at 9:16 p.m., ***@***.***> wrote:
> This issue still persists with the latest build. The custom filter workaround above doesn't work for me.
> 
> AGH just refuses to resolve my local domains when offline, the home page UI doesn't load correctly either, and I won't be able to update the settings using UI when Internet is down. I put the workaround @@||mydomain.tld^ directly into the yaml file and restart AGH, no luck.
> 
> It seems that AGH is overloaded with pending DoH requests and the log is flooded with many timeout requests.
> 
> Can we reopen this bug?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>
> zhouguiheng left a comment ([AdguardTeam/AdGuardHome#2657](https://github.com/AdguardTeam/AdGuardHome/issues/2657))
> This issue still persists with the latest build. The custom filter workaround above doesn't work for me.
> 
> AGH just refuses to resolve my local domains when offline, the home page UI doesn't load correctly either, and I won't be able to update the settings using UI when Internet is down. I put the workaround @@||mydomain.tld^ directly into the yaml file and restart AGH, no luck.
> 
> It seems that AGH is overloaded with pending DoH requests and the log is flooded with many timeout requests.
> 
> Can we reopen this bug?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

Clever workaround. But I still agree this issue should be re-opened and not given up on. It should not be just accepted by us loyal end users that shit hits the fan when internet drops, just because this bug keeps being ignored by the AGH team. And I would say it's quite a critical bug too. If this will for certain never be fixed, I'd also be open again to look for alternatives to AGH. So if that is the case, I'd like to know as well plz..

**Comment by adripo** [comment] 2025-03-24 20:02
I think it's easier to open a new issue and reference this one for the details. I doubt the AGH team checks closed issues.
