### ISSUE TITLE
dnsrewrite rules - client filter is ignored for queries from ipv6

### ISSUE THREAD

**Issue by xzwr** [AdguardTeam/AdGuardHome#6343] opened 2023-10-23 08:49 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS), AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.40

### Action

I have created a group "home" of persistent clients with ipv4 and  ipv6 link local address spaces.
I have set the following rule:
```
||test.test2.com^$client=home,dnsrewrite=NOERROR;AAAA;fe80::7777:d0ff:abcd:7575
```

### Expected result

I would expect the DNS to return the AAAA record `fe80::7777:d0ff:abcd:7575` for every machine in the client group "home"

### Actual result

In the query log the client is correctly identified and added to the group "home".
![Screenshot 2023-10-23 at 10 22 22](https://github.com/AdguardTeam/AdGuardHome/assets/5003726/b76a214d-3c03-4ff2-8e41-f7bcb4c92b04)

However if i query the dns via ipv6 the client filter is ignored and the request is processed:
```
nslookup -query=AAAA test.test2.com fe80::9209:d0ff:fe25:86b7          
Server:		fe80::9209:d0ff:fe25:86b7%5
Address:	fe80::9209:d0ff:fe25:86b7%5#53

Non-authoritative answer:
*** Can't find test.test2.com: No answer

Authoritative answers can be found from:
test.test2.com
	origin = ns1.parklogic.com
	mail addr = hostmaster.test2.com
	serial = 2023081501
	refresh = 3600
	retry = 7200
	expire = 1209600
	minimum = 3600
```

A query via ipv4 works as intended:
```
nslookup -query=AAAA test.test2.com 192.168.0.110
Server:		192.168.0.110
Address:	192.168.0.110#53
Non-authoritative answer:
test.test2.com	has AAAA address fe80::7777:d0ff:abcd:7575
```

**Comment by ainar-g** [comment] 2023-10-23 13:56
Duplicate of #6312

**Closed by ainar-g** 2023-10-23 13:56 UTC
