### ISSUE TITLE
Netflix refuses to work with AdGuard Home

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardHome#534] opened 2019-01-06 04:57 UTC
For some reason, trying to use Netflix on a Telstra TV device (powered by Roku) refuses to work with AdGuard Home... but it works fine with Pi-hole.

When I select 'Check your network', Netflix server 3 always results in a **nw-3-6** error which [according to Netflix](https://help.netflix.com/en/node/12977) is an issue connecting to Netflix. It also states my Connection speed is `0 Mbps` and that "Your device may not be connected to the internet. Please make sure your connection is working."

Considering using Pi-hole works flawlessly, something with AdGuard Home isn't liked by Netflix.

**Edit:** It also cannot access my account information or log me in if I'm not logged in yet.

**Comment by ameshkov** [comment] 2019-01-06 15:14
This is likely to be a duplicate of #521 

It'd be great if you can build AG Home from `fix/521` branch and verify it

**Closed by ameshkov** 2019-01-06 15:14 UTC
Labels: duplicate

**Comment by planet0** [comment] 2019-01-07 05:37
> This is likely to be a duplicate of #521

Oh good catch, didn't realise the issue was TCP related.

> It'd be great if you can build AG Home from `fix/521` branch and verify it

I have no idea how to build it and make it suitable for Raspberry Pi (32-bit ARM), but looking at #521 it seems like @alexruf figured it out in the end.

Happy to test it as well if either I'm guided on how to build it, or if I'm provided the linux_arm.tar.gz

**Comment by alexruf** [comment] 2019-01-07 06:45
> I have no idea how to build it and make it suitable for Raspberry Pi (32-bit ARM), but looking at #521 it seems like @alexruf figured it out in the end.

I uploaded a ARM binary for Raspberry Pi to my Dropbox ([here](https://www.dropbox.com/s/lmbeoafmu9mbego/AdGuardHome_linux_arm.tar.gz?dl=0)), so you can grab it from there if you like to test it on your own.

**Comment by ameshkov** [comment] 2019-01-08 23:50
@alexruf @planet0 thank you so much guys!

**Comment by ibksturm** [comment] 2019-01-11 22:40
hi guys

update to 0.92-f2 did a lot of performanceboost, thats fucking great! love it 🤩
