### ISSUE TITLE
Support for uploading local rules

### ISSUE THREAD

**Issue by cha0sCat** [AdguardTeam/AdGuardHome#914] opened 2019-08-05 15:10 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

In China, some of the rule lists cannot be obtained directly through HTTP requests (because of GFW). Currently, it is inconvenient to manually add rules only through configuration files.
### Proposed Solution

Support uploading local rules
### Alternatives Considered

manually add rules only through configuration files.
### Additional Information

None

**Comment by ameshkov** [comment] 2019-08-05 15:13
Duplicate of #817

**Closed by ameshkov** 2019-08-05 15:13 UTC
