### ISSUE TITLE
Internet down. AGH stops answer all request (even local)

### ISSUE THREAD

**Issue by james-1987** [AdguardTeam/AdGuardHome#6536] opened 2023-12-12 03:29 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

Version:  v0.107.42

### Action

Test to pulldown gateway WAN in pfsense main router. All request stops, even local req.

Having AGH to upstream to pfsense as a dns overide to local servers. 
If lookup pfsense from client direct it lookup my local req when WAN is down.
Having pfsense as secondary DNS is not optimal setup. AGH should work when WAN is down for local forwarding.

### Expected result

My local req should work if WAN is down.

### Actual result

Only cached DNS works. Timeout on nslookup test on client when i do local req.

**Comment by ainar-g** [comment] 2023-12-12 11:34
Duplicate of #4825

**Comment by ainar-g** [comment] 2023-12-12 11:34
Also, please be aware that Browsing Security and Parental Control require an internet connection.

**Closed by ainar-g** 2023-12-12 11:34 UTC
