### ISSUE TITLE
Live update of Query Log

### ISSUE THREAD

**Issue by grubeli** [AdguardTeam/AdGuardHome#2338] opened 2020-11-19 17:07 UTC
I think it would be quite useful to see live update from the query log, maybe not on default but as an option.

For example, sometimes I want to see what what domains are blocked or allowed while visiting a site. it can be used to find a FP.

NextDNS recently implemented the feature:
https://twitter.com/NextDNS/status/1313876219390300162

**Comment by Aikatsui** [comment] 2020-11-19 20:51
Duplicate of #666

**Closed** 2020-11-20 08:43 UTC
