### ISSUE TITLE
Untentional Blocking of Citizens Bank

### ISSUE THREAD

**Issue by misaligar** [AdguardTeam/AdGuardHome#7156] opened 2024-07-28 12:01 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.52

### Action

Unable to log in to www.citizensbankonline.com. I found that `content.citizensbankonline.com` is blocked. Unblocking this particular subdomain fixes the issue. Query shows `1Hosts (Lite)` blocks this subdomain but I cannot find it in their list of blocked domains.

![image](https://github.com/user-attachments/assets/748751ab-d8fc-4121-aafe-dd620e3ba508)

```sh
misaligar@macbook ~ % nslookup -debug -type=a 'content.citizensbankonline.com' '192.168.1.120'
Server:		192.168.1.120
Address:	192.168.1.120#53

------------
    QUESTIONS:
	content.citizensbankonline.com, type = A, class = IN
    ANSWERS:
    ->  content.citizensbankonline.com
	internet address = 0.0.0.0
	ttl = 10
    AUTHORITY RECORDS:
    ADDITIONAL RECORDS:
------------
Non-authoritative answer:
Name:	content.citizensbankonline.com
Address: 0.0.0.0
```

### Expected result

Log in without an issue.

### Actual result

Unable to log in.

**Comment by Dynamic5912** [comment] 2024-07-28 21:26
Because it's blocked by a cname or IP address in the 1Host Lite list.

**Comment by tjharman** [comment] 2024-07-28 22:20
This is not a bug in AdGuardHome, this is a filter list issue.  Closing this ticket.

**Closed by tjharman** 2024-07-28 22:20 UTC

**Comment by misaligar** [comment] 2024-07-29 01:30
Thanks. Submitted to 1Hosts repo. https://github.com/badmojr/1Hosts/issues/1812
