### ISSUE TITLE
Problem adding upstream DNS Server (https://dns.seby.io)

### ISSUE THREAD

**Issue by AnthonyBe** [AdguardTeam/AdGuardHome#430] opened 2018-10-26 01:12 UTC
Due to latency using Cloudflare DNS where I am, I wish to use a DNS server in same country as me - https://dns.seby.io - which I also use on PCs via DNScrypt-proxy.

When I add it to the list via AGH UI I get an error
I keep getting an error:

`Server "tls://45.76.113.31:853": could not be used, please check that you've written it correctly`

Am I doing something wrong or can I not use this DNS as an upstream?
The DNS server details are here - https://dns.seby.io

### Steps to reproduce
1. In AGH UI -> Settings -> Upstream DNS servers
2. Add tls://45.76.113.31:853 to top of list
3. Hit Apply and then Test Upstreams

### Actual behavior
Error:
`Server "tls://45.76.113.31:853": could not be used, please check that you've written it correctly`

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| 0.9 Hotfix 1
| How did you setup DNS configuration:| Windows DHCP Server
| If it's a router or IoT, please write device model:| na
| Operating system and version:| Ubuntu 18.04.1 running under Windows 10 WSL

**Comment by ameshkov** [comment] 2018-10-26 09:03
Most likely this is a duplicate of #414

**Closed by ameshkov** 2018-10-26 09:03 UTC
