### ISSUE TITLE
Error: token too long | 400

### ISSUE THREAD

**Issue by preshs** [AdguardTeam/AdGuardHome#6010] opened 2023-07-14 03:27 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.34

### Action

Adding a allow list from adguard dns filter list results in with the introduction of v0.107.34

Error: control/filtering/add_url | Couldn't fetch filter from URL "https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt": scanning filter contents: bufio.Scanner: token too long | 400

Previously working whilte list filters now not working either.

### Expected result

Expected result is that list is ingested without error and existing dns allow list rules works.

### Actual result

Error: control/filtering/add_url | Couldn't fetch filter from URL "https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt": scanning filter contents: bufio.Scanner: token too long | 400

**Comment by ppfeufer** [comment] 2023-07-14 06:14
See: https://github.com/AdguardTeam/AdGuardHome/issues/6003

**Comment by ainar-g** [comment] 2023-07-14 10:07
Duplicate of #6003

**Closed by ainar-g** 2023-07-14 10:07 UTC
