### ISSUE TITLE
Automatically update the Dashboard and Query Log.

### ISSUE THREAD

**Issue by marcelloinfoweb** [AdguardTeam/AdGuardHome#2342] opened 2020-11-20 11:35 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
Having to manually update the Dashboard and Query Log.

### Proposed Solution
Have an option that updates automatically the Dashboard and Query Log, a dropdown with the options of off and others with the times in seconds. These options can be loaded disabled and whoever wants (like me), enable it manually.

### Additional Information

![Dropdown-exemplo](https://user-images.githubusercontent.com/2093128/99795762-19a7e400-2b0b-11eb-9ea2-bc31554665d3.png)

**Comment by Aikatsui** [comment] 2020-11-21 15:00
Duplicate of #666

**Closed** 2020-11-23 12:39 UTC
Labels: duplicate
