### ISSUE TITLE
Cache hit statistic

### ISSUE THREAD

**Issue by BigArty** [AdguardTeam/AdGuardHome#6385] opened 2023-11-03 17:08 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

I want to know how often I need to make requests to upstream servers. I have a "Top upstreams" section, but I also want to know how much times the request was cached.

### Proposed solution

Add a section to home page of web UI or add a "cache" as another upstream for requests in "Top upstreams" section.

**Comment by ainar-g** [comment] 2023-11-07 11:09
Duplicate of #1453

**Closed by ainar-g** 2023-11-07 11:09 UTC
Labels: feature request
