### ISSUE TITLE
Client specific with regex does not work

### ISSUE THREAD

**Issue by ghahramani** [AdguardTeam/AdGuardHome#5650] opened 2023-03-29 02:55 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

64-bit ARM

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.21

### Description

Hi,

I have added the simple custom query to my adguard in my openwrt router and also specified the client in the panel with mac address but the filter does not work when I specify the client in regex filter rules

`/.*youtube.*/$client=Playstation`

It works perfectly when I use

`/.*youtube.*/`

#### Expected result
Should filter youtube only in Playstation client which is added by mac address 

#### Actual result
Does not filter unless I remove the $client

**Comment by ainar-g** [comment] 2023-03-29 10:08
Hello.  Unfortunately, I cannot reproduce this.  Some possible solutions:

1.  Please make sure you're using the client **name** as opposed to ClientID in the modifier.

2.  v0.107.21 is not the most recent release of AdGuard Home, so try updating.

**Comment by ainar-g** [comment] 2023-03-30 09:38
>  I am using the client name, I have attached the screenshot shot

Are you using an IP address to identify the `Playstation` client, a MAC, or both?  MAC identification only works if AdGuard Home is the DHCP server, which you indicated that it's not.  If the `Playstation` client has a static IP, I'd recommend using that.

 >  There is no update for openwrt, please see the attached screenshot

You have indicated that you've used the official installation method as opposed to an OS package.  I assume that that was incorrect?  The latest released version is v0.107.26.

**Comment by ghahramani** [comment] 2023-03-30 09:52
I used the package manager of openwrt, sorry if I selected it wrong, yes I am only using mac address only, no ip address. I will update it to use ip address and will let you know but it would be great if I could use it with mac address even if it is not dhcp server and the reason is I have ipv6 as well and it is hard to match with that as well as it comes from my isp.

**Comment by ghahramani** [comment] 2023-04-04 18:03
Ok, it seems it works with IP address and I used the exclude expression (~) but it is a bit hard as I used ipv6 as well and each device has multiple ones which makes it hard to just add each devices ipv4 and ipv6

**Comment by ainar-g** [comment] 2023-04-19 15:32
Apologies for the late response.  As mentioned, MAC addresses currently only work when AdGuard Home works as the network's DHCP server.  The issue about expanding that is #961.  You can add multiple IP addresses to each persistent client's identifier list, and if your devices support encrypted protocols, you could also use [ClientIDs][1].

I'll close this issue, as the basic problem is the same as in 961, if you don't mind.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/Clients#clientid

**Closed by ainar-g** 2023-04-19 15:32 UTC
Labels: waiting for data
