### ISSUE TITLE
Possibility to specify the times for filter lists update in another way

### ISSUE THREAD

**Issue by mahehro** [AdguardTeam/AdGuardHome#6583] opened 2023-12-25 11:32 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Currently, the filter lists are always updated x hours after the last update. No fixed times can be set in this way.

### Proposed solution

Possibility to specify differently when filters are updated. For example, via cron expressions or fixed times.

**Comment by ainar-g** [comment] 2023-12-25 11:43
Duplicate of #3044

**Closed by ainar-g** 2023-12-25 11:43 UTC
Labels: feature request
