### ISSUE TITLE
Update from v0.102.0 to v0.103.3 set DHCP to enabled (was Disabled)

### ISSUE THREAD

**Issue by AnthonyBe** [AdguardTeam/AdGuardHome#2019] opened 2020-08-12 06:29 UTC
### Issue Details

on 25 July I upgraded (via the UI) from v0.102.0 to v0.103.3
I have just rebooted the server (Windows Server 2012 R2) for the first time since then, and on reboot AGH did not start,
On checking the AGH.log I found the following being logged over and over:

```
2020/08/12 15:31:45 [info] AdGuard Home, version 0.103.3, channel release, arch windows amd64
2020/08/12 15:31:45 [info] AdGuard Home is running as a service
2020/08/12 15:31:46 [info] Initializing auth module: C:\install\AdGuardHome\data\sessions.db
2020/08/12 15:31:47 [info] Auth: initialized.  users:1  sessions:4
2020/08/12 15:31:47 [info] Initialize web module
2020/08/12 15:31:53 [info] Couldn't start listening socket on 0.0.0.0:67, cause: Couldn't set control message FlagInterface on connection, cause: not implemented on windows/amd64
2020/08/12 15:31:53 [fatal] Couldn't start DHCP server, cause: Couldn't start listening socket on 0.0.0.0:67, cause: Couldn't set control message FlagInterface on connection, cause: not implemented on windows/amd64
```
The last 2 lines were the giveaway - DHCP had been enabled.
Luckily DHCP in AGH doesn't work on Windows so the only issue was AGH not starting.
I manually changed the DHCP Enabled flag in the AdGuardHome.yaml back to False and then AGH started up as expected.

The issue here is that I did not enable DHCP.
I know it doesn't even work on Windows so I have no reason to enable it.

I'm raising this issue in case there was something in the code upgrade from v0.102.0 to v0.103.3 that may have flipped DHCP to enabled by default.

I'm not sure if my log file or config file are of any use here, but if so please let me know and I'll add them.

**Comment by ameshkov** [comment] 2020-08-12 08:30
I don't really understand how this happened, @szolin we should examine the upgrade code carefully one more time.

**Comment by szolin** [comment] 2020-08-12 09:42
> Couldn't start listening socket

I wonder who set the interface name for dhcp?  I doubt that we could automatically pick a valid interface on your system.
Can you show the rest of dhcp config in your yaml file?
Anyway, I couldn't reproduce the issue.

**Comment by AnthonyBe** [comment] 2020-08-13 02:52
DHCP Config:

```
dhcp:
  enabled: false
  interface_name: vEthernet (Hyper-V Virtual Switch)
  gateway_ip: 192.168.0.1
  subnet_mask: 255.255.255.0
  range_start: 192.168.0.2
  range_end: 192.168.0.99
  lease_duration: 604800
  icmp_timeout_msec: 0
```
I had played around when the feature was first introduced, but then discovered it didn't work on Windows. That explains why there is some local configuration in there.

Given it isn't possible to enable DHCP on a Windows machine through the UI, it could only have occurred through (i) manual edit, or (ii) programmatic edit through AGH update?

**Comment by ameshkov** [comment] 2020-08-13 09:17
> Given it isn't possible to enable DHCP on a Windows machine through the UI, it could only have occurred through (i) manual edit, or (ii) programmatic edit through AGH update?

Yeah, that's right.

**Comment by szolin** [comment] 2020-08-18 11:06
Closing this issue because I can't reproduce it.

**Closed by szolin** 2020-08-18 11:06 UTC
Labels: P3: Medium, bug
