### ISSUE TITLE
friendly names don't work anymore

### ISSUE THREAD

**Issue by tborychowski** [AdguardTeam/AdGuardHome#1719] opened 2020-05-22 09:48 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version (v0.102.0, Docker)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
v0.102.0, Docker

* **How did you setup DNS configuration:**
irrelevant

* **Operating system and version:**
Docker on Ubuntu Server 19.10
`/etc/hosts` file is configured properly (using `extra_hosts` key of the `docker-compose.yml`)

### Expected Behavior
"Top Clients" box on the landing page should show the "Friendly names" instead of just IPs.

### Actual Behavior
"Top Clients" shows IPs only (since the last update)

**Comment by ameshkov** [comment] 2020-05-22 09:51
You'd like to get the names from /etc/hosts, right?

**Comment by tborychowski** [comment] 2020-05-22 11:02
Yes, as described here: https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#friendly-names

When I add `extra_hosts` list in my `docker-compose.yml` they get added to `/etc/hosts` file in the container (I confirmed that that file is populated correctly in the container).

It worked before and stopped yesterday when I updated to the latest version.

**Comment by ameshkov** [comment] 2020-05-22 11:05
Got it, thank you!

Alternatively, you can use "Clients" section.

**Comment by tborychowski** [comment] 2020-05-22 11:45
@ameshkov thanks that works fine.
I will use that instead :-)

**Comment by szolin** [comment] 2020-05-25 08:12
I think it's a duplicate of #1686
Probably there are tab characters in your `/etc/hosts` file

**Comment by tborychowski** [comment] 2020-05-25 09:04
@szolin I have not edited the `/etc/hosts` manually.
But I checked just now and there are no tab characters, only spaces.

**Comment by szolin** [comment] 2020-05-26 07:52
Do you see the clients names in `Client settings`, section `Clients (runtime)` ?

**Comment by tborychowski** [comment] 2020-05-26 09:22
No, the bottom table is empty.

**Comment by szolin** [comment] 2020-05-26 12:51
Please attach your hosts file (a few lines will suffice, but don't change the whitespace) and debug logs while restarting the server.

**Comment by tborychowski** [comment] 2020-05-26 22:43
@szolin thanks for your help.
- Here's my [debug.log](https://github.com/AdguardTeam/AdGuardHome/files/4685351/debug.log)
- and here's a snippet from the [hosts](https://github.com/AdguardTeam/AdGuardHome/files/4685353/hosts.txt) file

Note: When I restarted AGH I now do have tabs in this hosts file (previously there were just spaces).

**Comment by szolin** [comment] 2020-05-27 07:30
Thank you! So this is a duplicate of #1686.
Tabs are not supported in the latest release - we already fixed this issue and it will be available in the next version.

**Closed by szolin** 2020-05-27 07:30 UTC
Labels: P3: Medium, bug
