### ISSUE TITLE
Statistics / logfile cannot be deleted by user as before. Why?

### ISSUE THREAD

**Issue by ulimanske** [AdguardTeam/AdGuardHome#4974] opened 2022-09-30 12:44 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Other (please mention in the description)

### CPU architecture

ARMv7

### Installation

Other (please mention in the description)

### Setup

On one machine

### AdGuard Home version

v0.107.14

#### Screenshots (if applicable)
![grafik](https://user-images.githubusercontent.com/43108001/193272314-d4d55136-566d-4fd4-b8e2-f5ee276aed0b.png)

#### Additional information
Tried to delete the "blocked domains" in the query protocol - get error: "Error: control/querylog_clear | only application/json is allowed | 415" - it was working until I installed the new version

**Comment by ainar-g** [comment] 2022-09-30 13:02
Duplicate of #4970

**Closed by ainar-g** 2022-09-30 13:02 UTC
