### ISSUE TITLE
［Feature Request］want Domain name pre-fetch & auto-refresh if TTL reach to zero

### ISSUE THREAD

**Issue by icesof** [AdguardTeam/AdGuardHome#2449] opened 2020-12-16 08:33 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [√] I am running the latest version
- [√] I checked the documentation and found no answer
- [√] I checked to make sure that this issue has not already been filed

### Problem Description
Used the "Fastest IP address" in Upstream DNS servers, mixed with multiple DNS server & upcoming statistics collection on fastest IP address. So, the it cost higher response time compare with other option. The peak will happened again and again if cached entity's TTL reach zero.

### Proposed Solution
Domain name pre-fetch, more faster to access popular websites.
Voting with most popular domain with pre-fetch function during service restart and TTL reach zero.

**Comment by ameshkov** [comment] 2020-12-16 08:37
Prefetch is rather complicated, I'd prefer #2145 instead.

Anyways, this is a duplicate of #1259

**Closed by ameshkov** 2020-12-16 08:37 UTC
