### ISSUE TITLE
More analytics for Adguard Home (Traffic Destination, apps, etc)

### ISSUE THREAD

**Issue by vstevenphan** [AdguardTeam/AdGuardHome#3377] opened 2021-07-25 15:30 UTC
I'm using NextDNS.io and it has very useful dashboard/analytics including Traffic Destinations, etc
I hope Adguard Home also have this analytics on the main page
https://imgur.com/jBJ2tQO
![Capture](https://user-images.githubusercontent.com/10742539/126904577-1e9597cf-3386-426e-885f-c6517304108d.PNG)

**Comment by hoshsadiq** [comment] 2021-07-27 04:22
In my opinion you should export this data to something else. AGH already collects this data, but adding complexity for this stuff isn't necessary because that's not what AGH is. There are better tools for analytics.

**Comment by Disqu3-mirOir-qt** [comment] 2021-07-27 09:27
Adguard target privacy , added more analytics realy don,t like idea

**Comment by Aikatsui** [comment] 2021-12-22 16:35
> Adguard target privacy , added more analytics realy don,t like idea

This is an on-premise software :smile:
(It'll be possible to enable/disable too)

**Comment by Aikatsui** [comment] 2021-12-22 17:23
Duplicate of #1605 #750

**Comment by ainar-g** [comment] 2021-12-22 17:58
Duplicate of #1605

**Closed by ainar-g** 2021-12-22 17:58 UTC
