### ISSUE TITLE
Can't remove AdAway blocklist on Edge

### ISSUE THREAD

**Issue by devipasigner** [AdguardTeam/AdGuardHome#5700] opened 2023-04-09 19:48 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.508+15bba281

#### What did you do?

Fresh install AdGuard Home Edge Build, go to blocklist tab, and remove both default blocklists.

#### Expected result

Both the AdGuard DNS filter and AdAway blocklist are removed.

#### Actual result

Only AdGuard DNS filter is able to removed. AdAway remains, and cannot be removed no matter what.

#### Screenshots (if applicable)

Nah.

#### Additional information

Another question, why is this blocklist even selected by default? Theres no point in adding it if its in a disabled state. If users want to use the AdAway blocklist they can select it through the "Choose from the list" options, just like every other blocklist. What makes AdAway so special?

**Comment by ainar-g** [comment] 2023-04-10 10:06
We cannot reproduce this behavior, although it could be caused by #5647.  When you say that “AdAway remains”, do you mean that you see it there after a page refresh, or does it not disappear at all?

 >  Another question, why is this blocklist even selected by default?  \[…\]

Please direct questions to the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions), as we strive to keep the Issues section dedicated to bugs and improvements only.

**Comment by Mizzick** [comment] 2023-06-22 13:32
Please have a look, the requested changes have been implemented.
The new build version=v0.108.0-a.578+66345e85 has been just published to the edge channel.

**Comment by ainar-g** [comment] 2023-06-27 10:21
We'll close this issue for now.  Please feel free to tell us if the issue isn't fixed for you.

**Closed by ainar-g** 2023-06-27 10:21 UTC
Labels: bug, P3: Medium
