### ISSUE TITLE
[Feature request] Block page

### ISSUE THREAD

**Issue by lordraiden** [AdguardTeam/AdGuardHome#830] opened 2019-06-13 06:08 UTC
Can we have a block page like pfblockerng has
https://forum.netgate.com/topic/143872/customizing-error-page

It would be nice if from that page we could temporarily allow or whitelist after logging in Adguard a kind of shortcut

**Comment by ameshkov** [comment] 2019-06-13 07:37
Duplicate of #454

**Closed by ameshkov** 2019-06-13 07:37 UTC
Labels: duplicate
