### ISSUE TITLE
I can not see client details in dark mode

### ISSUE THREAD

**Issue by ngosang** [AdguardTeam/AdGuardHome#5413] opened 2023-01-28 12:51 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.22

#### What did you do?
I can not see client details in dark mode

![image](https://user-images.githubusercontent.com/10577978/215267298-3b2f31c4-367c-4d49-a656-b1cef7a072c5.png)

**Comment by wwng2333** [comment] 2023-01-29 15:49
meet same problem here.
![image](https://user-images.githubusercontent.com/17147265/215338136-3bc62620-89a7-4b1e-bf73-54c45277f5e0.png)

**Comment by ainar-g** [comment] 2023-02-01 14:35
Duplicate of #5375

**Closed by ainar-g** 2023-02-01 14:35 UTC
