### ISSUE TITLE
Error in setup process

### ISSUE THREAD

**Issue by JJGO** [AdguardTeam/AdGuardHome#4000] opened 2021-12-23 18:23 UTC
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * Latest
* **How did you install AdGuard Home:**
  * With the curl script
* **CPU architecture:**
  * ARMv7 (RPi4)
* **Operating system and version:**
  * Raspbian 10 buster

### Expected Behavior
Setup process should work

### Actual Behavior
Unable to go beyond step 3, it goes back to step 2 with a red error popup saying `Error: control/install/check_config | Network Error`

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/3844846/147278488-c65c00f4-c39a-444f-983a-32cd587af01b.png)

</details>

### Additional Information
This ran perfectly last time I installed it on this machine and OS, so I'm not sure what I could be doing wrong.

I also tried uninstalling and then installing the `beta` branch but got the same error.

**Comment by ainar-g** [comment] 2021-12-23 18:29
Duplicate of #3987

**Comment by EugeneOne1** [comment] 2021-12-23 18:30
Probably a dup of #3987, should already be fixed in latest edge build.  I'll close it for now.

**Closed by ainar-g** 2021-12-23 18:29 UTC
