### ISSUE TITLE
Add DuckDuckGo safety search rule

### ISSUE THREAD

**Issue by furunos** [AdguardTeam/AdGuardHome#603] opened 2019-02-27 05:26 UTC
I'm glad that the safety search has worked again at v0.93.
I hope to add a safe search for DuckDuckGo.

```
--- AdGuardHome/dnsfilter/safesearch_orig.go
+++ AdGuardHome/dnsfilter/safesearch.go
@@ -14,6 +14,9 @@
 
 	"www.bing.com": "strict.bing.com",
 
+	"duckduckgo.com":     "safe.duckduckgo.com",
+	"www.duckduckgo.com": "safe.duckduckgo.com",
+
 	"www.google.com":    "forcesafesearch.google.com",
 	"www.google.ad":     "forcesafesearch.google.com",
 	"www.google.ae":     "forcesafesearch.google.com",
```

**Comment by ameshkov** [comment] 2019-02-27 07:56
Hm, have they finally added this option on a DNS level?

It's unclear from this thread if it was implemented or not:
https://www.reddit.com/r/duckduckgo/comments/8qwzyl/feature_request_allow_network_operators_for_force/

**Comment by ameshkov** [comment] 2019-02-27 07:56
Marking as duplicate of #268

**Closed by ameshkov** 2019-02-27 07:56 UTC
Labels: duplicate

**Comment by furunos** [comment] 2019-02-27 08:33
Thanks. I understood.
