### ISSUE TITLE
Client filter at Query Log doesnt work on name

### ISSUE THREAD

**Issue by HellStorm666** [AdguardTeam/AdGuardHome#1869] opened 2020-07-08 07:39 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ X ] I am running the latest version
- [ X ] I checked the documentation and found no answer
- [ X ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * V0.102.0
* **How did you setup DNS configuration:**
  * Debian Install
* **Operating system and version:**
  * Debian 10 x64

### Expected Behavior
Filtering at the Query Log, enter Device1 at the client filter part, I would expect that all devices that include the name Device1 would be listed there. If Device1 has 1 IPv4 and 3 IPv6 addresses I'd expect them all there.

### Actual Behavior
Filtering at the Query Log, enter Device1 at the client filter part, I get nothing. If i enter 123 I see Device1 with IP 192.168.1.123

### Additional Information
rDNS address (arpa) is configured and I doe see the device names (for IPv4)

**Comment by ameshkov** [comment] 2020-07-08 07:43
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/1273

**Closed by ameshkov** 2020-07-08 07:43 UTC
