### ISSUE TITLE
GUI elements or text config support for pointing to external SSL certificate and private keys.

### ISSUE THREAD

**Issue by ufufufu** [AdguardTeam/AdGuardHome#1037] opened 2019-09-30 15:12 UTC
With the latest version of Adguard Home (installed on a Linux dedicated server), if I want to enable HTTPS for the GUI, I will have to paste the contents of the certificate, and the private key, into two separate text fields. This can be cumbersome if I were to use short-lived SSL certificates like the ones from LetsEncrypt.

Therefore my feature request is to allow AdGuard Home to load the SSL certificate and the private keys from external files on the hard disk. Plus, I also hope that AdGuard Home can automatically load newer versions of the SSL certificate + private keys without needing to restart AdGuard Home service. 

Like this, I can script up acme.sh script to create LetsEncrypt certificate, then make it to install the certificate and the private key into a directory that Adguard Home can access, and then periodically renew it.

Thanks for the consideration.

**Comment by ameshkov** [comment] 2019-10-01 08:34
Duplicate of #634 

This feature is already available in the beta version

**Closed by ameshkov** 2019-10-01 08:34 UTC
