### ISSUE TITLE
[DNS-rewrite] - add the possibility to always apply it even when protection is off

### ISSUE THREAD

**Issue by scachemaille** [AdguardTeam/AdGuardHome#2211] opened 2020-10-21 19:23 UTC
- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Problem Description
Actually I use the DNS-rewrite option to be able to access different services with my FQDN that point to my external IP, because my router does not support reverse-NAT (access to my internal IP with my external IP and port forwarding).
I use the DNS-rewrite that map all the different service of my domain to the corresponding IP in my internal network,

The problem is if I turn off ADH protection, it also disable the DNS-rewrite entry and then all my service are resolved by external DNS and give my external IP then it does not work.

### Proposed Solution
To have the possibility to have fix DNS-rewrite that are still applied when protection is off.
for me the DNS-rewrite looks more like a local DNS  than a custom filtering. and I don't understand why it's deactivate when the protection is off. PiHole does not deactivate this option when we disable the protection. :thinking:

**Comment by KizunaH** [comment] 2020-10-24 13:20
Duplicate of #1558

**Comment by ameshkov** [comment] 2020-10-26 23:13
Merged into https://github.com/AdguardTeam/AdGuardHome/issues/1558

**Closed by ameshkov** 2020-10-26 23:13 UTC
Labels: duplicate
