### ISSUE TITLE
I suggest adding the option to disable caching for specific domain names in the DNS cache configuration.

### ISSUE THREAD

**Issue by gexiaopeng** [AdguardTeam/AdGuardHome#6116] opened 2023-08-19 03:05 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

My dynamic domain name's new IP resolution often experiences significant delays, resulting in ineffective access.

### Proposed solution

In DNS cache configuration, the ability to add a list of domain names to disable caching is added. At the same time, each request will dynamically call the upstream DNS to obtain the result, ignoring the TTL.

**Comment by fernvenue** [comment] 2023-08-20 06:26
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/4197.

**Closed** 2023-08-21 13:19 UTC
Labels: feature request
