### ISSUE TITLE
Support subdomain-based client configurations

### ISSUE THREAD

**Issue by alexzeitgeist** [AdguardTeam/AdGuardHome#780] opened 2019-05-27 18:15 UTC
Currently, AdGuard Home has only one configuration for every client. It'd be nice if we could define different configurations based on the requested subdomain. For example:

client1.adguarddns.com loads filters and/or settings as configured for client1
client2.adguarddns.com loads filters and/or settings as configured for client2
etc.

with
adguarddns.com being the default.

**Comment by ameshkov** [comment] 2019-05-27 22:49
Hm, this could be really useful for the VPS-hosted AGH.

**Comment by alexzeitgeist** [comment] 2019-06-01 17:32
@ameshkov I just saw the latest commits regarding support for "clients". Seems like now it's a lot easier to add subdomain-based client configurations... basically, we would need to add a textfield to add a subdomain in the client configuration, and in the backend parse the [Host request header](https://godoc.org/net/http#Request.Host). Of course, added logic would be needed, for example to avoid using the same subdomain for two different clients.

**Comment by ameshkov** [comment] 2019-06-03 09:00
"Clients" settings do look relevant to this feature request, but I don't think this is the same entity.

Also, I think it would be useful to allow having different configurations based on the different IP addresses (for those who use plain DNS).

> and in the backend parse the Host request header

This would limit this feature to DOH. In the case of DOH or DOT, we should read the TLS connection's SNI extension.

**Comment by ameshkov** [comment] 2021-01-13 09:38
Duplicate of #1383, to be implemented in v0.105

**Closed by ameshkov** 2021-01-13 09:38 UTC
Labels: duplicate
