### ISSUE TITLE
About more AdGuardHome ARM binaries

### ISSUE THREAD

**Issue by zxlhhyccc** [AdguardTeam/AdGuardHome#1239] opened 2019-12-07 06:44 UTC
The binary cannot run on arm castrated floating point arithmetic architecture, such as PHCOMM K3 routing, but armv5 binary can run on the arm of the castrated floating point arithmetic, proposed to arm architecture and provide different kinds of binary alone, making many binary on all is according to the armv5, armv6, armv7, armv8 compiled respectively download to use!!!

**Comment by ameshkov** [comment] 2019-12-08 18:44
That's possible, but it'd help if you create a pull request that makes necessary changes to https://github.com/AdguardTeam/AdGuardHome/blob/master/release.sh

Please don't change the naming of existing distribs, though.

**Comment by zxlhhyccc** [comment] 2019-12-10 10:35
> That's possible, but it'd help if you create a pull request that makes necessary changes to https://github.com/AdguardTeam/AdGuardHome/blob/master/release.sh
> 
> Please don't change the naming of existing distribs, though.

This script does not have the compiled code of armv5, can join the code of this architecture, so that the repository has the binary of armv5!

**Comment by zxlhhyccc** [comment] 2019-12-10 11:06
> That's possible, but it'd help if you create a pull request that makes necessary changes to https://github.com/AdguardTeam/AdGuardHome/blob/master/release.sh
> 
> Please don't change thaming of existing distribs, though.

It is recommended to compile arm architecture separately, such as armv5, armv6, armv7, armv8.

**Comment by ameshkov** [comment] 2019-12-10 17:28
Yeah, that's what I am talking about, please modify the script to add what's missing

**Comment by Mosney** [comment] 2019-12-14 20:42
@zxlhhyccc be patient and respect, no one has the responsibility to complete your request. And one more thing, try to some other translation software next time to better expression and communication.

**Comment by zxlhhyccc** [comment] 2019-12-18 15:00
> Yeah, that's what I am talking about, please modify the script to add what's missing

**Thank you very much for your answer!!**

**Comment by ArchiveBase** [comment] 2019-12-21 17:44
https://github.com/AdguardTeam/AdGuardHome/issues/1265

**Comment by JACK-THINK** [comment] 2019-12-31 02:09
The problem is easy to solve.

1. `vim AdGuardHome/release.sh`

2. Modify the line
   `CHANNEL=$channel GOOS=linux GOARCH=arm GOARM=6 f`
   to
   `CHANNEL=$channel GOOS=linux GOARCH=arm GOARM=5 f`

3. `release.sh`

4. `AdGuardHome/dist/AdGuardHome_linux_arm.tar.gz` is what you want.

**Comment by ameshkov** [comment] 2019-12-31 15:23
@szolin I've assigned this to v0.101.

Please note that we should change naming for the ARM builds

**Closed** 2020-01-15 15:58 UTC
Labels: P3: Medium, feature request, help wanted

**Comment by WildByDesign** [comment] 2020-01-16 15:44
Just a brief question regarding ARM binary downloads following the commits related to this issue report. The main AGH Github page _README.md_ has gotten a little bit confusing specifically for 32-bit ARM binary downloads.

It lists the following for 32-bit ARM:

- Raspberry Pi (32-bit ARMv6)
- Linux 32-bit ARMv5

I am an **ARMv7** user from OpenWrt and a relatively new user to AGH. My Linksys WRT3200acm router uses ARMv7 which is 32-bit ARM as well. I am actually running the Raspberry Pi (32-bit ARMv6) AGH binary and runs well.

I think that the documentation could be clarified a bit more. Maybe the download lists should read as such:

- Raspberry Pi (32-bit ARMv6 / ARMv7)
- Linux 32-bit ARMv5

Thank you for your time. :)

**Comment by ameshkov** [comment] 2020-01-16 17:56
Well, on ARMv7 you can run any binary including v5 and v6.
