### ISSUE TITLE
Error: control/filtering/refresh | Network Error When more than 38 blacklists are active new!

### ISSUE THREAD

**Issue by merj1928** [AdguardTeam/AdGuardHome#2682] opened 2021-02-14 05:15 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

### Issue Details:

If more than 38 blacklists are active in AdGuard Home I get this error message: 
Error: control/filtering/refresh | Network Error

* **Version of AdGuard Home server:**
  *  v0.105.0
* **How did you install AdGuard Home:**
  *  Raspberry Pi Guide here.
* **How did you setup DNS configuration:**
  *  Ubuntu Server, Asus RT AC68U Router
* **If it's a router or IoT, please write device model:**
  *  Raspberry Pi 3 Model B
* **Operating system and version:**
  *  Ubuntu Server (last)

### Actual Behavior
 If more than 38 blacklists are active in AdGuard Home I get this error message:  Error: control/filtering/refresh | Network Error 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by merj1928** [comment] 2021-02-14 05:19
@ainar-g  Sorry !!!
https://github.com/AdguardTeam/AdGuardHome/files/5976037/AdguardDebug.txt

**Comment by DandelionSprout** [comment] 2021-02-15 02:17
It doesn't seem to me personally like the problem is universal to all AGH installations, as my setup on a Raspberry Pi 4 4GB has 39 blacklists and seems able to refresh as normal.

**Comment by dioey** [comment] 2021-02-15 03:43
@DandelionSprout it because unbound as DNS Resolver, AdGuard Home Version: 0.104.3 doesn't have this error, best solution for now is to stick with Version: 0.104.3

**Comment by DandelionSprout** [comment] 2021-02-15 04:33
Okay, so it turns I had 3 of my lists turned off at the time of testing. After adding 3 more lists on my end, I now receive the exact same error that the OP got.

**Comment by dioey** [comment] 2021-02-15 04:41
@DandelionSprout interesting, are using unbound too? I thought only who using unbound have this error, AdGuard Home v0.105.0 have a lot of bug

**Comment by DandelionSprout** [comment] 2021-02-15 04:42
I am not using Unbound that I know of.

**Comment by merj1928** [comment] 2021-02-15 11:28
> @DandelionSprout interesting, are using unbound too? I thought only who using unbound have this error, AdGuard Home v0.105.0 have a lot of bug

With or without unbound. The error occurs when you update the lists manually.
However, it seems that they are updated during the automatic update.

**Comment by dioey** [comment] 2021-02-15 11:31
@merj1928 yeah I see the log filter update correctly, not sure what causing that error

**Comment by ainar-g** [comment] 2021-02-15 18:07
@merj1928, @dioey, we've published some fixes in the new v0.105.1.  It should be on all channels now.  Please let us know if these fixes resolve or alleviate the issue.  Thanks!

**Comment by merj1928** [comment] 2021-02-15 21:59
> @merj1928, @dioey, we've published some fixes in the new v0.105.1.  It should be on all channels now.  Please let us know if these fixes resolve or alleviate the issue.  Thanks!

All clear. Thank you very much.

**Comment by dioey** [comment] 2021-02-15 22:14
@ainar-g wow thanks it fixed now manual update filter no more error 😁😁

**Comment by merj1928** [comment] 2021-02-15 23:40
> @merj1928, @dioey, we've published some fixes in the new v0.105.1.  It should be on all channels now.  Please let us know if these fixes resolve or alleviate the issue.  Thanks!

The manual update, again brings the same error message

**Comment by merj1928** [comment] 2021-02-15 23:40
> @ainar-g wow thanks it fixed now manual update filter no more error 😁😁

The manual update, again brings the same error message. ???

**Comment by dioey** [comment] 2021-02-15 23:48
@merj1928 I think it fixed now, the problem for me before is after update too version v0.105.0 it cant manual update the DNS Blocklist filter, but v0.105.1 already fix this problems

**Comment by DandelionSprout** [comment] 2021-02-16 00:18
I can confirm that v0.105.1-beta.1 fixed the problem on my end, if I'm not seeing completely wrong.

**Comment by merj1928** [comment] 2021-02-16 09:33
Ok after a reboot, it seems to work now.

**Comment by ainar-g** [comment] 2021-02-16 10:12
Thank you all for testing!  Please file new issues if you find anything wrong.

**Closed by ainar-g** 2021-02-16 10:12 UTC
Labels: P2: High, bug
