### ISSUE TITLE
Remove from ,, Safe Search '' Youtube Restriction and create a separate section for it with the name ,, YouTube Restricted Mode '' as in AdGuard DNS.

### ISSUE THREAD

**Issue by NostalgicNeverGonnaGiveYouUp** [AdguardTeam/AdGuardHome#6055] opened 2023-07-29 13:44 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

When you enable safe search, it automatically blocks chat on YouTube.

### Proposed solution

Remove restrictions for YouTube from ,, SafeSearch '', and create a separate section in which the person himself decides if he wants to enable SafeSearch on YouTube.

### Alternatives considered and additional information

Create an additional section: Enable YouTube SafeSearch.

**Comment by ainar-g** [comment] 2023-07-31 10:26
Duplicate of #5659

**Closed by ainar-g** 2023-07-31 10:26 UTC
Labels: feature request
