### ISSUE TITLE
It is hoped that configuration export and import can be added

### ISSUE THREAD

**Issue by 1432447293** [AdguardTeam/AdGuardHome#6694] opened 2024-02-01 07:00 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

1. Reinstalling and restoring the configuration is troublesome.
2. When visiting websites such as baidu.com from China, they are matched to international server IP addresses.

### Proposed solution

1. Added configuration export and import function, which can be quickly restored when reinstalling or crashing.
2. Optimize the dns response. Can you separately configure domestic websites to use domestic dns and international websites to use international dns to facilitate quick access to the website? Currently, it is often the case that visits from China are matched to international server IPs.

**Comment by ainar-g** [comment] 2024-02-01 11:39
Duplicate of #1147

**Closed by ainar-g** 2024-02-01 11:39 UTC
Labels: feature request
