### ISSUE TITLE
Unable to start service "AdGuardHome.service: Failed with result 'exit-code'."

### ISSUE THREAD

**Issue by uncovery** [AdguardTeam/AdGuardHome#2538] opened 2021-01-11 11:46 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Issue Details

It's a freshly installed instance. I ran the install script, could access the website, did some (IMHO) trivial system settings. I logged out and my password would not work anymore. Assuming that I made a mistake when adding the password to my password manager, I reset the password in the .yaml file and tried to restart the service. this failed. starting it via commandline worked and I was able to login to the website again, but I was not able to start the service since then.

* **Version of AdGuard Home server:**
  * AdGuard Home, version 0.104.3, channel release, arch linux amd64
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * Linksys Velop
* **Operating system and version:**
  * CentOS Stream

### Expected Behavior
Starting the AdGuard Home server with `systemctl start AdGuardHome` should start the Daemon. 

### Actual Behavior
It does not. It did so on the first start (after running the install script) but now it does not do so anymore 

````
# systemctl status AdGuardHome
● AdGuardHome.service - AdGuard Home: Network-level blocker
   Loaded: loaded (/etc/systemd/system/AdGuardHome.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2021-01-11 06:39:17 EST; 9s ago
  Process: 2584750 ExecStart=/opt/AdGuardHome/AdGuardHome -s run (code=exited, status=200/CHDIR)
 Main PID: 2584750 (code=exited, status=200/CHDIR)

Jan 11 06:39:17 localhost.localdomain systemd[1]: AdGuardHome.service: Main process exited, code=exited, status=200/CHDIR
Jan 11 06:39:17 localhost.localdomain systemd[1]: AdGuardHome.service: Failed with result 'exit-code'.
````

Starting `/opt/AdGuardHome/AdGuardHome -s run` works fine however, of course then it's not running in the background.

**Comment by ameshkov** [comment] 2021-01-11 20:36
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by uncovery** [comment] 2021-01-12 01:35
Thanks a lot for helping with this issue.

So I just figured it out. Turns out that the service would not even create a logfile. So I went and dissected your install script and ultimately looked at the /etc/systemd/system/AdGuardHome.service file.

There was a line called "Workingdirectory=.... " 

so when I first ran the install script, I was not sure if it will download something that will be in continuous use, so I created a directory for AdGuard and ran the install script from there. Since the directory was empty after installing it, I deleted it later again, thinking it was not used.

Turns out it was set as the "Workingdirectory" in the .service file and that directory not existing broke everything.
I set that directory now to be /opt/AdGuardHome and everything works again.

I am not sure if I did something wrong and I am not sure what sets the this parameter in the .service file, if that is done by you or Linux. However I think this should not be as it is. Either the docs should define where to start the installscript from (e.g. "Run the following command in your terminal from your /root directory". or the Workingdirectory should be set to something that is guaranteed to exist such as /temp, or whatever. Just my 2 cents.

**Comment by ameshkov** [comment] 2021-01-12 09:25
Tbh, this sounds like a legit bug, thank you for looking into it!

**Comment by uncovery** [comment] 2021-01-12 09:26
glad to have helped 👍

**Comment by EugeneOne1** [comment] 2021-04-14 10:35
@uncovery, hello again!  It seems that the issue you faced was luckily solved along with the work on v0.106.0.  Could you please try to install _AdGuard Home_ via the script and check if the working directory is set properly?

**Comment by uncovery** [comment] 2021-04-15 05:00
I have it up and running now, how do I do this without messing with my existing install?

**Comment by EugeneOne1** [comment] 2021-04-15 07:48
In case you running the line exactly copied from our _README.md_, i.e. `curl -sSL https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh`, it's actually using the script version from the latest commit in the `master` branch, so it doesn't depend on the release.Anyway, you could try to reproduce the issue on any other device.

**Comment by EugeneOne1** [comment] 2021-04-20 13:52
We'll close this issue for now.  Please feel free to reopen it if our solution won't fix the problem for you.

**Closed by EugeneOne1** 2021-04-20 13:52 UTC
Labels: P3: Medium, bug, needs investigation

**Comment by kettly1260** [comment] 2021-05-01 03:37
> We'll close this issue for now. Please feel free to reopen it if our solution won't fix the problem for you.

I still faced this problem on centos 8.

AdGuardHome.service - AdGuard Home: Network-level blocker
   Loaded: loaded (/etc/systemd/system/AdGuardHome.service; enabled; vendor preset: disabled): 2048 ki   Active: activating (auto-restart) (Result: exit-code) since Sat 2021-05-01 03:30:36 UTC; 875ms agoi  Process: 46572 ExecStart=/usr/local/bin/AdGuardHome -s run (code=exited, status=209/STDOUT)
 Main PID: 46572 (code=exited, status=209/STDOUT):]:784

**Comment by ainar-g** [comment] 2021-05-04 13:12
@kettly1260, hello and thank you for the report.  Please open a new issue about your problem and fill all fields of the issue template so that we could properly investigate the issue.  Also, please make sure that you are installing the most recent version of AGH.

**Comment by yueyue5201314** [comment] 2024-04-09 06:46
You can use the Linux command that has been issued to directly run Adg to see why the service has exited. I also encountered the same problem, and after running it, I found that it was a port occupancy issue. It has now been resolved!
`/opt/AdGuardHome/AdGuardHome - s run`
