### ISSUE TITLE
Summary of valid domains among all the block lists

### ISSUE THREAD

**Issue by lordraiden** [AdguardTeam/AdGuardHome#1476] opened 2020-03-14 17:43 UTC
It would be nice to have a summary of how many domains are valid among all the block lists added to adguard. So repeated, invalid, etc. are not considered.
Somehow like pihole does
![imagen](https://user-images.githubusercontent.com/17175395/76687388-bbde0680-6623-11ea-93d5-f0c9e178e5d9.png)

**Comment by ArchiveBase** [comment] 2020-03-15 00:45
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/400#issuecomment-533940085 https://github.com/AdguardTeam/AdGuardHome/issues/1364

> how many domains are valid among all the block lists added to adguard. So repeated, invalid, etc. are not considered.

https://github.com/AdguardTeam/AdGuardHome/issues/1450 (only for local lists)

**Comment by ameshkov** [comment] 2020-03-16 09:53
Marked as dup.

We'll try to take it into account when we'll be redesigning filters settings (which is necessary to implement #1325 )

**Closed by ameshkov** 2020-03-16 09:53 UTC
Labels: duplicate
