### ISSUE TITLE
ADH ignores external Whitelist rules

### ISSUE THREAD

**Issue by ExternalDatabase** [AdguardTeam/AdGuardHome#2431] opened 2020-12-13 12:44 UTC
### Issue Details

* **Version of AdGuard Home server:**
  * v0.104.3
* **How did you setup DNS configuration:**
  * IoT
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 3 Model B
* **Operating system and version:**
  * Raspbian 10 (buster); ADH is running within Docker

### Expected Behavior
Adguard Home should understand and apply external whitelist rules over the blocking ones.

### Actual Behavior
I have one external whitelist in section Filters > DNS allowlists
That list is hosted on GitHub (domain https://gist.githubusercontent.com/...) and has Adb format checked with Adguard Home documentation.
It's enabled, refreshing every 12 hours and Adguard Home shows correct number of rules (60) and correct last time updated.
Rules inside that list are 100% correct (checked in docs) and sometimes copy-pasted from Filters > Custom filtering rules (after that removed from custom list).

Adguard Home uses custom blocklist i.e. to block Microsoft telemetry, so the address **login.live.com** is blocked.
I need it to be not blocked, so I clicked on "Unblock" button on Querylist, then I went to Filters > Custom filtering rules and copied that entry from custom rules to my Github-hosted whitelist with that syntax:
**@@||login.live.com^$important**
After that I updated Adguard Home allowlists. I see the domains count got +1, update time refreshed and when I clicked on link it shows me the actual list with that rule present.

I flushed DNS on my PC and browser and it passed (OK) until next scheduled lists refresh time.
It stopped working next day (query of domain login.live.com is blocked again).

**Comment by ameshkov** [comment] 2020-12-14 07:55
If you're using `@@`-kind of rules (which "allow" content by themselves), you don't have to use "Allowlists". On the contrary, you can simply use "Blocklists" and your custom list there. This way you can use your list not just to unblock stuff, but to block as well.

Regarding the original issue, I am not able to reproduce it on my side.

Do you still have the rule on your list?
Could you please share the list with us so that we could try to reproduce this?
Or maybe create a new one (with which the issue is reproduced) and share it?

**Comment by EugeneOne1** [comment] 2020-12-18 11:44
We're closing this issue for now. Please feel free to reopen it if our solution won't solve it.

**Closed by EugeneOne1** 2020-12-18 11:44 UTC
Labels: question
