### ISSUE TITLE
Logs export features

### ISSUE THREAD

**Issue by JuanRodenas** [AdguardTeam/AdGuardHome#5022] opened 2022-10-10 08:00 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
Hello Adguard,

I open this request, so that you implement the option to export the logs. That option that can be exported in dates, would be a valuable option.

Sincerely, Juan

**Comment by ainar-g** [comment] 2022-10-11 11:21
Duplicate of #3389

**Closed by ainar-g** 2022-10-11 11:21 UTC
