### ISSUE TITLE
H3 upstream servers are not denoted as such in Query Log

### ISSUE THREAD

**Issue by agneevX** [AdguardTeam/AdGuardHome#6102] opened 2023-08-13 05:34 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer
- [X] I have searched other issues and found no duplicates
- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)
- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Docker arm64

### AdGuard Home version

0.108.0-a.650+c54635e8

### Additional information and/or screenshots

AdGuard Home shows upstream resolvers starting with `https` when `h3` is specifically used.

<img width="608" alt="Screenshot 1" src="https://github.com/AdguardTeam/AdGuardHome/assets/19761269/3ec28832-6528-41dd-bf09-ad23a293c2fc">

<img width="622" alt="Screenshot 2" src="https://github.com/AdguardTeam/AdGuardHome/assets/19761269/a30354f2-48e1-477c-81bc-7c77056b1957">

**Comment by ainar-g** [comment] 2023-08-14 11:17
Duplicate of #5501

**Closed by ainar-g** 2023-08-14 11:17 UTC
