### ISSUE TITLE
Add Geo-Restriction for clients based on Source IP

### ISSUE THREAD

**Issue by L8X** [AdguardTeam/AdGuardHome#5808] opened 2023-05-07 12:55 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?

I'm sure we're all aware, most DNS requests coming from places like Russia, China, North Korea, or Iran, are usually abuse, so blocking them is a good security benefit to prevent things like DoS / DDoS.

#### Proposed solution

Add the ability to use built in AdGuard GeoIP system to drop queries from clients based on ISO country code (eg: RU, CN, IR, NK)

#### Alternatives considered

N/A (The only way this is logically possible is doing it via AGH itself)

#### Additional information

N/A

**Comment by ainar-g** [comment] 2023-06-27 10:40
Duplicate of #1487

**Closed by ainar-g** 2023-06-27 10:40 UTC
