### ISSUE TITLE
Add graph for blocked queries per blocklsit

### ISSUE THREAD

**Issue by GeorgeG92** [AdguardTeam/AdGuardHome#6651] opened 2024-01-19 12:31 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

It would be nice to be able to see blocked queries grouped by blocklist, just like on nextdns.io ('Blocked Reasons'). That way a user could get feedback about the performance of each blocklists that he/she is using. 

### Proposed solution

That could either be a matrix of ['Blocklist': CountQueriesBlocked] 
e.g.

1hosts (Lite) : 19572
AdGuard DNS filter: 10248
etc

or a Piechart which also shows relative measures.

**Comment by ainar-g** [comment] 2024-01-22 11:05
Duplicate of #4524

**Closed by ainar-g** 2024-01-22 11:05 UTC
Labels: feature request
