### ISSUE TITLE
Add picture in place of blocked ad

### ISSUE THREAD

**Issue by gnimor** [AdguardTeam/AdGuardHome#1359] opened 2020-01-17 15:20 UTC
To be honest, this is not a bug but perhaps a feature. I am just wondering if it is possible to add an image in place of the blocked ad. I checked the configuration but I didn't find anything which sounds like what I want to achieve.

**Comment by ameshkov** [comment] 2020-01-19 13:25
It looks like a duplicate of #1121.

You can achieve this already, but you'll need to set up a separate "pixel server" first:

1. Set up a pixel server
2. Configure blocking mode in AdGuard Home to return the IP address of your pixel server

**Closed by ameshkov** 2020-01-19 13:25 UTC
Labels: duplicate
