### ISSUE TITLE
Query log UI issue on tablet device

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardHome#4775] opened 2022-07-24 19:47 UTC
* **Version of AdGuard Home server:** v0.108.0-a.119+1c89394a

### Actual Behavior

On iPad, Block button covers client name, and it is hard to press client IP or the name

Better use the same popup as on mobile phone design, when press/click the log item.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/180663172-7250ec7d-2ddc-46a8-9b72-a58e2fa16250.png)

</details>

**Comment by laughtLOOL** [comment] 2022-07-27 16:16
That not only for iPad, on the any mobile or even PC on small size webiste, when the feature column  on the top left need to click to open, that would have that issue

**Comment by ainar-g** [comment] 2022-08-03 12:58
We've made some improvements in 053bb72 and a few other commits.  The new design (#2554) should not have these issues, so we'll close this one for now.

**Closed by ainar-g** 2022-08-03 12:58 UTC
Labels: bug, P4: Low, UI

**Comment by agneevX** [comment] 2022-08-03 14:39
Hello,

This is quite a bad UI change. Earlier I could tap the question glyphs to hover over the information. 
Now it straight away opens a modal meant for mobile devices with no apparent way to close them. This also spans across the entire screen.

This modal pops up when I tap just about anywhere in Query Log.

![image](https://user-images.githubusercontent.com/19761269/182634555-0db99f49-c645-4f92-bd1e-1351a0ea7d3a.png)

This is also quite buggy. If I simulate a tablet device on desktop, click _anywhere_, close the modal by pressing Esc and immediately hover over a question glyph, it shows the box.

**Comment by ainar-g** [comment] 2022-08-03 14:45
@agneevX, clicking outside of the modal closes it for me.  Is that not the case for you?  Although, I personally would also add an explicit :x: button.

 >  This modal pops up when I tap just about anywhere in Query Log.

I cannot reproduce that.  For me, it only opens when I click on a query log record.

Can you file a new issue, including your OS/browser and the viewport size in the Additional section?  Thanks.
