### ISSUE TITLE
 Error: control/only application/json is allowed | 415

### ISSUE THREAD

**Issue by 911realdeb** [AdguardTeam/AdGuardHome#4978] opened 2022-10-01 11:58 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

ARMv7

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

Version: v0.107.14

#### What did you do?
clear log
#### Expected result
clear log
#### Actual result
Error: control/stats_reset | only application/json is allowed | 415

Error: control/querylog_clear | only application/json is allowed | 415

#### Screenshots (if applicable)
![Capture d’écran 2022-10-01 075619](https://user-images.githubusercontent.com/114809426/193408448-57edc273-1732-4035-8e0e-738ef2949dea.png)

**Comment by wolkenschieber** [comment] 2022-10-01 20:21
Seems to be a general error. I'm getting the same message when trying to change _General settings_ -> _Use Safe Search_, and others.

**Comment by wolkenschieber** [comment] 2022-10-02 08:33
The lastest version working for me is `v0.107.13`, latest (`v0.107.14`) and beta (`v0.108.0-b.16`) are showing error _415_.

**Comment by wolkenschieber** [comment] 2022-10-02 09:50
Duplicate of #4970

**Comment by Zer0Gideon** [comment] 2022-10-02 16:28
I fixed this error with edit parameter from false to true in AdGuardHome.yaml file
safebrowsing_enabled: true

**Comment by photomme** [comment] 2022-10-03 08:35
Getting some issue.

**Closed** 2022-10-03 11:50 UTC
Labels: duplicate
