### ISSUE TITLE
v0.106.0 failes to start in combination with portainer (Docker) and custom macvlan network (+ IPv6)

### ISSUE THREAD

**Issue by darkman1983** [AdguardTeam/AdGuardHome#3030] opened 2021-04-29 07:00 UTC
* **Version of AdGuard Home server:**
  * v0106.0
* **How did you install AdGuard Home:**
  * Portainer (Docker) custom network macvlan
* **How did you setup DNS configuration:**
  * PI 4 +Portainer (Docker)
* **If it's a router or IoT, please write device model:**
  * PI 4 B
* **CPU architecture:**
  * ARM
* **Operating system and version:**
  * Raspbian latest

### Expected Behavior
Adguard Home starts and keeps running

### Actual Behavior
Adguard Home doesn't start successfully, version 0.105.0 worked fine. I get the following error for IPv6:
2021/04/29 06:47:09 [fatal] dnsServer.Prepare: setting up resolvers: systemResolvers: lookup test1619678829794219268.org on [fe80::42:c0ff:fea8:107%eth0]:53: parsing "fe80::42:c0ff:fea8:107%eth0": the passed string is not a valid IP address

### Screenshots
Will provide them later, if needed.

<details><summary>Screenshot:</summary>

</details>

**Comment by EugeneOne1** [comment] 2021-04-29 11:33
Is this a duplicate of #3022?

**Comment by darkman1983** [comment] 2021-04-29 11:51
yes, it is, damn i've searched, but the title of the problem differs so much, i haven't found it.
Shame on me 😁

**Comment by ainar-g** [comment] 2021-04-29 11:53
Thanks for checking!  We'll release v0.106.1 in the nearest future, and that should fix your issue as well.  We'll close this issue for now.

**Closed by ainar-g** 2021-04-29 11:53 UTC
