### ISSUE TITLE
"Check filtering" does not display all lists domain is in

### ISSUE THREAD

**Issue by 4d62ext** [AdguardTeam/AdGuardHome#6964] opened 2024-05-03 18:56 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v107.48

### Action

1. Create two or more filter lists with the same domain. Ex: `self.events.data.microsoft.com` and load those lists into AdGuard
2. Enter the domain in the "check the filtering" page
3. Only one of the lists should be shown

### Expected result

2 lists should be shown 

### Actual result

Only one list is shown (screenshot)

### Additional information and/or screenshots

![IMG_0125](https://github.com/AdguardTeam/AdGuardHome/assets/157558804/8555ea71-fecb-4e5b-ab8f-57ad1f87a456)

**Comment by tjharman** [comment] 2024-05-04 02:15
I'm not 100% sure this will be considered a bug, as I'm not sure the intended behaviour when you have multiple lists with the same entries.   I have however marked it as such and we'll see what the devs say.  Thanks for reporting.

**Comment by EugeneOne1** [comment] 2024-05-06 11:16
Looks like a duplicate of #4028.  As for the query log, it actually shows the rules applied, so it should not be ambiguous.

**Closed by EugeneOne1** 2024-05-06 11:16 UTC
Labels: bug
