### ISSUE TITLE
Force clean optimistic DNS cache

### ISSUE THREAD

**Issue by hexclann** [AdguardTeam/AdGuardHome#4349] opened 2022-03-02 05:41 UTC
I have optimistic DNS cache enabled on my Adguard v0.107.4 when I clear statistics and query logs, DNS cache will not be cleared. Is there any way to purge the DNS cache?

**Comment by ainar-g** [comment] 2022-03-02 11:36
This is a duplicate of #1905.  Currently, the workaround is to set the cache size value to `0` and then reset it back to the desired value.

**Closed by ainar-g** 2022-03-02 11:36 UTC
