### ISSUE TITLE
Query Log "."

### ISSUE THREAD

**Issue by Suspectxyzz** [AdguardTeam/AdGuardHome#6426] opened 2023-11-15 15:17 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

FreeBSD, ARMv7

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

 v0.108.0-b.49

### Action

```sh
nslookup -debug -type=a 'www.example.com' '$YOUR_AGH_ADDRESS'
```

### Expected result

I don't know how it affects, but it's definitely a bug

### Actual result

I think I've seen this one before but I can't find the post anymore

### Additional information and/or screenshots

![1](https://github.com/AdguardTeam/AdGuardHome/assets/45514952/3538e92b-e266-4b75-a0cb-f0d2f09ebbf6)
![image](https://github.com/AdguardTeam/AdGuardHome/assets/45514952/b3c1919a-aad5-4b46-9966-4b484dd2cb0d)
![image](https://github.com/AdguardTeam/AdGuardHome/assets/45514952/68df664b-0976-4f94-be98-7c8cebc07703)

**Comment by ainar-g** [comment] 2023-11-16 10:38
Duplicate of #5995

**Comment by ainar-g** [comment] 2023-11-16 10:39
While it's not an `NS` query, it is most likely that these are real queries made by a client in your network.

**Closed by ainar-g** 2023-11-16 10:38 UTC
