### ISSUE TITLE
可否增加日志的多条件查询啊？

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardHome#5810] opened 2023-05-08 12:48 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Description

I am sorry my english is so poor,so I have to write this in chinese.
在指定了客户端的情况下，增加条件也无法进一步搜索。通过上面的图片可以看到，192.168.1.102 访问了 goldendict.org，可是使用 （ "192.168.1.102" goldendict.org ） 这样的条件却无法搜索到记录。可不可以实现像搜索引擎一样多条件搜索呢？
![111](https://user-images.githubusercontent.com/79040749/236828138-2b2d1f4c-6029-4c10-9b2c-a9d6e34fc6c3.jpg)
![螢幕快照_2023-05-08_20-41-39](https://user-images.githubusercontent.com/79040749/236828262-16c387e6-5462-430a-b51f-2eaab0d52889.jpg)

**Comment by schzhn** [comment] 2024-02-29 16:32
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/3734

**Closed by schzhn** 2024-02-29 16:32 UTC
Labels: duplicate
