### ISSUE TITLE
Ibksturm DoQ Server Add

### ISSUE THREAD

**Issue by ibksturm** [AdguardTeam/AdGuardHome#4920] opened 2022-09-14 19:41 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
New Servers add
#### Proposed solution
See A
#### Additional information
Hi There

Update my DNS Servers, Add your dnsproxy solution for DoH, DoT, DoQ and DNSCRYPT

Servers:

Dns-Over-TLS
ibksturm.synology.me / 213.196.191.96 / Port 853

DNS-over-QUIC
ibksturm.synology.me / 213.196.191.96 / Port 853

DNS-over-HTTPS/2
https://ibksturm.synology.me/dns-query

Please ad them to the Publicserverlist

Greets

Andi

**Comment by ainar-g** [comment] 2022-09-15 11:56
Duplicate of AdguardTeam/KnowledgeBaseDNS#68

**Closed by ainar-g** 2022-09-15 11:56 UTC
