### ISSUE TITLE
Bug in mobileconfig

### ISSUE THREAD

**Issue by attinderdhillon** [AdguardTeam/AdGuardHome#3172] opened 2021-05-23 11:28 UTC
1. If adguard is on a non-standard HTTPS port.  The "iOS and macOS configuration" for DNS-over-HTTPS doesn't add the Port to the query URL.

2. For "DNS-over-TLS" If a client ID is specified it is prefixed to the URL.

In both cases, the URL is not reachable and DNS fail.

**Comment by EugeneOne1** [comment] 2021-05-25 09:43
@attinderdhillon, the first point is definitely a bug.  We're already working on fixing it.

The second point is an expected behavior.  See "[Clients](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients#identifying-clients)" section of our wiki.

**Comment by attinderdhillon** [comment] 2021-05-26 06:23
DNS-over-TLS

So I assume we need to add a DNS entry for this to work? 

I believe many of us are using sub-domains for adguard (dns.example.com) , multi-level wildcards are not supported AFAIK. 
client-id.dns.example.com will not work with wildcard SSL  of *.example.com

Kindly look into the possibility of using hyphens ex.  clientid-dns.example.com.

**Comment by EugeneOne1** [comment] 2021-05-27 16:35
We have already [discussed](https://github.com/AdguardTeam/AdGuardHome/issues/1383#issuecomment-751662530) using hyphens and decided to reject the idea, since that would exclude hyphens from client IDs themselves.  For example, in `a-b-c.example.com`, is the client ID `a-b` or `a`?

There is no such problem with DNS-over-HTTPS since client ID is used as part of URL there.  So you may want to use that.

**Comment by EugeneOne1** [comment] 2021-06-02 11:08
@attinderdhillon, hello!  The fix for the issue is available in latest edge build.  Could you please check if our solution work fine?

**Comment by attinderdhillon** [comment] 2021-06-02 12:21
Still port missing from Doh config..

**Comment by EugeneOne1** [comment] 2021-06-02 12:33
@attinderdhillon, a few questions to clarify:
1. How did you setup the latest edge build?
2. Could you please attach a screenshot of your Setup Guide → DNS Privacy settings?
3. What is the value of the `tls.port_https` field in `AdGuardHome.yaml`?

**Comment by attinderdhillon** [comment] 2021-06-02 13:28
1.  Stop, rename AdguardHome, pulled the latest edge build and start.

2. `DNS Privacy
 
DNS-over-TLS: Use tls://dns.domain.com:853 string.
DNS-over-HTTPS: Use https://dns.domain.com:444/dns-query string.

Here's a list of software you can use.`

3 `tls:
  enabled: true
  server_name: dns.domain.com
  force_https: true
  port_https: 444
  port_dns_over_tls: 853
  port_dns_over_quic: 784
  port_dnscrypt: 0
`

**Comment by EugeneOne1** [comment] 2021-06-02 14:18
@attinderdhillon, as your "screenshot" says, the port is defined correctly and should be presented in the resulting URL.  However, the fix only affected the bottom part of the page, where the button for downloading the `*.mobileconfig` file located:

![image](https://user-images.githubusercontent.com/38542664/120496588-5b70eb80-c3c6-11eb-83fe-a16a41ffbc93.png)

Could you please show this part?

**Comment by attinderdhillon** [comment] 2021-06-03 04:32
I don't have that option.

https://tinyurl.com/y3djyw9f

**Comment by EugeneOne1** [comment] 2021-06-03 08:46
@attinderdhillon, well, your version of _AdGuard Home_ is v0.107.0-b.1 which is the first beta of v0.107.0.  The fix is only included into edge builds for now.  You can find the instructions on how to get it [here](https://github.com/AdguardTeam/AdGuardHome#test-unstable-versions).

**Comment by attinderdhillon** [comment] 2021-06-03 09:37
My Bad, Working fine in the edge built, Thank You.

**Comment by EugeneOne1** [comment] 2021-06-03 09:39
It's okay.  Thanks for testing.  Will close the issue for now.

**Closed by EugeneOne1** 2021-06-03 09:39 UTC
Labels: P3: Medium, bug
