### ISSUE TITLE
Add a prefetch option to Optimistic DNS cache 

### ISSUE THREAD

**Issue by jumpsmm7** [AdguardTeam/AdGuardHome#3993] opened 2021-12-23 04:49 UTC
I saw in the last release 
Optimistic DNS cache (#2145)
To reduce latency you may make AdGuard Home respond from the cache even when the stored entry is expired, while trying to refresh them at the same timearrows_counterclockwise This checkbox is located in Settings → DNS settings → DNS cache configuration and it's not ticked by default. Responses made from DNS cache are marked with a special label in the Query log.

The incorporation of serving expired has been added for, in the same spirit of Optimistic DNS cache, would it be possible to add a prefetch policy ( if there is not one already incorporated that is?) to reduce how often entries are served as expired?

**Comment by agneevX** [comment] 2021-12-23 09:20
I think it's better to serve expired entries with a very low TTL, and refresh the entry automatically in the background rather than prefetch. 

However, it does make sense for popular items to be auto-refreshed on expiration.

**Comment by ainar-g** [comment] 2021-12-23 11:16
Duplicate of #1259

**Closed by ainar-g** 2021-12-23 11:16 UTC
