### ISSUE TITLE
BlockList used Counter

### ISSUE THREAD

**Issue by x0tester0x** [AdguardTeam/AdGuardHome#6293] opened 2023-10-10 09:32 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

I want to see which BlockList how often blocks something.

### Proposed solution

Implement a counter how often every blocklist was used to block something, because in the query log I can already see by which BlockList it was blocked.

**Comment by ainar-g** [comment] 2023-10-12 14:55
Duplicate of #4524

**Closed by ainar-g** 2023-10-12 14:55 UTC
Labels: feature request
