### ISSUE TITLE
AGH - pause/disable protection has no effect

### ISSUE THREAD

**Issue by medicus07** [AdguardTeam/AdGuardHome#3651] opened 2021-09-24 19:12 UTC
Prerequisites:

[ x] I am running the latest version
[ x] I checked the documentation and found no answer
[ x] I checked to make sure that this issue has not already been filed

Issue Detail:

After pausing/ disabling protection in the web GUI, websites are still blocked in safari on iPhone and Mac. Clearing cache makes no difference. 

Version of AdGuard Home server:
0.106.3

How did you install AdGuard Home:
docker on Synology DiskStation 

How did you setup DNS configuration:
Router

If it's a router or IoT, please write device model:
FritzBox 6591 Cable

Expected Behavior
stop protection until it is enabled again 

Actual Behavior
continued protection

**Comment by ameshkov** [comment] 2021-09-27 09:29
> After pausing/ disabling protection in the web GUI, websites are still blocked in safari on iPhone and Mac. Clearing cache makes no difference.

I cannot reproduce this. Could you please show the result of `nslookup` command instead of just checking if a website is blocked or not?

For instance, try `nslookup doubleclick.net` with protection enabled and then after you disable it run it again and see if there's any difference.

**Comment by medicus07** [comment] 2021-09-27 17:13
I tested the nslookup command today...

With and without  protection enabled I got the same result in terminal (MacBook Air M1, MacOS 11.6):

`Server:		192.168.1.83
Address:	192.168.1.83#53

Non-authoritative answer:
Name:	doubleclick.net
Address: 0.0.0.0`

**Comment by ameshkov** [comment] 2021-09-28 09:20
That's quite weird.

To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) AdGuard Home to write verbose-level log.
2. Reproduce the issue.
3. Post the log file here.

**Comment by medicus07** [comment] 2021-09-28 18:33
Hi Andrey,
here is the log (I renamed the json to pdf for upload)
[log.json.pdf](https://github.com/AdguardTeam/AdGuardHome/files/7246548/log.json.pdf)

Thank you.

**Comment by EugeneOne1** [comment] 2021-09-29 10:08
@medicus07, it seems, one of your upstream servers blocks some domains on its own, including the `doubleclick.net`.  You may fix it using [domain-specific](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#specifying-upstreams-for-domains) upstream.  We'll close the issue for now, if you don't mind.

**Closed by EugeneOne1** 2021-09-29 10:08 UTC
Labels: waiting for data
