### ISSUE TITLE
Activate Filter Rules for Special Clients

### ISSUE THREAD

**Issue by LPDaVinci** [AdguardTeam/AdGuardHome#6449] opened 2023-11-22 21:13 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

I can create clients and block special services.
p.e. for the Net 10.0.1.1/24 i can disable special services but im not able to disable filter lists or make some filter lists for a client only.

### Proposed solution

A feature that allows special filter lists to be activated/deactivated in the client edit settings, similar to the services.

**Comment by ainar-g** [comment] 2023-11-23 14:04
Duplicate of #435

**Closed by ainar-g** 2023-11-23 14:04 UTC
Labels: feature request
