### ISSUE TITLE
private DNS from Android: connection not possible (IPv6)

### ISSUE THREAD

**Issue by Birbber** [AdguardTeam/AdGuardHome#3794] opened 2021-11-02 09:39 UTC
@LarsMde commented on [Tue Nov 02 2021](https://github.com/AdguardTeam/AdguardForAndroid/issues/4017)

I have a problem since 01 Oct 2021. I cannot establish a private DNS (DNS-over-TLS) on Android (Pixel5, Huawei M5) to Adguard Home (version: v0.106.3) behind a Docker instance.  The error message is always "unable to connect" - not very helpful. Interestingly, DNS-over-TLS from the Fritzbox (SoHo router) to the same Adguard Home works.
The Docker setup includes an IP dual stack, basically IPv6 is preferred. Docker brings its own IPv6 NAT, see also ip6tables -L, data packets are forwarded to the appropriate port of the Local Unicast Address if needed.

```
# ip -6 a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1000
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 2a03:4000:5b:824:4816:a2ff:fe85:4d18/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::4816:a2ff:fe85:4d18/64 scope link
       valid_lft forever preferred_lft forever
...
4: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP
    inet6 fd00:dead:beef:c0::1/80 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::42:3fff:fe1d:fa6d/64 scope link
       valid_lft forever preferred_lft forever
    inet6 fe80::1/64 scope link
       valid_lft forever preferred_lft forever
...

#ip6tables -L
Chain DOCKER (3 references)
target     prot opt source               destination
...
ACCEPT     tcp      anywhere             fd00:dead:beef:c0:0:242:ac11:3  tcp dpt:domain-s
ACCEPT     udp      anywhere             fd00:dead:beef:c0:0:242:ac11:3  udp dpt:domain-s
...
```

If I use tcpdump/wireshark to cut along the data packets, I have different output depending on the scenario, unfortunately I can't look inside the data packets due to TLS. In both cases a complete TCP communication takes place (SYN, SYN/ACK, ACK, ..., FIN, RST). I suspect the problem with TLS, unfortunately I have no idea what Android does differently than the router at home. 

DNS-over-TLS from Android:
```
tcpdump -i docker0 -n 'ip6 host fd00:dead:beef:c0:0:242:ac11:3' and port 853
09:34:53.162901 IP6 2a00:20:c056:2880:11a1:8ce7:6e50:5ec.38080 > fd00:dead:beef:c0:0:242:ac11:3.853: Flags [S], seq 1671323040, win 65535, options [mss 1440,sackOK,TS val 1011599993 ecr 0,nop,wscale 8], length 0
09:34:53.162939 IP6 fd00:dead:beef:c0:0:242:ac11:3.853 > 2a00:20:c056:2880:11a1:8ce7:6e50:5ec.38080: Flags [S.], seq 4239390154, ack 1671323041, win 42840, options [mss 1440,sackOK,TS val 315576482 ecr 1011599993,nop,wscale 11], length 0
09:34:53.202568 IP6 2a00:20:c056:2880:11a1:8ce7:6e50:5ec.38080 > fd00:dead:beef:c0:0:242:ac11:3.853: Flags [.], ack 1, win 256, options [nop,nop,TS val 1011600024 ecr 315576482], length 0
09:34:53.215434 IP6 2a00:20:c056:2880:11a1:8ce7:6e50:5ec.38080 > fd00:dead:beef:c0:0:242:ac11:3.853: Flags [P.], seq 1:256, ack 1, win 256, options [nop,nop,TS val 1011600024 ecr 315576482], length 255
09:34:53.215449 IP6 fd00:dead:beef:c0:0:242:ac11:3.853 > 2a00:20:c056:2880:11a1:8ce7:6e50:5ec.38080: Flags [.], ack 256, win 21, options [nop,nop,TS val 315576534 ecr 1011600024], length 0
09:34:53.218059 IP6 fd00:dead:beef:c0:0:242:ac11:3.853 > 2a00:20:c056:2880:11a1:8ce7:6e50:5ec.38080: Flags [P.], seq 1:2857, ack 256, win 21, options [nop,nop,TS val 315576537 ecr 1011600024], length 2856
09:34:53.218081 IP6 fd00:dead:beef:c0:0:242:ac11:3.853 > 2a00:20:c056:2880:11a1:8ce7:6e50:5ec.38080: Flags [P.], seq 2857:4719, ack 256, win 21, options [nop,nop,TS val 315576537 ecr 1011600024], length 1862
09:34:53.268143 IP6 2a00:20:c056:2880:11a1:8ce7:6e50:5ec.38080 > fd00:dead:beef:c0:0:242:ac11:3.853: Flags [.], ack 1429, win 268, options [nop,nop,TS val 1011600082 ecr 315576537], length 0
09:34:53.268153 IP6 2a00:20:c056:2880:11a1:8ce7:6e50:5ec.38080 > fd00:dead:beef:c0:0:242:ac11:3.853: Flags [.], ack 2857, win 279, options [nop,nop,TS val 1011600083 ecr 315576537], length 0
09:34:53.268155 IP6 2a00:20:c056:2880:11a1:8ce7:6e50:5ec.38080 > fd00:dead:beef:c0:0:242:ac11:3.853: Flags [.], ack 4285, win 290, options [nop,nop,TS val 1011600083 ecr 315576537], length 0
09:34:53.268194 IP6 2a00:20:c056:2880:11a1:8ce7:6e50:5ec.38080 > fd00:dead:beef:c0:0:242:ac11:3.853: Flags [.], ack 4719, win 301, options [nop,nop,TS val 1011600083 ecr 315576537], length 0
09:34:53.273157 IP6 2a00:20:c056:2880:11a1:8ce7:6e50:5ec.38080 > fd00:dead:beef:c0:0:242:ac11:3.853: Flags [P.], seq 256:286, ack 4719, win 301, options [nop,nop,TS val 1011600084 ecr 315576537], length 30
09:34:53.273180 IP6 fd00:dead:beef:c0:0:242:ac11:3.853 > 2a00:20:c056:2880:11a1:8ce7:6e50:5ec.38080: Flags [.], ack 286, win 21, options [nop,nop,TS val 315576592 ecr 1011600084], length 0
09:34:53.273232 IP6 fd00:dead:beef:c0:0:242:ac11:3.853 > 2a00:20:c056:2880:11a1:8ce7:6e50:5ec.38080: Flags [F.], seq 4719, ack 286, win 21, options [nop,nop,TS val 315576592 ecr 1011600084], length 0
09:34:53.337973 IP6 2a00:20:c056:2880:11a1:8ce7:6e50:5ec.38080 > fd00:dead:beef:c0:0:242:ac11:3.853: Flags [R], seq 1671323326, win 0, length 0
```

DNS-over-TLS from Fritzbox (SoHo router):
```
tcpdump -i docker0 -n 'ip6 host fd00:dead:beef:c0:0:242:ac11:3' and port 853
09:32:11.223052 IP6 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629 > fd00:dead:beef:c0:0:242:ac11:3.853: Flags [S], seq 72838380, win 28800, options [mss 1440,sackOK,TS val 22703711 ecr 0,nop,wscale 7], length 0
09:32:11.223091 IP6 fd00:dead:beef:c0:0:242:ac11:3.853 > 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629: Flags [S.], seq 2474163512, ack 72838381, win 42840, options [mss 1440,sackOK,TS val 3707710723 ecr 22703711,nop,wscale 11], length 0
09:32:11.248965 IP6 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629 > fd00:dead:beef:c0:0:242:ac11:3.853: Flags [.], ack 1, win 225, options [nop,nop,TS val 22703736 ecr 3707710723], length 0
09:32:11.257527 IP6 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629 > fd00:dead:beef:c0:0:242:ac11:3.853: Flags [P.], seq 1:518, ack 1, win 225, options [nop,nop,TS val 22703739 ecr 3707710723], length 517
09:32:11.257556 IP6 fd00:dead:beef:c0:0:242:ac11:3.853 > 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629: Flags [.], ack 518, win 21, options [nop,nop,TS val 3707710757 ecr 22703739], length 0
09:32:11.260305 IP6 fd00:dead:beef:c0:0:242:ac11:3.853 > 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629: Flags [P.], seq 1:2857, ack 518, win 21, options [nop,nop,TS val 3707710760 ecr 22703739], length 2856
09:32:11.260332 IP6 fd00:dead:beef:c0:0:242:ac11:3.853 > 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629: Flags [P.], seq 2857:4719, ack 518, win 21, options [nop,nop,TS val 3707710760 ecr 22703739], length 1862
09:32:11.284581 IP6 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629 > fd00:dead:beef:c0:0:242:ac11:3.853: Flags [.], ack 1429, win 248, options [nop,nop,TS val 22703773 ecr 3707710760], length 0
09:32:11.284589 IP6 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629 > fd00:dead:beef:c0:0:242:ac11:3.853: Flags [.], ack 2857, win 270, options [nop,nop,TS val 22703773 ecr 3707710760], length 0
09:32:11.293202 IP6 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629 > fd00:dead:beef:c0:0:242:ac11:3.853: Flags [.], ack 4285, win 292, options [nop,nop,TS val 22703775 ecr 3707710760], length 0
09:32:11.293208 IP6 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629 > fd00:dead:beef:c0:0:242:ac11:3.853: Flags [.], ack 4719, win 315, options [nop,nop,TS val 22703776 ecr 3707710760], length 0
09:32:11.301811 IP6 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629 > fd00:dead:beef:c0:0:242:ac11:3.853: Flags [P.], seq 518:582, ack 4719, win 315, options [nop,nop,TS val 22703792 ecr 3707710760], length 64
09:32:11.301843 IP6 fd00:dead:beef:c0:0:242:ac11:3.853 > 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629: Flags [.], ack 582, win 21, options [nop,nop,TS val 3707710801 ecr 22703792], length 0
09:32:11.327727 IP6 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629 > fd00:dead:beef:c0:0:242:ac11:3.853: Flags [P.], seq 582:633, ack 4719, win 315, options [nop,nop,TS val 22703814 ecr 3707710801], length 51
09:32:11.327744 IP6 fd00:dead:beef:c0:0:242:ac11:3.853 > 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629: Flags [.], ack 633, win 21, options [nop,nop,TS val 3707710827 ecr 22703814], length 0
09:32:11.362257 IP6 fd00:dead:beef:c0:0:242:ac11:3.853 > 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629: Flags [P.], seq 4719:4743, ack 633, win 21, options [nop,nop,TS val 3707710862 ecr 22703814], length 24
09:32:11.362301 IP6 fd00:dead:beef:c0:0:242:ac11:3.853 > 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629: Flags [P.], seq 4743:4824, ack 633, win 21, options [nop,nop,TS val 3707710862 ecr 22703814], length 81
09:32:11.388268 IP6 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629 > fd00:dead:beef:c0:0:242:ac11:3.853: Flags [.], ack 4824, win 315, options [nop,nop,TS val 22703877 ecr 3707710862], length 0
09:32:15.574317 IP6 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629 > fd00:dead:beef:c0:0:242:ac11:3.853: Flags [P.], seq 633:693, ack 4824, win 315, options [nop,nop,TS val 22708063 ecr 3707710862], length 60
09:32:15.574359 IP6 fd00:dead:beef:c0:0:242:ac11:3.853 > 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629: Flags [.], ack 693, win 21, options [nop,nop,TS val 3707715074 ecr 22708063], length 0
09:32:15.600338 IP6 fd00:dead:beef:c0:0:242:ac11:3.853 > 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629: Flags [P.], seq 4824:4848, ack 693, win 21, options [nop,nop,TS val 3707715100 ecr 22708063], length 24
09:32:15.600378 IP6 fd00:dead:beef:c0:0:242:ac11:3.853 > 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629: Flags [P.], seq 4848:4922, ack 693, win 21, options [nop,nop,TS val 3707715100 ecr 22708063], length 74
09:32:15.625763 IP6 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629 > fd00:dead:beef:c0:0:242:ac11:3.853: Flags [.], ack 4922, win 315, options [nop,nop,TS val 22708115 ecr 3707715100], length 0
09:32:23.628282 IP6 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629 > fd00:dead:beef:c0:0:242:ac11:3.853: Flags [F.], seq 693, ack 4922, win 315, options [nop,nop,TS val 22716116 ecr 3707715100], length 0
09:32:23.628392 IP6 fd00:dead:beef:c0:0:242:ac11:3.853 > 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629: Flags [P.], seq 4922:4946, ack 694, win 21, options [nop,nop,TS val 3707723128 ecr 22716116], length 24
09:32:23.628444 IP6 fd00:dead:beef:c0:0:242:ac11:3.853 > 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629: Flags [F.], seq 4946, ack 694, win 21, options [nop,nop,TS val 3707723128 ecr 22716116], length 0
09:32:23.658467 IP6 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629 > fd00:dead:beef:c0:0:242:ac11:3.853: Flags [R], seq 72839074, win 0, length 0
09:32:23.667103 IP6 2a02:810d:8000:69:ede2:7a4c:b486:58d7.33629 > fd00:dead:beef:c0:0:242:ac11:3.853: Flags [R], seq 72839074, win 0, length 0
```
These are the settings and result at SoHo router (connection established):
![DNSoTLS](https://user-images.githubusercontent.com/47632487/139820350-89f9eb5e-f0c3-4e53-8432-a8279520feda.PNG)

![DNSused](https://user-images.githubusercontent.com/47632487/139820423-713e7f49-e5c7-412c-a6fc-4091b48fa08d.PNG)

A google search on the problem has been unsuccessful so far, maybe others in the community have similar problems.

Any ideas or indeed a bug?

**Comment by LarsMde** [comment] 2021-11-02 10:15
There is a technical error in the description above (second paragraph), here is the correction:

Docker setup includes an IP dual stack, basically IPv6 is preferred. Docker brings its own IPv6 NAT (NAT66), see also ip6tables -L. Data packets are forwarded to the appropriate port of the unique-local address fd80:: if needed.

**Comment by LarsMde** [comment] 2021-11-03 08:58
The problem was indeed related to Let's Encrypt and the expired certificate of the original root CA. The certificate generated by Let's Encrypt even after September 31, 2021 still contains the expired CA in the certificate chain. The implementation of DNS-over-TLS on Android evaluates this and prevents TLS.

I have documented the solution in my [blog](https://kwellkorn.de/2021/11/03/privates-dns-mit-lets-encyrpt-und-adguard-home/) (only in German). In short: If you use certbot to renew your Let's Encrypt certificates, the parameter _--preferred-chain="ISRG Root X1"_ should fix the problem.

The issue can be closed.

**Comment by ainar-g** [comment] 2021-11-03 10:43
Duplicate of #3689

**Closed by ainar-g** 2021-11-03 10:43 UTC
