### ISSUE TITLE
v0.93 - Redirect to https  does not work

### ISSUE THREAD

**Issue by zeus10000** [AdguardTeam/AdGuardHome#607] opened 2019-02-27 23:18 UTC
With Redirect to HTTPS set to enabled, I do not see the http link getting redirected to https instead it shows as cannot connect to server.

```
bind_host: 0.0.0.0
bind_port: 3000
auth_name: ########
auth_pass: ########
language: ""
dns:
  bind_host: 0.0.0.0
  port: 53
  protection_enabled: true
  filtering_enabled: true
  blocked_response_ttl: 10
  querylog_enabled: true
  ratelimit: 20
  ratelimit_whitelist: []
  refuse_any: true
  bootstrap_dns: 8.8.8.8:53
  parental_sensitivity: 13
  parental_enabled: true
  safesearch_enabled: false
  safebrowsing_enabled: true
  upstream_dns:
  - tls://1.1.1.1
  - tls://1.0.0.1
tls:
  enabled: true
  server_name: ########
  force_https: true
  port_https: 443
  port_dns_over_tls: 853
  certificate_chain: |-
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  private_key: |-
    -----BEGIN PRIVATE KEY-----
    -----END PRIVATE KEY-----
```

**Comment by ameshkov** [comment] 2019-02-28 10:19
Do you mean that when you open the admin interface using the HTTP link, it is not getting redirected to HTTPS://adguardhomeadmin ?

**Comment by jimitsalvi** [comment] 2019-02-28 15:31
That is correct. 

Atleast that is my understanding of the redirect feature.

**Comment by ameshkov** [comment] 2019-02-28 17:47
Well, I need a little bit more info about it.

Do you use a domain name or an IP address in the HTTP link?
Is the port 3000 open and reachable?
Does direct HTTPS link work?

**Comment by jimitsalvi** [comment] 2019-02-28 18:00
I use domain in the HTTP link.

Yes, port 80, 443 and 3000 are open and reachable and https link works.

**Comment by ameshkov** [comment] 2019-02-28 18:02
So just to make sure: do you use `http://domain:3000/` link?

**Comment by jimitsalvi** [comment] 2019-02-28 18:12
Yes

**Comment by jimitsalvi** [comment] 2019-02-28 22:18
I was playing around the WEB UI port setting, after changing the port from 3000 to 80 restarted adguard service, I could see the redirect to https working, after which I switched back the web UI port 3000, restarted adguard service and still the redirect to HTTPS worked.


Could this be a one-off issue?

**Comment by ameshkov** [comment] 2019-03-01 07:22
Good idea btw, so it might not work right after enabling HTTPS. We'll check it, thank you!

**Comment by admitrevskiy** [comment] 2019-03-20 07:31
@jimitsalvi Hi!
I can't reproduce this issue. Have you faced this problem again?

**Comment by jimitsalvi** [comment] 2019-03-21 02:01
I have not build a new ADG server from scratch again, it is only during the initial ADG setup I faced this issue. So far after the workaround (my last comment above), I have never faced this issue again once the server was up and running.

**Comment by ameshkov** [comment] 2019-03-21 08:18
Thank you for the information!

I'll close this issue for now, please reopen if it happens again, we'll look into it.

**Closed by ameshkov** 2019-03-21 08:18 UTC
Labels: cannot reproduce
