### ISSUE TITLE
 failed to sufficiently increase receive buffer size

### ISSUE THREAD

**Issue by beruangkutub** [AdguardTeam/AdGuardHome#5907] opened 2023-06-15 04:35 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux/ARMv7

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.32

### Action

```sh
nslookup -debug -type=a 'www.example.com' '$YOUR_AGH_ADDRESS'
```

### Expected result

**failed to sufficiently increase receive buffer size (was: 176 kiB, wanted: 2048 kiB, got: 352 kiB).**

### Actual result

(was: 176 kiB, wanted: 2048 kiB, got: 352 kiB).

**Comment by ainar-g** [comment] 2023-06-15 14:20
Duplicate of #5903

**Closed by ainar-g** 2023-06-15 14:20 UTC
