### ISSUE TITLE
AdGuard OPNsense Plugin Broke my Local-Domain setup 

### ISSUE THREAD

**Issue by thorrrr** [AdguardTeam/AdGuardHome#5827] opened 2023-05-17 08:43 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

FreeBSD

### CPU architecture

AMD64

### Installation

Custom port 5353

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

Version:  v0.107.29

### Description

I heard there was an issue with OPNsesnse several weeks ago that ADGuard plugin was faulty.
So i held off and waiting for a fix i read that it had been fixed so i updated yesterday 16 May 2023
Currently 
opnsense.localdomain
--
Versions | OPNsense 23.1.7_3
-amd64FreeBSD 13.1-RELEASE
-p7OpenSSL 1.1.1t 7 Feb 2023

After update i have lost total access to my localdomain url addresses and need to use the ip address to access.
If i check ADGuard upstream is fine showing no issues!
But obviously having used ADGuard for 12 months on OPNsesne there is an issue with the plugin in realtion tothe OPNsense update.
I don't tinker so my settings have never changed for 12 months.
There is conflicting advice saying its ADGuard issue some say it OPNsesne but they say its a plugin issue.
So as a user we end up in swirl of the blame game. But just looking for some guidance on how to track down what is the issue  

Please see link to see if it helps identify any bad settings see [HERE](https://photos.app.goo.gl/zHz98z7Vnhd2RS4a8)

**Comment by tommiyau** [comment] 2023-05-21 02:21
Similar to myself. I had a working configuration that ran with opnsense. Upgrade to 107.29 and now the LAN clients never get a DNS service in the DHCP request. I'm not sure exactly why that is the case. I've spent a number of hours on this already. The easiest answer unfortunately at present is to leave unbound to do the blocking instead of trying to use adguard. When doing that the lan clients get a DNS entry.

**Comment by tommiyau** [comment] 2023-05-21 04:29
Edit: This appears to be an unbound issue in opnsense. By default opnsense states that it will provide a DNS of the lan default gateway as part of the dhcp request if the services->DHCPv4_LAN -> DNS field is blank. However in 23.1.7 this appears to only occur if unbound is set to run on port 53. If you take a default unbound configuration ie. no adguard and change the listening port to 54 a DHCP request then does not get any option6 (DNS server) included in its response. This is independent of adguard and hence appears to be an opnsense issue instead of an adguard issue.

**Comment by micfogas** [comment] 2023-06-02 10:48
I believe this happened when the change to how opnsense handles primary DNS occurred. The issue is definitely either in the plugin (you'd have to contact mimugmail on opnsense forums) or the need to adjust your configuration on opnsense. Like tommyiau said though, it's not an AdGuardHome issue.

You may want to take a look at the AGH documentation regarding forward lookups for more details, but I'll point out what you should look for.

You can specify forward lookup servers by domain by adding an entry such as:

`[/localdomain/]udp://127.0.0.1:5353`

This would try to resolve any DNS requests it receives for any .localdomain url using a DNS server running on port 5353 on the localhost. That would be your unbound server that's running your DHCP. I also have unbound configured without any forward lookups so that if something weird happens, it won't try to resolve anything except the hosts registered via status or dynamic leases. I also added, in the Disallowed Domains setting, the following lines:

`||*.wpad^$important
||wpad.localdomain^$important
||*.wpad.localdomain^$important`

to stop windows browsers from trying to use wpad lookups if the hostname isn't registered in unbound.

Anyway, this should be closed as this issue has nothing to do with AGH.

**Closed** 2024-04-09 23:36 UTC
Labels: cannot reproduce
