### ISSUE TITLE
Is it possible to add editing and commenting functions to the dns_rewrites module?

### ISSUE THREAD

**Issue by aTenb** [AdguardTeam/AdGuardHome#5697] opened 2023-04-08 11:10 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
Is it possible to add editing and commenting functions to the dns_rewrites module?
#### Proposed solution
Is it possible to add editing and commenting functions to the dns_rewrites module?
#### Alternatives considered
Is it possible to add editing and commenting functions to the dns_rewrites module?
#### Additional information
Is it possible to add editing and commenting functions to the dns_rewrites module?

**Comment by fernvenue** [comment] 2023-04-09 04:30
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/1577, and you can use Custom filtering rules with [`dnsrewrite`](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#dnsrewrite) for now.

**Closed** 2023-04-09 11:40 UTC
