### ISSUE TITLE
ipset - unexpected family ProtoUnspec [v0.108.0-b.49-50]

### ISSUE THREAD

**Issue by odcold** [AdguardTeam/AdGuardHome#6420] opened 2023-11-14 10:29 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, MIPS LE

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

AdGuard Home v0.108.0-b.49

### Action

ipset create bypass hash:ip

ipset file is filled with domains

ipset_file: /opt/etc/AdGuardHome/ipset.conf

### Expected result

adresses are added to ipset

### Actual result

2023/11/14 10:18:11.705099 [error] dnsforward: ipset: adding host ips: unexpected family ProtoUnspec for ipset "bypass"
2023/11/14 10:18:16.576093 [error] dnsforward: ipset: adding host ips: unexpected family ProtoUnspec for ipset "bypass"
2023/11/14 10:18:29.545826 [error] dnsforward: ipset: adding host ips: unexpected family ProtoUnspec for ipset "bypass"
2023/11/14 10:18:29.574250 [error] dnsforward: ipset: adding host ips: unexpected family ProtoUnspec for ipset "bypass"

### Additional information and/or screenshots

rolling back to beta 48 fixes this issue

**Comment by schzhn** [comment] 2023-11-14 15:32
Hello, @odcold, could you please help us investigate the issue?

- What is version of ipset (`ipset --version`)?
- How does output of the `ipset list bypass` looks like (you can strip `Members`)?
- Does the error message disappear if you specify the family (`ipset create bypass hash:ip family ipv4`)?

**Comment by dorner365** [comment] 2023-11-26 01:33
I'm seeing the same fatal error as @odcold in an identical configuration where the ipsets are created without additional parameters. The `ipset list` command `Type`, `Revision` and `Header` are identical.
V0.108.0-b.49 works with no errors.

**Comment by schzhn** [comment] 2023-11-27 17:24
@odcold, unfortunately, we cannot reproduce that.
Could you please check if [v0.107.39](https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.39) does work for you?

**Comment by schzhn** [comment] 2023-11-28 10:18
@dorner365, in v0.108.0-b.49 there was no ipset configuration check at startup, so you get the ipset related errors in runtime.

**Comment by dorner365** [comment] 2023-11-28 21:14
> so you get the ipset related errors in runtime.
I have this error on 2 different systems (of which one is Ubuntu 20.04.6 LTS). The error as it stands is misleading - what is "unexpected ipset family "ProtoUnspec" in the runtime context?

**Comment by schzhn** [comment] 2023-11-29 16:25
@dorner365, thank you for the additional information.
In v0.108.0-b.49 you can see non-fatal errors like this at runtime in the log
`2023/11/29 19:12:30.109275 [error] dnsforward: ipset: adding host ips: unexpected family ProtoUnspec for ipset "bypass"`
We are investigating an issue.

**Comment by dorner365** [comment] 2023-11-30 16:30
Seems alright on Ubuntu 20.04.6:

????@????:/opt/AdGuardHome# systemctl status AdGuardHome
● AdGuardHome.service - AdGuard Home: Network-level blocker
     Loaded: loaded (/etc/systemd/system/AdGuardHome.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2023-11-30 11:12:48 EST; 19s ago
    Process: 68510 ExecStartPre=/bin/mkdir -p /var/log/ (code=exited, status=0/SUCCESS)
   Main PID: 68511 (AdGuardHome)
      Tasks: 8 (limit: 4554)
     Memory: 52.1M
     CGroup: /system.slice/AdGuardHome.service
             └─68511 /opt/AdGuardHome/AdGuardHome -s run

Nov 30 11:12:48 <system> systemd[1]: Starting AdGuard Home: Network-level blocker...
Nov 30 11:12:48 <system> systemd[1]: Started AdGuard Home: Network-level blocker.

????@????:/opt/AdGuardHome# ./AdGuardHome --version
AdGuard Home, version v0.108.0-a.779+2965d1fb

No [fatal] error anymore. Thank you!

**Comment by dorner365** [comment] 2023-12-08 19:26
With the v0.108.0-b.51 all related log entries now are [info]; no more errors. On my systems the original ipset ProtoUnspec is resolved. Thank you.

**Comment by schzhn** [comment] 2023-12-12 10:52
We are closing this issue. Please let us know if the problem persists.

**Closed by schzhn** 2023-12-12 10:52 UTC
Labels: bug, P3: Medium
