### ISSUE TITLE
Save DHCP static leases on AdGuardHome.yaml

### ISSUE THREAD

**Issue by MuadDibVV** [AdguardTeam/AdGuardHome#5396] opened 2023-01-23 17:08 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
Keeping DHCP static lease configuration after each recreation of docker container

#### Proposed solution
Writing DHCP configuration on  AdGuardHome.yaml :
dhcp:
&nbsp;&nbsp;static_leases:
&nbsp;&nbsp;&nbsp;&nbsp;- host_name : 'Test1'
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;id_mac : "AA:AA:AA:AA:AA:AA"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ip : "XXX.XXX.XXX.XXX"
&nbsp;&nbsp;&nbsp;&nbsp;- host_name : 'Test2'
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;id_mac : "AA:AA:AA:AA:AA:AB"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ip : "XXX.XXX.XXX.XXY"

Thank you

**Comment by mikeeq** [comment] 2023-01-29 13:03
Related to: https://github.com/AdguardTeam/AdGuardHome/issues/1700

**Comment by Birbber** [comment] 2023-02-09 16:42
Sorry for the long silence. Looks like a duplicate of #1700 indeed. Will close this one.

**Closed** 2023-02-09 16:42 UTC
Labels: duplicate
