### ISSUE TITLE
Add adguard-dns.io Statistics

### ISSUE THREAD

**Issue by Fluqzy** [AdguardTeam/AdGuardHome#4461] opened 2022-04-03 21:08 UTC
Hey,
i would like to get a feature, that is currently in the ["beta" private Adguard DNS](https://adguard-dns.io).
In the Statistics Tab, there are many things Adguard Home currently do not have.
Top Domains are in a slitly other way there, but Requests type, Top companys and Top destination is not in Adguard Home and i didnt find a feature request for that. I would like to see all Statistics listed there in the future Adguard Home.

![image](https://cdn.fluqzy.eu/RUviF0mz.png)

Best regards,
Fluqzy

**Comment by fernvenue** [comment] 2022-04-04 00:17
Cloudflare Zero Trust Gateway also has this kind feature:

![screnshot](https://user-images.githubusercontent.com/84565547/161455096-4895140d-204a-4d7f-81ab-60b339f6f25e.png)

I think such request analysis really useful too, and it is becoming more common actually, but seems like there will be additional resource overhead. If the dev team is willing to add this feature, I hope this feature will not cause too much resource overhead, or let it be turned off by default.

**Comment by ainar-g** [comment] 2022-04-05 12:00
This is a bit of a duplicate of #2075 and #2554 issues, as we're in the process of redesigning the dashboard, and most of the stuff you mention are already planned there.  I'll take not of the requests from here though.  Thanks.

**Closed by ainar-g** 2022-04-05 12:00 UTC
Labels: duplicate
