### ISSUE TITLE
Web Management UI Suggestion

### ISSUE THREAD

**Issue by Minggt** [AdguardTeam/AdGuardHome#4504] opened 2022-04-18 20:06 UTC
It will be better if the web UI has dark model which automatically change with system setting. 
Every time I open the web at night, the white and bright UI hurt my eyes😂.

**Comment by fernvenue** [comment] 2022-04-19 06:23
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/613.

**Closed** 2022-04-19 09:16 UTC
Labels: duplicate
