### ISSUE TITLE
`dns.bind_hosts` for addresses that aren't permanent

### ISSUE THREAD

**Issue by nagisa** [AdguardTeam/AdGuardHome#6145] opened 2023-08-27 09:58 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

`dns.bind_hosts` today requires that there is an interface with each of the addresses at the time `adguardhome` starts up. This presents a complication when some of the interfaces aren’t static (e.g. WiFi, VPN) or if setting up an interface depends on being able to resolve DNS in the first place (leading to chicken-egg problem.) In particular `AdGuardHome` today will fail with an error message along the lines of

```
2023/08/27 12:41:12.796923 [fatal] couldn't start forwwarding DNS server: starting listeners: listening on udp addr 100.64.0.8:53: listening to udp socket: listen udp 100.64.0.8:53: bind: cannot assign requested address
```

Which then leaves the system without any DNS at all (since it is set up to use `127.0.0.1` as the DNS server…)

### Proposed solution

`dnsmasq` had a functionality that allowed it to start even if the interfaces it was specified to bind to weren’t yet available. It would then monitor interface list at the runtime and bind/unbind sockets as the interfaces would come up or down.

I suggest that `adguardhome` should be doing the same, rather than crashing if it is unable to bind one of some of the interfaces/addresses.

### Alternatives considered and additional information

There is a system-side fix that I’m planning to use for the time being: bind to `0.0.0.0` and then use firewall rules to allow/deny access to adguardhome from specific interfaces.

**Comment by sbe-arg** [comment] 2024-06-18 01:40
Similar https://github.com/AdguardTeam/AdGuardHome/issues/7081 I chose to bind to 127.0.0.1 instead of 0.0.0.0

**Comment by ainar-g** [comment] 2024-06-18 12:17
Duplicate of #5909

**Closed by ainar-g** 2024-06-18 12:17 UTC
Labels: feature request
