### ISSUE TITLE
[bug] Can't Set Tags on Client via Mobile UI

### ISSUE THREAD

**Issue by Ultrabenosaurus** [AdguardTeam/AdGuardHome#1499] opened 2020-03-22 09:05 UTC
The new Client Tags feature can't be set via the mobile UI on Chrome or Firefox, tested on Android 9 using finger and Note 8 stylus input.

[https://youtu.be/m3KpOx7TPu4](https://youtu.be/m3KpOx7TPu4) 

I haven't tested via the desktop UI yet as I'm on the clock working from home and thought I'd just setup my work laptop in AGH real quick. I'll report back this afternoon once I've switched back to my PC and tested it.

**Comment by ArchiveBase** [comment] 2020-03-22 10:51
Already fixed https://github.com/AdguardTeam/AdGuardHome/commit/6eadca25d1ab7498abb8027e7dc866ee2d930a31
Did you test unstable build?

**Comment by ameshkov** [comment] 2020-03-22 11:32
Yeah, duplicate of #1471

**Closed by ameshkov** 2020-03-22 11:32 UTC
Labels: duplicate
