### ISSUE TITLE
List all filters that contain this domain 列出包含此条域名的所有过滤器

### ISSUE THREAD

**Issue by hacamer** [AdguardTeam/AdGuardHome#4666] opened 2022-06-12 05:20 UTC
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Problem Description
I hope 
我希望
In Domain Checker and Block Logs
在域名检查器和拦截日志中
List all filters that contain this domain
列出包含此条域名的所有过滤器
If multiple filters block the domain
如果多个过滤器拦截了这个域
Shows a list of all filters that block this domain
展示拦截该域名的所有过滤器列表
It is very helpful for users to give feedback to developers
它对用户向开发者反馈非常有帮助
Can AdGuardteam make it happen?
AdGuardTeam能实现它吗
Thanks.
谢谢
### Proposed Solution
List all filters that contain this domain

### Alternatives Considered
No 
### Additional Information
other discussions : #4028 
![IMG_20220612_131725](https://user-images.githubusercontent.com/73057402/173216874-0b60470d-b788-4588-9d99-3fccedb4ac9d.jpg)
![IMG_20220612_131707](https://user-images.githubusercontent.com/73057402/173216875-3f177817-fd09-4d39-ae7c-73ebc18b8320.jpg)

**Comment by q3v5** [comment] 2022-06-13 00:03
这个太实用了啊，有可能好几个规则都拦截了，它就显示一个。

**Comment by hacamer** [comment] 2022-06-13 12:02
> 这个太实用了啊，有可能好几个规则都拦截了，它就显示一个。

确实

**Comment by hacamer** [comment] 2022-07-09 05:15
![image](https://user-images.githubusercontent.com/73057402/178092649-21450b9a-1022-40a7-a3fc-969db1e51ae8.png)
Just like this
就像这样

**Comment by ainar-g** [comment] 2022-09-06 14:46
Duplicate of #4028

**Closed by ainar-g** 2022-09-06 14:46 UTC
Labels: feature request
