### ISSUE TITLE
individual shutdown of the log

### ISSUE THREAD

**Issue by spot320** [AdguardTeam/AdGuardHome#4857] opened 2022-08-22 13:43 UTC
### Prerequisites

- [ ] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [ ] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Description

Hello. I use Adguardhome on openwrt and I like it a lot. Could you add the ability to choose in the settings of clients. So that you can keep or on the contrary disable the log for each client individually. Thank you.

**Comment by ainar-g** [comment] 2022-08-22 14:38
Duplicate of #4299

**Closed by ainar-g** 2022-08-22 14:38 UTC
Labels: duplicate
