### ISSUE TITLE
Outgoing DoT traffic without any tls config

### ISSUE THREAD

**Issue by tescophil** [AdguardTeam/AdGuardHome#2003] opened 2020-08-07 07:52 UTC
### Issue Details

* **Version of AdGuard Home server:**
   * v0.102.0
* **How did you setup DNS configuration:**
  * AdGuard IP provided over DHCP + Android Private DNS setting
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 3 Model B
* **Operating system and version:**
  * HassOS 4.11, HA 0.113.3

### Expected Behavior
I don't have any DoT upstream DNS servers configured, so I don't expect the system to generate these requests

### Actual Behavior
I only have one DoH upstream DNS configured, and one local DNS server for resolving local host names which was working perfectly well. However, when I tried setting the private DNS option on my Android phone (which uses DoT) and pointing this at my own AdGuard instance I began to see corresponding outgoing DoT requests on port 853 to 1.1.1.1 coming from AdGuard server. No config exists for tls://1.1.1.1, so where is this coming from ?

### Screenshots
![Screenshot from 2020-08-07 08-34-42](https://user-images.githubusercontent.com/59442445/89621800-dee6ac80-d889-11ea-9383-6a316a95065b.png)

You can see from the screen shot that there is a DoH connection to Cloudflair (104.16.248.249), some port 53 traffic to my local DNS server (192.168.10.1) and several outgoing DoT requests on port 853 to 1.1.1.1 for which no configuration exists in my setup.

### Additional Information
My DNS config:
```
https://cloudflare-dns.com/dns-query
[//myhouse.duckdns.org/]192.168.10.1
[/168.192.in-addr.arpa/]192.168.10.1
```
Bootstrap DNS
```
192.168.10.1
```

**Comment by szolin** [comment] 2020-08-07 08:14
If you don't see those connections in AGH debug logs, then it's not AGH who initiates them.  Can you please check this?

**Comment by tescophil** [comment] 2020-08-07 08:34
Hmm..., I don't see anything useful in the logs that relate to DNS requests at all, its just full of stuff like this : 
```
[07/Aug/2020:09:25:09 +0100] 200 192.168.10.1, 172.30.32.1(172.30.32.2) GET /main.126de13aae65a32470fd.js HTTP/1.1 (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36)
[07/Aug/2020:09:25:10 +0100] 200 192.168.10.1, 172.30.32.1(172.30.32.2) GET /control/status HTTP/1.1 (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36)
[07/Aug/2020:09:25:10 +0100] 200 192.168.10.1, 172.30.32.1(172.30.32.2) GET /control/access/list HTTP/1.1 (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36)
[07/Aug/2020:09:25:10 +0100] 200 192.168.10.1, 172.30.32.1(172.30.32.2) GET /control/stats HTTP/1.1 (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36)
[07/Aug/2020:09:25:11 +0100] 200 192.168.10.1, 172.30.32.1(172.30.32.2) GET /control/tls/status HTTP/1.1 (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36)
[07/Aug/2020:09:25:11 +0100] 200 192.168.10.1, 172.30.32.1(172.30.32.2) POST /control/version.json HTTP/1.1 (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36)
[07/Aug/2020:09:25:11 +0100] 200 192.168.10.1, 172.30.32.1(172.30.32.2) GET /control/stats_info HTTP/1.1 (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36)
[07/Aug/2020:09:25:11 +0100] 200 192.168.10.1, 172.30.32.1(172.30.32.2) GET /control/profile HTTP/1.1 (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36)
```
I find it too coincidental that as soon as I start sending DoT requests to myhouse.duckdns.org:853 (my AdGuard instance) that I immediately see corresponding tls://1.1.1.1:853 requests coming FROM my AdGuard instance

**Comment by szolin** [comment] 2020-08-07 09:12
No, I mean AGH debug logs.

How to enable AdGuard Home debug logs:

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by tescophil** [comment] 2020-08-07 09:25
My AdGuard config now looks like this:
```
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
log_file: /tmp/adhuardhomedebug.log
verbose: true
```
Restarted the AddOn, no log in /tmp in the HassIO container, or the host OS.

**Comment by tescophil** [comment] 2020-08-08 13:12
I updated to HassOS 4.12 yesterday and no longer see the 853 requests in my logs...

**Comment by tescophil** [comment] 2020-08-10 12:52
BUMP..., anyone want to let me know how to collect the logs from AdGuard Home running on HassOS ??

**Comment by ameshkov** [comment] 2020-08-10 16:45
Hm, tbh I don't know how to do this in your case.

@frenck sorry for bothering you, could you please advise how to properly change AGH configuration in this case?

We need to have `log_file` and `verbose` changed.

**Comment by frenck** [comment] 2020-08-10 16:54
@ameshkov Don't feel sorry to bother me, so no excuses needed. Happy to help.

There is nothing in the issue that ties it to AdGuard itself, that is an assumption at this point.

This same issue was created on the Home Assistant repositories. So maybe @tescophil it is helpful to link to up next time.

Since this is a Home Assistant installation with a Supervisor, Home Assistant itself uses it as a fallback, which cannot be disabled.

My guess would thus be the internal DNS server of Home Assistant and not AdGuard. Especially since the add-on does not modify the working of AdGuard.

**Comment by ameshkov** [comment] 2020-08-10 17:06
@frenck 

Yeah, this does explain everything, thank you!

What about the configuration question? If there are more questions from people with HA-managed AG installation, I'd like to be able to explain to them how to enable verbose-level logging.

**Comment by tescophil** [comment] 2020-08-10 17:20
@frenck Sorry about the cross post, I'll link up better next time ;-)

And wow, so the HA supervisor has cloudflair TLS DNS hardcoded.., for what possible reason ?

**Comment by frenck** [comment] 2020-08-10 17:32
@ameshkov Every add-on has a `log_level` setting, e.g., `log_level: debug` that can be added to the add-on configuration.

@tescophil It is used by HA DNS as a fallback in case it has DNS issues. Unfortunately, a lot of people end up breaking DNS in their homes (for example, but not limited to, AdGuard). Networking is, unfortunately, considered a difficult subject for a lot of people. 

If you have further questions about that, I'd recommend joining the Home Assistant Discord chat or Home Assistant Community forum, as that is way off-topic for this repository.

**Comment by ameshkov** [comment] 2020-08-10 17:36
@frenck thank you!

Closing this issue as this apparently is not an AG issue.

**Closed by ameshkov** 2020-08-10 17:36 UTC
Labels: question
