### ISSUE TITLE
Allow binding to specific multiple lans

### ISSUE THREAD

**Issue by AndrewW-GIT** [AdguardTeam/AdGuardHome#1823] opened 2020-06-22 18:09 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

 I am running the latest version
 I checked the documentation and found no answer
 I checked to make sure that this issue has not already been filed

### Problem Description
It would be nice to be able to configure which lans AdGaurd is bound to, as I'm trying to install the s/w on a server which is already running bind configurations  which looks up against different dns servers depending on the source of the traffic. I was considering fronting bind with multiple AdGuard instances to cover for the different network traffic. For this to be possible i need to bind to multiple but specified lans and not all 20 of then of which 10 are taken for bind.

### Proposed Solution
Ability to select which multiple interfaces AdGuard could bind to

### Alternatives Considered
See Problem description

### Additional Information
See Problem description

**Comment by Revertron** [comment] 2021-01-25 18:17
I think it is a duplicate of #1401.
BTW, also waiting for this option.

**Comment by ameshkov** [comment] 2021-01-26 09:53
Indeed a duplicate, thank you!

We'll definitely implement this, the re-designed AGH will have it.

**Closed by ameshkov** 2021-01-26 09:53 UTC
Labels: duplicate
