### ISSUE TITLE
macOS and Windows's edge channel builds is empty.

### ISSUE THREAD

**Issue by hezhijie0327** [AdguardTeam/AdGuardHome#2510] opened 2020-12-31 13:58 UTC
`https://static.adguard.com/adguardhome/edge/AdGuardHome_darwin_amd64.zip`
`https://static.adguard.com/adguardhome/edge/AdGuardHome_windows_amd64.zip`
<img width="920" alt="Xnip 2020-12-31 21 56 00" src="https://user-images.githubusercontent.com/58100052/103413065-00d32980-4bb3-11eb-82a5-3abf9cee351a.png">

**Comment by ainar-g** [comment] 2020-12-31 14:02
Duplicate of #2507.  We're working on it!

**Closed by ainar-g** 2020-12-31 14:02 UTC
Labels: duplicate
