### ISSUE TITLE
Suggestion: Query logs can be categorized by filters, DNS, black/whitelist, and query queries

### ISSUE THREAD

**Issue by AlephZHAO** [AdguardTeam/AdGuardHome#6154] opened 2023-08-29 09:06 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

查询日志只能通过域名来查询，以放行/拦截为分类，不能通过DNS过滤规则来查询/分类，不方便管理

### Proposed solution

请求一个新的功能:查询日志可以通过 `过滤器-DNS黑/白名单-对应的规则列表标题` 来**查询/分类**，方便查看哪一个规则的效率最高并进行调整

**Comment by ainar-g** [comment] 2023-08-29 11:09
Please only add one request per issue.

Marking as duplicate of #6032 and #6056.

**Closed by ainar-g** 2023-08-29 11:09 UTC
Labels: feature request

**Comment by AlephZHAO** [comment] 2023-08-30 02:19
Ok thanks
