### ISSUE TITLE
Error: control/clients/add | Network Error

### ISSUE THREAD

**Issue by dbowles1975** [AdguardTeam/AdGuardHome#5950] opened 2023-06-30 10:46 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Windows/386

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-b.38

### Action

Attempted to add persistent client. 

### Expected result

Persistent client would be added. 

### Actual result

Error: control/clients/add | Network Error displayed in bottom right cornet of screen, 

### Additional information and/or screenshots

![Screenshot 2023-06-30 064512](https://github.com/AdguardTeam/AdGuardHome/assets/14967573/e1291f17-286c-47a3-b959-9795ef332543)

I was able to add five persistent clients this morning before updating to most recent version. After updating, I get the error above.

**Comment by ainar-g** [comment] 2023-06-30 10:54
Duplicate of #5946

**Closed by ainar-g** 2023-06-30 10:54 UTC
