### ISSUE TITLE
Support dnsmasq's add-subnet feature

### ISSUE THREAD

**Issue by elahd** [AdguardTeam/AdGuardHome#2065] opened 2020-09-04 21:35 UTC
### Problem Description & Alternatives Considered

AdGuard Home does not process IP addresses forwarded by dnsmasq's add-subnet parameter. My setup is below:

1. AdGuard Home runs on a Raspberry Pi.
2. Ubiquiti USG running dnsmasq with the below notable properties:
a. DHCP server enabled.
b. Parameter add-subnet=32,128.
c. Parameter strict-order enabled.
d. AdGuard Home is primary DNS server. Cloudflare's malware blocking DNS is secondary.

This setup ensures that if the Pi running AdGuard becomes unavailable, the USG will fall back to Cloudflare. The strict-order parameter ensures that the USG will always exclusively use AdGuard when the Pi is available.

I'd like to see individual IPs listed in AdGuard's UI, but all requests forwarded through dnsmasq show up under the router's IP:

![image](https://user-images.githubusercontent.com/466460/92286195-52ed9200-eed4-11ea-99fb-fb08a11e035e.png)

### Proposed Solution

AdGuard Home should process IP addresses forwarded by dnsmasq's add-subnet parameter.

### Additional Information

See [dnsmasq man page](https://manpages.debian.org/buster/dnsmasq-base-lua/dnsmasq.8.en.html) for (light) details about the add-subnet parameter. Also see the description for add-mac, another potentially useful parameter.

**Comment by ameshkov** [comment] 2020-09-06 21:57
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/1727

**Closed by ameshkov** 2020-09-06 21:57 UTC
Labels: duplicate
