### ISSUE TITLE
[Feature request] Search Query Log Using Client Name

### ISSUE THREAD

**Issue by fr45er** [AdguardTeam/AdGuardHome#2454] opened 2020-12-17 17:09 UTC
![CA2B7C04-EC4D-4D61-8C3E-F8B25FD4CBE6](https://user-images.githubusercontent.com/76176646/102519107-fcbeec00-4089-11eb-966e-4e19e42cf7ce.jpg)

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ Y] I am running the latest version
- [ Y] I checked the documentation and found no answer
- [ Y] I checked to make sure that this issue has not already been filed

### Problem Description

Search by device name in the Query Log - I can only currently search by IP,  I assigned all of my daughters devices with Names (FIRSTNAME - DEVICE) and it would be useful to search by FIRSTNAME and just to see these on the Query Log

### Proposed Solution

In the Query log - I can search by Client IP - is it possible to have a search by client name (as defined under client settings)

For example - my daughter has a phone, tablet, laptop and console,  they are all named as "DEVICE - NAME" using client settings

**Comment by ameshkov** [comment] 2020-12-17 19:49
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/1273

**Closed by ameshkov** 2020-12-17 19:49 UTC
