### ISSUE TITLE
Hide a certain client information in the request log

### ISSUE THREAD

**Issue by woboo110** [AdguardTeam/AdGuardHome#2460] opened 2020-12-21 03:24 UTC
Hope to increase the function of hiding all requests of a client in the log, such as the request of the router itself

**Comment by Aikatsui** [comment] 2020-12-21 05:08
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/1717#issuecomment-633257356

**Closed** 2020-12-21 10:36 UTC
Labels: duplicate
