### ISSUE TITLE
Configuration Backup / Restore ability

### ISSUE THREAD

**Issue by Aipoc76** [AdguardTeam/AdGuardHome#6264] opened 2023-09-29 03:25 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

I would like to see the ability to download my configuration.  All Settings, Filters, Custom Rules ect.  The rational behind this is so i can move adguard to different servers easily with out having to recreate everything.

### Proposed solution

Simple export to CSV file, and Import buttons be made.

**Comment by agneevX** [comment] 2023-10-01 12:40
Though not accessible from the web UI, you can copy the yaml file from the server.

**Comment by Aipoc76** [comment] 2023-10-01 14:28
and where would this be located in the docker of homeassistant?  I cant find adguard anywhere using "find -iname adguard" from root of the shell command.

**Comment by agneevX** [comment] 2023-10-01 17:18
Not sure about that since it's a third-party install and isn't officially supported.

**Comment by duckxx** [comment] 2023-10-07 15:13
这功能的确需要，如果在SNAP安装的adguardhome，那必须要有备份功能。

**Comment by fernvenue** [comment] 2023-10-08 09:27
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/4802, see also https://github.com/AdguardTeam/AdGuardHome/issues/573 and https://github.com/AdguardTeam/AdGuardHome/issues/1147 for similar requests.

**Closed** 2023-10-12 15:24 UTC
Labels: feature request
