### ISSUE TITLE
Rules depending the day, hours. 

### ISSUE THREAD

**Issue by Vercety87** [AdguardTeam/AdGuardHome#3227] opened 2021-06-05 06:03 UTC
Hi,

It would be nice to be able to custom filtering depending the day/hours. 

I would like to block all work related domain during the weekend. 

Is it something planned for futur version ?

Thanks.

**Comment by Aikatsui** [comment] 2021-06-05 13:10
Duplicate of #1203

**Closed** 2021-06-06 12:44 UTC
