### ISSUE TITLE
Make server-side error messages translatable

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdGuardHome#1470] opened 2020-03-13 15:50 UTC
With v0.101.0, I typed wrong login data.
I saw the error message, but it's not translated.
Something wrong or just miss it?
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/3KrYwU5.png)
</details><br/>

Crowdin has some issues, and I can't normally open projects now.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/rgjkv7H.png)
</details><br/>

Wait until Crowdin becomes normal.

**Comment by ameshkov** [comment] 2020-03-14 10:42
The problem is that some errors (the ones which are returned by the "server") aren't translatable yes.

So this is actually a more general issue - we should move these messages to the client-side in order to fix this.

**Comment by ameshkov** [comment] 2020-03-14 10:45
@szolin assigned this to v0.104 for now.

Here's what I suggest:

1. Introduce an "errorCode" and "errorDetails" fields to the HTTP error response
2. The client-side should be able to interpret this "errorCode" and print a human-readable error message.
3. The actual error details should be hidden under some "Show details" link.

**Comment by ainar-g** [comment] 2021-06-03 14:40
This will probably be implemented as a part of our redesign, since we will also switch to error codes instead of verbatim error strings.  I will merge this issue into the one about the redesign,  #2554.

Thanks!

**Closed by ainar-g** 2021-06-03 14:40 UTC
Labels: P3: Medium, enhancement, localization
