### ISSUE TITLE
The cpu is full

### ISSUE THREAD

**Issue by hadesya** [AdguardTeam/AdGuardHome#4147] opened 2022-01-16 15:42 UTC
![image](https://user-images.githubusercontent.com/50535150/149666911-c2761b2c-a4ca-4007-95e7-cac0b87658e5.png)

**Comment by hadesya** [comment] 2022-01-16 16:37
![image](https://user-images.githubusercontent.com/50535150/149669007-81ef7ebb-5e28-47f5-9c7b-c1276b96d196.png)

**Comment by ainar-g** [comment] 2022-01-19 12:30
Possibly a duplicate of #4042.  Have you updated to v0.107.2?

**Comment by hadesya** [comment] 2022-01-19 13:30
0.108

**Comment by ainar-g** [comment] 2022-01-19 14:26
I see.  Can you enable [verbose logging][1] and look, what kind of logs are printed during the CPU spikes?  Or send the logs to devteam@adguard.com with the corresponding subject line?  Thanks!

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Closed** 2022-09-02 12:09 UTC
Labels: duplicate
