### ISSUE TITLE
Recreation Time from NextDNS

### ISSUE THREAD

**Issue by grubeli** [AdguardTeam/AdGuardHome#2327] opened 2020-11-17 16:41 UTC
"Blocked services" feature is really good, I'm using it to block Netflix and adult sites for my kids, but sometimes I want to unlock Netflix for an hour or two, so it would be useful to have a feature to choose time slot when things would get unblocked.
NextDNS (I'm using it for up-streaming now) have the feature:
![image](https://user-images.githubusercontent.com/74614193/99417793-39b08b00-28f2-11eb-8605-eca56e8e08da.png)

### Proposed Solution
I don't think that it's technically very challenging to unblock specified services at specific time, maybe one additional thread

### Alternatives Considered
Using NextDNS is alternative but only 300 000 queries are FREE, and also it's preferable to have one control panel.

### Additional Information
https://www.reddit.com/r/nextdns/comments/jfztoq/introducing_recreation_time/

**Comment by Aikatsui** [comment] 2020-11-17 18:39
Duplicate of #951

**Closed** 2020-11-17 18:44 UTC

**Comment by Aikatsui** [comment] 2020-11-19 20:52
https://github.com/AdguardTeam/AdGuardHome/issues/1692
