### ISSUE TITLE
Clients identification issue

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#6628] opened 2024-01-09 17:35 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

0.107.43

### Action

Hello,
1. Add client with ID 172.16.0.0/24
2. Enable IP anonymization
3. Set up private IP of my DNS in any other server settings like:
/etc/systemd/resolved.conf
/etc/network/interfaces 
etc.
4. Restart the server
5. Check the Top clients section and see:
![image](https://github.com/AdguardTeam/AdGuardHome/assets/45385632/b539999f-8fec-4462-bea3-82a7e874c88d)
7. Go to journal's section and enter "172.16.0.1" - nothing found. Only 172.16.0.0 + I don't have the client with ID 82.146.42.213, but I see the queries from 82.146.0.0 and this is my server's IP. The verbose log will be send to devteam@adguard.com

Please check why these queries were recorded incorrectly. Thank you.

### Expected result

Correctly recorded queries 🙂

### Actual result

Incorrect queries in journal

**Comment by EugeneOne1** [comment] 2024-01-11 16:36
@ammnt, hello and thanks for the report.  Could you please clarify a few things:
 1. If I understand correctly, the records found are indeed from the client with the address `172.16.0.1`.  Were these recorded requests made before the anonymization turned on?  The anonymization feature actually processes the query log records at both write and read stages, so that if the actual record contains a full IP address, it will match the corresponding search query.
 1. Don't you expect the queries from `82.146.42.213`?  Is this the server running AdGuard Home?

In any case, it's recommended to clear out the statistics and query logs after enabling the anonymization feature to ensure the data consistency.

We have also fixed an anonymization-related bug in the statistics, but we haven't released it yet on the stable channels, so could you please try the latest edge builds and let us know if the situation is better there?

**Comment by ammnt** [comment] 2024-01-11 18:17
@EugeneOne1, hey👋
1. No, from `172.16.0.2` and `176.16.0.3` too and these queries were added to the journal when anonymization was already enabled;
2. No, I don't expect the queries from `82.146.42.213` because my server doesn't listen `82.146.42.213:53` but only `172.16.0.2:53` and `82.146.42.213 `is Ip address of docker host machine.

Unfortunately I can't check the edge build right now, but I can sent you more verbose logs😀

**Comment by EugeneOne1** [comment] 2024-01-16 14:44
@ammnt, hello again.  Regarding the requests from `82.146.42.213`, the received log file doesn't actually contain any real requests from it, so it's pretty hard to tell if this is related to an untrusted proxy or some other software hosted on the same host machine.  I think it is worth trying to add the address as a trusted proxy and see if the requests keep coming.

Nonetheless, I don't think I understand entirely your setup and the environment.  Which else DNS-related software works between your clients and the AdGuard Home instance?  If the client for `172.16.0.0/24` subnet actually called "Server"?

Do you mean that after anonymization enabled you can't find the requests from `172.16.0.1`?  Or do you mean that searching for `172.16.0.1` gives the results for `172.16.0.0`?  Note that the first case is the intended behavior.

**Comment by EugeneOne1** [comment] 2024-01-18 16:36
@ammnt, we'd prefer to keep the conversation via email at devteam@adguard.com if you want to keep it private.

**Comment by ammnt** [comment] 2024-01-19 04:15
@EugeneOne1, 
1. I have trusted proxy rows in my AGH config like 172.16.0.0/24 etc.
2. Yes, I have the client with 172.16.0.0/24 identification🙂
3. Yes, I have 172.16.0.1 client in the TOP section of the main page, but I can't find 172.16.0.1 in the journal section. Only 172.16.0.0. I thought anonymisation should apply to the top section too:
![image](https://github.com/AdguardTeam/AdGuardHome/assets/45385632/4608fc01-a5e7-4049-a3da-edbe74733044)
![image](https://github.com/AdguardTeam/AdGuardHome/assets/45385632/168e5277-eb69-43a8-a42c-bc58cdf56944)
4. I also have requests in the top section like:
![image](https://github.com/AdguardTeam/AdGuardHome/assets/45385632/767aca62-9ad7-4c90-b4bd-446a3d0a31d8)
and this query has been recorded with anonymisation enabled:
![image](https://github.com/AdguardTeam/AdGuardHome/assets/45385632/a7d920a5-622b-4d87-878b-b92ec3a90540)

Something wrong here🤯

**Comment by EugeneOne1** [comment] 2024-01-22 12:02
@ammnt, looks almost like #6584 and should be fixed in the edge build.  Could you please check the one?

**Comment by ammnt** [comment] 2024-01-22 17:27
@EugeneOne1, yeah. It looks similar.

**Closed** 2024-01-27 17:26 UTC
Labels: waiting for data
