### ISSUE TITLE
Missing translation for theme toggle button 

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdGuardHome#5376] opened 2023-01-19 15:55 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.22

### Description

Missing translation for theme toggle

**Comment by ainar-g** [comment] 2023-01-19 15:56
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/5375#issuecomment-1396977464.  Please send dark theme feedback there.  Thanks.

**Closed by ainar-g** 2023-01-19 15:56 UTC
