### ISSUE TITLE
[Feature Request] Even Richer Statistics

### ISSUE THREAD

**Issue by SukkaW** [AdguardTeam/AdGuardHome#3900] opened 2021-11-29 22:43 UTC
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

- An overall `Root Domains` section for `Aggregate of all queries made for root domains and all their subdomains.`.
  Here is an example from `NextDNS.io`:

  ![image](https://user-images.githubusercontent.com/40715044/143952500-23221492-a3a0-40fb-b55c-b66b56db52ab.png)

- Since AdGuardHome added support for DNSSEC (https://github.com/AdguardTeam/AdGuardHome/issues/66), I'd like to see how many queries are validated with DNSSEC.
  An example from `NextDNS.io` (again!):

  ![image](https://user-images.githubusercontent.com/40715044/143953426-180caca8-376c-418e-99f2-801c976e0d6b.png)

- Show traffic destination from queries.
  An example from `NextDNS.io` (again!):
  ![image](https://user-images.githubusercontent.com/40715044/143953961-d0319b6d-c0d4-45a5-8e91-6b12907fe4b2.png)

### Proposed Solution

- AdGuardHome already has `Top queried domains`, but I'd like to see overall statistics on which domain I requested most (Still a lot of websites still use domain sharding, a hacky optimization for the dark age of HTTP/1.1. And they mess up `Top queried domains` quite a lot, and `Root Domains` section will come in handy).
- AdGuardHome already has destination IP info in the query log. However, traffic destination analysis requires a GeoIP database (e.g. MaxMind's GeoLite).

**Comment by Aikatsui** [comment] 2021-12-22 17:21
Duplicate of #1605 750

**Comment by ainar-g** [comment] 2021-12-22 17:59
Duplicate of #1605

**Closed by ainar-g** 2021-12-22 17:59 UTC
Labels: feature request
