### ISSUE TITLE
Adguard Home DHCP Issue

### ISSUE THREAD

**Issue by Saku241** [AdguardTeam/AdGuardHome#3366] opened 2021-07-20 18:16 UTC
### Issue Details

* **Version of AdGuard Home server:**
  * v0.106.3
* **How did you install AdGuard Home:**
  * `curl -sSL https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh`
* **How did you setup DNS configuration:**
  * Load-balancing
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 3 Model B
* **CPU architecture:**
  * ARM64
* **Operating system and version:**
  * Raspbian 10

### Actual Behavior

I got a problem with the DHCP of Adguard Home. I disabled my router's DHCP and Adguard DHCP seems to work fine with WIFI devices because they are granted an IP BUT for Wired devices (RJ45) they never get an IP. 
I actually have to add every MAC addresses of wired devices to manually assign IP to each. It kinda works but sometimes when I turn on my computer, it takes a while to get an IP (approx. 30s-2m).  

My IP Range is 192.168.1.2 to 192.168.1.126, subnet 255.255.255.0 and lease 86400sec

### Additional Information

I added the MAC addresses of my devices in client section but I cant determine the device if it's an other IP, I thought it would be able to identify with only the MAC Address

**Comment by Saku241** [comment] 2021-07-21 14:16
> Hello. Are you sure that your router processes both wired and wireless connections using a single DHCP server? 

Not sure but my router got basic dhcp options 

I’ll try the verbose and update ticket

**Comment by ainar-g** [comment] 2021-07-21 14:51
Please make sure that AdGuardHome is actually up.  For example that the web interface is shown and that you can see DNS queries on the Query Log page.

**Comment by Saku241** [comment] 2021-07-21 14:54
Adguard is on but there's no query as devices didnt get a correct local ip. If I put back verbose false and log_file "", Adguard start working as normal.. Anything wrong with the log_file directory ?

**Comment by ainar-g** [comment] 2021-07-21 15:01
Are you sure that `/home/pi/logs` is a **file** and that AGH can access it?

**Comment by Saku241** [comment] 2021-07-21 15:41
> Are you sure that `/home/pi/logs` is a **file** and that AGH can access it?

Oof I thought it was only a directory not a file...

So here's verbosse logs :

- https://pastebin.com/raw/tBFgcYrt Here, I got my local ip (192.168.1.22) with static lease in approx 30-45sec
- https://pastebin.com/raw/Rfi0rNh2 Here, I removed the static lease only for 2c:f0:5d:60:34:79. It seems to loop and I never received the supposed 192.168.1.10, I never got internet on my pc at this state. 

After that I manually put 192.168.1.10 as my ip and 192.168.1.2 as dns and Adguard could identify my pc in clients BUT in statistics, there is 2 instances : Bryan-PC (192.168.1.22) and Bryan-PC (192.168.1.10), they should be merge as it is the same client just on different ip, isnt it ?

**Comment by Saku241** [comment] 2021-07-27 17:40
Any update since ?

**Comment by ainar-g** [comment] 2021-07-28 13:00
Hi, sorry for the delay.  It seems like the machine just doesn't accept the IP for some reason and resends `DISCOVER` immediately after receiving an IP from AGH.  Were you able to make sure that there are no other DHCP servers in the network?

Also, could you try to either increase the `icmp_timeout_msec` parameter in the configuration file to `3000` or decreasing it to `250`?  Perhaps that IP is already taken, but AGH cannot see that.

**Comment by Saku241** [comment] 2021-07-28 13:09
> Hi, sorry for the delay. It seems like the machine just doesn't accept the IP for some reason and resends `DISCOVER` immediately after receiving an IP from AGH. Were you able to make sure that there are no other DHCP servers in the network?
> 
> Also, could you try to either increase the `icmp_timeout_msec` parameter in the configuration file to `3000` or decreasing it to `250`? Perhaps that IP is already taken, but AGH cannot see that.

Yep i'll try that but as I said, its not the only machine, every machine with a ethernet connection does this.
I'll try that and give you updates

**Comment by Saku241** [comment] 2021-07-29 12:54
So I tried `3000` and `250` and it changes absolutely nothing. 
On Adguard/#dhcp it clearly show me that I was supposed to have `192.168.1.10` with a lease but my machine never get that ip assigned.
I had to add a static lease to get it work again

**Comment by hoshsadiq** [comment] 2021-07-30 11:48
I think I have the same issue. None of my devices were able to connect earlier. I had to switch off AGH's DHCP, re-enable DHCP on my router, connect my devices, then re-enable DHCP on AGH.

**Comment by EugeneOne1** [comment] 2021-07-30 16:46
@Saku241, there is a possibility, that we've reproduced the issue, but we need some details about your setup:

Which OS is on your `2c:f0:5d:60:34:79` machine?

*  If Unix-like (i.e. Linux, MacOS, FreeBSD, etc.), what DHCP client is used and how is it configured?  The thing is that some clients may be configured to ignore some specific DHCP `OFFER`s.  For example, `dhclient` on FreeBSD has an option `-u` which...
   > Forces dhclient to reject leases with unknown options in them.  The default behaviour is to accept such lease offers.

* If Windows, the issue may be caused by the same reason, but it's more complicated to diagnose.  Could you please try the ways from those topics:
  *  [Topic 1](https://social.technet.microsoft.com/Forums/lync/en-US/7127b4ea-9ea2-467f-af4e-f61de3bf7bf8/devices-do-not-reply-to-dhcp-offer?forum=ws16essentials);
  *  [Topic 2](https://social.technet.microsoft.com/Forums/en-US/7b0b875c-3406-4dff-a438-121428c79442/windows-10-clients-doesent-accept-dhcpoffers?forum=win10itpronetworking);
  *  [Topic 3](https://superuser.com/questions/952566/windows-7-ignoring-dhcp-offer-packets).

We'll try to find the solution in the meantime.

**Comment by hoshsadiq** [comment] 2021-07-30 17:32
@EugeneOne1 all of my devices that are not working are all Linux devices plus an Android device. Anything I can upload for diagnosis?

**Comment by EugeneOne1** [comment] 2021-07-30 17:39
@hoshsadiq, we'll need your AdGuard Home verbose logs at least.  My colleague Ainar [provided](https://github.com/AdguardTeam/AdGuardHome/issues/3366#issuecomment-884220380) the link to the instructions on how to collect those.

**Comment by Saku241** [comment] 2021-07-30 17:45
@EugeneOne1 my OS is windows but my device replied to my modem’s DHCP before I install Adguard so I doubt there’s a problem with my device

I’ll try those 3 topics and give you updates

**Comment by Saku241** [comment] 2021-08-17 15:18
Any updates since? 
For my part, none of the previous topic changed something for my side, I still need static lease for some devices

**Comment by EugeneOne1** [comment] 2021-08-20 09:36
@Saku241, yep, the problem may be related to the DHCP flags that your machine expects.  We've filed a few issues (#3443, #3043) and are already reviewing the PR (#3458) to fix those.

**Comment by EugeneOne1** [comment] 2021-09-13 17:59
@Saku241, the latest build from edge channel contains some improvements to DHCP server's logic in general and DHCP options in particular.  Could you please check if the issue still persists?

**Comment by Saku241** [comment] 2021-09-13 18:36
> @Saku241, the latest build from edge channel contains some improvements to DHCP server's logic in general and DHCP options in particular. Could you please check if the issue still persists?

v0.107.0-b.9 ? How can I update from v0.106.3 ? Is there any update system in the UI ?

**Comment by EugeneOne1** [comment] 2021-09-14 07:08
@Saku241, well, to update it with latest edge build, you may use the script with special flags:

```sh
curl -sSL https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -r -c edge
```

This will simply reinstall you AdGuard Home, but make sure you have to backup files from working and configuration directory, if those are important.

**Comment by EugeneOne1** [comment] 2021-09-15 10:10
@Saku241, the fix is now also available in the most recent beta build.  The installation method is rather similar:

```sh
curl -sSL https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -r -c beta
```

**Comment by EugeneOne1** [comment] 2021-09-17 15:42
@Saku241, we'll close the issue for now.  Please consider reopening it if our solution won't make Home's DHCP server work properly.

**Closed by EugeneOne1** 2021-09-17 15:42 UTC
Labels: waiting for data

**Comment by Saku241** [comment] 2021-12-26 17:42
still an issue in v0.107.0

**Comment by HammerHeston** [comment] 2022-01-01 02:17
I just installed AdGuard Home via the TrueNAS plugin and DHCP is still not working.

The installed AdGuard Home version is 0.107.0.b.7

I performed an nmap scan and the server isn't even listening for DHCP requests.

**Comment by TienNguyenanh** [comment] 2022-01-09 16:21
I also encountered the same situation.
AdGuardHome worked, ads blocked, but dhcp not working.
AdGuard Home version is 0.107.2-1

**Comment by MakerLab-Dev** [comment] 2022-01-15 22:27
I have AdGuard Home running in a docker container and I'm also encountering problems related to DHCP, it mainly works for WiFi connected devices but for wired ones it doesn't seem to work (at least Windows 10, my linux machines seem to work even with a wired connection)
Maybe this is Windows related since in my case every other OS seem to work

**Comment by zglurb** [comment] 2022-02-26 13:07
Hello, I've just installed AdGuard Home and the DHCP is working fine for all my devices except for one that seems to ignore the DHCP offers from AdGuard. It's not a computer, it's an IoT device I don't have access to.

From @EugeneOne1 :
> If Unix-like (i.e. Linux, MacOS, FreeBSD, etc.), what DHCP client is used and how is it configured? The thing is that some clients may be configured to ignore some specific DHCP OFFERs. For example, dhclient on FreeBSD has an option -u which forces dhclient to reject leases with unknown options in them. The default behaviour is to accept such lease offers.

I tried to compare the DHCP offer from my router (which is accepted) and the one from AdGuard with Wireshark and the only difference I could spot was this option from the AdGuard's offer that is not in my router's.

```
Option: (61) Client identifier
    Length: 7
    Hardware type: Ethernet (0x01)
    Client MAC address: <mydevicemacaddress> (<mydevicemacaddress>)
```

So I guess it could be it. Is there a way to not send this option?

**Comment by sslesar** [comment] 2022-09-30 19:56
https://i.imgur.com/4eKQIMI.png
I believe these buttons are glitches.
First press "Check for DHCP servers" then click "Enable DHCP server". Should appear grey button with the word "Disable DHCP server"
However, there was a glitch that did not work "Enable DHCP server" and no grey button appeared.
Don't forget to turn off the DHCP server on your router.
