### ISSUE TITLE
Light drop-down list in query log

### ISSUE THREAD

**Issue by Birbber** [AdguardTeam/AdGuardHome#5445] opened 2023-02-03 12:31 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Windows

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.23

#### Actual result
Light drop-down list appears in query log while dark theme is chosen

![image](https://user-images.githubusercontent.com/78078725/216603915-412977a5-a556-4397-b488-cdb3837d3430.png)

**Comment by ainar-g** [comment] 2023-02-03 13:45
Duplicate of #5441

**Closed by ainar-g** 2023-02-03 13:45 UTC
Labels: UI
