### ISSUE TITLE
redirect user to custom block page if blocked access to site 

### ISSUE THREAD

**Issue by ElectricReality** [AdguardTeam/AdGuardHome#640] opened 2019-03-13 16:48 UTC
Would it be a good idea if the user will be redirected to a custom block page if user tries to view a blocked site in Custom filtering rules?

**Comment by ameshkov** [comment] 2019-03-13 16:49
Hi! Marked as duplicate of #454 

Please vote for existing feature requests.

**Closed by ameshkov** 2019-03-13 16:49 UTC
Labels: duplicate
