### ISSUE TITLE
AdGuard not running after power outage

### ISSUE THREAD

**Issue by gyCfjSnO** [AdguardTeam/AdGuardHome#4309] opened 2022-02-18 07:21 UTC
Just had a power outage in our neighbourhood which caused the computer running AdGuard Home to power off.

When power was restored we had no internet so I checked the computer running AdGuard Home and it running as when I checked sudo systemcpl AdGuard Home was red and it had a red dot before the name, the web address wasn't accessible either.

Running sudo snap restart AdGuard-home made it run again giving access to the internet.

Can you please help me with instructions on how I can find out in the logs what caused AdGuard Home not to run?

I'm running Debian 11 on 4th Gen Intel i5 and AdGuard Home is version v0.108.0-b.3.

**Comment by EugeneOne1** [comment] 2022-02-18 09:22
@gyCfjSnO, hello.  See the [wiki page](https://github.com/adguardteam/adguardhome/wiki/FAQ#logs).

So the AGH has successfully restarted and continued working?

**Comment by gyCfjSnO** [comment] 2022-02-18 09:57
> @gyCfjSnO, hello. See the [wiki page](https://github.com/adguardteam/adguardhome/wiki/FAQ#logs).
> 
> So the AGH has successfully restarted and continued working?

When I restarted it via snap it started working. Wanting to find out why it didn't start in the first place after a power outage as it's the first time it hasn't come back to life after a power outage.

I will check the logs and post back.

**Comment by gyCfjSnO** [comment] 2022-02-27 09:30
Had another power outage and AdGuard didn't come back up.

```
htpc@HTPC:~$ sudo snap logs adguard-home                                        2022-02-27T19:18:39+10:00 adguard-home.adguard-home[1748]: 2022/02/27 19:18:39.695214 [fatal] couldn't start forwarding DNS server: listening to udp socket: listen udp 192.168.0.2:53: bind: cannot assign requested address                   2022-02-27T19:18:39+10:00 systemd[1]: snap.adguard-home.adguard-home.service: Main process exited, code=exited, status=1/FAILURE                                2022-02-27T19:18:39+10:00 systemd[1]: snap.adguard-home.adguard-home.service: Failed with result 'exit-code'.                                                   2022-02-27T19:18:39+10:00 systemd[1]: snap.adguard-home.adguard-home.service: Consumed 1.889s CPU time.                                                         2022-02-27T19:18:40+10:00 systemd[1]: snap.adguard-home.adguard-home.service: Scheduled restart job, restart counter is at 10.                                  2022-02-27T19:18:40+10:00 systemd[1]: Stopped Service for snap application adguard-home.adguard-home.                                                           2022-02-27T19:18:40+10:00 systemd[1]: snap.adguard-home.adguard-home.service: Consumed 1.889s CPU time.                                                         2022-02-27T19:18:40+10:00 systemd[1]: snap.adguard-home.adguard-home.service: Start request repeated too quickly.                                               2022-02-27T19:18:40+10:00 systemd[1]: snap.adguard-home.adguard-home.service: Failed with result 'exit-code'.                                                   2022-02-27T19:18:40+10:00 systemd[1]: Failed to start Service for snap application adguard-home.adguard-home.
```

**Comment by gyCfjSnO** [comment] 2022-02-28 02:14
My understand, I could be wrong, is that the AdGuard snap is booting before the PC is getting an IP and that is why it isn't starting correctly. Could this be resolved by running the AdGuard snap after everything has loaded during boot? I couldn't seem to find any commands on how to do this.

**Comment by gyCfjSnO** [comment] 2022-03-09 01:13
I have tried seeking assistance over at the Snap forums but have been unsuccessful so far.

https://forum.snapcraft.io/t/adguard-home-snap-not-loading-after-power-outage/28926

**Comment by gyCfjSnO** [comment] 2022-03-09 01:14
> There isn't anything wrong with these logs, really. The logs from the time of actual outage could shed more light. Also, what kind of upstream server did you use? Any DoH/DoQ/DoT ones?

I have tried seeking assistance over at the Snap forums but have been unsuccessful so far.

https://forum.snapcraft.io/t/adguard-home-snap-not-loading-after-power-outage/28926

**Comment by ainar-g** [comment] 2022-03-09 15:07
Apologies for absence of responses from our side.  Unfortunately, I'm not sure if I can be of any help with the interaction between snapd, systemd, and AdGuard Home.  The two things that you could possibly try are:

1.  Edit the resulting `.service` file to add some kind of pre-launch sleep.

2.  Install AGH as a binary as opposed to a Snapcraft package and see if the situation improves.

**Comment by gyCfjSnO** [comment] 2022-03-10 00:35
> Apologies for absence of responses from our side. Unfortunately, I'm not sure if I can be of any help with the interaction between snapd, systemd, and AdGuard Home. The two things that you could possibly try are:
> 
> 1. Edit the resulting `.service` file to add some kind of pre-launch sleep.
> 2. Install AGH as a binary as opposed to a Snapcraft package and see if the situation improves.

Removing AGH snap, and installing via GitHub has resolved the issue... 😂 haha

**Comment by ainar-g** [comment] 2022-03-10 13:17
Thanks for testing!  I would say that that most probably means that the issue is not with AGH, or at least not directly.  If you still want a contained solution, you could try the Docker image.  Otherwise, you could probably just use the simple binary package.

**Comment by Birbber** [comment] 2022-09-01 12:43
Closing this issue as completed.

**Closed by Birbber** 2022-09-01 12:43 UTC
Labels: snap

**Comment by nick191007** [comment] 2022-09-14 08:28
i am not sure if am at the right place to share my issue but it seem i am having the similar issue. where in my Raspberry pi 4  has ad guard Home over it. when ever there is a power outage i am able to ssh it but no internet until i reboot the system (Pi) for the internet to work again.

installed OS :- Pi lite Version.
ad guard Home 

not sure how to get the log file as am new to it.

**Comment by nick191007** [comment] 2022-09-14 15:27
@ainar-g thanks for the quick update will try to debug it and share any update on new one if any.
