### ISSUE TITLE
V0.102.0-101-gda6c log problem

### ISSUE THREAD

**Issue by banbendalao** [AdguardTeam/AdGuardHome#1852] opened 2020-06-30 14:05 UTC
V0.102.0-101-gda6c does not show the reason for interception

**Comment by banbendalao** [comment] 2020-06-30 14:10
I need to know which rule it was intercepted, such as `||google.com^`

**Comment by ameshkov** [comment] 2020-06-30 14:32
Duplicate of #1828

**Closed by ameshkov** 2020-06-30 14:32 UTC
Labels: duplicate
