### ISSUE TITLE
cache-min-ttl

### ISSUE THREAD

**Issue by csousougen** [AdguardTeam/AdGuardHome#1214] opened 2019-11-27 17:59 UTC
Admins are using using very low DNS TTLs, making caching inefficient.
Could you please add the option to set a minimum TTL value and override the one provided?

Thank you.

**Comment by ameshkov** [comment] 2019-11-27 22:17
Thank you for the feature request! Let's see how many upvotes it gets

**Comment by 280blocker** [comment] 2020-01-03 16:04
This is the most voted request in open issues.
I think this feature will reduce the load on AdGuardHome.

**Comment by csousougen** [comment] 2020-01-06 17:00
CoreDNS supports this feature as much as serve_stale and prefetch. 
While CoreDNS is overkill for a home system, these feature would make it lighter and save data for mobile users.

**Comment by ameshkov** [comment] 2020-01-06 19:00
Assigned to v0.102

**Comment by adworacz** [comment] 2020-01-30 01:19
Since I configure this on dnsmasq or DNSCrypt-proxy currently, I'd like to request the following:
* cache_size (entries - easier than thinking about bytes)
* cache_size = 1024
* cache_min_ttl = 2400
* cache_max_ttl = 86400
* cache_neg_min_ttl = 60
* cache_neg_max_ttl = 600

Those config directives and values are taken from DNSCrypt-proxy: https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Caching

If I had to pick, I'd say that `cache_min_ttl` and `cache_max_ttl` are the highest priority (for me), followed by `cache_size` (entries), and then the `*neg*` versions of things.

**Comment by adworacz** [comment] 2020-01-31 19:07
Hmm, looks like (unless I'm way off base) the primary ttl/caching logic happens here:
https://github.com/AdguardTeam/dnsproxy/blob/d4772f979c7711d93fa67a1de5bb3f45974226fb/proxy/cache.go#L126-L152

I don't know go much, but I might take a crack at implementing cache_min/max_ttl here. We'll see how free I am this weekend.

**Comment by ameshkov** [comment] 2020-02-02 16:18
Yeah, but I am not sure how safe would be to change that method.

Maybe it'd be better to change `packResponse` which is used before putting DNS queries to the cache:
https://github.com/AdguardTeam/dnsproxy/blob/d4772f979c7711d93fa67a1de5bb3f45974226fb/proxy/cache.go#L197

**Comment by adworacz** [comment] 2020-02-04 17:47
Ahh okay, I'll take a look at what it will take to update `packResponse`.

I should be able to find some time in the next few days.

**Comment by adworacz** [comment] 2020-02-08 18:41
Got a quick version put together, pushed here: https://github.com/adworacz/dnsproxy/tree/minMaxTTL

However, it's still a WIP, as tests still need to be updated, and likely one or two other things (like the README).

**Comment by ameshkov** [comment] 2020-02-09 13:42
Cool, the only thing that I don't like are the default values. I suppose by default `dnsproxy` should not modify what it gets from the DNS server.

**Comment by adworacz** [comment] 2020-02-10 17:50
> Cool, the only thing that I don't like are the default values. I suppose by default `dnsproxy` should not modify what it gets from the DNS server.

Fair enough - I was on the fence about this when I was working on it, so I'll support "unset" options for the min/max ttl, which should fix the existing tests in the process. I'll write a custom test specifically around the ttl overriding.

**Comment by ArchiveBase** [comment] 2020-02-11 19:23
https://github.com/AdguardTeam/AdGuardHome/issues/1395

**Comment by adworacz** [comment] 2020-02-13 17:04
Got unset ttl working, iterating on the tests now. 

All existing tests pass, but I wrote a custom one for ttl overrides, and that’s failing currently. I’m looking into the cause (while I learn Go at the same time).

**Comment by adworacz** [comment] 2020-02-14 17:34
Okay got tests working!

My branch is updated (linked above). 

I want to update the README to reflect the new CLI options, then I’ll submit a pull request to dnsproxy. 

Do y’all prefer squashed commits or are multiple commits in a PR okay?

**Comment by ameshkov** [comment] 2020-02-14 17:45
@adworacz cool, thank you! I'd prefer squashed

**Comment by adworacz** [comment] 2020-02-15 06:22
Pull request for dnsproxy is up: https://github.com/AdguardTeam/dnsproxy/pull/84

For anyone else reading along - this does not mean Adguard Home supports setting TTL's yet. The front end interface needs to be updated, now that the core DNS library has support for setting TTLs.

**Comment by szolin** [comment] 2020-02-18 10:05
Found in dnsmasq's man page:
```
--neg-ttl=<time>
    Negative replies from upstream servers normally contain time-to-live information in SOA records which dnsmasq uses for caching. If the replies from upstream servers omit this information, dnsmasq does not cache the reply. This option gives a default value for time-to-live (in seconds) which dnsmasq uses to cache negative replies even in the absence of an SOA record. 
--max-ttl=<time>
    Set a maximum TTL value that will be handed out to clients. The specified maximum TTL will be given to clients instead of the true TTL value if it is lower. The true TTL value is however kept in the cache to avoid flooding the upstream DNS servers. 
--max-cache-ttl=<time>
    Set a maximum TTL value for entries in the cache. 
--min-cache-ttl=<time>
    Extend short TTL values to the time given when caching them. Note that artificially extending TTL values is in general a bad idea, do not do it unless you have a good reason, and understand what you are doing. Dnsmasq limits the value of this option to one hour, unless recompiled. 
```
Interesting that dnsmasq warns users when they use `min-cache-ttl` as something may break;  also they limit this value to one hour - should we do the same?

**Comment by ameshkov** [comment] 2020-02-18 10:13
Yes, I think limiting it is reasonable

**Comment by adworacz** [comment] 2020-02-20 05:50
Hmm okay, I can do that. Where’s the best place to store the constant representing the max? 

And do we want a simple min() call, passing in the two values, or more official validation?

**Comment by szolin** [comment] 2020-02-20 07:06
As this is just one Go package - you can simply add a new constant to the `const` section at the top in proxy.go.

I don't think we should warn user if he uses a value larger than our limit, so a simple min() will suffice.

**Comment by ameshkov** [comment] 2020-02-20 08:14
We should warn in the help text, though

**Comment by adworacz** [comment] 2020-02-20 19:19
Roger roger - I'll work on these updates (still without a proper go install on this laptop, will be on a better laptop soon).

**Closed** 2020-03-20 16:17 UTC
Labels: P3: Medium, feature request

**Comment by lordraiden** [comment] 2020-05-17 10:17
@adworacz @ameshkov 
By default the values are for ttl min and max are 0. What is the behabiour in this case? In my log I see different ttl values for each domain, how are these defined?

Do you plan to add a place in the interface to edit this? Something like the advaced settings of pfsense
![imagen](https://user-images.githubusercontent.com/17175395/82141772-66e38a00-9838-11ea-9000-88f11290fe4b.png)

**Comment by ameshkov** [comment] 2020-05-18 08:30
@lordraiden there's a task for that: #1587

**Comment by lhzw** [comment] 2020-09-12 02:40
Er, I don't like the limit of min-cache-ttl, we should believe our users can do the right thing, just like  linux.
