### ISSUE TITLE
Supports DNS rewriting based on response IPs

### ISSUE THREAD

**Issue by HX-Technology-LLC** [AdguardTeam/AdGuardHome#6992] opened 2024-05-12 16:23 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

CDN providers such as Akamai and cloudflare, they have many IPs and they are common to different websites, some IPs have fast connection speeds and some have slow connection speeds, can we support rewriting based on the response IPs and IP range, to rewrite all of them to fast response IPs?

### Proposed solution

Improve dns rewrite

**Comment by MadSpindel** [comment] 2024-05-13 11:19
Do you mean you only want to use the option "Fastest IP address" for specific CDN providers? And for the rest, you want to use Load-balancing or Parallel requests?

If so, if we had #6800, we could use CDN lists and point them to another Adguard Home instance with the "Fastest IP address" enabled. Also #3342 would be useful, and maybe #5144

**Comment by agneevX** [comment] 2024-05-14 06:36
> some IPs have fast connection speeds and some have slow connection speeds, can we support 
rewriting based on the response IPs and IP range,

I hope you understand how CDNs work, in particular how load-balancing works with very low TTLs for IP addresses returned. So what you're asking for is simply not possible. 

The best option for you is public resolvers that support ECS so you're able to connect to servers closer to you.

**Comment by ainar-g** [comment] 2024-05-17 14:04
Duplicate of #6325

**Closed by ainar-g** 2024-05-17 14:04 UTC
Labels: feature request
