### ISSUE TITLE
Drop Down list for Bootstrap & Upstream DNS servers

### ISSUE THREAD

**Issue by gyCfjSnO** [AdguardTeam/AdGuardHome#5717] opened 2023-04-13 08:06 UTC
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
Manually finding Bootstrap & Upstream DNS servers
#### Proposed solution
Drop Down list for Bootstrap & Upstream DNS servers
#### Alternatives considered
Radio Buttons & Upload function
#### Additional information
N/A

**Comment by ainar-g** [comment] 2023-04-13 11:36
Duplicate of #724

**Closed by ainar-g** 2023-04-13 11:36 UTC
