### ISSUE TITLE
AdGuard redirecting to HTTPS even when the relevant option is disabled

### ISSUE THREAD

**Issue by agneevX** [AdguardTeam/AdGuardHome#3558] opened 2021-09-06 10:42 UTC
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:** 0.106.3
* **How did you install AdGuard Home:** Docker
* **CPU architecture:** arm64
* **Operating system and version:** Ubuntu 20.04

### Details

AGH redirects to HTTPS when configuration is saved in `Encryption settings` despite the `Redirect to HTTPS automatically` button being unchecked.

**Comment by ainar-g** [comment] 2021-09-06 10:59
Hello.  We cannot reproduce this.  Please add the following information:

1.  Which browser are you using?

1.  Have you cleaned the browser's cache after changing the setting?

1.  If you're using Firefox, is the HTTPS-Only Mode enabled?  If not, are there any extensions that could result in similar behaviour?

Thanks.

**Comment by agneevX** [comment] 2021-09-06 11:58
> Which browser are you using?

Safari 14.1.2. 

Screen recording here: https://www.dropbox.com/s/anvimy80yutvjpq/screen_rec.mov?dl=0

**Comment by ainar-g** [comment] 2021-09-07 09:54
Thanks!  I think we are able to reproduce the issue.

**Comment by ainar-g** [comment] 2021-12-09 11:15
@agneevX, I can't seem to reproduce this any more, at least in Firefox.  My colleague couldn't reproduce it on Safari either.  Is this still an issue for you on the latest `edge`/`beta` builds?

**Comment by agneevX** [comment] 2021-12-09 11:22
I encountered this yesterday on MS Edge, running `
v0.107.0-a.213+936a7057`.

Just updated to `v0.107.0-a.221+434032f8`, and I can reproduce it here too.

**Comment by ainar-g** [comment] 2021-12-10 15:35
@agneevX, hm.  It's weird.  I distinctly remember being able to reproduce it, but now I cannot.  Here's what I'm trying:

1.  Go to the “Settings → Encryption settings” page.

2.  Uncheck “Redirect to HTTPS automatically”.

3.  Press “Save”.

4.  Edit the address bar to include `http://` instead of `https://`.

Is this similar to what you're doing?

**Comment by agneevX** [comment] 2021-12-10 17:08
Within 10s of hitting Save, I'm redirected to the https version.

**Comment by ainar-g** [comment] 2021-12-10 17:29
Ah, I see now.  That's why I've been confused.  Seems like a UI bug.  Thanks!

**Comment by ainar-g** [comment] 2021-12-13 11:23
@agneevX, it should be fixed on `edge` in `v0.107.0-a.225+0bd436f4` on the `edge` channel.

**Closed** 2021-12-13 14:36 UTC
Labels: bug, P3: Medium, UI
